
----------------------------------------
--         2014-07-12 20:32:49          --
------------------------------------------
--[[	=== HSP Plugin Module ===	cl_NewVoice, v1.1	Proper voice chat indicator, WHY THE 5 SECOND FADEOUT, GARRY]]local Shade = Color(0,0,0,150)local function VoicePaint(self,w,h)	if not (IsValid(self.ply) and IsValid( LocalPlayer() )) then return end		local Col = self.Color	--if self.ply != LocalPlayer() then --No flashing for local!		Col.a = self.ply:VoiceVolume() * 255	--end		self.LabelName:SetText( (not self.ply:Alive() and "*DEAD* " or "")..self.LabelName.OldText)		draw.RoundedBox(4, 0, 0, w, h, Col)	draw.RoundedBox(4, 1, 1, w-2, h-2, Shade)endlocal PlayerVoicePanels = {}local function PlayerEndVoice(ply)		if IsValid( PlayerVoicePanels[ply] ) then		PlayerVoicePanels[ply]:Remove()		PlayerVoicePanels[ply] = nil	endendhook.Add("PlayerEndVoice", "PlayerEndVoice", PlayerEndVoice)local function PlayerStartVoice(ply)	if not IsValid(g_VoicePanelList_HSP) then return end		PlayerEndVoice(ply)	if not IsValid(ply) then return end		local pnl = g_VoicePanelList_HSP:Add("VoiceNotify")		pnl:Setup(ply)		pnl.LabelName.OldText = pnl.LabelName:GetText()		pnl:SetAlpha(255)		pnl.Paint = VoicePaint		pnl.Think = nil	PlayerVoicePanels[ply] = pnlendhook.Add("PlayerStartVoice", "PlayerStartVoice", PlayerStartVoice)local function VoiceClean()	for ply,pnl in pairs(PlayerVoicePanels) do		if (not IsValid(pnl)) or (not IsValid(ply)) then			PlayerEndVoice(ply)		end	endendtimer.Create("VoiceClean", 3, 0, VoiceClean)hook.Add("Think", "ReplaceGarrysVoice", function()	if IsValid(g_VoicePanelList) then		g_VoicePanelList:Remove()		g_VoicePanelList = nil				g_VoicePanelList_HSP = vgui.Create("DPanel")			g_VoicePanelList_HSP:ParentToHUD()			g_VoicePanelList_HSP:SetPos(ScrW() - 260, 100)			g_VoicePanelList_HSP:SetSize(250, ScrH() - 200)		g_VoicePanelList_HSP:SetDrawBackground(false)				print("[HSP] Removed and replaced shitty voice panel")		hook.Remove("Think", "ReplaceGarrysVoice")	endend)

----------------------------------------
--         2014-07-12 20:32:49          --
------------------------------------------
--[[	=== HSP Plugin Module ===	cl_NewVoice, v1.1	Proper voice chat indicator, WHY THE 5 SECOND FADEOUT, GARRY]]local Shade = Color(0,0,0,150)local function VoicePaint(self,w,h)	if not (IsValid(self.ply) and IsValid( LocalPlayer() )) then return end		local Col = self.Color	--if self.ply != LocalPlayer() then --No flashing for local!		Col.a = self.ply:VoiceVolume() * 255	--end		self.LabelName:SetText( (not self.ply:Alive() and "*DEAD* " or "")..self.LabelName.OldText)		draw.RoundedBox(4, 0, 0, w, h, Col)	draw.RoundedBox(4, 1, 1, w-2, h-2, Shade)endlocal PlayerVoicePanels = {}local function PlayerEndVoice(ply)		if IsValid( PlayerVoicePanels[ply] ) then		PlayerVoicePanels[ply]:Remove()		PlayerVoicePanels[ply] = nil	endendhook.Add("PlayerEndVoice", "PlayerEndVoice", PlayerEndVoice)local function PlayerStartVoice(ply)	if not IsValid(g_VoicePanelList_HSP) then return end		PlayerEndVoice(ply)	if not IsValid(ply) then return end		local pnl = g_VoicePanelList_HSP:Add("VoiceNotify")		pnl:Setup(ply)		pnl.LabelName.OldText = pnl.LabelName:GetText()		pnl:SetAlpha(255)		pnl.Paint = VoicePaint		pnl.Think = nil	PlayerVoicePanels[ply] = pnlendhook.Add("PlayerStartVoice", "PlayerStartVoice", PlayerStartVoice)local function VoiceClean()	for ply,pnl in pairs(PlayerVoicePanels) do		if (not IsValid(pnl)) or (not IsValid(ply)) then			PlayerEndVoice(ply)		end	endendtimer.Create("VoiceClean", 3, 0, VoiceClean)hook.Add("Think", "ReplaceGarrysVoice", function()	if IsValid(g_VoicePanelList) then		g_VoicePanelList:Remove()		g_VoicePanelList = nil				g_VoicePanelList_HSP = vgui.Create("DPanel")			g_VoicePanelList_HSP:ParentToHUD()			g_VoicePanelList_HSP:SetPos(ScrW() - 260, 100)			g_VoicePanelList_HSP:SetSize(250, ScrH() - 200)		g_VoicePanelList_HSP:SetDrawBackground(false)				print("[HSP] Removed and replaced shitty voice panel")		hook.Remove("Think", "ReplaceGarrysVoice")	endend)
