
----------------------------------------
--         2014-07-12 20:32:49          --
------------------------------------------
--[[	=== HSP Plugin Module ===	cl_UHNode, v1.0	Replace the icons for stuff with the UH logo]]local function NewAddNode(self, strName, strIcon)	self:CreateChildNodes()		local pNode = vgui.Create("DTree_Node", self)		pNode:SetText(strName)		pNode:SetParentNode(self)		pNode:SetRoot( self:GetRoot() )				if strName == "United Hosts" then			strIcon = "hsp/uh_16.png"		end				pNode:SetIcon(strIcon)		pNode:SetDrawLines( !self:IsRootNode() )	self:InstallDraggable(pNode)		self.ChildNodes:Add(pNode)	self:InvalidateLayout()		return pNodeend--derma.DefineControl( "DTree_Node", "Tree Node", PANEL, "DPanel" )local function DefineControl(name,desc,PANEL,base)	if name == "DTree_Node" and desc == "Tree Node" and base == "DPanel" then --Node!		PANEL.AddNode = NewAddNode	end		return derma.DefineControlOld(name,desc,PANEL,base)endHSP.Detour.Global("derma", "DefineControl", DefineControl)

----------------------------------------
--         2014-07-12 20:32:49          --
------------------------------------------
--[[	=== HSP Plugin Module ===	cl_UHNode, v1.0	Replace the icons for stuff with the UH logo]]local function NewAddNode(self, strName, strIcon)	self:CreateChildNodes()		local pNode = vgui.Create("DTree_Node", self)		pNode:SetText(strName)		pNode:SetParentNode(self)		pNode:SetRoot( self:GetRoot() )				if strName == "United Hosts" then			strIcon = "hsp/uh_16.png"		end				pNode:SetIcon(strIcon)		pNode:SetDrawLines( !self:IsRootNode() )	self:InstallDraggable(pNode)		self.ChildNodes:Add(pNode)	self:InvalidateLayout()		return pNodeend--derma.DefineControl( "DTree_Node", "Tree Node", PANEL, "DPanel" )local function DefineControl(name,desc,PANEL,base)	if name == "DTree_Node" and desc == "Tree Node" and base == "DPanel" then --Node!		PANEL.AddNode = NewAddNode	end		return derma.DefineControlOld(name,desc,PANEL,base)endHSP.Detour.Global("derma", "DefineControl", DefineControl)
