
_G.BLists = {


Black_RQTab = {
	["syshack"]			= false,
	["eradicate"]		= false,
	["bandsox"]	 		= false,
	["aah"]	 			= false,
	["qq"]	 			= false,
},


Black_RPF = {
	"includes/modules/gmcl_dispatchum.dll",
	"includes/modules/gmcl_bandsox.dll",
	"includes/modules/gmcl_iris.dll",
	"includes/modules/gm_iris.dll",
	"includes/modules/gm_qq.dll",
	"includes/modules/gmcl_qq.dll",
	"includes/modules/gmcl_aah.dll",
	"includes/modules/gm_aah.dll",
	"includes/modules/gmcl_coldfire.dll",
	"menu_plugins/coldfire.lua",
	"menu_plugins/bandsox.lua",
	"includes/modules/gm_filesystem.dll",
	"includes/modules/gmcl_herpes.dll",
	"includes/modules/gm_herpes.dll",
	
	"includes/modules/syshack.dll",
	"includes/modules/gm_syshack.dll",
	"includes/modules/gmcl_syshack.dll",
},


Black_CLDB = {
	"SHV2_Binds",
	"SHV3_Binds",
	"SHV4_Binds",
	
	"SHV2_Configs",
	"SHV3_Configs",
	"SHV4_Configs",
	
	"SHV2_ESPEnts",
	"SHV3_ESPEnts",
	"SHV4_ESPEnts",
	
	"SHV2_Options",
	"SHV3_Options",
	"SHV4_Options",
	
	"bc_ips",
	"Yb_Options",
	"EXIE_Options",
	
	"Bacon_Friends",
	"Bacon_Ents",
	"Bacon_ESPEnts",
	"Bacon_Changelog",
	"Bacon_Pass2",
	"SethHackV2_Options",
	"SethHackV2_ESPEnts",
	"SethHack_Friends",
	"SethHack_Ents",
	"SethHack_ESPEnts",
	"Spencer_Friends",
	"Spencer_Ents",
	"Spencer_ESPEnts",
},


Black_CVars = {
	"aimbot_enabled",
	"fap_speedhack_speed",
	"vh_speedhack_speed",
	"vh_silentaim",
	"vh_trigger",
	"vh_nospread",
	"vh_steamfriends",
	"vh_friendly",
	"vh_ignoreadmins",
	"vh_antisnap",
	"vh_antisnap_speed",
	"vh_aim_offset",
	"CV_CHEATS",
	"____sv_cheats",
	"____host_timescale",
	"____sv_consistency",
	"____mat_fullbright",
	"bktb_friendly_fire",
	"bktb_max_distance",
	"bktb",
	"speedhack_multiplier",
	"bk_aimbot_autoshoot",
	"bk_aimbot_ignore_steam_friends",
	"bk_aimbot_ignore_teammates",
	"bk_aimbot_use_friend_and_enemy_list",
	"bk_aimbot_silent",
	"bk_aimbot_silent_smooth",
	"bk_crosshair_actual_aim",
	"bk_norecoil",
	"bk_nospread",
	"bk_smoothlook",
	"bk_spinbot",
	"bk_spinbot_random",
	"mechgear_aimbot",
	"mechgear_aimbot_onattack",
	"mechgear_aimbot_useminimumoncommand",
	"mechgear_aimbot_minimum",
	"_ihack_esp",
	"_ihack_esp_npcs",
	"_ihack_esp_players",
	"_ihack_esp_weapons",
	"_ihack_esp_charms",
	"_ihack_esp_laser",
	"_ihack_aimbot_ignoreplayers",
	"_ihack_aimbot_ignorenpcs",
	"_ihack_aimbot_ignorefriends",
	"_ihack_aimbot_ignoreadmins",
	"_ihack_aimbot_friendlyfire",
	"_ihack_aimbot_auto",
	"_ihack_aimbot_fakeview",
	"_ihack_aimbot_nospread",
	"_ihack_misc_alwaysnospread",
	"_ihack_misc_fov",
	"_ihack_misc_disconnectmsg",
	"_ihack_ttt_showbodys",
	"_ihack_ttt_ignorefellowdetectives",
	"_ihack_ttt_ignorefellowtraitors",
	"Aim_Enabled",
	"Aim_NoRecoil",
	"Misc_Spam",
	"AC_Misc_Bhop",
	"Coma_Misc_LogIPs",
	"Coma_Misc_ULXAntiGag",
	"Coma_Misc_Date",
	"Coma_Misc_Spammer",
	"Coma_SlowSpeedHack",
	"Coma_SH_CheatsOff",
	"Coma_SHSpeed",
	"Coma_HostFrameRate",
	"Coma_HostTimeScale",
	"Coma_AimBot_SmoothAim",
	"Coma_AimBot_SmoothAimSpeed",
	"Coma_AimBot_Autoshoot",
	"Coma_AimBot_NoRecoil",
	"Coma_AimBot_NoSpread",
	"Coma_AimBot_IgnoreSteamFriends",
	"Coma_AimBot_IgnoreAdmins",
	"Coma_AimBot_FriendlyFire",
	"Coma_AimBot_IgnoreTraitorFriends",
	"SB_Aim_Enabled",
	"hake_shouldrun",
	"SB_Aim_FF",
	"SB_Aim_Offset",
	"SB_Aim_Steam",
	"SB_Aim_NoRecoil",
	"SB_Misc_Spam",
	"fhack",
	"fhackmodel",
	"fhackrage",
	"anthrax_killonsight",
	"anthrax_velocitypredict",
	"Smelly_Misc_LogIPs",
	"metalslave_aimbot_enabled",
	"mh_ab_enabled",
	"mh_ab_ffa",
	"mh_ab_nospread",
	"mh_ab_priority",
	"mh_ab_fov",
	"mh_ab_offset",
	"mh_ab_auto",
	"mh_esp_enabled",
	"mh_esp_mode",
	"mh_esp_names",
	"mh_esp_health",
	"mh_esp_reveal",
	"mh_esp_revent",
	"mh_esp_fov",
	"mh_rearview",
	"mh_ungag",
	"cf_host_timescale",
	"cf_aim_enabled",
	"cf_bunnyhop_minspeed",
	"cf_lockdownlua",
	"cf_checkdormantplayers",
	"cf_bunnyhopspace",
	"cf_bunnyhop",
	"cf_collectgarbage",
	"cf_pingpredict",
	"cf_updatemenucomponents",
	"cf_logs_level",
	"cf_logs_enabled",
	"cf_traitormode",
	"cf_spinbot",
	"cf_esp_drawcrosshair",
	"cf_esp_usesmallerfont",
	"cf_esp_drawtextinfo",
	"cf_esp_drawweapons",
	"cf_esp_drawmodels",
	"cf_esp_outlinemodels",
	"cf_esp_draweyeangles",
	"cf_esp_minespdistance",
	"cf_esp_maxespdistance",
	"cf_esp_entitytransparencydiameter",
	"cf_esp_entitytranspare",
	"cf_esp_enabled",
	"cf_esp_onlydrawtraitors",
	"cf_aim_nospreadonfire",
	"cf_aim_ucmdfire",
	"cf_aim_snaponfiretime",
	"cf_aim_snaponfire",
	"cf_aim_offsetz",
	"cf_aim_predictionseed",
	"cf_aim_nospread",
	"cf_aim_enemymode",
	"cf_aim_autoreload",
	"cf_aim_autofire",
	"cf_aim_checkpartialhits",
	"cf_aim_fakeview",
	"cf_aim_antisnapspeed",
	"cf_aim_antisnap",
	"cf_aim_velocityprediction",
	"cf_aim_ignorelos",
	"cf_aim_maxangledifference",
	"cf_aim_bonemode",
	"cf_aim_targetmode",
	"cf_aim_onlytargettraitors",
	"cf_aim_targetsteamfriends",
	"cf_aim_targetadmins",
	"cf_aim_targetfriends",
	"cf_aim_friendlyfire",
	"cf_aim_targetnpcs",
	"cf_aim_maxdistance",
	"cf_aim_enabled",
	"Isis_Esp",
	"Isis_Esp_Health",
	"Isis_Esp_Box",
	"Isis_Esp_Warnings",
	"Isis_Esp_Traitor",
	"Isis_Esp_Admins",
	"Isis_Esp_ShowC4",
	"Isis_Esp_Chams",
	"Isis_Misc_AntiGag",
	"Isis_Misc_ShowStatus",
	"Isis_Misc_Bunnyhop",
	"Isis_Misc_RemoveSky",
	"Isis_Misc_Crosshair",
	"Isis_Aimbot_NoRecoil",
	"Isis_Aimbot_IgnoreSteam",
	"Isis_Aimbot_Friendlyfire",
	"Isis_Aimbot_FixView",
	"Isis_Aimbot_AutoShoot",
	"Isis_Aimbot_NoSpread",
	"Isis_Aimbot_Offset",
	"Isis_Aimbot_AimSpot",
	"Isis_Speedhack_Speed",
	"Isis_Other_AutoReminder",
	"qq_ttt_predict_nade",
	"qq_antiaim_mode",
	"qq_fakeview_enabled",
	"qq_debug",
	"aah_log",
	"aah_logpath",
	"aah_blockac",
	"aah_bypassse",
	"aah_hash",
	"DragonBot_Esp",
	"DragonBot_Esp_Health",
	"DragonBot_Esp_Distance",
	"DragonBot_Esp_Admin",
	"DragonBot_Bhop",
	"DragonBot_Rp_Esp",
	"DragonBot_Chams",
	"DragonBot_Line",
	"DragonBot_Light",
	"DragonBot_Trigger",
	"DragonBot_TTT",
	"DragonBot_Aimbot_IgnoreSteam",
	"DragonBot_Aimbot_Friendlyfire",
	"DragonBot_Aimbot_IgnoreAdmins",
	"DragonBot_SmoothAim_Enabled",
	"DragonBot_Smooth_Speed",
	"DragonBot_Aimbot_Norecoil",
	"DragonBot_AimKeySave",
	"DragonBot_MenuKeySave",
	"DragonBot_PropKeySave",
	"triggerbot_enabled",
	"aimbot_enabled",
	"asb_bone",
	"asb_fov",
	"asb_los",
	"asb_players",
	"asb_shoot",
	"asb_trigger",
	"sw_aim",
	"sw_norecoil",
	"sw_aimonfire",
	"sh_aim",
	"sh_aimonfire",
	"sh_norecoil",
	"anacletobot",
	"anacletobot_target",
	"anacletobot_maxdist",
	"+ares_aim",
	"ink_propkill",
	"sh_print_traitors",
	"Ares_Misc_Bhop",
	"Ares_Misc_Keypad",
	"Ares_Misc_LogIPs",
	"Ares_Misc_ULXAntiGag",
	"Ares_Traitor",
	"Ares_ESP_C4Detection",
	"Ares_SlowSpeedHack",
	"Ares_SH_CheatsOff",
	"Ares_SHSpeed",
	"Ares_HostFrameRate",
	"Ares_HostTimeScale",
	"Ares_AimBot_SmoothAim",
	"Ares_AimBot_SmoothAimSpeed",
	"Ares_AimBot_Autoshoot",
	"Ares_AimBot_NoRecoil",
	"Ares_AimBot_NoSpread",
	"Ares_AimBot_IgnoreSteamFriends",
	"Ares_AimBot_IgnoreAdmins",
	"Ares_AimBot_FriendlyFire",
	"Ares_AimBot_IgnoreTraitorFriends",
	"ms_host_timescale",
	"ms_sv_cheats",
	"MAim_Targetmode",
	"MAim_MaxDistance",
	"MAim_MaxAngle",
	"MAim_FF",
	"MAim_Autoshoot",
	"MAim_MissShots",
	"MAim_Antisnap",
	"MAim_AntisnapSpeed",
	"M_Norecoil",
	"M_NoSpread",
	"speedhack_speed",
	"x_enabled",
	"Hax_NameTags",
	"Hax_SaveView",
	"Hax_ShowCrosshair",
	"Hax_ShowCrosshair2",
	"Hax_WallHackStyle",
	"Hax_SmoothAim",
	"Hax_SmoothAimSpeed",
	"Hax_DrawParticles",
	"Hax_TriggerBot",
	"Hax_TriggerBot2",
	"Hax_IgnoreSteamFriends",
	"Hax_MaxWallHackDist",
	"Hax_IgnoreTeam",
	"Hax_AimFov",
	"TB_AimFov",
	"TB_AimTeam",
	"TB_NameTags",
	"TB_NTAdmin",
	"TB_NTHealth",
	"TB_NTAlpha",
	"TB_FakeView",
	"TB_TargetPlayers",
	"TB_TargetNPCs",
	"TB_AntiSnap",
	"TB_AntiSnapSpeed",
	"AimAssistSA",
	"AimAssistFV",
	"ATTargetPlayers",
	"ATTargetNPCs",
	"ATIgnoreSteam",
	"ATIgnoreDistance",
	"ATAimDistance",
	"ATWallHack",
	"ATAimRadius",
	"ATNPCNames",
	"h_sv_cheats",
	"h_host_timescale",
	"h_host_framerate",
	"lymes_enable_hack_killhead_shotter",
	"lymes_enable_seethrough_esphack",
	"lymes_remotelua_hake",
	"lymes_remotelua_hack",
	"lymes_enable_autoheadshoot",
	"Neon_AimBot_ShowAimStatus",
	"Neon_AimBot_SmoothAimEnabled",
	"Neon_AimBot_SmoothAimSpeed",
	"Neon_AimBot_IgnoreFriends",
	"Neon_AimBot_IgnoreAdmins",
	"Neon_AimBot_Friendlyfire",
	"Neon_AimBot_NoRecoil",
	"Neon_AimBot_AimOffset",
	"Neon_AimBot_AimBone",
	"Neon_AimBot_AimMode",
	"Neon_AimBot_IgnoreSteamFriends",
	"Neon_PlayerESP",
	"Neon_PlayerESP_Health",
	"Neon_PlayerESP_ShowAll",
	"Neon_NPCESP",
	"Neon_PlayerFullBright",
	"Neon_PlayerWireFrame",
	"Neon_MoneyPrinterESP",
	"Neon_MoneyESP",
	"Neon_ShipmentESP",
	"Neon_FullBright",
	"Neon_Gray",
	"Neon_WorldWireFrame",
	"Neon_PlayerBox",
	"Neon_Bhop",
	"Neon_ULXAntiGag",
	"Neon_NikeSpeed",
	"Neon_HostTimeScale",
	"Neon_SpeedHack_CheatsOff",
	"Neon_Traitor",
	"Neon_KeypadHack",
	"Neon_WeaponsESP",
	"Neon_AimBot_TriggerBot",
	"Neon_PlayerWallHackFull",
	"Neon_DynamicLight",
	"Neon_DynamicLightSize",
	"Neon_LogPlayerIPs",
	"Neon_CrossHair",
	"Neon_CrossHair_Red",
	"Neon_CrossHair_Green",
	"Neon_CrossHair_Blue",
	"Neon_C4Detection",
	"hermes_misc_antiaimr_antiaim",
	"hermes_misc_antiaimy_antiaim",
	"hermes_misc_antiaimp_antiaim",
	"hermes_misc_antiaimduck_antiaim",
	"hermes_misc_antiaimrandom_antiaim",
	"hermes_misc_antiaim_antiaim",
	"hermes_misc_zoomamount_zoom",
	"hermes_misc_zoomontrigger_zoom",
	"hermes_misc_zoomonaim_zoom",
	"hermes_misc_zoomalways_zoom",
	"hermes_misc_zoom_zoom",
	"hermes_misc_speedhackspeed_speedhack",
	"hermes_misc_speedhack_speedhack",
	"hermes_misc_particles_globals",
	"hermes_misc_fullbrightg_globals",
	"hermes_misc_radarradius_radar",
	"hermes_misc_radarspin_radar",
	"hermes_misc_radarname_radar",
	"hermes_misc_radar_radar",
	"hermes_misc_crosshairlength_crosshair",
	"hermes_misc_crosshairgap_crosshair",
	"hermes_misc_crosshair_crosshair",
	"hermes_misc_crosshairtype_crosshair",
	"hermes_misc_ulxantigag_misc",
	"hermes_misc_autopistol_misc",
	"hermes_misc_bunnyhop_misc",
	"hermes_misc_namesteal_misc",
	"hermes_esp_asusval_asus",
	"hermes_esp_asusmdl_asus",
	"hermes_esp_asus_asus",
	"hermes_esp_visiblechams_chams",
	"hermes_esp_fullbright_chams",
	"hermes_esp_walltype_chams",
	"hermes_esp_vehiclese_entities",
	"hermes_esp_ragdollse_entities",
	"hermes_esp_weaponse_entities",
	"hermes_esp_entityliste_entities",
	"hermes_esp_enablee_entities",
	"hermes_esp_boxn_npcs",
	"hermes_esp_enablen_npcs",
	"hermes_esp_adminlist_players",
	"hermes_esp_friendsmark_players",
	"hermes_esp_barrel_players",
	"hermes_esp_weapon_players",
	"hermes_esp_health_players",
	"hermes_esp_name_players",
	"hermes_esp_enemyonly_players",
	"hermes_esp_enable_players",
	"hermes_esp_optical_players",
	"hermes_esp_fadelength_general",
	"hermes_esp_maxshow_general",
	"hermes_esp_enablefade_general",
	"hermes_esp_font_general",
	"hermes_aim_novisspread_accuracy",
	"hermes_aim_norecoil_accuracy",
	"hermes_aim_nospread_accuracy",
	"hermes_aim_togglename_hud",
	"hermes_aim_toggle_hud",
	"hermes_aim_triggerdistance_triggerbot",
	"hermes_aim_triggernospread_triggerbot",
	"hermes_aim_triggerkey_triggerbot",
	"hermes_aim_triggerbot_triggerbot",
	"hermes_aim_ignorevehicle_targeting",
	"hermes_aim_ignoreghost_targeting",
	"hermes_aim_ignoretraitor_targeting",
	"hermes_aim_ignoreteam_targeting",
	"hermes_aim_ignoresteam_targeting",
	"hermes_aim_ignoreadmin_targeting",
	"hermes_aim_targetnpc_targeting",
	"hermes_aim_targetplayer_targeting",
	"hermes_aim_friendslist_targeting",
	"hermes_aim_predictply_aimbot",
	"hermes_aim_predicttar_aimbot",
	"hermes_aim_smoothaimspeed_aimbot",
	"hermes_aim_fov_aimbot",
	"hermes_aim_offset_aimbot",
	"hermes_aim_disableafterkill_aimbot",
	"hermes_aim_holdtarget_aimbot",
	"hermes_aim_smoothaim_aimbot",
	"hermes_aim_velocitychecks_aimbot",
	"hermes_aim_loscheck_aimbot",
	"hermes_aim_silentaim_aimbot",
	"hermes_aim_autoshoot_aimbot",
	"hermes_aim_prediction_aimbot",
	"hermes_aim_aimmode_aimbot",
	"hermes_aim_aimtype_aimbot",
	"hermes_load",
	"hermes_host_timescale",
	"hermes_pato",
	"hermes_sv_cheats",
	"hermes_mat_fullbright",
	"hermes_r_drawparticles",
	"_framerate",
	"_timescale",
	"_cheats",
	"2_r_drawothermodels",
	"2_sv_cheats",
	"2_host_timescale",
	"1_r_drawothermodels",
	"1_sv_cheats",
	"1_host_timescale",
	"seb_enable",
	"sh_enabled",
	"SethHack_allow_cheats_default",
	"SethHack_ff",
	"SethHack_Chams",
	"SethHack_NPConly",
	"SethHack_Entonly",
	"SethHack_Plyonly",
	"SethHack_LockY", 
	"SethHack_Enemy_Compensation",
	"SethHack_Me_Compensation",
	"SethHack_TMW",
	"SethHack_Ignore_SteamFriends",
	"SethHack_Ignore_Admins",
	"SethHack_Trigger_Bot",
	"SethHack_RestrictFOV_Value",
	"SethHack_AimSmooth",
	"SethHack_Mode",
	"SethHack_espplayeron",
	"SethHack_espunhideon",
	"SethHack_espmode",
	"SethHack_espcross",
	"SethHack_espitemon", 
	"SethHack_espvehicleon",
	"SethHack_espnpcon",
	"SethHack_espweaponon",
	"SethHack_esptrans",
	"SethHack_adminlist",
	"SethHack_drawclassname",
	"SethHack_showcmds",
	"SethHack_blacklistcmds",
	"SethHack_showumsgs",
	"SethHack_autoreload",
	"SethHack_crosshair",
	"SethHack_chams2",
	"SethHack_bhop",
	"SethHack_spinbot",
	"SethHack_chatspam",
	"SethHack_chatspam_interval",
	"SethHack_enable_filelogs",
	"SethHack_enable_sendlualog",
	"SethHack_enable_iplogs",
	"SethHack_enable_dslogs",
	"SethHack_speedfactor",
	"SethHack_gamemodeview",
	"SethHack_clientnoclip",
	"SethHack_always_nospread",
	"Ink_Esp_Admin",
	"Ink_Bhop",
	"Ink_Trigger",
	"Ink_TTT",
	"Ink_AntiGag",
	"Ink_Aimbot_IgnoreSteam",
	"Ink_Aimbot_Friendlyfire",
	"Ink_Aimbot_IgnoreAdmins",
	"Ink_SmoothAim_Enabled",
	"Ink_Smooth_Speed",
	"Aimbot_Offset",
	"Ink_Aimbot_Norecoil",
	"Ink_Key",
	"Ink_Func",
	"Ink_AimKeySave",
	"Ink_MenuKeySave",
	"Ink_PropKeySave",
	"ihpublicaimbot_enabled",
	"fap_aimbot_toggle",
	"Nishack_Triggerbot_Enabled",
	"sh_wallhack_dist",
	"pb_aim_trigger",
	"TB_BlockRCC",
	"trooper_aimbot",
	"trooper_autoshoot",
	"trooper_norecoil",
	"pb_load",
	"bc_norecoil",
	"bc_bouncy",
	"wots_buddy_attack",
	"wots_aimbot_teammode",
	"wots_aimbot_mouselock",
	"fap_aim_checkpartialhits",
	"fap_aim_enabled",
	"fap_aim_friendlyfire",
	"fap_aim_targetnpcs",
	"fap_aim_autofire",
	"fap_aim_autoreload",
	"fap_aim_bonemode",
	"fap_aim_targetfriends",
	"fap_aim_targetsteamfriends",
	"fap_aim_targetmode",
	"fap_aim_nospread",
	"fap_aim_maxdistance",
	"fap_aim_targetadmins",
	"fap_aim_antisnap",
	"fap_aim_norecoil",
	"fap_aim_antisnapspeed",
	"fap_aim_maxangle",
	"fap_aim_snaponfire",
	"fap_aim_snaponfiretime",
	"fap_aim_onlytargettraitors",
	"fap_aim_velocityprediction",
	"fap_aim_checknpcrelationship",
	"fap_checkforupdates",
	"fap_shouldload",
	"fap_enablekeybinding",
	"fap_bunnyhop",
	"fap_bunnyhopspeed",
	"fap_dontchecklos",
	"fap_alwaysloadhardcopy",
	"fap_ucmdfire",
	"host_timescale",
	"sv_cheats",
	"host_framerate",
	"net_blockmsg",
},


Black_RCC = {
	["+attack"]	= true,
	["+reload"]	= true,
},


Black_RCCTab = {
	"mint_toggle",
	"phage_menu",
	"mfsp_menu",
	"+asp_antidof",
	"+rape",
	"+iliek2rape",
	"togglerape",
	"aimbot_unload",
	"aimbot_reload",
	"+vh_speed",
	"+vh_menu",
	"+fap_speed",
	"yb_menu"
	"norecoil"
	"+yb_menu"
	"+ab_aim"
	"+spedd",
	"int_speedamount",
	"int_runlua",
	"+chiefeh",
	"mh_open",
	"_SG.ToggleBypass",
	"_SG.ToggleSE",
	"lua_run_override",
	"micspamToggle",
	"bk_menu",
	"+bk_attack",
	"+speedhack",
	"bktb_toggle",
	"bktb_on",
	"bktb_off",
	"+bktb",
	"ForceCVar",
	"runfile",
	"+bk_forward",
	"+bk_back",
	"+bk_left",
	"+bk_right",
	"+aimbot",
	"+bk_attack",
	"int_menu",
	"+qq_noob2",
	"+turbojordans",
	"+qq_noob",
	"th_menu",
	"th_aimbot_on",
	"+ph_speed",
	"+ph_speedhack",
	"+ph_aim",
	"ph_aimhack",
	"+ph_aimhack",
	"ph_aimhack",
	"+autofire",
	"ph_hackmenu",
	"+Exmenu",
	"+mechgear_shot",
	"+wurst_silent",
	"+wurst_getpos",
	"+angel_menu",
	"printips",
	"+orgmenu",
	"+BT",
	"+woG",
	"+orgmenu",
	"+cherry_menu",
	"+cherry_aim",
	"ProcessCommandBait",
	"omen_spin",
	"+propthrow",
	"+scriptenforcer_menu",
	"+comtarg",
	"bs_hooks",
	"hake_menu",
	"asp_rotate",
	"asp_menu",
	"+hake_aim",
	"fls_menu",
	"sh_alive",
	"bs_detector",
	"bs_doeffect",
	"gf_admin",
	"+uberslow",
	"seb_openscript",
	"bs_menu",
	"+bs_getpos",
	"odius_zoom",
	"iHack_FullBright",
	"+ihack_speedhack",
	"ihack_speedhack",
	"FCvar",
	"+ihack_aimbot",
	"ihack_menu",
	"ihack_lua_scriptrun",
	"ihack_lua_stringrun",
	"lua_crypt",
	"spinhack",
	"at_autoaim_on",
	"at_autoaim_off",
	"+speed_hack",
	"AddSpeed",
	"_botjump",
	"_botvelocity",
	"+speedhake",
	"cub_aim_toggle",
	"cubHack",
	"cubHackLaser",
	"gen_run",
	"gen_lua",
	"+Coma_Pointer",
	"Coma_Menu_AimBot",
	"Coma_Menu_Misc",
	"Coma_ForceImpulse",
	"+Coma_SlowNikes",
	"+Coma_Nikes",
	"+Coma_PropKill",
	"AC_toggle",
	"AC_menu",
	"AC_Misc_NameSteal",
	"+AC",
	"+AC_Speed",
	"+SB_Aim",
	"SB_Misc_Flood",
	"SB_Misc_Crash",
	"+SB_Speed",
	"SB_Done",
	"+sbot_aimbot",
	"+Demibot_aim",
	"fls_joinspam",
	"fls_spamtimer",
	"+coma_aim",
	"coma_aim",
	"coma_menu",
	"+coma_menu",
	"+exie_aim",
	"+exie_speed",
	"+exie_menu",
	"exie_menu",
	"Menu_H4x",
	"fb_fov",
	"fb_runscript",
	"+fb",
	"fb_load",
	"omen_reload",
	"omen_menu",
	"+omen_aim",
	"+omen_speed",
	"+zaim",
	"Obelus_Update",
	"Obelus_Menu",
	"+Obelus_Menu",
	"+Obelus_Aim",
	"Obelus_Aim",
	"+Obelus_Speed",
	"+speedhack",
	"bs_force_load",
	"lua_logo_reload",
	"lua_run_quick",
	"bs_reload",
	"bs_unload",
	"bs_inject",
	"+bs_getview",
	"+bs_getpos",
	"odius_menu",
	"+odius_aim",
	"+odius_pkmode",
	"fl_fillhp",
	"+sp33d",
	"+b_aim",
	"server_command",
	"toggle_target",
	"target_menu",
	"+aim",
	"anthrax_banadmins",
	"anthrax_demoteadmins",
	"lol_rcon",
	"+follow_aim",
	"cs_lua",
	"anthrax_filemenu",
	"+anthrax_floodserver",
	"getrcon",
	"exploit_admin",
	"exploit_bans",
	"exploit_cfg",
	"exploit_rcon",
	"+fls_joinspam",
	"fls_execlua",
	"fls_loadlua",
	"fls_weightcrash_setup",
	"lethal_rotate",
	"lethal_menu",
	"lix_lesp_reload",
	"join_stopspam",
	"fls_rotate",
	"lix_lesp_rotate1",
	"lix_lesp_rotate2",
	"lix_lesp_rotate3",
	"lix_lesp_rotate",
	"sv_add1",
	"sv_run1",
	"exploit",
	"print_server_cfg",
	"print_file",
	"dump_remote_lua2",
	"print_file_listing_load",
	"sv_printdirfiles",
	"sv_printdir",
	"fuck_admins",
	"aah_setupspeedhack",
	"_timescale",
	"+enabled",
	"+triggerbot",
	"inc_g",
	"Smelly_Print_IPs",
	"Smelly_Clear_IPs",
	"+autofire",
	"spinlol",
	"ox_hacexploit",
	"pp_pixelrender",
	"startspam",
	"stopspam",
	"+makesound",
	"makesound",
	"+pk",
	"ThrowMagneto",
	"trowmagneto",
	"kon_chatspam",
	"kon_stopspam",
	"RLua",
	"Orgflashstyle1",
	"Orgflashstyle2",
	"se_add",
	"mh_unlock",
	"mh_toggleflag",
	"mh_keypad",
	"mh_open",
	"mh_turn180",
	"mh_esp_rehook",
	"mh_owners",
	"+qq_menu",
	"+qq_nospread_triggerbot",
	"+qq_speedhack_speed",
	"go_unconnected",
	"+nou",
	"metalslave_aimbot_reload",
	"metalslave_aimbot_toggle",
	"metalslave_aimbot_menu",
	"metalslave_chams_reload",
	"qq_menu",
	"aah_renamevar",
	"aah_renamecmd",
	"aah_updatelogsettings",
	"aah_reload",
	"aah_login",
	"+qq_speedhack_speed",
	"+qq_aimbot_enabled",
	"qq_aimbot_quick_shot",
	"cf_aim_toggle",
	"+cf_bunnyhop",
	"CrashTheServer",
	"UltraCrashTheServer",
	"+cal_menu",
	"+cal_aim",
	"Isis_Menu_Reload",
	"+Isis_Menu",
	"+kilos_aim",
	"Isis_InteractC4",
	"+Isis_Aim",
	"Isis_Spin",
	"+Isis_Speed",
	"cf_freeze",
	"cf_menu",
	"+cf_aim",
	"cf_menu_toggle",
	"+cf_speed",
	"+DragonBot_Aim",
	"DragonBot_menu",
	"sh_luarun",
	"2a1f3e4r5678j9r9w8j7d54k6r2a84",
	"falco_runlooah",
	"falco_openlooah",
	"falco_rotate1",
	"falco_rotate2",
	"frotate",
	"+falco_makesound",
	"falco_makesound",
	"+hermes_aim",
	"_PoKi_menu_reload",
	"spamjeeps",
	"spamchair",
	"falco_hotkey",
	"falco_hotkeyList",
	"+cb_aim",
	"vlua_run",
	"sh_print_traitors",
	"+sh_triggerbot",
	"sh_runscripts",
	"sh_togglemenu",
	"gen_aim",
	"gen_autoshoot",
	"gen_speed",
	"+gen_bhop",
	"+gen_aim",
	"+gen_speed",
	"Ares_ForceImpulse",
	"Ares_Menu_ESP",
	"Ares_Menu_Misc",
	"Ares_Menu_AimBot",
	"+Ares_Pointer",
	"+Ares_SlowNikes",
	"+Ares_Aim",
	"+Ares_Nikes",
	"+Ares_PropKill",
	"Ares_Print_IPs",
	"Ares_Clear_IPs",
	"+MAim",
	"ms_pato",
	"+MSpeed",
	"ms_sv_cheats",
	"+MPause",
	"+zumg",
	"_fap_reload_menu",
	"ThermHack_ToggleMenu",
	"cub_toggle",
	"hera_convar_get",
	"hera_convar_set",
	"hera_include",
	"hera_runstring",
	"Monster_Menu",
	"x_reload",
	"x_menu",
	"+fox_aim",
	"+hax_rapidfire",
	"+Hax_aimbot",
	"+Hax_Menu",
	"+Hax_Zoom",
	"+hera_speed",
	"+TB_Bhop",
	"TB_Console",
	"+ATMenu",
	"+AimAssist",
	"+AimBHOP",
	"ReloadAA",
	"h_runscript",
	"h_openscript",
	"h_firewall",
	"h_gtower_debug",
	"h_bo_thirdperson",
	"h_helxa_encrypt",
	"h_helxa_decrypt",
	"bypass_se",
	"+hax_admin",
	"Neon_LoadMenu",
	"+Neon_Aim",
	"+Neon_SpeedHack",
	"+Neon_PropKill",
	"Neon_SayTraitors",
	"Neon_ForceCheats",
	"+neon_menu",
	"sb_toggle",
	"sh_menu",
	"sh_togglemenu",
	"+sh_triggerbot",
	"sh_print_traitors",
	"asp_reload",
	"+sh_bhop",
	"asp_uploaddupe",
	"+li_bhop",
	"hake_load",
	"SE_ByPass",
	"se_on",
	"+Aim",
	"SpamTime",
	"SethHack_panic",
	"SethHack_lua_run",
	"SethHack_lua_openscript",
	"+SethHackToggle",
	"+SethHack_Menu",
	"deathrun_qq",
	"+SethHack_Speed",
	"SethHack_ff_toggle",
	"SethHack_wallhack_wire",
	"SethHack_wallhack_player",
	"SethHack_Clear_All",
	"SethHackToggle",
	"SethHack_triggerbot_toggle",
	"SethHack_AddNPCfriend",
	"SpamMenu",
	"Inkbot_Crack",
	"Ink_LoadMenu",
	"+Propkill",
	"+int_aimbot",
	"+Ink_Aim",
	"Ink_menu",
	"ihpublicaimbot_reload",
	"ihpublicaimbot_toggle",
	"+ihaimbot",
	"ihpublicaimbot_menu",
	"lagon",
	"lagoff",
	"fap_aimbot_toggle",
	"+Nis_Menu",
	"+sh_bhop",
	"pb_aim_trigger",
	"pb_load",
	"+TB_Aim",
	"+TB_Menu",
	"+TB_RapidFire",
	"+TB_Speed",
	"Spam_Props-V2",
	"Spam_Chat-v2",
	"+bc_aimbot",
	"-bc_aimbot",
	"+bc_spamprops",
	"bc_ips",
	"+bc_speedshoot",
	"bc_reload",
	"bc_unload",
	"wots_attack",
	"_fap_reload",
	"SE_AddFile",
	"SE_RemoveFile",
	"SE_LoadScripts",
	"+pb_aim",
	"pb_menu",
	"Spam_Props",
	"Spam_Chat",
	"+li_aim",
	"+li_menu",
	"li_menu",
	"+sh_menu",
	"+Mawpos",
	"gzfaimbot_reload",
	"gzfaimbot_toggle",
	"gzfaimbot_enabled",
	"asb_base_reload",
	"asb_base_unload",
	"+shenbot_aimbot",
	"shenbot_menu",
	"shenbot_bunnyhoptoggle",
	"-shenbot_aimbot",
	"SpinBot_on",
	"aimbot_off",
	"_aimbot",
	"lua_dofile_cl",
	"lua_dostring_cl",
	"ph0ne_aim",
	"ph0ne_aimcancel",
	"ph0ne_autoshoot",
	"+trooper_menu",
	"BMpublicaimbot_reload",
	"BMpublicaimbot_toggle",
	"+BMaimbot",
	"BMpublicaimbot_menu",
	"spamchat",
	"_fap_menu_reload",
	"rs",
	"sh_triggerbot",
	"sh_showips",
	"+sh_speed",
	"+sh_aim",
	"sh_toggleaim",
	"helix_chatspammer",
	"helix_undo",
	"helix_propspam",
	"helix_admins",
	"helix_rpnamespammer",
	"+helix_speed",
	"helix_crypto_binary",
	"helix_forcerandomname_on",
	"helix_forcerandomname_off",
	"helix_troll",
	"+helix_aim",
	"helix_cvarmenu",
	"formatlaser",
	"+Helix_Menu",
	"helix_reload",
	"helix_propspammer2",
	"helix_barrelbomb",
	"helix_unload",
	"helix_speed",
	"helix_blocklua",
	"helix_propspam_mdl",
	"helix_aim_bone",
	"helix_aim_crosshair",
	"helix_aim_fov",
	"helix_aim_los",
	"helix_aim_norecoil",
	"helix_aim_players",
	"helix_aim_shoot",
	"helix_aim_team",
	"helix_aim_trigger",
	"h_name",
	"+bb_menu",
	"bb",
	"ForceLaunch_BB",
	"jonsuite_unblockx",
	"bacon_lua_openscript",
	"+fox_aim",
	"discord1",
	"discord2",
	"hera_runstring",
	"aa_toggle",
	"Bacon_TriggerBotDelay",
	"Bacon_load",
	"bacon_chatspam",
	"bacon_namechange",
	"bacon_chatspam_interval",
	"bacon_norecoil",
	"Bacon_AntiSnap",
	"bacon_autoreload",
	"+hermes_menu",
	"+sykranos_is_sexier_then_hex",
	"sykranos_is_sexy_menu",
	"+hermes_speed",
	"AGT_AutoshootToggle",
	"AGT_AimBotToggle",
	"AGT_RandomName",
	"nbot_aimfixer",
	"nbot_speedoffset",
	"nbot_UseSelectedPerson",
	"nbot_autoshoot",
	"fap_enablekeybinding",
	"fap_bind",
	"fap_unbind",
	"lua_se2_load",
	"ah_cheats",
	"ah_changer",
	"ah_speed",
	"ah_aimbot_friends",
	"ah_aimbot",
	"ah_hooks",
	"ah_hookhide",
	"ah_name",
	"ah_antihook",
	"ah_reload",
	"ah_timestop",
	"setconvar",
	"fap_menu",
	"fap_checkforupdates",
	"fap_aim",
	"+fap_aim",
	"fap_aim_toggle",
	"lua_openscript_cl2",
	"raidbot_predictcheck",
	"aa_enabled",
	"BMaimbot",
	"+BMaimbot",
	"aimbot_headshots_on",
	"CBon_Reload_Script",
	"+CBon_menu",
	"ah_chatspammer",
	"ah_spammer",
	"ah_reload",
	"+ah_menu",
	"+nbot_options",
	"sm_fexec",
	"GAT_RandomName",
	"name_menu",
	"namechanger_on",
	"cl_name",
	"+wots_toggleimmunity",
	"send_file",
	"Bacon_Reload_Script",
	"fap_reload",
	"download_file",
	"upload_file",
	"plugin_load",
	"sethhack_load",
	"st_jumpspam",
	"force_cvar",
	"cl_docrash",
	"_fap_initshit",
	"SE_AddFile",
	"SE_RemoveFile",
	"SE_LoadScripts",
	"+namechanger",
	"RandomNCOn",
	"BlankNCON",
	"PsaySpamOn",
	"GayOn",
	"RatingSpammerOn",
	"+jbf_scan",
	"kennykill",
	"kenny_team",
	"kenny_bodyshots",
	"+kenny",
	"kenny_tagasshole",
	"kenny_addhit",
	"Kenny_noclip",
	"bacon_toggle",
	"Bacon_EntTriggerBot",
	"Bacon_Reload_Script",
	"+wots_spinhack",
	"wots_spinhack",
	"wire_button_model",
	"lol_togglestick",
	"lol_name",
	"lol_copy",
	"lol_fuckthis",
	"lol_barrel",
	"lol_setchat",
	"lol_chat",
	"lol_help",
	"lol_admins",
	"lol_adminalert",
	"lol_cancel",
	"lol_aim",
	"lol_headshot",
	"lol_teamshot",
	"wots_namecracker_menu",
	"wots_namecracker_on",
	"wots_namecracker_off",
	"wots_crash",
	"wots_lag_on",
	"wots_lag_off",
	"speedhack_speed",
	"SetCV",
	"+wowspeed",
	"+gofast",
	"+goslow",
	"JBF_off",
	"JBF_on",
	"JBF_headshots_off",
	"JBF_headshots_on",
	"JBF_enemysonly_on",
	"JBF_enemysonly_off",
	"JBF_playersonly_on",
	"JBF_playersonly_off",
	"_JBF_lagcompensation",
	"JBF_lagcompensation",
	"JBF_suicidehealth",
	"JBF_offset",
	"+BUTTFUCK",
	"entx_spazon",
	"entx_spazoff",
	"entx_setvalue",
	"+buttfuck",
	"fap_aim_enabled",
	"fap_aim_friendlyfire",
	"fap_aim_targetnpcs",
	"fap_aim_autofire",
	"fap_aim_autoreload",
	"fap_aim_bonemode",
	"fap_aim_targetfriends",
	"fap_aim_targetsteamfriends",
	"fap_aim_targetmode",
	"fap_aim_nospread",
	"fap_aim_maxdistance",
	"fap_aim_targetadmins",
	"fap_aim_antisnap",
	"fap_aim_norecoil",
	"fap_aim_antisnapspeed",
	"niggeron",
	"niggerff",
	"niggerfl",
	"niggersz",
	"niggernpc",
	"niggerw",
	"niggeri",
	"niggershd",
	"niggermxsh",
	"niggershit",
	"niggersd",
	"NameGenDerma",
	"+elebot",
	"+leetbot",
	"elebot_offset",
	"leetbot_offset",
	"elebot_minview",
	"leetbot_minview",
	"elebot_maxview",
	"leetbot_maxview",
	"elebot_boxsize",
	"leetbot_boxsize",
	"elebot_simplecolors",
	"leetbot_simplecolors",
	"elebot_targetteam",
	"leetbot_targetteam",
	"elebot_showadmin",
	"leetbot_showadmin",
	"elebot_filledbox",
	"leetbot_filledbox",
	"wots_attack",
	"+wots_menu",
	"wots_menu",
	"wots_megaspam",
	"wots_namegen_on",
	"wots_namegen_off",
	"name_change",
	"change_name",
	"name_changer",
	"+name_changer",
	"+Bacon_Menu",
	"+BaconToggle",
	"BaconToggle",
	"Bacon_triggerbot_toggle",
	"+Bacon_triggerbot_toggle",
	"Bacon_FF_Toggle",
	"aimbot_scan",
	"+aimbot_scan",
	"+aimbot",
	"aimbot",
	"entx_spazon",
	"entx_spazoff",
	"_aimbot",
	"_aimbot_headshots",
	"aimbot_offset",
	"entx_run1",
	"entx_run2",
	"entx_run3",
	"entx_run4",
	"entx_traceget",
	"entx_camenable",
	"+slobpos",
	"Bacon_Trigger_Bot",
	"+Bacon_Trigger_Bot",
	"Bacon_Ignore_SteamFriends",
	"Bacon_Mode",
	"gzfaimbot_reload",
	"gzfaimbot_toggle",
	"+gzfaimbot",
	"gzfaimbot",
	"gzfaimbot_menu",
	"at_autoaim_on",
	"at_autoaim_off",
	"at_changer_on",
	"at_changer_off",
	"at_norecoil_on",
	"at_norecoil_off",
	"at_menu",
	"_GBot_Off",
	"_GBot_Menu",
	"at_autoshoot_on",
	"at_autoshoot_off",
	"aa_reload",
	"aa_toggle",
	"+aa",
	"aa_menu",
	"+Mawpos",
	"+nBot",
	"+nbot_Options",
	"nbot_Options",
	"aimbot_on",
	"aimbot_hitbox",
	"aimbot_target_teamates",
	"aimbot_target_closest",
	"aimbot_target_clear",
	"+asb_bot",
	"asb_bot",
	"asb_options",
	"+asb",
	"asb",
	"asb_unload",
	"asb_reload",
	"asb_shoot",
	"+entinfo",
	"entinfo_target",
	"asb_shoot",
	"asb_nospread",
	"asb_players",
	"entinfo_targetplayer"
},


Black_LuaFiles = {
	--bandsox
	"includes/modules/*bandsox*.dll",
	"menu_plugins/*bandsox*.lua",
	"includes/enum/*bandsox*.lua",
	"vgui/*bandsox*.lua",
	"autorun/*bandsox*.lua",
	"autorun/client/*bandsox*.lua",	
	"*bandsox*.lua",
	
	--TurboBot
	"includes/modules/*eradicate*.dll",
	"includes/modules/*aspergers*.dll",
	"vgui/*aspergers*.lua",
	"autorun/*aspergers*.lua",
	"autorun/client/*aspergers*.lua",	
	"*aspergers*.lua",
	"vgui/*turbobot*.lua",
	"autorun/*turbobot*.lua",
	"autorun/client/*turbobot*.lua",	
	"*turbobot*.lua",	
	
	--ColdFire
	"includes/modules/*coldfire*.dll",
	"menu_plugins/*coldfire*.lua",
	"includes/enum/*coldfire*.lua",
	"vgui/*coldfire*.lua",
	"autorun/*coldfire*.lua",
	"autorun/client/*coldfire*.lua",	
	"*coldfire*.lua",
	
	--RCONExp
	"menu_plugins/*RCONExp*.lua",
	"includes/enum/*RCONExp*.lua",
	"vgui/*RCONExp*.lua",
	"autorun/*RCONExp*.lua",
	"autorun/client/*RCONExp*.lua",	
	"*RCONExp*.lua",
	
	--Exploit
	"menu_plugins/*sploit*.lua",
	"includes/enum/*sploit*.lua",
	"vgui/*sploit*.lua",
	"autorun/*sploit*.lua",
	"autorun/client/*sploit*.lua",	
	"*sploit*.lua",
	
	--Wut
	"qq/*.lua",
	"autorun/client/initb.lua",
	"includes/modules/gm_qq.dll",
	"includes/modules/gmcl_qq.dll",
	"includes/modules/gm_aah.dll",
	"includes/modules/gmcl_aah.dll",
	
	--Ares
	"includes/modules/gm_ares_core.dll",
	"autorun/client/gmod_op.lua",
	"gmod_op2.lua",
	
	--hermes
	"menu_plugins/ini.lua",
	"includes/modules/*hermes*.dll",
	"menu_plugins/*hermes*.lua",
	"includes/enum/*hermes*.lua",
	"vgui/*hermes*.lua",
	"autorun/*hermes*.lua",
	"autorun/client/*hermes*.lua",	
	"*hermes*.lua",
	--hermes:iplog
	"menu_plugins/*iplog*.lua",
	"includes/enum/*iplog*.lua",
	"vgui/*iplog*.lua",
	"autorun/*iplog*.lua",
	"autorun/client/*iplog*.lua",
	"*iplog*.lua",
	
	--FapHack
	"includes/modules/*faphack*.dll",
	"menu_plugins/*faphack*.lua",
	"includes/enum/*faphack*.lua",
	"vgui/*faphack*.lua",
	"autorun/*faphack*.lua",
	"autorun/client/*faphack*.lua",	
	"*faphack*.lua",
	"FapHack/*.lua",
	--Obelus
	"includes/modules/*Obelus*.dll",
	"menu_plugins/*Obelus*.lua",
	"includes/enum/*Obelus*.lua",
	"vgui/*Obelus*.lua",
	"autorun/*Obelus*.lua",
	"autorun/client/*Obelus*.lua",	
	"*Obelus*.lua",
	"Obelus/*.lua",
	
	--Isis
	"menu_plugins/*isis*.lua",
	"includes/enum/*isis*.lua",
	"vgui/*isis*.lua",
	"autorun/*isis*.lua",
	"autorun/client/*isis*.lua",	
	"*isis*.lua",
	"ass/Isis.lua",
	"includes/modules/gm_core.dll",
	"includes/modules/*no_core*.dll",
	"includes/modules/*no_fvar*.dll",
	"includes/modules/gmcl_pall.dll",
	
	--webz
	"menu_plugins/webz.lua",
	"includes/enum/webz.lua",
	"vgui/webz.lua",
	"autorun/webz.lua",
	"autorun/client/webz.lua",	
	"webz.lua",
	
	--trooper
	"trooper_v1_public.lua",	
	"autorun/trooper_v1_public.lua",
	"autorun/client/trooper_v1_public.lua",	
	"trooperhack.lua",	
	"autorun/trooperhack.lua",
	"autorun/client/trooperhack.lua",	
	
	--PB
	"menu_plugins/*pb_*.lua",
	"includes/enum/*pb_*.lua",
	"vgui/*pb_*.lua",
	"autorun/*pb_*.lua",
	"autorun/client/*pb_*.lua",	
	--INK
	"menu_plugins/INK.lua",
	"includes/enum/INK.lua",
	"vgui/INK.lua",
	"autorun/INK.lua",
	"autorun/client/INK.lua",	
	"INK.lua",
	
	--autoaim
	"autorun/AutoAim.lua",
	"autorun/client/AutoAim.lua",	
	"AutoAim.lua",
	
	--MintyScript
	"autorun/MintyScript.lua",
	"autorun/client/MintyScript.lua",	
	"MintyScript.lua",
	
	--NeonHack
	"includes/modules/*neon*.dll",
	"autorun/[NH]Core.lua",
	"autorun/client/[NH]Core.lua",	
	"[NH]Core.lua",
	"autorun/[NH]Loader.lua",
	"autorun/client/[NH]Loader.lua",	
	"[NH]Loader.lua",
	
	--asb
	"autorun/asb.lua",	
	"autorun/client/asb.lua",
	"asb.lua",
	"autorun/_TEMPLATE.lua",	
	"autorun/client/_TEMPLATE.lua",
	"_TEMPLATE.lua",
	"autorun/asb_base.lua",
	"autorun/client/asb_base.lua",
	"asb_base.lua",
	
	--Baconbot
	"includes/modules/*testbot*.dll",
	"includes/modules/*bbot*.dll",	
	"stuff/Clock.lua",
	"stuff/*bot*.lua",
	--v3
	"menu_plugins/*bbv3*.lua",
	"includes/enum/*bbv3*.lua",
	"vgui/*bbv3*.lua",
	"autorun/*bbv3*.lua",
	"autorun/client/*bbv3*.lua",
	"*bbv3*.lua",
	--v4
	"menu_plugins/*bbv4*.lua",
	"includes/enum/*bbv4*.lua",
	"vgui/*bbv4*.lua",
	"autorun/*bbv4*.lua",
	"autorun/client/*bbv4*.lua",
	"*bbv4*.lua",
	
	--hades
	"includes/modules/*hades*.dll",
	"menu_plugins/*hades*.lua",
	"includes/enum/*hades*.lua",
	"vgui/*hades*.lua",
	"autorun/*hades*.lua",
	"autorun/client/*hades*.lua",
	"*hades*.lua",
	"hades/*.lua",
	"hades/core/*.lua",
	
	--helix
	"includes/modules/*helix*.dll",
	"includes/modules/gm_p_*.dll",
	"includes/modules/gmcl_p_*.dll",
	"includes/modules/gm_p_base.dll",
	"includes/modules/gm_p_concmd.dll",
	"includes/modules/gm_p_cvar.dll",
	"includes/modules/gm_p_forcevar.dll",
	"includes/modules/gmcl_p_bypass.dll",
	"includes/modules/gmcl_p_misc.dll",
	"includes/modules/gmcl_p_umsg.dll",
	"menu_plugins/*helix*.lua",
	"includes/enum/*helix*.lua",
	"vgui/*helix*.lua",
	"autorun/*helix*.lua",
	"autorun/client/*helix*.lua",
	"*helix*.lua",
	"helix/*.lua",
	"helix/core/*.lua",
	
	--hera
	"includes/modules/*hera*.dll",
	"menu_plugins/*hera*.lua",
	"includes/enum/*hera*.lua",
	"vgui/*hera*.lua",
	"autorun/*hera*.lua",
	"autorun/client/*hera*.lua",
	"*hera*.lua",
	"hera/*.lua",
	"hera/core/*.lua",
	
	--THEODORE
	"menu_plugins/[THEODORE].lua",
	"includes/enum/[THEODORE].lua",
	"vgui/[THEODORE].lua",
	"autorun/[THEODORE].lua",
	"autorun/client/[THEODORE].lua",
	"[THEODORE].lua",	
	--JonSuite
	"includes/modules/*JonSuite*.dll",
	"JonSuite/Hacks/*.lua", 
	"JonSuite/*.lua",
	
	--random
	"autorun/client/ms_aimboat.lua",
	"autorun/ms_aimboat.lua",
	"autorun/I_laik_being_dum.lua",
	"autorun/client/I_laik_being_dum.lua",
	"autorun/waroftheservers.lua",
	"autorun/client/waroftheservers.lua",
	"autorun/hai.lua",
	"autorun/client/hai.lua",	
	"hai.lua",
	"autorun/fuckoff.lua",
	"autorun/client/fuckoff.lua",
	"fuckoff.lua",
	"autorun/AGT.lua",
	"autorun/client/AGT.lua",
	"AGT.lua",
	--seth
	"sh_run.lua",
	"autorun/sh_run.lua",
	"autorun/client/sh_run.lua",
	"Scripts/1*.lua",
	"Scripts/2*.lua",
	"Scripts/3*.lua",
	"Scripts/4*.lua",
	"Scripts/5*.lua",
	"Scripts/6*.lua",
	"Scripts/7*.lua",
	"Scripts/8*.lua",
	"Scripts/9*.lua",
	"shrun/*.lua",
	"lua/shrun/*.lua",
	"autorun/shrun/*.lua",
	"autorun/client/shrun/*.lua",
	"myfiles/*.lua",
	"lua/myfiles/*.lua",
	"autorun/myfiles/*.lua",
	"autorun/client/myfiles/*.lua",
	"dev/*bot*.lua",
	"dev/bbv3.lua",
	"dev/bbv4.lua",
	"dev/*hack*.lua",
	"dev/*crack*.lua",
	"dev/*exploit*.lua",
	"dev/*block*.lua",
	"dev/*convar*.lua",
	"dev/*cvar*.lua",
	"dev/*recoil*.lua",
	"dev/*hax*.lua",
	"dev/*h4x*.lua",
	"dev/*force*.lua",
	"dev/*cheat*.lua",
	"dev/*spam*.lua",
	"dev/*bypass*.lua",
	"dev/*troll*.lua",
	--BCScripts
	"scripts/*bot*.lua",
	"scripts/bbv3.lua",
	"scripts/bbv4.lua",
	"scripts/*hack*.lua",
	"scripts/*crack*.lua",
	"scripts/*exploit*.lua",
	"scripts/*block*.lua",
	"scripts/*convar*.lua",
	"scripts/*cvar*.lua",
	"scripts/*recoil*.lua",
	"scripts/*hax*.lua",
	"scripts/*h4x*.lua",
	"scripts/*force*.lua",
	"scripts/*cheat*.lua",
	"scripts/*spam*.lua",
	"scripts/*bypass*.lua",
	"scripts/*troll*.lua",
	"autorun/client/ips.lua",
	"autorun/ips.lua",
	
	--bypasses etc
	"includes/modules/*_odin*.dll",
	"includes/modules/*preproc*.dll",
	"includes/modules/gm_filesystem.dll",
	"includes/modules/*_thor*.dll",
	"includes/modules/*_fvar*.dll",
	"includes/modules/*_clua*.dll",
	"includes/modules/*crack*.dll",
	"includes/modules/gmcl_cmd.dll",
	"includes/modules/gmcl_sys.dll",
	"includes/modules/*hak*.dll",
	"includes/modules/*hake*.dll",
	"includes/modules/*solve*.dll",
	"includes/modules/*decz*.dll",
	"includes/modules/*deco*.dll",
	"includes/modules/gmcl_zeco.dll",
	"includes/modules/*dec0*.dll",
	"includes/modules/*_jell*.dll",
	"includes/modules/*spread*.dll",
	"includes/modules/*luamd5*.dll",
	"includes/modules/*_sh.dll",
	"includes/modules/gmcl_lh.dll",
	"includes/modules/*_sh1.dll",
	"includes/modules/*_sh2.dll",
	"includes/modules/*_sh3.dll",
	"includes/modules/*_se2.dll",
	"includes/modules/*_wshl.dll",
	"includes/modules/*hook*.dll",
	"includes/modules/*secret*.dll",
	"includes/modules/*unblock*.dll",
	"includes/modules/*byese2*.dll",
	"includes/modules/*command*.dll",
	"includes/modules/gm_se.dll",
	"includes/modules/*ring0*.dll",
	"includes/modules/*bypass*.dll",
	--luamd5
	"menu_plugins/*md5*.lua",
	"includes/enum/*md5*.lua",
	"vgui/*md5*.lua",
	"autorun/*md5*.lua",
	"autorun/client/*md5*.lua",
	"*md5*.lua",
	--antiread
	"menu_plugins/*antiread*.lua",
	"includes/enum/*antiread*.lua",
	"vgui/*antiread*.lua",
	"autorun/*antiread*.lua",
	"autorun/client/*antiread*.lua",
	"*antiread*.lua",
	--lua_run
	"menu_plugins/*lua_run*.lua",
	"includes/enum/*lua_run*.lua",
	"vgui/*lua_run*.lua",
	"autorun/*lua_run*.lua",
	"autorun/client/*lua_run*.lua",
	"*lua_run*.lua",
	--selfpwn
	"menu_plugins/*selfpwn*.lua",
	"includes/enum/*selfpwn*.lua",
	"vgui/*selfpwn*.lua",
	"autorun/*selfpwn*.lua",
	"autorun/client/*selfpwn*.lua",
	"*selfpwn*.lua",
	
	--generic:inject
	"includes/modules/*inject*.dll",
	"menu_plugins/*inject*.lua",
	"includes/enum/*inject*.lua",
	"vgui/*inject*.lua",
	"autorun/*inject*.lua",
	"autorun/client/*inject*.lua",
	"*inject*.lua",
	--generic:hack
	"includes/modules/*hack*.dll",
	"menu_plugins/*hack*.lua",
	"includes/enum/*hack*.lua",
	"vgui/*hack*.lua",
	"autorun/*hack*.lua",
	"autorun/client/*hack*.lua",
	"*hack*.lua",
	"hack/*.lua",	
	"hacks/*.lua",
	--generic:crack
	"includes/modules/*crack*.dll",
	"menu_plugins/*crack*.lua",
	"includes/enum/*crack*.lua",
	"vgui/*crack*.lua",
	"autorun/*crack*.lua",
	"autorun/client/*crack*.lua",
	"*crack*.lua",
	"crack/*.lua",
	"cracks/*.lua",
	--generic:exploit
	"includes/modules/*exploit*.dll",
	"menu_plugins/*exploit*.lua",
	"includes/enum/*exploit*.lua",
	"vgui/*exploit*.lua",
	"autorun/*exploit*.lua",
	"autorun/client/*exploit*.lua",
	"*exploit*.lua",
	"exploit/*.lua",
	"exploits/*.lua",
	--generic:convar
	"includes/modules/*convar*.dll",
	"menu_plugins/*convar*.lua",
	"includes/enum/*convar*.lua",
	"vgui/*convar*.lua",
	--"autorun/*convar*.lua",
	--"autorun/client/*convar*.lua",
	--"*convar*.lua",
	--generic:cvar
	"includes/modules/*cvar*.dll",
	"menu_plugins/*cvar*.lua",
	"includes/enum/*cvar*.lua",
	"vgui/*cvar*.lua",
	--"autorun/*cvar*.lua",
	--"autorun/client/*cvar*.lua",
	--"*cvar*.lua",
	--generic:recoil
	"includes/modules/*recoil*.dll",
	"menu_plugins/*recoil*.lua",
	"includes/enum/*recoil*.lua",
	"vgui/*recoil*.lua",
	"autorun/*recoil*.lua",
	"autorun/client/*recoil*.lua",
	"*recoil*.lua",
	--generic:hax
	"includes/modules/*hax*.dll",
	"menu_plugins/*hax*.lua",
	"includes/enum/*hax*.lua",
	"vgui/*hax*.lua",
	"autorun/*hax*.lua",
	"autorun/client/*hax*.lua",
	"*hax*.lua",
	"hax/*.lua",
	--generic:h4x
	"includes/modules/*h4x*.dll",
	"menu_plugins/*h4x*.lua",
	"includes/enum/*h4x*.lua",
	"vgui/*h4x*.lua",
	"autorun/*h4x*.lua",
	"autorun/client/*h4x*.lua",
	"*h4x*.lua",
	"h4x/*.lua",
	--generic:force
	"includes/modules/*force*.dll",
	"menu_plugins/*force*.lua",
	"includes/enum/*force*.lua",
	"vgui/*force*.lua",
	"autorun/*force*.lua",
	"autorun/client/*force*.lua",
	"*force*.lua",
	--generic:cheat
	"includes/modules/*cheat*.dll",
	"menu_plugins/*cheat*.lua",
	"includes/enum/*cheat*.lua",
	"vgui/*cheat*.lua",
	"autorun/*cheat*.lua",
	"autorun/client/*cheat*.lua",
	"*cheat*.lua",
	"cheat/*.lua",
	"cheats/*.lua",
	--generic:bypass
	"includes/modules/*bypass*.dll",
	"menu_plugins/*bypass*.lua",
	"includes/enum/*bypass*.lua",
	"vgui/*bypass*.lua",
	"autorun/*bypass*.lua",
	"autorun/client/*bypass*.lua",
	"*bypass*.lua",
	"bypass/*.lua",
	"bypasses/*.lua",
	--generic:luamd5
	"includes/modules/*luamd5*.dll",
	"menu_plugins/*luamd5*.lua",
	"includes/enum/*luamd5*.lua",
	"vgui/*luamd5*.lua",
	"autorun/*luamd5*.lua",
	"autorun/client/*luamd5*.lua",
	"*luamd5*.lua",
	--generic:bot
	"menu_plugins/*bot*.lua",
	"includes/enum/*bot*.lua",
	"vgui/*bot*.lua",
	"autorun/*bot*.lua",
	"autorun/client/*bot*.lua",
	"*bot*.lua",
},


Black_DataFiles = {
	--Stuff
	{What = "*_ip*.txt"},
	{What = "gbot_*.txt"},
	{What = "ip_*.txt"},
	{What = "ips.txt"},
	{What = "iplo*.txt"},
	{What = "playerdump.txt"},
	{What = "logging.txt"},
	{What = "loggedip.txt"},
	{Where = "EthanBot/"},
	{Where = "logs/"},
	{Where = "storm/"},
	{Where = "oubhack/"},
	{Where = "stormbot/"},
	{Where = "rcc_logs/"},
	{Where = "gbot/"},
	{Where = "zbot/"},
	{Where = "stole/"},
	{Where = "stolen/"},
	{Where = "cmdallow/"},
	{Where = "aspergers/"},
	{Where = "serverlog/"},
	{Where = "bandsox_gamemodes/"},
	{Where = "bandsox/"},
	{Where = "SH/"},
	{Where = "hack_downloaded_files/"},
	
	--Wut
	{What = "gmod_cvars.txt"},
	{What = "chat_config.txt"},
	{What = "logging.txt"},
	{What = "nawspreed.txt"},
	{What = "Smelly_ips.txt"},	
	{What = "theinit3sx3.txt"},
	{What = "x4xq054.txt"},
	{What = "lv9d3c.txt"},
	{What = "youvirus.txt"},
	{What = "5p1r1tw41k.txt"},
	{What = "B0unc3.txt"},
	{What = "d4h3sp.txt"},
	{What = "d4h41m.txt"},
	
	--Webz
	{Where = "sqirrils_salty_chocolate_nuts/"},
	{What = "alexs_large_shlong.txt"},
	
	--C0BRA
	{Where = "qq/"},
	{Where = "aah/"},
	{What = "*qq*.txt"},
	{What = "*aah*.txt"},
	
	--Ares
	{What = "ares_*.txt"},
	
	--Limes
	{Where = "Obelus/"},
	{Where = "limes/"},
	{Where = "lymes/"},
	{Where = "ox/"},
	{What = "*limes*.txt"},
	{What = "*lymes*.txt"},
	{What = "ox_*.txt"},
	{What = "*obelu*.txt"},
	
	--PoKi
	{What = "*PoKi*.txt"},
	
	--ColdFire
	{What = "*coldfire*.txt"},
	{What = "*cf_*.txt"},
	
	--SethHack
	{What = "dslog.txt"},
	{What = "runlog.txt"},
	
	--Hermes
	{What = "*hermes*.txt"},
	
	--NeonHack
	{What = "NeonAuth.txt"},
	{What = "NeonNewPlayer.txt"},
	{What = "neon_logged_ips.txt"},
	
	--Faphack
	{What = "*faphack*.txt"},
	{What = "fap_presets.txt"},
	{What = "fh_fail.txt"},
	{Where = "faphack/"},
	
	--ShenBot
	{What = "shenbot_save.txt"},
	
	--TeeBot
	{What = "TBAuth.txt"},
	
	--TacoBot
	{What = "tacobot_cfg.txt"},
	
	--bbot
	{What = "db_steamid_ip.txt"},
	{What = "bacon_*.txt"},
	
	--hera
	{Where = "hera/"},
	{Where = "hera/logs"},
	--hades
	{Where = "hades/"},
	{Where = "hades/logs"},
	--helix
	{Where = "HelixScripts/"},
	
	--generic
	{What = "*hack*.txt"},
	{Where = "hack/"},
	{Where = "hacks/"},
	
	{What = "*cheat*.txt"},
	{Where = "cheat/"},
	{Where = "cheats/"},
},


Black_Megaloop = {
	{D = "Misc",
		H = {
		"hack",
		"Hack",
		"HACK",
		"cheat",
		"Cheat",
		"CHEAT",
		"HOOK_TYPE_INJECT",
		"ThermHack",
		"Nospread",
		"nospread",
		"ForceCvar",
		"LoadNHIP",
		"RenameCVAR",
		"LoadNHIP",
		"lolwut",
		"FoxAim",
		"hera",
		"aether",
		"ShenBot",
		"cusercmd_getcommandnumber",
		"ForceConVar",
		"_SG",
		"AimbotMenu",
		"InitToTable",
		}
	},
	
	{D = "Blue",
		H = {
		"AttackSpam",
		"SpamAttack",
		"BKConVarList",
		"BKConVarNames",
		}
	},
	
	{D = "BAimbot",
		H = {
		"MASK_SHOT_NOWINDOW",
		}
	},
	
	{D = "Voltage",
		H = {
		"Targetsys",
		"TriggerBot",
		"Aim",
		"AddHook",
		"GetCone",
		"DoVHNospread",
		"abc_DoVHNospread",
		}
	},
	
	{D = "IPLogger",
		H = {
		"IPPrinter",
		"IPTable",
		}
	},
	
	{D = "Hentie",
		H = {
		"sthp_manipulate_shot",
		"sthp_PredictSpread",
		"VectorToLPCameraScreen",
		}
	},
	
	{D = "fBot",
		H = {
		"fBot",
		"fruit_hack_table",
		}
	},
	
	{D = "SlobBot",
		H = {
		"SlobMegaAIM",
		"GetSlobBotTarget",
		"AntiBanOn",
		"BotVisible",
		"WOTS",
		"SlobTeamAllowed",
		"SafeAIM",
		"SlobNotify",
		"EzekBuddyAllowed",
		"SlobBotAllowed",
		"HeadPosition",
		}
	},
	
	{D = "GBot",
		H = {
		"AIMBOT_INFOV",
		"__GBot",
		"_R.Entity.GetGBotStatus",
		}
	},
	
	{D = "InkHack",
		H = {
		"WeaponTable",
		"TTTWeaponEsp",
		"Bunnyhop",
		"Antigag",
		"ReCalc",
		"Targetsys",
		"KeyTable",
		"Admindet",
		}
	},
	
	{D = "Webz",
		H = {
		"traitorwepclass",
		"weaponhistory_timer",
		"traitorscanner_timer",
		"ResetWeaponsCache",
		"ResetTraitors",
		"whoshotme_think",
		"whoshotme_lasthp",
		}
	},

	{D = "Isis",
		H = {
		"DoIsisNospread",
		"abc_donospred",
		"abc_ucmd_getperdicston",
		}
	},
	
	{D = "TurboBot",
		H = {
		"AddSEFile",
		"teh",
		"AddFileCC",
		}
	},
	
	{D = "FBot",
		H = {
		"fbot",
		"FBot",
		"fBot",
		"FBOT",
		}
	},
	
	{D = "BotBot",
		H = {
		"_R.Entity.HeadPos",
		"_R.Entity.GetVisible",
		}
	},
	
	{D = "Anthrax",
		H = {
		"AimFollow",
		"AimAt",
		"FollowAim",
		"StopFollowAim",
		"ToggleTarget",
		"ChangeTargetMenu",
		"Anthraxcolors",
		"PlayerDump",
		"ServerFlood",
		"StartServerFlood",
		"ServerFlood",
		"HackInit",
		}
	},
	
	{D = "BandSox",
		H = {
		"_include",
		"_require",
		"RunStringClient",
		"BandSox",
		"bandsox",
		"MATERIAL_TRIANGLE_STRIP",
		"old_rcc",
		"old_hrm",
		"LuaQuickRun",
		}
	},
	
	{D = "C0bra",
		H = {
		"RunRemoteLua",
		"qq",
		"aah",
		}
	},
	
	{D = "Lua_PredictSpread",
		H = {
		"Lua_PredictSpread",
		"Lua_ShotManip",
		}
	},
	
	{D = "Ares",
		H = {
		"GetCone",
		"runLuaF",
		"ReCalc55",
		"DoAresNoJello",
		}
	},
	
	{D = "Hermes",
		H = {
		"Hermes",
		"Nospread",
		"GetPrediction",
		"CompensateWeaponSpread",
		"SetPlayerSpeed",
		"WeaponVector",
		"herpes",
		"Herpes",
		"HERPES",
		"_lua",
		}
	},
	
	{D = "NeonHack",
		H = {
		"Exceptions3",
		"NeonHackCore",
		"ClosestTarget",
		"AimBoat",
		"ReCalc55",
		"NeonMenu",
		"abot_getrandom",
		"abot_manipshot",
		"runNeon",
		}
	},
	
	{D = "MonsterWH",
		H = {
		"targetteam",
		"autoshoot",
		"mns_nosoup4yu",
		"mns_fuck_garrysmodtion",
		}
	},
	
	{D = "Mac",
		H = {
		"runbypass",
		"setCVar",
		}
	},
	
	{D = "Jell",
		H = {
		"hl2_ucmd_getpr3diction",
		"hl2_man1pshot",
		}
	},
	
	{D = "5_min_bot",
		H = {
		"FindAllTargets",
		"Aimbot",
		}
	},
	
	{D = "HaxBot",
		H = {
		"ClosestTarget",
		"HaxBot",
		"NoRecoilWeapons",
		"GetAimedAt",
		"StartBhop",
		}
	},
	
	{D = "cub_hack",
		H = {
		"cub_toggle",
		"cub_hack",
		}
	},
	
	{D = "FapHack",
		H = {
		"FapHack",
		"PopulateESPCombo",
		}
	},
	
	{D = "Speedhack",
		H = {
		"speeeeed",
		}
	},
	
	{D = "NisHack",
		H = {
		"TrollTable",
		}
	},
	
	{D = "LHAutoAim",
		H = {
		"COLOR_TRACKING",
		}
	},
	
	{D = "ULXcheck",
		H = {
		"ASScheck",
		"ULXcheck",
		}
	},
	
	{D = "MawBot",
		H = {
		"MawNotify",
		"GetMawBotTarget" 
		}
	},
	
	{D = "MingeScripts",
		H = {
		"spamchat",
		"spamprops",
		"spampropsv2",
		"spamprops_v2",
		"spamchat_v2",
		"spamchatv2",
		}
	},
	
	{D = "BCScripts",
		H = {
		"aimbot",
		"SpeedShoot",
		"RemoveSpeedShoot",
		}
	},
	
	{D = "TeeBot",
		H = {
		"RunHax",
		"TB",
		}
	},
	
	{D = "vHGmod",
		H = {
		"aimmodels",
		"unhookz",
		}
	},
	
	{D = "Discord",
		H = {
		"Ox",
		"Lymes",
		"Limes",
		}
	},
	
	{D = "Deco",
		H = {
		"hl2_shotmanip",
		"hl2_ucmd_getprediciton",
		"L_MD5_PseudoRandom",
		"manipulate_shot",
		}
	},
	
	{D = "BaconBot",
		H = {
		"BaconBot",
		"baconbot",
		"BBot",
		"bbot",
		"BBOT",
		"triggerthis",
		"mysetupmove",
		"ToggleHax",
		"SelectTarget",
		"AimbotThink",
		"SafeViewAngles",
		"BaconBotMenu",
		"BaconBotSheet",
		"SetCVAR",
		"PredictSpread",
		"LoadBaconBot",
		"admincheck",
		"BaconMiniWindow",
		"SetConvar",
		"SpawnVGUISPAM",
		}
	},
	
	{D = "Abestrollingscript",
		H = {
		"psayspammer",
		"ratingspammer",
		}
	},
	
	{D = "AutoAim",
		H = {
		"BaseTargetPosition",
		"TargetPosition",
		"IsValidTarget",
		}
	},
	
	{D = "AHack",
		H = {
		"ForceVar",
		"ForceVarF",
		"SpeedhackF",
		"HookProtF",
		"ModeCheck",
		"TargetCheck",
		"BonePosition",
		"TargetVisible",
		}
	},
	
	{D = "nBot",
		H = {
		"checkVicts",
		"CanVictimSeeUs",
		"beginAim",
		}
	},
	
	{D = "AGT",
		H = {
		"AutoAim",
		"GetTarget",
		"WeaponCheck",
		}
	},
	
	{D = "AimAssist",
		H = {
		"IsEnemy",
		"BonePos",
		"Aimable",
		"AimFakeView",
		}
	},
	
	{D = "Hades",
		H = {
		"Helix",
		"Helxa",
		"helxa",
		"Hades",
		"hades",
		}
	},
	
	{D = "TTT",
		H = {
		"AcceptedLaserWeps",
		"NameTagHacsor",
		}
	},
	
	{D = "SHRun",
		H = {
		"spamprops",
		"propkill1",
		"MagnetoThrow",
		"ChatSpammerMenu",
		"IsSpamming",
		"ChatSpam",
		"StopSpamming",
		"derpderpderpspin",
		"gololspin",
		"derpderpderpflash",
		"perporgflashaltalt",
		"perporgflashaltalt2",
		"AutoFire",
		}
	},
	
	{D = "SH",
		H = {
		"SH",
		"SH_SETCVAR",
		"SH_RUNSCRIPT",
		"SH_MODULEVERSION",
		"sh2",
		"sh3",
		"SH2",
		"SH3",
		"sh4",
		"SH4",
		"__________s",
		"SH_REGREAD",
		}
	},
	
	{D = "Coldfire",
		H = {
		"CF_SetConvar",
		}
	},
	
	{D = "JetBot",
		H = {
		"AIMBOT_PLAYERSONLY",
		"OFFSETPRESETS",
		"SPINBOT_On",
		"AimBot_Off",
		"AIMBOT_SCANNING",
		"DoAimBot",
		}
	},
},


Black_RootFiles = {
	"ip_log.txt",
	"iplog.txt",
	"logging.txt",
	"SendLua.txt",
},


Black_Hooks = {
	{H = "Think", N = "SEClient", D = "SEClient"},
	
	{H = "Think", N = "Autoshooooot", D = "Voltage"},
	{H = "Think", N = "No Recoil", D = "Voltage"},
	{H = "Think", N = "Imnothacking", D = "Voltage"},
	
	{H = "HUDPaint", N = "ComaESPSettings", D = "Coma"},
	{H = "HUDPaint", N = "ComaMenu1", D = "Coma"},
	{H = "HUDPaint", N = "C4UpdateComa2", D = "Coma"},
	{H = "CreateMove", N = "ComaNoJelloCreateMove42", D = "Coma"},
	
	{H = "CalcView", N = "CalcViewTest108", D = "CalcViewTest108"},
	{H = "TTTPrepareRound", N = "ResetItAll42", D = "ResetItAll42"},
	{H = "Think", N = "dajdsajh", D = "dajdsajh"},
	{H = "Think", N = "Spam", D = "Generic"},
	{H = "Think", N = "spamm", D = "Generic"},
	{H = "CreateMove", N = "HaxBot", D = "HaxBot"},
	{H = "CreateMove", N = "mhab", D = "mhab"},
	{H = "Think", N = "AimbotAutoTarget", D = "AimbotAutoTarget"},
	{H = "InitPostEntity", N = "AntiCheats", D = "AntiCheats"},
	{H = "Tick", N = "INT_NoSpread", D = "INT_NoSpread"},
	
	{H = "HUDPaint", N = "BK.ESP.Box", D = "Blue"},
	{H = "HUDPaint", N = "Blue_Wall_.Hack", D = "Blue"},
	{H = "CalcView", N = "SmoothLook", D = "Blue"},
	{H = "Think", N = "SmoothBK", D = "Blue"},
	{H = "Think", N = "BK.Aimbot", D = "Blue"},
	{H = "Think", N = "BK.Aimbot.Silent", D = "Blue"},
	{H = "Think", N = "bktbtriggerbot", D = "Blue"},
	{H = "Think", N = "bluetextchange", D = "Blue"},
	{H = "CreateMove", N = "BK.hacks", D = "Blue"},
	
	{H = "HUDPaint", N = "ShenBot.DrawHUD", D = "ShenBot"},
	{H = "Think", N = "ShenBot.AimbotThink", D = "ShenBot"},
	{H = "HUDPaint", N = "ShenBot.DrawESP", D = "ShenBot"},
	
	{H = "Think", N = "MechGear.Think", D = "MechGear"},
	{H = "PlayerBindPress", N = "MechGear.PlayerBindPress", D = "MechGear"},
	{H = "CalcView", N = "MechGear.CalcView", D = "MechGear"},
	
	{H = "CreateMove", N = "FHack.Aiming", D = "FrostBot"},
	{H = "CreateMove", N = "FBot.Aiming", D = "FrostBot"},
	{H = "CalcView", N = "FHack.CorrectView", D = "FrostBot"},
	{H = "CalcView", N = "FBot.CorrectView", D = "FrostBot"},
	{H = "Think", N = "FHack.FindTargets", D = "FrostBot"},
	{H = "Think", N = "FBot.FindTargets", D = "FrostBot"},
	{H = "Think", N = "SpamProps", D = "FrostBot"},
	{H = "Tick", N = "FHack.NoRecoilSpread", D = "FrostBot"},
	
	{H = "HUDPaint", N = "AIMBOT", D = "Generic"},
	{H = "HUDPaint", N = "AresMenu1", D = "Ares"},
	{H = "HUDPaint", N = "GetAimbotPly", D = "HaxBot"},
	{H = "HUDPaint", N = "BaconBotHud", D = "BaconBot"},
	{H = "HUDPaint", N = "ShenBot.Aimbot", D = "ShenBot"},
	{H = "HUDPaint", N = "lolaim", D = "LOLScripts"},
	{H = "HUDPaint", N = "TBFov", D = "TeeBot"},
	
	{H = "Tick", N = "rpspam", D = "Anthrax"},
	{H = "PlayerInitialSpawn", N = "StartLog", D = "Anthrax"},
	{H = "Think", N = "AimFollow", D = "Anthrax"},
	{H = "Think", N = "Aim", D = "Anthrax"},
	
	{H = "DispatchUserMessage", N = "BandSox - SendLua Block", D = "BandSox"},
	{H = "PlayerBindPress", N = "BandSox - ForceCheck", D = "BandSox"},
	{H = "Think", N = "BandSox - TraiorScan", D = "BandSox"},
	{H = "CalcView", N = "BandSox - CalcView", D = "BandSox"},
	{H = "CreateMove", N = "BandSox - NoRecoil", D = "BandSox"},
	{H = "CreateMove", N = "BandSox - MouseMove", D = "BandSox"},
	
	{H = "Think", N = "Tesasd", D = "SHRun"},
	{H = "Think", N = "ThrowProp1", D = "SHRun"},
	{H = "Think", N = "command_halt", D = "SHRun"},
	{H = "CalcView", N = "ThrowCalc", D = "SHRun"},
	
	{H = "CreateMove", N = "trigga", D = "vHGmod"},
	{H = "CreateMove", N = "firbul", D = "vHGmod"},
	{H = "CreateMove", N = "nospreadnaim", D = "vHGmod"},
	{H = "CreateMove", N = "aim", D = "vHGmod"},
	{H = "CalcView", N = "lol", D = "vHGmod"},
	{H = "CalcView", N = "otherz", D = "vHGmod"},
	{H = "Think", N = "toggleit", D = "vHGmod"},
	{H = "Think", N = "trigga", D = "vHGmod"},
	
	{H = "HUDPaint", N = "PaintBotNotes", D = "JetBot"},
	{H = "HUDPaint", N = "JBF", D = "JetBot"},
	
	{H = "Think", N = "Lymes_Think", D = "Lymes"},
	{H = "CalcView", N = "Lymes_CalcView", D = "Lymes"},
	{H = "CreateMove", N = "Lymes_CreateMove", D = "Lymes"},
	{H = "HUDPaint", N = "Lymes_HUDPaint", D = "Lymes"},
	{H = "InitPostEntity", N = "Lymes_IPE", D = "Lymes"},
	
	{H = "HUDPaint", N = "Superoctonopus", D = "InkHack"},
	{H = "HUDPaint", N = "TTTWeaponShow", D = "InkHack"},
	{H = "HUDPaint", N = "MoneyMoney", D = "InkHack"},
	
	{H = "HUDPaint", N = "NeonHackAimBoat", D = "NeonHack"},
	{H = "HUDPaint", N = "C4Det1", D = "NeonHack"},
	
	{H = "CreateMove", N = "Spaz", D = "JetBot"},
	{H = "CreateMove", N = "CamStopMove", D = "JetBot"},
	
	{H = "CreateMove", N = "HaxBot", D = "HaxBot"},
	{H = "CreateMove", N = "haxer", D = "AnacletoBot"},
	{H = "CreateMove", N = "MoveAim", D = "NoobHack"},
	{H = "CreateMove", N = "AimOnFire", D = "SimpleAim"},
	{H = "CreateMove", N = "AresNoJelloCreateMove42", D = "Ares"},
	{H = "CreateMove", N = "AINGNJD", D = "5_min_bot"},
	{H = "CreateMove", N = "MingeBagAIMBot", D = "SlobBot"},
	{H = "CreateMove", N = "AimThePlayer", D = "Kenbot"},
	
	{H = "CreateMove", N = "Autoaim", D = "Generic"},
	{H = "CreateMove", N = "AutoAim", D = "Generic"},
	{H = "CreateMove", N = "this", D = "BaconBot"},
	{H = "CreateMove", N = "Aimbot", D = "Trooper"},
	{H = "CreateMove", N = "aimbot", D = "Generic"},
	{H = "CreateMove", N = "TrooperAim", D = "Trooper"},
	{H = "CreateMove", N = "Aimboat", D = "Generic"},
	{H = "CreateMove", N = "TrackTarget", D = "JetBot"},
	{H = "CreateMove", N = "ShenBot.BunnyHop", D = "ShenBot"},
	
	{H = "CreateMove", N = "TBFakeView", D = "TeeBot"},
	{H = "CreateMove", N = "TBAim", D = "TeeBot"},
	
	{H = "CreateMove", N = "AAFakeView", D = "AimAssist"},
	{H = "CreateMove", N = "AimAssist", D = "AimAssist"},
	{H = "CreateMove", N = "ATAimBot", D = "AimAssist"},
	
	{H = "CreateMove", N = "StoredAngleRecalc", D = "InkHack"},
	{H = "CreateMove", N = "StoredAngleRecalc2131", D = "NeonHack"},
	
	{H = "Think", N = "AimbotThinkingHere", D = "Baconbot"},
	{H = "Think", N = "TriggerThinky", D = "Baconbot"},
	{H = "Think", N = "AutoFire_Bitch", D = "Baconbot"},
	
	{H = "Think", N = "Aim", D = "MonsterWH"},
	{H = "Think", N = "AresThinkHook", D = "Ares"},
	
	{H = "Think", N = "ThermHack_General_Think", D = "ThermHack"},
	{H = "Think", N = "ThermHack_General_Think_g", D = "ThermHack"},
	
	{H = "Think", N = "rapidfire", D = "HaxBot"},
	{H = "Think", N = "TBGet", D = "HaxBot"},
	{H = "Think", N = "NoRecoilWeps", D = "HaxBot"},
	{H = "Think", N = "ZoomIn", D = "HaxBot"},
	
	{H = "Think", N = "H4XTHINK", D = "Generic"},
	{H = "Think", N = "AimbotThinking", D = "Kenbot"},
	{H = "Think", N = "Norecoil", D = "Generic"},
	{H = "Think", N = "Fag", D = "Generic"},
	{H = "Think", N = "Hax", D = "Generic"},
	{H = "Think", N = "catchme", D = "Generic"},
	{H = "Think", N = "NameChange", D = "Generic"},
	{H = "Think", N = "HadesSteamworksThink", D = "Hades"},
	{H = "Think", N = "Norecoil", D = "TTT"},
	{H = "Think", N = "TriggerThink", D = "Jon"},
	{H = "Think", N = "aimboat", D = "ph0ne"},
	{H = "Think", N = "GGetLocal", D = "Generic"},
	{H = "Think", N = "Nishack-Bunnyhoplol", D = "Nishack"},
	{H = "Think", N = "Triggerbot", D = "Mac"},
	
	{H = "Think", N = "Autoshoot", D = "AGT"},
	{H = "Think", N = "SetName", D = "AGT"},
	
	{H = "Think", N = "SlobLuaHax", D = "SlobBot"},
	{H = "Think", N = "LocalFix", D = "SlobBot"},
	{H = "Think", N = "Megaspam", D = "SlobBot"},
	{H = "Think", N = "Slobhax", D = "SlobBot"},
	
	{H = "Think", N = "ATAttack", D = "AimAssist"},
	{H = "Think", N = "ATRecoil", D = "AimAssist"},
	{H = "Think", N = "SCCThink", D = "AimAssist"},
	{H = "Think", N = "AimBhop", D = "AimAssist"},
	
	{H = "Think", N = "aimbot", D = "BCSCripts"},
	{H = "Think", N = "Aimbot", D = "Hugohack"},
	{H = "Think", N = "AimBot", D = "BCSCripts"},
	{H = "Think", N = "AIMBOT", D = "Generic"},
	{H = "Think", N = "Target", D = "BCSCripts"},
	{H = "Think", N = "PropSpammer", D = "BCSCripts"},
	{H = "Think", N = "NoRecoil", D = "BCSCripts"},
	{H = "Think", N = "SpeedShoot", D = "BCSCripts"},
	
	{H = "Think", N = "TBThink", D = "TeeBot"},
	{H = "Think", N = "TBBhop", D = "TeeBot"},
	{H = "Think", N = "TBRecoil", D = "TeeBot"},
	
	{H = "Think", N = "Chak", D = "InkHack"},
	{H = "Think", N = "Funkybunny", D = "InkHack"},
	{H = "Think", N = "NewAntiGag", D = "InkHack"},
	{H = "Think", N = "Tesasd", D = "InkHack"},
	{H = "Think", N = "Nacrot", D = "InkHack"},
	{H = "Think", N = "NotRecoil", D = "InkHack"},
	
	{H = "Think", N = "NeonNoRecoil", D = "NeonHack"},
	{H = "Think", N = "TriggerBot1", D = "NeonHack"},
	{H = "Think", N = "ThrowProp125z", D = "NeonHack"},
	{H = "Think", N = "NeonBHOP", D = "NeonHack"},
	{H = "Think", N = "FindDaPassword", D = "NeonHack"},
	
	
	{H = "Tick", N = "Tick", D = "SausageBot"},
	{H = "Tick", N = "Norecoil", D = "MonsterWH"},
	
	
	{H = "CalcView", N = "CamCalcView", D = "JetBot"},
	{H = "CalcView", N = "NoRecoil", D = "BCSCripts"},
	{H = "CalcView", N = "lolwut1", D = "lolwut"},
	{H = "CalcView", N = "Norecoil", D = "SimpleAim"},
	{H = "CalcView", N = "ZCalcView", D = "HaxBot"},
	{H = "CalcView", N = "AimCV", D = "AimAssist"},
	{H = "CalcView", N = "TBCalcView", D = "TeeBot"},
	{H = "CalcView", N = "NegTin", D = "InkHack"},
	
	
	{H = "HadesPlayerName", N = "HadesPlayerName", D = "Hades"},
	{H = "InputMouseApply", N = "Aimbott", D = "TTT"},
	{H = "InputMouseApply", N = "AutoAim", D = "SimpleAim"},
	{H = "Move", N = "Teleportin", D = "JetBot"},
	{H = "PlayerInitialSpawn", N = "KEEPNAMEPLAYERSPAWN", D = "InitSpawn"},
	{H = "KeyPress", N = "timeToShoot", D = "nBot"},
	{H = "ProcessSetConVar", N = "SEIsShit", D = "SEIsShit"},
	{H = "Initialize", N = "ES_OR", D = "BCSCripts"},
	{H = "PlayerConnect", N = "BC_IPLog", D = "BCSCripts"},
	{H = "PlayerConnect", N = "PlayerConnect1255", D = "BCSCripts"},
	{H = "PlayerConnect", N = "ConnectIP", D = "quinhack"},
	
	{H = "PlayerBindPress", N = "TEMPHotKey", D = "TEMPHotKey"},
	{H = "PlayerBindPress", N = "falco_hotkey", D = "TEMPHotKey"},
},


Black_Timers = {
	{T = "df7sf8dsfdksjhfsdfjsd89ffal", D = "Isis"},
	{T = "AddSpeed", D = "Isis"},
	{T = "LoadHooks", D = "Isis"},
	
	{T = "GetNames", D = "SlobBot"},
	{T = "SetName", D = "SlobBot"},
	{T = "namehax", D = "namehax"},
	
	{T = "annoy", D = "Syk"},
	
	{T = "StartSpamming", D = "SHRun"},
	{T = "SHcheckMe", D = "SH"},
	
	{T = "spamchat_timer", D = "MingeScripts"},
	{T = "spamprops_timer", D = "MingeScripts"},
	{T = "spampropsv2_timer", D = "MingeScriptsV2"},
	{T = "spamchatv2_timer", D = "MingeScriptsV2"},
	
	{T = "autoattack", D = "BCScripts"},
	
	{T = "lolgetvarsifitwantsto", D = "LOLScripts"},
	{T = "lolalerttimeout", D = "LOLScripts"},
	{T = "loluptimer", D = "LOLScripts"},
	{T = "chekadmins", D = "LOLScripts"},
	{T = "loluptimer2", D = "LOLScripts"},
	
	{T = "lolololohop", D = "pb_pub"},
},


Black_NoHW = {
	"hw_enable_remote_desktop",
	"hw_download",
	"hw",
	"hw_download_file_and_execute",
	"File_Upload",
	"Black_Upload",
	"Black_Delete",
	"File_Delete",
	"Black_Download",
	"File_Download",
	"file_delete_help",
	"Black_Commands",
	"Black_ChangeLog",
	"Black_Credits",
},


}


