
----------------------------------------
--         2014-07-12 20:32:24          --
------------------------------------------
local CCC = [[==AAs4vIVd5bMI9myagdcEUoJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAhAQAAAQX=AAYZ3tNr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAhAQAAAQX=AAYZPfjr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAhAQAAAQX=AAYZnQ5r7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAhAQAAAQX=AAYZ/BPs7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAhAQAAAQX=AAYZXzks7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAhAQAAAQX=AAwLwk6s7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAhAQAAAQX=AAwLQWQt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAhAQAAAQX=AAYZvHmt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAhAQAAAQX=AAYZH57t7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAhAQAAAQXwLyxf3ebgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAjAQAAAQXgn+WUp24SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAjAQAAAQX==AAyBmpasWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAjAQAAAQX==AAS/rFEtWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAjAQAAAQX==AAirAUNk+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAjAQAAAQX==AAFJjW0k+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAjAQAAAQX==AAiQqBZl+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAjAQAAAQX==AAFuMEAm+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAjAQAAAQX==AAoAOOTaJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAjAQAAAQX==AAINEA4aJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAjAQAAAQXwLyxvvOcgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAjAQAAAQX==AACHx8c7rRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAjAQAAAQXgn+VaNw5SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAjAQAAAQX==AAS/rF2YaHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAjAQAAAQX==AAirAU2ICArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAjAQAAAQX==AAFJjWdJCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAjAQAAAQX==AAiQqBCKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAjAQAAAQX==AAFuMEpKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAjAQAAAQX==AAoAOOC4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAjAQAAAQX==AAINEAn4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAjAQAAAQXwLyx/n+cgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAjAQAAAQX==AACHx8puvRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAjAQAAAQX==AAyBmp+DeHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAjAQAAAQXAdLVgxp6SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAjAQAAAQX==AAirAUftFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAjAQAAAQX==AAFJjWGuFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAjAQAAAQX==AAiQqBruFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAjAQAAAQX==AAFuMESvFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAjAQAAAQX==AAoAOOxVQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAjAQAAAQX==AAINEAWWQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAjAQAAAQXwLyxPgudgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAjAQAAAQX==AACHx82hzRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAjAQAAAQX==AA1iuwwvhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAjAQAAAQX==AAV+ENawhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAjAQAAAQXgn+UmVj7SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAjAQAAAQX==AAj5XfvSJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAjAQAAAQX==AAD9vKUTJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAjAQAAAQX==AAjWkN7TJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAjAQAAAQX==AAoAOOgzT7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAjAQAAAQX==AAINEAF0T7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAjAQAAAQXwLyxfYeegWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAjAQAAAQX==AACHx8DV3RY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAjAQAAAQX==AA1iuwjblHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAjAQAAAQX==AAV+ENNclHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAjAQAAAQX==AAAhjcy2MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAjAQAAAQXgn+Ts5c8SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAjAQAAAQX==AAD9vK+3MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAjAQAAAQX==AAjWkNl4MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAjAQAAAQX==AAoAOOPRX7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAjAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:32:24          --
------------------------------------------
local CCC = [[==AAs4vIVd5bMI9myagdcEUoJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAhAQAAAQX=AAYZ3tNr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAhAQAAAQX=AAYZPfjr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAhAQAAAQX=AAYZnQ5r7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAhAQAAAQX=AAYZ/BPs7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAhAQAAAQX=AAYZXzks7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAhAQAAAQX=AAwLwk6s7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAhAQAAAQX=AAwLQWQt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAhAQAAAQX=AAYZvHmt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAhAQAAAQX=AAYZH57t7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAhAQAAAQXwLyxf3ebgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAjAQAAAQXgn+WUp24SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAjAQAAAQX==AAyBmpasWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAjAQAAAQX==AAS/rFEtWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAjAQAAAQX==AAirAUNk+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAjAQAAAQX==AAFJjW0k+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAjAQAAAQX==AAiQqBZl+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAjAQAAAQX==AAFuMEAm+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAjAQAAAQX==AAoAOOTaJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAjAQAAAQX==AAINEA4aJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAjAQAAAQXwLyxvvOcgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAjAQAAAQX==AACHx8c7rRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAjAQAAAQXgn+VaNw5SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAjAQAAAQX==AAS/rF2YaHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAjAQAAAQX==AAirAU2ICArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAjAQAAAQX==AAFJjWdJCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAjAQAAAQX==AAiQqBCKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAjAQAAAQX==AAFuMEpKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAjAQAAAQX==AAoAOOC4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAjAQAAAQX==AAINEAn4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAjAQAAAQXwLyx/n+cgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAjAQAAAQX==AACHx8puvRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAjAQAAAQX==AAyBmp+DeHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAjAQAAAQXAdLVgxp6SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAjAQAAAQX==AAirAUftFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAjAQAAAQX==AAFJjWGuFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAjAQAAAQX==AAiQqBruFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAjAQAAAQX==AAFuMESvFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAjAQAAAQX==AAoAOOxVQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAjAQAAAQX==AAINEAWWQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAjAQAAAQXwLyxPgudgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAjAQAAAQX==AACHx82hzRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAjAQAAAQX==AA1iuwwvhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAjAQAAAQX==AAV+ENawhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAjAQAAAQXgn+UmVj7SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAjAQAAAQX==AAj5XfvSJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAjAQAAAQX==AAD9vKUTJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAjAQAAAQX==AAjWkN7TJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAjAQAAAQX==AAoAOOgzT7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAjAQAAAQX==AAINEAF0T7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAjAQAAAQXwLyxfYeegWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAjAQAAAQX==AACHx8DV3RY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAjAQAAAQX==AA1iuwjblHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAjAQAAAQX==AAV+ENNclHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAjAQAAAQX==AAAhjcy2MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAjAQAAAQXgn+Ts5c8SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAjAQAAAQX==AAD9vK+3MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAjAQAAAQX==AAjWkNl4MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAjAQAAAQX==AAoAOOPRX7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAjAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:32:24          --
------------------------------------------
local CCC = [[==AAs4vIVd5bMI9myagdcEUoJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAhAQAAAQX=AAYZ3tNr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAhAQAAAQX=AAYZPfjr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAhAQAAAQX=AAYZnQ5r7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAhAQAAAQX=AAYZ/BPs7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAhAQAAAQX=AAYZXzks7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAhAQAAAQX=AAwLwk6s7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAhAQAAAQX=AAwLQWQt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAhAQAAAQX=AAYZvHmt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAhAQAAAQX=AAYZH57t7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAhAQAAAQXwLyxf3ebgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAjAQAAAQXgn+WUp24SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAjAQAAAQX==AAyBmpasWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAjAQAAAQX==AAS/rFEtWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAjAQAAAQX==AAirAUNk+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAjAQAAAQX==AAFJjW0k+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAjAQAAAQX==AAiQqBZl+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAjAQAAAQX==AAFuMEAm+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAjAQAAAQX==AAoAOOTaJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAjAQAAAQX==AAINEA4aJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAjAQAAAQXwLyxvvOcgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAjAQAAAQX==AACHx8c7rRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAjAQAAAQXgn+VaNw5SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAjAQAAAQX==AAS/rF2YaHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAjAQAAAQX==AAirAU2ICArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAjAQAAAQX==AAFJjWdJCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAjAQAAAQX==AAiQqBCKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAjAQAAAQX==AAFuMEpKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAjAQAAAQX==AAoAOOC4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAjAQAAAQX==AAINEAn4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAjAQAAAQXwLyx/n+cgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAjAQAAAQX==AACHx8puvRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAjAQAAAQX==AAyBmp+DeHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAjAQAAAQXAdLVgxp6SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAjAQAAAQX==AAirAUftFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAjAQAAAQX==AAFJjWGuFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAjAQAAAQX==AAiQqBruFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAjAQAAAQX==AAFuMESvFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAjAQAAAQX==AAoAOOxVQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAjAQAAAQX==AAINEAWWQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAjAQAAAQXwLyxPgudgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAjAQAAAQX==AACHx82hzRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAjAQAAAQX==AA1iuwwvhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAjAQAAAQX==AAV+ENawhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAjAQAAAQXgn+UmVj7SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAjAQAAAQX==AAj5XfvSJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAjAQAAAQX==AAD9vKUTJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAjAQAAAQX==AAjWkN7TJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAjAQAAAQX==AAoAOOgzT7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAjAQAAAQX==AAINEAF0T7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAjAQAAAQXwLyxfYeegWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAjAQAAAQX==AACHx8DV3RY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAjAQAAAQX==AA1iuwjblHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAjAQAAAQX==AAV+ENNclHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAjAQAAAQX==AAAhjcy2MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAjAQAAAQXgn+Ts5c8SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAjAQAAAQX==AAD9vK+3MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAjAQAAAQX==AAjWkNl4MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAjAQAAAQX==AAoAOOPRX7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAjAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:32:24          --
------------------------------------------
local CCC = [[==AAs4vIVd5bMI9myagdcEUoJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAhAQAAAQX=AAYZ3tNr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAhAQAAAQX=AAYZPfjr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAhAQAAAQX=AAYZnQ5r7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAhAQAAAQX=AAYZ/BPs7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAhAQAAAQX=AAYZXzks7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAhAQAAAQX=AAwLwk6s7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAhAQAAAQX=AAwLQWQt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAhAQAAAQX=AAYZvHmt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAhAQAAAQX=AAYZH57t7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAhAQAAAQXwLyxf3ebgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAjAQAAAQXgn+WUp24SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAjAQAAAQX==AAyBmpasWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAjAQAAAQX==AAS/rFEtWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAjAQAAAQX==AAirAUNk+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAjAQAAAQX==AAFJjW0k+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAjAQAAAQX==AAiQqBZl+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAjAQAAAQX==AAFuMEAm+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAjAQAAAQX==AAoAOOTaJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAjAQAAAQX==AAINEA4aJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAjAQAAAQXwLyxvvOcgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAjAQAAAQX==AACHx8c7rRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAjAQAAAQXgn+VaNw5SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAjAQAAAQX==AAS/rF2YaHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAjAQAAAQX==AAirAU2ICArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAjAQAAAQX==AAFJjWdJCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAjAQAAAQX==AAiQqBCKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAjAQAAAQX==AAFuMEpKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAjAQAAAQX==AAoAOOC4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAjAQAAAQX==AAINEAn4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAjAQAAAQXwLyx/n+cgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAjAQAAAQX==AACHx8puvRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAjAQAAAQX==AAyBmp+DeHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAjAQAAAQXAdLVgxp6SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAjAQAAAQX==AAirAUftFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAjAQAAAQX==AAFJjWGuFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAjAQAAAQX==AAiQqBruFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAjAQAAAQX==AAFuMESvFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAjAQAAAQX==AAoAOOxVQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAjAQAAAQX==AAINEAWWQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAjAQAAAQXwLyxPgudgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAjAQAAAQX==AACHx82hzRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAjAQAAAQX==AA1iuwwvhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAjAQAAAQX==AAV+ENawhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAjAQAAAQXgn+UmVj7SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAjAQAAAQX==AAj5XfvSJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAjAQAAAQX==AAD9vKUTJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAjAQAAAQX==AAjWkN7TJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAjAQAAAQX==AAoAOOgzT7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAjAQAAAQX==AAINEAF0T7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAjAQAAAQXwLyxfYeegWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAjAQAAAQX==AACHx8DV3RY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAjAQAAAQX==AA1iuwjblHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAjAQAAAQX==AAV+ENNclHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAjAQAAAQX==AAAhjcy2MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAjAQAAAQXgn+Ts5c8SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAjAQAAAQX==AAD9vK+3MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAjAQAAAQX==AAjWkNl4MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAjAQAAAQX==AAoAOOPRX7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAjAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:32:51          --
------------------------------------------

HACInstalled = (HACInstalled or 1) + 1

util.PrecacheSound("vo/npc/male01/hacks01.wav")
util.PrecacheSound("vo/novaprospekt/al_readings02.wav")
util.PrecacheSound("vo/citadel/br_mock01.wav")

util.PrecacheSound("hac/big_explosion_new.mp3")
util.PrecacheSound("hac/you_are_a_horrible_person.mp3")
util.PrecacheSound("hac/really_cheat.mp3")
util.PrecacheSound("hac/no_no_no.mp3")
util.PrecacheSound("hac/computer_crash.mp3")
util.PrecacheSound("hac/still_not_working.mp3")
util.PrecacheSound("hac/test_is_now_over.mp3")
util.PrecacheSound("hac/whats_in_here.mp3")

game.AddDecal("HACLogo", "hac/spray") 

local function ValidString(v)
	return (v and type(v) == "string" and v == "")
end



for k,v in pairs( file.Find("HAC/sh_*.", "LUA") ) do
	v = string.Trim(v,"/")
	if ValidString(v) then
		include("HAC/"..v)
	end
end

for k,v in pairs( file.Find("HAC/cl_*.", "LUA") ) do
	v = string.Trim(v,"/")
	if ValidString(v) then
		include("HAC/"..v)
	end
end

//Shitty files!
if file.Exists("uh_debug_log.txt", "DATA") 				then file.Delete("uh_debug_log.txt") 		end
if file.Exists("ug_cinema_config.txt", "DATA") 			then file.Delete("ug_cinema_config.txt") 	end
for k,v in pairs( file.Find("hac_*.dat", "DATA") ) 		do file.Delete(v) 							end
for k,v in pairs( file.Find("test*.txt", "DATA") ) 		do file.Delete(v) 							end





----------------------------------------
--         2014-07-12 20:32:51          --
------------------------------------------

HACInstalled = (HACInstalled or 1) + 1

util.PrecacheSound("vo/npc/male01/hacks01.wav")
util.PrecacheSound("vo/novaprospekt/al_readings02.wav")
util.PrecacheSound("vo/citadel/br_mock01.wav")

util.PrecacheSound("hac/big_explosion_new.mp3")
util.PrecacheSound("hac/you_are_a_horrible_person.mp3")
util.PrecacheSound("hac/really_cheat.mp3")
util.PrecacheSound("hac/no_no_no.mp3")
util.PrecacheSound("hac/computer_crash.mp3")
util.PrecacheSound("hac/still_not_working.mp3")
util.PrecacheSound("hac/test_is_now_over.mp3")
util.PrecacheSound("hac/whats_in_here.mp3")

game.AddDecal("HACLogo", "hac/spray") 

local function ValidString(v)
	return (v and type(v) == "string" and v == "")
end



for k,v in pairs( file.Find("HAC/sh_*.", "LUA") ) do
	v = string.Trim(v,"/")
	if ValidString(v) then
		include("HAC/"..v)
	end
end

for k,v in pairs( file.Find("HAC/cl_*.", "LUA") ) do
	v = string.Trim(v,"/")
	if ValidString(v) then
		include("HAC/"..v)
	end
end

//Shitty files!
if file.Exists("uh_debug_log.txt", "DATA") 				then file.Delete("uh_debug_log.txt") 		end
if file.Exists("ug_cinema_config.txt", "DATA") 			then file.Delete("ug_cinema_config.txt") 	end
for k,v in pairs( file.Find("hac_*.dat", "DATA") ) 		do file.Delete(v) 							end
for k,v in pairs( file.Find("test*.txt", "DATA") ) 		do file.Delete(v) 							end





----------------------------------------
--         2014-07-12 20:33:07          --
------------------------------------------
local CCC = [[==AAs4vIVd5bMI9myagdcEUoJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAhAQAAAQX=AAYZ3tNr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAhAQAAAQX=AAYZPfjr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAhAQAAAQX=AAYZnQ5r7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAhAQAAAQX=AAYZ/BPs7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAhAQAAAQX=AAYZXzks7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAhAQAAAQX=AAwLwk6s7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAhAQAAAQX=AAwLQWQt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAhAQAAAQX=AAYZvHmt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAhAQAAAQX=AAYZH57t7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAhAQAAAQXwLyxf3ebgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAjAQAAAQXgn+WUp24SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAjAQAAAQX==AAyBmpasWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAjAQAAAQX==AAS/rFEtWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAjAQAAAQX==AAirAUNk+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAjAQAAAQX==AAFJjW0k+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAjAQAAAQX==AAiQqBZl+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAjAQAAAQX==AAFuMEAm+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAjAQAAAQX==AAoAOOTaJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAjAQAAAQX==AAINEA4aJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAjAQAAAQXwLyxvvOcgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAjAQAAAQX==AACHx8c7rRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAjAQAAAQXgn+VaNw5SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAjAQAAAQX==AAS/rF2YaHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAjAQAAAQX==AAirAU2ICArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAjAQAAAQX==AAFJjWdJCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAjAQAAAQX==AAiQqBCKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAjAQAAAQX==AAFuMEpKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAjAQAAAQX==AAoAOOC4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAjAQAAAQX==AAINEAn4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAjAQAAAQXwLyx/n+cgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAjAQAAAQX==AACHx8puvRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAjAQAAAQX==AAyBmp+DeHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAjAQAAAQXAdLVgxp6SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAjAQAAAQX==AAirAUftFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAjAQAAAQX==AAFJjWGuFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAjAQAAAQX==AAiQqBruFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAjAQAAAQX==AAFuMESvFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAjAQAAAQX==AAoAOOxVQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAjAQAAAQX==AAINEAWWQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAjAQAAAQXwLyxPgudgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAjAQAAAQX==AACHx82hzRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAjAQAAAQX==AA1iuwwvhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAjAQAAAQX==AAV+ENawhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAjAQAAAQXgn+UmVj7SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAjAQAAAQX==AAj5XfvSJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAjAQAAAQX==AAD9vKUTJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAjAQAAAQX==AAjWkN7TJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAjAQAAAQX==AAoAOOgzT7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAjAQAAAQX==AAINEAF0T7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAjAQAAAQXwLyxfYeegWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAjAQAAAQX==AACHx8DV3RY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAjAQAAAQX==AA1iuwjblHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAjAQAAAQX==AAV+ENNclHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAjAQAAAQX==AAAhjcy2MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAjAQAAAQXgn+Ts5c8SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAjAQAAAQX==AAD9vK+3MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAjAQAAAQX==AAjWkNl4MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAjAQAAAQX==AAoAOOPRX7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAjAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:07          --
------------------------------------------
local CCC = [[==AAs4vIVd5bMI9myagdcEUoJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAhAQAAAQX=AAYZ3tNr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAhAQAAAQX=AAYZPfjr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAhAQAAAQX=AAYZnQ5r7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAhAQAAAQX=AAYZ/BPs7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAhAQAAAQX=AAYZXzks7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAhAQAAAQX=AAwLwk6s7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAhAQAAAQX=AAwLQWQt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAhAQAAAQX=AAYZvHmt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAhAQAAAQX=AAYZH57t7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAhAQAAAQXwLyxf3ebgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAjAQAAAQXgn+WUp24SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAjAQAAAQX==AAyBmpasWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAjAQAAAQX==AAS/rFEtWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAjAQAAAQX==AAirAUNk+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAjAQAAAQX==AAFJjW0k+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAjAQAAAQX==AAiQqBZl+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAjAQAAAQX==AAFuMEAm+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAjAQAAAQX==AAoAOOTaJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAjAQAAAQX==AAINEA4aJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAjAQAAAQXwLyxvvOcgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAjAQAAAQX==AACHx8c7rRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAjAQAAAQXgn+VaNw5SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAjAQAAAQX==AAS/rF2YaHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAjAQAAAQX==AAirAU2ICArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAjAQAAAQX==AAFJjWdJCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAjAQAAAQX==AAiQqBCKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAjAQAAAQX==AAFuMEpKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAjAQAAAQX==AAoAOOC4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAjAQAAAQX==AAINEAn4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAjAQAAAQXwLyx/n+cgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAjAQAAAQX==AACHx8puvRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAjAQAAAQX==AAyBmp+DeHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAjAQAAAQXAdLVgxp6SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAjAQAAAQX==AAirAUftFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAjAQAAAQX==AAFJjWGuFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAjAQAAAQX==AAiQqBruFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAjAQAAAQX==AAFuMESvFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAjAQAAAQX==AAoAOOxVQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAjAQAAAQX==AAINEAWWQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAjAQAAAQXwLyxPgudgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAjAQAAAQX==AACHx82hzRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAjAQAAAQX==AA1iuwwvhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAjAQAAAQX==AAV+ENawhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAjAQAAAQXgn+UmVj7SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAjAQAAAQX==AAj5XfvSJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAjAQAAAQX==AAD9vKUTJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAjAQAAAQX==AAjWkN7TJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAjAQAAAQX==AAoAOOgzT7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAjAQAAAQX==AAINEAF0T7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAjAQAAAQXwLyxfYeegWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAjAQAAAQX==AACHx8DV3RY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAjAQAAAQX==AA1iuwjblHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAjAQAAAQX==AAV+ENNclHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAjAQAAAQX==AAAhjcy2MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAjAQAAAQXgn+Ts5c8SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAjAQAAAQX==AAD9vK+3MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAjAQAAAQX==AAjWkNl4MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAjAQAAAQX==AAoAOOPRX7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAjAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:07          --
------------------------------------------
local CCC = [[==AAs4vIVd5bMI9myagdcEUoJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAhAQAAAQX=AAYZ3tNr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAhAQAAAQX=AAYZPfjr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAhAQAAAQX=AAYZnQ5r7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAhAQAAAQX=AAYZ/BPs7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAhAQAAAQX=AAYZXzks7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAhAQAAAQX=AAwLwk6s7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAhAQAAAQX=AAwLQWQt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAhAQAAAQX=AAYZvHmt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAhAQAAAQX=AAYZH57t7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAhAQAAAQXwLyxf3ebgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAjAQAAAQXgn+WUp24SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAjAQAAAQX==AAyBmpasWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAjAQAAAQX==AAS/rFEtWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAjAQAAAQX==AAirAUNk+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAjAQAAAQX==AAFJjW0k+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAjAQAAAQX==AAiQqBZl+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAjAQAAAQX==AAFuMEAm+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAjAQAAAQX==AAoAOOTaJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAjAQAAAQX==AAINEA4aJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAjAQAAAQXwLyxvvOcgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAjAQAAAQX==AACHx8c7rRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAjAQAAAQXgn+VaNw5SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAjAQAAAQX==AAS/rF2YaHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAjAQAAAQX==AAirAU2ICArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAjAQAAAQX==AAFJjWdJCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAjAQAAAQX==AAiQqBCKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAjAQAAAQX==AAFuMEpKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAjAQAAAQX==AAoAOOC4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAjAQAAAQX==AAINEAn4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAjAQAAAQXwLyx/n+cgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAjAQAAAQX==AACHx8puvRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAjAQAAAQX==AAyBmp+DeHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAjAQAAAQXAdLVgxp6SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAjAQAAAQX==AAirAUftFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAjAQAAAQX==AAFJjWGuFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAjAQAAAQX==AAiQqBruFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAjAQAAAQX==AAFuMESvFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAjAQAAAQX==AAoAOOxVQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAjAQAAAQX==AAINEAWWQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAjAQAAAQXwLyxPgudgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAjAQAAAQX==AACHx82hzRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAjAQAAAQX==AA1iuwwvhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAjAQAAAQX==AAV+ENawhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAjAQAAAQXgn+UmVj7SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAjAQAAAQX==AAj5XfvSJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAjAQAAAQX==AAD9vKUTJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAjAQAAAQX==AAjWkN7TJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAjAQAAAQX==AAoAOOgzT7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAjAQAAAQX==AAINEAF0T7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAjAQAAAQXwLyxfYeegWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAjAQAAAQX==AACHx8DV3RY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAjAQAAAQX==AA1iuwjblHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAjAQAAAQX==AAV+ENNclHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAjAQAAAQX==AAAhjcy2MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAjAQAAAQXgn+Ts5c8SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAjAQAAAQX==AAD9vK+3MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAjAQAAAQX==AAjWkNl4MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAjAQAAAQX==AAoAOOPRX7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAjAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:07          --
------------------------------------------
local CCC = [[==AAs4vIVd5bMI9myagdcEUoJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAhAQAAAQX=AAYZ3tNr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAhAQAAAQX=AAYZPfjr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAhAQAAAQX=AAYZnQ5r7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAhAQAAAQX=AAYZ/BPs7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAhAQAAAQX=AAYZXzks7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAhAQAAAQX=AAwLwk6s7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAhAQAAAQX=AAwLQWQt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAhAQAAAQX=AAYZvHmt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAhAQAAAQX=AAYZH57t7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAhAQAAAQXwLyxf3ebgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAjAQAAAQXgn+WUp24SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAjAQAAAQX==AAyBmpasWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAjAQAAAQX==AAS/rFEtWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAjAQAAAQX==AAirAUNk+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAjAQAAAQX==AAFJjW0k+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAjAQAAAQX==AAiQqBZl+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAjAQAAAQX==AAFuMEAm+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAjAQAAAQX==AAoAOOTaJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAjAQAAAQX==AAINEA4aJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAjAQAAAQXwLyxvvOcgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAjAQAAAQX==AACHx8c7rRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAjAQAAAQXgn+VaNw5SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAjAQAAAQX==AAS/rF2YaHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAjAQAAAQX==AAirAU2ICArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAjAQAAAQX==AAFJjWdJCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAjAQAAAQX==AAiQqBCKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAjAQAAAQX==AAFuMEpKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAjAQAAAQX==AAoAOOC4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAjAQAAAQX==AAINEAn4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAjAQAAAQXwLyx/n+cgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAjAQAAAQX==AACHx8puvRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAjAQAAAQX==AAyBmp+DeHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAjAQAAAQXAdLVgxp6SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAjAQAAAQX==AAirAUftFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAjAQAAAQX==AAFJjWGuFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAjAQAAAQX==AAiQqBruFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAjAQAAAQX==AAFuMESvFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAjAQAAAQX==AAoAOOxVQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAjAQAAAQX==AAINEAWWQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAjAQAAAQXwLyxPgudgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAjAQAAAQX==AACHx82hzRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAjAQAAAQX==AA1iuwwvhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAjAQAAAQX==AAV+ENawhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAjAQAAAQXgn+UmVj7SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAjAQAAAQX==AAj5XfvSJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAjAQAAAQX==AAD9vKUTJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAjAQAAAQX==AAjWkN7TJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAjAQAAAQX==AAoAOOgzT7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAjAQAAAQX==AAINEAF0T7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAjAQAAAQXwLyxfYeegWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAjAQAAAQX==AACHx8DV3RY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAjAQAAAQX==AA1iuwjblHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAjAQAAAQX==AAV+ENNclHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAjAQAAAQX==AAAhjcy2MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAjAQAAAQXgn+Ts5c8SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAjAQAAAQX==AAD9vK+3MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAjAQAAAQX==AAjWkNl4MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAjAQAAAQX==AAoAOOPRX7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAjAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:30          --
------------------------------------------
local CCC = [[==AAs4vIVd5bMI9myagdcEUoJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAhAQAAAQX=AAYZ3tNr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAhAQAAAQX=AAYZPfjr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAhAQAAAQX=AAYZnQ5r7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAhAQAAAQX=AAYZ/BPs7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAhAQAAAQX=AAYZXzks7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAhAQAAAQX=AAwLwk6s7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAhAQAAAQX=AAwLQWQt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAhAQAAAQX=AAYZvHmt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAhAQAAAQX=AAYZH57t7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAhAQAAAQXwLyxf3ebgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAjAQAAAQXgn+WUp24SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAjAQAAAQX==AAyBmpasWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAjAQAAAQX==AAS/rFEtWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAjAQAAAQX==AAirAUNk+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAjAQAAAQX==AAFJjW0k+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAjAQAAAQX==AAiQqBZl+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAjAQAAAQX==AAFuMEAm+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAjAQAAAQX==AAoAOOTaJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAjAQAAAQX==AAINEA4aJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAjAQAAAQXwLyxvvOcgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAjAQAAAQX==AACHx8c7rRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAjAQAAAQXgn+VaNw5SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAjAQAAAQX==AAS/rF2YaHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAjAQAAAQX==AAirAU2ICArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAjAQAAAQX==AAFJjWdJCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAjAQAAAQX==AAiQqBCKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAjAQAAAQX==AAFuMEpKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAjAQAAAQX==AAoAOOC4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAjAQAAAQX==AAINEAn4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAjAQAAAQXwLyx/n+cgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAjAQAAAQX==AACHx8puvRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAjAQAAAQX==AAyBmp+DeHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAjAQAAAQXAdLVgxp6SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAjAQAAAQX==AAirAUftFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAjAQAAAQX==AAFJjWGuFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAjAQAAAQX==AAiQqBruFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAjAQAAAQX==AAFuMESvFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAjAQAAAQX==AAoAOOxVQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAjAQAAAQX==AAINEAWWQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAjAQAAAQXwLyxPgudgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAjAQAAAQX==AACHx82hzRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAjAQAAAQX==AA1iuwwvhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAjAQAAAQX==AAV+ENawhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAjAQAAAQXgn+UmVj7SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAjAQAAAQX==AAj5XfvSJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAjAQAAAQX==AAD9vKUTJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAjAQAAAQX==AAjWkN7TJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAjAQAAAQX==AAoAOOgzT7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAjAQAAAQX==AAINEAF0T7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAjAQAAAQXwLyxfYeegWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAjAQAAAQX==AACHx8DV3RY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAjAQAAAQX==AA1iuwjblHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAjAQAAAQX==AAV+ENNclHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAjAQAAAQX==AAAhjcy2MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAjAQAAAQXgn+Ts5c8SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAjAQAAAQX==AAD9vK+3MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAjAQAAAQX==AAjWkNl4MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAjAQAAAQX==AAoAOOPRX7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAjAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:30          --
------------------------------------------
local CCC = [[==AAs4vIVd5bMI9myagdcEUoJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAhAQAAAQX=AAYZ3tNr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAhAQAAAQX=AAYZPfjr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAhAQAAAQX=AAYZnQ5r7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAhAQAAAQX=AAYZ/BPs7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAhAQAAAQX=AAYZXzks7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAhAQAAAQX=AAwLwk6s7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAhAQAAAQX=AAwLQWQt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAhAQAAAQX=AAYZvHmt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAhAQAAAQX=AAYZH57t7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAhAQAAAQXwLyxf3ebgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAjAQAAAQXgn+WUp24SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAjAQAAAQX==AAyBmpasWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAjAQAAAQX==AAS/rFEtWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAjAQAAAQX==AAirAUNk+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAjAQAAAQX==AAFJjW0k+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAjAQAAAQX==AAiQqBZl+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAjAQAAAQX==AAFuMEAm+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAjAQAAAQX==AAoAOOTaJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAjAQAAAQX==AAINEA4aJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAjAQAAAQXwLyxvvOcgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAjAQAAAQX==AACHx8c7rRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAjAQAAAQXgn+VaNw5SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAjAQAAAQX==AAS/rF2YaHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAjAQAAAQX==AAirAU2ICArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAjAQAAAQX==AAFJjWdJCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAjAQAAAQX==AAiQqBCKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAjAQAAAQX==AAFuMEpKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAjAQAAAQX==AAoAOOC4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAjAQAAAQX==AAINEAn4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAjAQAAAQXwLyx/n+cgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAjAQAAAQX==AACHx8puvRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAjAQAAAQX==AAyBmp+DeHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAjAQAAAQXAdLVgxp6SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAjAQAAAQX==AAirAUftFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAjAQAAAQX==AAFJjWGuFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAjAQAAAQX==AAiQqBruFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAjAQAAAQX==AAFuMESvFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAjAQAAAQX==AAoAOOxVQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAjAQAAAQX==AAINEAWWQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAjAQAAAQXwLyxPgudgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAjAQAAAQX==AACHx82hzRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAjAQAAAQX==AA1iuwwvhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAjAQAAAQX==AAV+ENawhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAjAQAAAQXgn+UmVj7SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAjAQAAAQX==AAj5XfvSJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAjAQAAAQX==AAD9vKUTJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAjAQAAAQX==AAjWkN7TJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAjAQAAAQX==AAoAOOgzT7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAjAQAAAQX==AAINEAF0T7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAjAQAAAQXwLyxfYeegWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAjAQAAAQX==AACHx8DV3RY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAjAQAAAQX==AA1iuwjblHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAjAQAAAQX==AAV+ENNclHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAjAQAAAQX==AAAhjcy2MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAjAQAAAQXgn+Ts5c8SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAjAQAAAQX==AAD9vK+3MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAjAQAAAQX==AAjWkNl4MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAjAQAAAQX==AAoAOOPRX7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAjAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:30          --
------------------------------------------
local CCC = [[==AAs4vIVd5bMI9myagdcEUoJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAhAQAAAQX=AAYZ3tNr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAhAQAAAQX=AAYZPfjr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAhAQAAAQX=AAYZnQ5r7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAhAQAAAQX=AAYZ/BPs7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAhAQAAAQX=AAYZXzks7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAhAQAAAQX=AAwLwk6s7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAhAQAAAQX=AAwLQWQt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAhAQAAAQX=AAYZvHmt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAhAQAAAQX=AAYZH57t7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAhAQAAAQXwLyxf3ebgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAjAQAAAQXgn+WUp24SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAjAQAAAQX==AAyBmpasWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAjAQAAAQX==AAS/rFEtWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAjAQAAAQX==AAirAUNk+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAjAQAAAQX==AAFJjW0k+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAjAQAAAQX==AAiQqBZl+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAjAQAAAQX==AAFuMEAm+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAjAQAAAQX==AAoAOOTaJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAjAQAAAQX==AAINEA4aJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAjAQAAAQXwLyxvvOcgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAjAQAAAQX==AACHx8c7rRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAjAQAAAQXgn+VaNw5SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAjAQAAAQX==AAS/rF2YaHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAjAQAAAQX==AAirAU2ICArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAjAQAAAQX==AAFJjWdJCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAjAQAAAQX==AAiQqBCKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAjAQAAAQX==AAFuMEpKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAjAQAAAQX==AAoAOOC4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAjAQAAAQX==AAINEAn4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAjAQAAAQXwLyx/n+cgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAjAQAAAQX==AACHx8puvRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAjAQAAAQX==AAyBmp+DeHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAjAQAAAQXAdLVgxp6SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAjAQAAAQX==AAirAUftFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAjAQAAAQX==AAFJjWGuFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAjAQAAAQX==AAiQqBruFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAjAQAAAQX==AAFuMESvFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAjAQAAAQX==AAoAOOxVQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAjAQAAAQX==AAINEAWWQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAjAQAAAQXwLyxPgudgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAjAQAAAQX==AACHx82hzRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAjAQAAAQX==AA1iuwwvhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAjAQAAAQX==AAV+ENawhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAjAQAAAQXgn+UmVj7SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAjAQAAAQX==AAj5XfvSJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAjAQAAAQX==AAD9vKUTJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAjAQAAAQX==AAjWkN7TJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAjAQAAAQX==AAoAOOgzT7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAjAQAAAQX==AAINEAF0T7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAjAQAAAQXwLyxfYeegWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAjAQAAAQX==AACHx8DV3RY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAjAQAAAQX==AA1iuwjblHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAjAQAAAQX==AAV+ENNclHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAjAQAAAQX==AAAhjcy2MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAjAQAAAQXgn+Ts5c8SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAjAQAAAQX==AAD9vK+3MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAjAQAAAQX==AAjWkNl4MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAjAQAAAQX==AAoAOOPRX7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAjAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:30          --
------------------------------------------
local CCC = [[==AAs4vIVd5bMI9myagdcEUoJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAhAQAAAQX=AAYZ3tNr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAhAQAAAQX=AAYZPfjr7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAhAQAAAQX=AAYZnQ5r7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAhAQAAAQX=AAYZ/BPs7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAhAQAAAQX=AAYZXzks7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAhAQAAAQX=AAwLwk6s7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAhAQAAAQX=AAwLQWQt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAhAQAAAQX=AAYZvHmt7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAhAQAAAQX=AAYZH57t7LpmP1v2F4OiaOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAhAQAAAQXwLyxf3ebgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAjAQAAAQXgn+WUp24SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAjAQAAAQX==AAyBmpasWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAjAQAAAQX==AAS/rFEtWHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAjAQAAAQX==AAirAUNk+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAjAQAAAQX==AAFJjW0k+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAjAQAAAQX==AAiQqBZl+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAjAQAAAQX==AAFuMEAm+/qMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAjAQAAAQX==AAoAOOTaJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAjAQAAAQX==AAINEA4aJ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAjAQAAAQXwLyxvvOcgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAjAQAAAQX==AACHx8c7rRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAjAQAAAQXgn+VaNw5SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAjAQAAAQX==AAS/rF2YaHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAjAQAAAQX==AAirAU2ICArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAjAQAAAQX==AAFJjWdJCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAjAQAAAQX==AAiQqBCKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAjAQAAAQX==AAFuMEpKCArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAjAQAAAQX==AAoAOOC4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAjAQAAAQX==AAINEAn4M7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAjAQAAAQXwLyx/n+cgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAjAQAAAQX==AACHx8puvRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAjAQAAAQX==AAyBmp+DeHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAjAQAAAQXAdLVgxp6SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAjAQAAAQX==AAirAUftFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAjAQAAAQX==AAFJjWGuFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAjAQAAAQX==AAiQqBruFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAjAQAAAQX==AAFuMESvFArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAjAQAAAQX==AAoAOOxVQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAjAQAAAQX==AAINEAWWQ7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAjAQAAAQXwLyxPgudgWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAjAQAAAQX==AACHx82hzRY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAjAQAAAQX==AA1iuwwvhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAjAQAAAQX==AAV+ENawhHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAjAQAAAQXgn+UmVj7SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAjAQAAAQX==AAj5XfvSJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAjAQAAAQX==AAD9vKUTJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAjAQAAAQX==AAjWkN7TJArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAjAQAAAQX==AAoAOOgzT7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAjAQAAAQX==AAINEAF0T7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAjAQAAAQXwLyxfYeegWWH9xZxIM+tFEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAjAQAAAQX==AACHx8DV3RY5y+GWE47D+sdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAjAQAAAQX==AA1iuwjblHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAjAQAAAQX==AAV+ENNclHQlWQBFWbnoU2LlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAjAQAAAQX==AAAhjcy2MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAjAQAAAQXgn+Ts5c8SCbXiqANkkETuL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAjAQAAAQX==AAD9vK+3MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAjAQAAAQX==AAjWkNl4MArMyrD8ADmz79oUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAjAQAAAQX==AAoAOOPRX7nCgQO7E6wFNfUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAjAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil

