
local BadFiles = {}
BadFiles = {
	--generic:hack
	"includes/modules/*hack*.dll",
	"menu_plugins/*hack*.lua",
	"includes/enum/*hack*.lua",
	"vgui/*hack*.lua",
	"autorun/*hack*.lua",
	"autorun/client/*hack*.lua",
	"*hack*.lua",
	"*hacks*.lua",	
	"hack/*.lua",
	--generic:hax
	"includes/modules/*hax*.dll",
	"menu_plugins/*hax*.lua",
	"includes/enum/*hax*.lua",
	"vgui/*hax*.lua",
	"autorun/*hax*.lua",
	"autorun/client/*hax*.lua",
	"*hax*.lua",
	"hax/*.lua",
	--generic:h4x
	"includes/modules/*h4x*.dll",
	"menu_plugins/*h4x*.lua",
	"includes/enum/*h4x*.lua",
	"vgui/*h4x*.lua",
	"autorun/*h4x*.lua",
	"autorun/client/*h4x*.lua",
	"*h4x*.lua",
	"h4x/*.lua",
	--generic:force
	"includes/modules/*force*.dll",
	"menu_plugins/*force*.lua",
	"includes/enum/*force*.lua",
	"vgui/*force*.lua",
	"autorun/*force*.lua",
	"autorun/client/*force*.lua",
	"*force*.lua",
	--generic:cheat
	"menu_plugins/*cheat*.lua",
	"includes/enum/*cheat*.lua",
	"vgui/*cheat*.lua",
	"autorun/*cheat*.lua",
	"autorun/client/*cheat*.lua",
	"*cheat*.lua",
	"cheat/*.lua",
	"cheats/*.lua",
	--generic:spam
	"autorun/*spam*.lua",
	"autorun/client/*spam*.lua",
	"*spam*.lua",
	--generic:bypass
	"menu_plugins/*bypass*.lua",
	"includes/enum/*bypass*.lua",
	"vgui/*bypass*.lua",
	"autorun/*bypass*.lua",
	"autorun/client/*bypass*.lua",
	"*bypass*.lua",
	"bypass/*.lua",
	"bypasses/*.lua",
	--generic:bot
	"menu_plugins/*bot*.lua",
	"includes/enum/*bot*.lua",
	"vgui/*bot*.lua",
	"autorun/*bot*.lua",
	"autorun/client/*bot*.lua",
	"*bot*.lua",
	--generic:troll
	"autorun/*troll*.lua",
	"autorun/client/*troll*.lua",
	"*troll*.lua",
	
	--JonSuite
	"JonSuite/Hacks/*.lua", 
	"JonSuite/*.lua",
	
	--FapHack
	"menu_plugins/*faphack*.lua",
	"includes/enum/*faphack*.lua",
	"vgui/*faphack*.lua",
	"autorun/*faphack*.lua",
	"autorun/client/*faphack*.lua",	
	"*faphack*.lua",
	"FapHack/*.lua",

	--hades
	"includes/modules/*hades*.dll",
	"menu_plugins/*hades*.lua",
	"includes/enum/*hades*.lua",
	"vgui/*hades*.lua",
	"autorun/*hades*.lua",
	"autorun/client/*hades*.lua",
	"*hades*.lua",
	"hades/*.lua",
	"hades/core/*.lua",

	--Baconbot
	"includes/modules/*testbot*.dll",
	"includes/modules/*bbot*.dll",	
	"stuff/Clock.lua",
	
	--name
	"autorun/Adv.Name.lua",
	"autorun/client/Adv.Name.lua",
	"Adv.Name.lua",
	"autorun/name_new.lua",	
	"autorun/client/name_new.lua",
	"name_new.lua",
	"autorun/namescript.lua",
	"autorun/client/namescript.lua",
	"namescript.lua",
	"autorun/randomname.lua",
	"autorun/client/randomname.lua",
	"randomname.lua",
	
	--asb
	"autorun/asb.lua",	
	"autorun/client/asb.lua",
	"asb.lua",
	"autorun/_TEMPLATE.lua",	
	"autorun/client/_TEMPLATE.lua",
	"_TEMPLATE.lua",
	"autorun/asb_base.lua",
	"autorun/client/asb_base.lua",
	"asb_base.lua",
	
	--autoaim
	"autorun/AutoAim.lua",
	"autorun/client/AutoAim.lua",	
	"AutoAim.lua",
	
	--random
	"autorun/I_laik_being_dum.lua",
	"autorun/client/I_laik_being_dum.lua",
	"autorun/waroftheservers.lua",
	"autorun/client/waroftheservers.lua",
	"autorun/hai.lua",
	"autorun/client/hai.lua",	
	"hai.lua",
	"autorun/fuckoff.lua",
	"autorun/client/fuckoff.lua",
	"fuckoff.lua",
	"autorun/AGT.lua",
	"autorun/client/AGT.lua",
	"AGT.lua",

	--bypasses etc
	"includes/modules/gm_funcsolver.dll",
	"includes/modules/gm_concmd.dll",
	"includes/modules/*_decz.dll",
	"includes/modules/gm_bindkey.dll",	
	"includes/modules/*luamd5*.dll",
	"includes/modules/*_deco.dll",
	"includes/modules/*_se2.dll",
	"includes/modules/*secret*.dll",
	"includes/modules/*unblock*.dll",
	"includes/modules/*byese2*.dll",
	"includes/modules/*convar*.dll",
	"includes/modules/*command*.dll",
	--random bypasses
	"menu_plugins/abc_panel.lua",
	"vgui/abc_panel.lua",
	--luamd5
	"menu_plugins/*luamd5*.lua",
	"includes/enum/*luamd5*.lua",
	"vgui/*luamd5*.lua",
	"autorun/*luamd5*.lua",
	"autorun/client/*luamd5*.lua",
	"*luamd5*.lua",
	--antiread
	"menu_plugins/*antiread*.lua",
	"includes/enum/*antiread*.lua",
	"vgui/*antiread*.lua",
	"autorun/*antiread*.lua",
	"autorun/client/*antiread*.lua",
	"*antiread*.lua",
	--lua_run
	"menu_plugins/*lua_run*.lua",
	"includes/enum/*lua_run*.lua",
	"vgui/*lua_run*.lua",
	"autorun/*lua_run*.lua",
	"autorun/client/*lua_run*.lua",
	"*lua_run*.lua",
	--selfpwn
	"menu_plugins/*selfpwn*.lua",
	"includes/enum/*selfpwn*.lua",
	"vgui/*selfpwn*.lua",
	"autorun/*selfpwn*.lua",
	"autorun/client/*selfpwn*.lua",
	"*selfpwn*.lua"
}

