concommand.Add("mt_reload", function() include("custom_menu/ml_maptest.lua") end)

local BadMaps = {
	["gm_construct.bsp"] = true,
	["gm_flatgrass.bsp"] = true,
	["background01.bsp"] = true,
	["background02.bsp"] = true,
	["background03.bsp"] = true,
	["background04.bsp"] = true,
	["background05.bsp"] = true,
	["background06.bsp"] = true,
	["background07.bsp"] = true,
	["credits.bsp"] = true,
	["d1_canals_01.bsp"] = true,
	["d1_canals_01a.bsp"] = true,
	["d1_canals_02.bsp"] = true,
	["d1_canals_03.bsp"] = true,
	["d1_canals_05.bsp"] = true,
	["d1_canals_06.bsp"] = true,
	["d1_canals_07.bsp"] = true,
	["d1_canals_08.bsp"] = true,
	["d1_canals_09.bsp"] = true,
	["d1_canals_10.bsp"] = true,
	["d1_canals_11.bsp"] = true,
	["d1_canals_12.bsp"] = true,
	["d1_canals_13.bsp"] = true,
	["d1_eli_01.bsp"] = true,
	["d1_eli_02.bsp"] = true,
	["d1_town_01.bsp"] = true,
	["d1_town_01a.bsp"] = true,
	["d1_town_02.bsp"] = true,
	["d1_town_02a.bsp"] = true,
	["d1_town_03.bsp"] = true,
	["d1_town_04.bsp"] = true,
	["d1_town_05.bsp"] = true,
	["d1_trainstation_01.bsp"] = true,
	["d1_trainstation_02.bsp"] = true,
	["d1_trainstation_03.bsp"] = true,
	["d1_trainstation_04.bsp"] = true,
	["d1_trainstation_05.bsp"] = true,
	["d1_trainstation_06.bsp"] = true,
	["d2_coast_01.bsp"] = true,
	["d2_coast_03.bsp"] = true,
	["d2_coast_04.bsp"] = true,
	["d2_coast_05.bsp"] = true,
	["d2_coast_07.bsp"] = true,
	["d2_coast_08.bsp"] = true,
	["d2_coast_09.bsp"] = true,
	["d2_coast_10.bsp"] = true,
	["d2_coast_11.bsp"] = true,
	["d2_coast_12.bsp"] = true,
	["d2_prison_01.bsp"] = true,
	["d2_prison_02.bsp"] = true,
	["d2_prison_03.bsp"] = true,
	["d2_prison_04.bsp"] = true,
	["d2_prison_05.bsp"] = true,
	["d2_prison_06.bsp"] = true,
	["d2_prison_07.bsp"] = true,
	["d2_prison_08.bsp"] = true,
	["d3_breen_01.bsp"] = true,
	["d3_c17_01.bsp"] = true,
	["d3_c17_02.bsp"] = true,
	["d3_c17_03.bsp"] = true,
	["d3_c17_04.bsp"] = true,
	["d3_c17_05.bsp"] = true,
	["d3_c17_06a.bsp"] = true,
	["d3_c17_06b.bsp"] = true,
	["d3_c17_07.bsp"] = true,
	["d3_c17_08.bsp"] = true,
	["d3_c17_09.bsp"] = true,
	["d3_c17_10a.bsp"] = true,
	["d3_c17_10b.bsp"] = true,
	["d3_c17_11.bsp"] = true,
	["d3_c17_12.bsp"] = true,
	["d3_c17_12b.bsp"] = true,
	["d3_c17_13.bsp"] = true,
	["d3_citadel_01.bsp"] = true,
	["d3_citadel_02.bsp"] = true,
	["d3_citadel_03.bsp"] = true,
	["d3_citadel_04.bsp"] = true,
	["d3_citadel_05.bsp"] = true,
	["intro.bsp"] = true,
	["advisor_test.bsp"] = true,
	["autorpv1.bsp"] = true,
	["background.bsp"] = true,
	["bhop_wetlands.bsp"] = true,
	["castledefense.bsp"] = true,
	["combine_fun.bsp"] = true,
	["combine_onslaught.bsp"] = true,
	["combine_onslaughtv1_1.bsp"] = true,
	["combine_onslaughtv2.bsp"] = true,
	["combine_onslaught_ep2.bsp"] = true,
	["crater.bsp"] = true,
	["dev_box.bsp"] = true,
	["de_hoejhus.bsp"] = true,
	["de_relic.bsp"] = true,
	["dm_thursday.bsp"] = true,
	["dr_carbonic_v3.bsp"] = true,
	["duckhunt_party.bsp"] = true,
	["duckhunt_party_v2.bsp"] = true,
	["esiphar.bsp"] = true,
	["gmdm_antlions_ep2.bsp"] = true,
	["gm_2cliffs.bsp"] = true,
	["gm_711_v5.bsp"] = true,
	["gm_apartment.bsp"] = true,
	["gm_apoc_v1.bsp"] = true,
	["gm_assault_v2.bsp"] = true,
	["gm_atomic.bsp"] = true,
	["gm_azalea.bsp"] = true,
	["gm_bigassmapv2.bsp"] = true,
	["gm_blackmesa_sigma_by_freakrules.bsp"] = true,
	["gm_bounize.bsp"] = true,
	["gm_boxed.bsp"] = true,
	["gm_buttes.bsp"] = true,
	["gm_cliffside_v2.bsp"] = true,
	["gm_closedin.bsp"] = true,
	["gm_constructconsp.bsp"] = true,
	["gm_construct_bunker.bsp"] = true,
	["gm_construct_flatgrass_v6.bsp"] = true,
	["gm_derpityda.bsp"] = true,
	["gm_devcity.bsp"] = true,
	["gm_dmm_cabin.bsp"] = true,
	["gm_duckhunt.bsp"] = true,
	["gm_duststruct.bsp"] = true,
	["gm_endlessocean.bsp"] = true,
	["gm_essentials.bsp"] = true,
	["gm_excess_waters.bsp"] = true,
	["gm_findthefort8.bsp"] = true,
	["gm_flatbuild_pb.bsp"] = true,
	["gm_flatgrass2.bsp"] = true,
	["gm_flatgrass_pit.bsp"] = true,
	["gm_flatgrass_remake.bsp"] = true,
	["gm_flatmulti.bsp"] = true,
	["gm_flatsnow_xdc_r1_1.bsp"] = true,
	["gm_flying_reliquies.bsp"] = true,
	["gm_fortexia_v1.bsp"] = true,
	["gm_funroom_v12.bsp"] = true,
	["gm_gmnzrace.bsp"] = true,
	["gm_gmodopoly.bsp"] = true,
	["gm_gmodsauce.bsp"] = true,
	["gm_hl1_cliff.bsp"] = true,
	["gm_hl1_interloper.bsp"] = true,
	["gm_isles.bsp"] = true,
	["gm_jon_island.bsp"] = true,
	["gm_kbmodernhouse.bsp"] = true,
	["gm_lake_final.bsp"] = true,
	["gm_lava.bsp"] = true,
	["gm_lostconstruct.bsp"] = true,
	["gm_mc_construct.bsp"] = true,
	["gm_mc_construct_final.bsp"] = true,
	["gm_mental_asylum.bsp"] = true,
	["gm_minecraft.bsp"] = true,
	["gm_minecrafter_day.bsp"] = true,
	["gm_mix_v5.bsp"] = true,
	["gm_moving_train.bsp"] = true,
	["gm_neverendingwar_prototype.bsp"] = true,
	["gm_opposedbases.bsp"] = true,
	["gm_overgrown_build.bsp"] = true,
	["gm_pd_destruct.bsp"] = true,
	["gm_pd_terrageosord.bsp"] = true,
	["gm_peaceforest_winter.bsp"] = true,
	["gm_perfectworld_v1.bsp"] = true,
	["gm_racelandschool.bsp"] = true,
	["gm_race_natura_v2.bsp"] = true,
	["gm_risk.bsp"] = true,
	["gm_roadspace.bsp"] = true,
	["gm_ruvillagev2.bsp"] = true,
	["gm_seascraper.bsp"] = true,
	["gm_simplestruct.bsp"] = true,
	["gm_smallfight.bsp"] = true,
	["gm_speedway_v2.bsp"] = true,
	["gm_stramicbuild_b7.bsp"] = true,
	["gm_the_cage_v3.bsp"] = true,
	["gm_tinystruct.bsp"] = true,
	["gm_transporter.bsp"] = true,
	["gm_tugofwar_combine.bsp"] = true,
	["gm_tullysbunker.bsp"] = true,
	["gm_ultimate_flatgrass.bsp"] = true,
	["gm_valley.bsp"] = true,
	["gm_voided_fixed.bsp"] = true,
	["gm_warmth.bsp"] = true,
	["gm_zach_island.bsp"] = true,
	["gunship_onslaght.bsp"] = true,
	["harbor2ocean_navalb3.bsp"] = true,
	["hoejhus9_minecraft.bsp"] = true,
	["home.bsp"] = true,
	["mg_eye_train_b1_fix.bsp"] = true,
	["mg_space_eye_smash.bsp"] = true,
	["neostruct_extended.bsp"] = true,
	["os_antlion_siege.bsp"] = true,
	["phys_bibridgeton.bsp"] = true,
	["phys_jenga.bsp"] = true,
	["prisonv2.bsp"] = true,
	["pyth_targettest.bsp"] = true,
	["rainbow_drop.bsp"] = true,
	["rp_dependancev1beta14.bsp"] = true,
	["rp_fortlongcat_v2i.bsp"] = true,
	["rp_prison.bsp"] = true,
	["rp_sunvale.bsp"] = true,
	["rp_sunvale_v2.bsp"] = true,
	["sb_new_worlds_2.bsp"] = true,
	["sdk_dmm_building.bsp"] = true,
	["sdk_dynamic_water.bsp"] = true,
	["steampunk.bsp"] = true,
	["ttt_67th_way.bsp"] = true,
	["ttt_crummycradle_a4.bsp"] = true,
	["ttt_infini_b3.bsp"] = true,
	["vs_underground_v2.bsp"] = true,
	["wall-mart_v6_final.bsp"] = true,
	["wm_nightspell.bsp"] = true,
	["wm_winterwarfare.bsp"] = true,
	["zm_lv426.bsp"] = true,
	["zm_survive.bsp"] = true,
	["zombiesurvival_mojave.bsp"] = true,
	["zombiesurvival_mojave_lonesome.bsp"] = true,
	["zs_gravity_v2.bsp"] = true,
	["zs_obj_vertigo_v0.bsp"] = true,
	["zs_trainterminal.bsp"] = true,
	["zwonder_2_v2.bsp"] = true,
	["cs_assault.bsp"] = true,
	["cs_compound.bsp"] = true,
	["cs_havana.bsp"] = true,
	["cs_italy.bsp"] = true,
	["cs_militia.bsp"] = true,
	["cs_office.bsp"] = true,
	["de_aztec.bsp"] = true,
	["de_cbble.bsp"] = true,
	["de_chateau.bsp"] = true,
	["de_dust.bsp"] = true,
	["de_dust2.bsp"] = true,
	["de_inferno.bsp"] = true,
	["de_nuke.bsp"] = true,
	["de_piranesi.bsp"] = true,
	["de_port.bsp"] = true,
	["de_prodigy.bsp"] = true,
	["de_tides.bsp"] = true,
	["de_train.bsp"] = true,
	["test_hardware.bsp"] = true,
	["test_speakers.bsp"] = true,
	["ep2_background01.bsp"] = true,
	["ep2_background02.bsp"] = true,
	["ep2_background02a.bsp"] = true,
	["ep2_background03.bsp"] = true,
	["ep2_outland_01.bsp"] = true,
	["ep2_outland_01a.bsp"] = true,
	["ep2_outland_02.bsp"] = true,
	["ep2_outland_03.bsp"] = true,
	["ep2_outland_04.bsp"] = true,
	["ep2_outland_05.bsp"] = true,
	["ep2_outland_06.bsp"] = true,
	["ep2_outland_06a.bsp"] = true,
	["ep2_outland_07.bsp"] = true,
	["ep2_outland_08.bsp"] = true,
	["ep2_outland_09.bsp"] = true,
	["ep2_outland_10.bsp"] = true,
	["ep2_outland_10a.bsp"] = true,
	["ep2_outland_11.bsp"] = true,
	["ep2_outland_11a.bsp"] = true,
	["ep2_outland_11b.bsp"] = true,
	["ep2_outland_12.bsp"] = true,
	["ep2_outland_12a.bsp"] = true,
	["arena_badlands.bsp"] = true,
	["arena_granary.bsp"] = true,
	["arena_lumberyard.bsp"] = true,
	["arena_nucleus.bsp"] = true,
	["arena_offblast_final.bsp"] = true,
	["arena_ravine.bsp"] = true,
	["arena_sawmill.bsp"] = true,
	["arena_watchtower.bsp"] = true,
	["arena_well.bsp"] = true,
	["cp_5gorge.bsp"] = true,
	["cp_badlands.bsp"] = true,
	["cp_coldfront.bsp"] = true,
	["cp_degrootkeep.bsp"] = true,
	["cp_dustbowl.bsp"] = true,
	["cp_egypt_final.bsp"] = true,
	["cp_fastlane.bsp"] = true,
	["cp_foundry.bsp"] = true,
	["cp_freight_final1.bsp"] = true,
	["cp_gorge.bsp"] = true,
	["cp_granary.bsp"] = true,
	["cp_gravelpit.bsp"] = true,
	["cp_gullywash_final1.bsp"] = true,
	["cp_junction_final.bsp"] = true,
	["cp_manor_event.bsp"] = true,
	["cp_mountainlab.bsp"] = true,
	["cp_steel.bsp"] = true,
	["cp_well.bsp"] = true,
	["cp_yukon_final.bsp"] = true,
	["ctf_2fort.bsp"] = true,
	["ctf_doublecross.bsp"] = true,
	["ctf_sawmill.bsp"] = true,
	["ctf_turbine.bsp"] = true,
	["ctf_well.bsp"] = true,
	["itemtest.bsp"] = true,
	["koth_badlands.bsp"] = true,
	["koth_harvest_event.bsp"] = true,
	["koth_harvest_final.bsp"] = true,
	["koth_lakeside_final.bsp"] = true,
	["koth_nucleus.bsp"] = true,
	["koth_sawmill.bsp"] = true,
	["koth_viaduct.bsp"] = true,
	["koth_viaduct_event.bsp"] = true,
	["pl_badwater.bsp"] = true,
	["pl_barnblitz.bsp"] = true,
	["pl_frontier_final.bsp"] = true,
	["pl_goldrush.bsp"] = true,
	["pl_hoodoo_final.bsp"] = true,
	["pl_thundermountain.bsp"] = true,
	["pl_upward.bsp"] = true,
	["plr_hightower.bsp"] = true,
	["plr_nightfall_final.bsp"] = true,
	["plr_pipeline.bsp"] = true,
	["tc_hydro.bsp"] = true,
	["tr_dustbowl.bsp"] = true,
	["tr_target.bsp"] = true,
	["ep1_background01.bsp"] = true,
	["ep1_background01a.bsp"] = true,
	["ep1_background02.bsp"] = true,
	["ep1_c17_00.bsp"] = true,
	["ep1_c17_00a.bsp"] = true,
	["ep1_c17_01.bsp"] = true,
	["ep1_c17_02.bsp"] = true,
	["ep1_c17_02a.bsp"] = true,
	["ep1_c17_02b.bsp"] = true,
	["ep1_c17_05.bsp"] = true,
	["ep1_c17_06.bsp"] = true,
	["ep1_citadel_00.bsp"] = true,
	["ep1_citadel_01.bsp"] = true,
	["ep1_citadel_02.bsp"] = true,
	["ep1_citadel_02b.bsp"] = true,
	["ep1_citadel_03.bsp"] = true,
	["ep1_citadel_04.bsp"] = true,
	["dm_lockdown.bsp"] = true,
	["dm_overwatch.bsp"] = true,
	["dm_powerhouse.bsp"] = true,
	["dm_resistance.bsp"] = true,
	["dm_runoff.bsp"] = true,
	["dm_steamlab.bsp"] = true,
	["dm_underpass.bsp"] = true,
	["background1.bsp"] = true,
	["background2.bsp"] = true,
	["escape_00.bsp"] = true,
	["escape_01.bsp"] = true,
	["escape_02.bsp"] = true,
	["testchmb_a_00.bsp"] = true,
	["testchmb_a_01.bsp"] = true,
	["testchmb_a_02.bsp"] = true,
	["testchmb_a_03.bsp"] = true,
	["testchmb_a_04.bsp"] = true,
	["testchmb_a_05.bsp"] = true,
	["testchmb_a_06.bsp"] = true,
	["testchmb_a_07.bsp"] = true,
	["testchmb_a_08.bsp"] = true,
	["testchmb_a_08_advanced.bsp"] = true,
	["testchmb_a_09.bsp"] = true,
	["testchmb_a_09_advanced.bsp"] = true,
	["testchmb_a_10.bsp"] = true,
	["testchmb_a_10_advanced.bsp"] = true,
	["testchmb_a_11.bsp"] = true,
	["testchmb_a_11_advanced.bsp"] = true,
	["testchmb_a_13.bsp"] = true,
	["testchmb_a_13_advanced.bsp"] = true,
	["testchmb_a_14.bsp"] = true,
	["testchmb_a_14_advanced.bsp"] = true,
	["testchmb_a_15.bsp"] = true,
	["asc_vanilla.bsp"] = true,
	["dfa_islands.bsp"] = true,
	["dfa_rsi_i.bsp"] = true,
}



local AllMaps 	= {}
local DoneMaps	= {}
local function GetAllMaps()
	for k,v in pairs( file.Find("maps/*.bsp", true) ) do
		v = v:lower()
		
		if not BadMaps[v] then
			table.insert(AllMaps, v)
		end
	end
end
timer.Simple(0.1, GetAllMaps)


local function LoadNextMap()
	local Total = #AllMaps
	if (Total == 0) then
		print("! No maps in folder!")
		return
	elseif (Total > 50) then
		print("! Too many maps, this isn't testing!")
		return
	end
	
	local Map
	for k,v in pairs(AllMaps) do
		if not DoneMaps[v] then
			DoneMaps[v]	= true
			Map = v
			break
		end
	end
	
	if not Map then
		print("! Out of maps!")
		return
	end
	
	print( Format("LoadNextMap (%s/%s): %s", table.Count(DoneMaps), Total, Map) )
	timer.Simple(0.1, HeXLRCL, "disconnect")
	timer.Simple(0.5, HeXLRCL, "map "..Map)
end
concommand.Add("mt_next", LoadNextMap)


local function DumpAllMaps()
	local tot = 0
	for k,v in pairs(AllMaps) do
		file.Append("mt_dump.txt", Format('\t["%s"] = true,\n', v) )
		tot = tot + 1
	end
	
	print("! dumped: "..tot.." maps")
end
concommand.Add("mt_dump", DumpAllMaps)






