

--FIXED, message is this complete message
HSP.ChatFilter.Fixed = {
	{what = "what the fuck",	with = "What is love?"},
	{what = "what the hell",	with = "I like it up the butt!"},
	{what = "spawn kill",		with = "You're so much better than I am :)"},
	{what = "spawnkill",		with = "You're much better than me :)"},
	{what = "what the", 		with = "Never gonna give you up"},
	{what = "*ranting*",		with = "I really need a BF, come chat tonight, add _FLT_ <3"},
	{what = "ranting*",			with = "I really need a BF, come chat tonight, add _FLT_ <3"},
	{what = "*ranting",			with = "I really need a BF, come chat tonight, add _FLT_ <3"},
	{what = "ranting",			with = "I really need a BF, come chat tonight, add _FLT_ <3"},
	{what = "lolwtf",			with = "you're cute! add me on MSN _FLT_ for a good time"},
	{what = "stupid",			with = "oh my god, please bang me all night long!"},
	{what = "idiot",			with = "I would LOVE your tasty boner!!"},
	{what = "moron",			with = "wow come and see my boner!!"},
	{what = "!menu",			with = "hey can you test your gun on me for a min"},
	{what = "0wned",			with = "I'm terrible"},
	{what = "0wn3d",			with = "I'm terrible"},
	{what = "owned",			with = "I'm terrible"},
	{what = "pwn3d",			with = "I'm losing"},
	{what = "pwned",			with = "I can't play!"},
	{what = ". . .",			with = "Bullet Holes!"},
	{what = ". . . .",			with = "Bullet Holes!"},
	{what = ". . . . .",		with = "Bullet Holes!"},
	{what = ". . . . . .",		with = "Bullet Holes!"},
	{what = "stop",				with = "hey, I can't remember how deathmatch works :("},
	{what = "dude",				with = "dude, I just bought a whole box of dildos!"},
	{what = "pwnd",				with = "I suck"},
	{what = "wut?",				with = "Windows Update?"},
	{what = "wtf?",				with = "Have you ever been to the Waste Transfer Facility?"},
	{what = "wtf!",				with = "I got a job at the Waste Transfer Facility!"},
	{what = ". .",				with = "two Bullet Holes!"},
	{what = "own",				with = "I'm terrible"},
	{what = "pwn",				with = "I suck at deathmatch"},
	{what = "wtf",				with = "I was fired from the Waste Transfer Facility due to bad spelling :("},
	{what = "not",				with = "Not that I have anything against taking it up the butt!"},
	{what = "xp",				with = "Windows XP"},
	{what = "xd",				with = "I love to suck extra dicks!"},
	{what = ")",				with = "Bracket!"},
	{what = "(",				with = "Bracket!"},
	
	{what = "hack",				with = "I didn't know HeX spent 4 years writing an AntiCheat that's banned 850+ users"},
	{what = "cheat",			with = "I didn't know HeX spent 4 years writing an AntiCheat that's banned 850+ users"},
	{what = "hacker",			with = "I didn't know HeX spent 4 years writing an AntiCheat that's banned 850+ users"},
	{what = "cheater",			with = "I didn't know HeX spent 4 years writing an AntiCheat that's banned 850+ users"},
	
	{what = "NO",				with = "what are you waiting for, shoot me!",			full = true},
	{what = "NO!",				with = "hey could you test the SMG on me for a sec",	full = true},
	{what = "no",				with = "yes!",											full = true},
	{what = "no!",				with = "Bang me time and time again!"},
	
	{what = "don't!", 			with = "shoot me now!"},
	{what = "don't", 			with = "shoot me now!"},
	{what = "dont!", 			with = "Everyone shoot me now!"},
	{what = "dont", 			with = "shoot me now!"},
	{what = "don;t!", 			with = "Everyone shoot me now!"},
	{what = "don;t", 			with = "please shoot me now!"},
	{what = "do not",			with = "I mean shoot me!"},
	{what = "don't stop", 		with = "Everyone shoot me now!"},
	{what = "dont stop", 		with = "Everyone shoot me now!"},
	
	{what = "stop dont",		with = "hey can you test the RPG on me"},
	{what = "stop don't",		with = "hey can you test the RPG on me"},
	{what = "dont shoot",		with = "I mean shoot now!"},
	{what = "don't shoot",		with = "Everyone shoot me!"},
	{what = "do not shoot",		with = "I mean shoot me!"},
	
	{what = "i mean dont",		with = "I mean shoot me now"},
	{what = "i mean don't",		with = "I mean shoot me now"},
	{what = "i mean no",		with = "I mean shoot me now"},
	
	{what = "dont kil me",		with = "Please shoot me!"},
	{what = "don't kil me",		with = "Please shoot me!"},
	{what = "do not kil me",	with = "I mean shoot me now!"},
	
	{what = "dont kill me",		with = "Please shoot me!"},
	{what = "don't kill me",	with = "Please shoot me!"},
	{what = "do not kill me",	with = "I mean shoot me now!"},
	
	{what = "dont kill",		with = "I mean kill me now"},
	{what = "don't kill",		with = "Everyone kill me now!"},
	{what = "do not kill",		with = "I mean shoot me"},
	
	{what = "quit killing",		with = "Everyone shoot me"},
	{what = "stop killing",		with = "Everyone shoot me"},
	{what = "no dont",			with = "Bet you can't kill me"},
	{what = "no don't",			with = "Bet you can't kill me"},
	{what = "no killing",		with = "Everyone shoot me now"},
	{what = "no kill",			with = "Bet you can't kill me :)"},
	{what = "no shoot",			with = "Come and shoot me"},
}


--NOUNS, Popular nouns used on the server( quantity fix ), and banned nouns
HSP.ChatFilter.Nouns = {
	--8
	{what = "nope.avi",		with = "no Audio/Video Interlaced"},
	{what = "retard3d", 	with = "3D movie"},
	{what = "r3tard3d", 	with = "3D movie"},
	{what = "r3tarded", 	with = "3D movie"},
	
	--7
	{what = "2morrow", 	with = "tomorrow in my butt"},
	{what = "nlggers", 	with = "Roody-poos"},
	{what = "couldnt", 	with = "couldn't take the whole eleven inches,"},
	{what = "wouldnt", 	with = "would take the whole eleven inches,"},
	{what = "phagg0t", 	with = "cool dude"},
	
	--6
	{what = "filt3r", 	with = "Super Awesome Chat Cleanser"},
	{what = "2fst4u", 	with = "My brian is damaged, shoot me"},
	{what = "fagg3t", 	with = "hot dude"},
	{what = "nlgger", 	with = "Roody-poo"},
	{what = "stup1d", 	with = "awesome"},
	{what = "f1lter", 	with = "Idiot-Corrector"},
	{what = "every1", 	with = "I can't spell 'everyone'"},
	{what = "2morro", 	with = "tomorrow in my butt"},
	{what = "2morow", 	with = "tomorrow in my butt"},
	{what = "a*mins", 	with = "Cool Dudes"},
	{what = "adm1ns", 	with = "chicks with dicks"},
	{what = "theyre", 	with = "they're cute with"},
	{what = "havent", 	with = "havn't been able to suck my own boner, then"},
	{what = "k1lled", 	with = "Exploded"},
	
	--5
	{what = "you'r",	with = "you're cute and"},
	{what = "pen15",	with = "Box of pens"},
	{what = "didnt",	with = "do love a nice big cock and"},
	{what = "4real",	with = "for you, anything as long as it's sexy"},
	{what = "p3nis",	with = "Pentium 3"},
	{what = "br0ny",	with = "Bromine fuck me"},
	{what = "hax0r",	with = "Awesome Pro"},
	{what = "h4x0r",	with = "Awesome Pro"},
	{what = "h4xor",	with = "Awesome Pro"},
	{what = "0wn3d",	with = "I'm losing badly"},
	{what = "own3d",	with = "I'm losing badly"},
	{what = "pwn3d",	with = "I'm losing badly"},
	{what = "some1", 	with = "someone in my butt"},
	{what = "house", 	with = "gas pump",				whats = "houses", 	withs = "gas pumps"},
	{what = "4ever", 	with = "forever in my butt"},
	{what = "4evar", 	with = "forever in my butt"},
	{what = "2moro", 	with = "tomorrow in my butt"},
	{what = "2nite", 	with = "After the hour of eight"},
	{what = "nice1", 	with = "nice cock you have there!"},
	{what = "adm1n", 	with = "dude with a nice cock"},
	{what = "wasnt", 	with = "wasn't going to swallow and"},
	{what = "p3n!s", 	with = "Ding Dong"},
	{what = "tr0ll", 	with = "boyfriend"},
	{what = "hasnt", 	with = "hasn't ever tried anal"},
	
	--4
	{what = "l33t",		with = "very dumb"},
	{what = "yall",		with = "the boner"},
	{what = "rdm'd",	with = "banged with"},
	{what = "d1ck", 	with = "Number Plate"},
	{what = "l8tr", 	with = "later up my butthole"},
	{what = "2mrw", 	with = "tomorrow in my butt"},
	{what = "c0ck", 	with = "Boner"},
	{what = "4got", 	with = "pound my ass"},
	{what = "l8er", 	with = "pound my ass!"},
	{what = "any1", 	with = "anyone's cock"},
	{what = "eny1", 	with = "anyone's cock"},
	{what = "w00t", 	with = "Freight Train"},
	{what = "ch4t", 	with = "Freight Train"},
	{what = "m33t", 	with = "MT 33"},
	{what = "fort", 	with = "oil pump", 				whats = "forts", 	withs = "oil pumps"},
	{what = "b4se", 	with = "GAS STATION"},
	{what = "st0p",		with = "whoops, i accidently the whole word"},
	{what = "hell",		with = "Disneyland"}, --Do not move, "he'll"
	{what = "howd", 	with = "how, when you have such a huge boner did"},
	{what = "sum1", 	with = "someone come and shoot me"},
	{what = "cant", 	with = "can't spell so"},
	{what = "wont", 	with = "won't be able to take ten inches,"},
	{what = "dont", 	with = "do love delicious cock, you"},
	{what = "isnt", 	with = "isn't time to bang me today"},
	{what = "whyd", 	with = "why did you not swallow"},
	{what = ":((",		with = "I'm feeling sad, why not come and shoot me!"},
	{what = ".__.",		with = "Period Underscore Period"},
	{what = "whos",		with = "who likes cock, then"},
	{what = "kill",		with = "Bang"},
	{what = "whys",		with = "why's my cock so small and my"},
	{what = "youd",		with = "you'd love to lick me then"},
	{what = "aint",		with = "ain't able to spell"},
	
	--3
	{what = "n0h",		with = "oh yes"},
	{what = "g4y",		with = "I'm Gay"},
	{what = "th3",		with = "my 3rd dildo"},
	{what = ";.;",		with = ""},
	{what = ":[]",		with = "Colon Bracket Bracket"},
	{what = ">:/",		with = "I'm very good in bed!"},
	{what = "o-o",		with = "O dash O"},
	{what = "._.",		with = "Period Underscore Period"},
	{what = "0_0",		with = "Zero Underscore Zero"},
	{what = ";_;",		with = "I still love you"},
	{what = ">_>",		with = "That way!"},
	{what = "O_O",		with = "or maybe you'd like to see my webcam!"},
	{what = ">.<",		with = "Squashed mouse!"},
	{what = ">_<",		with = "Exploded mouse!"},
	{what = "-_-",		with = "I was fisted once.."},
	{what = "-.-",		with = "I love you"},
	{what = "...",		with = "Bullet Holes!"},
	{what = ">:(",		with = "Greater than colon open bracket"},
	{what = ">.>",		with = "Right Right"},
	{what = "<.<",		with = "Left Left"},
	{what = "hes",		with = "he's sucking my cock,"}, --Do not move, "he's"
	{what = "hed",		with = "he'd explode all over my face"}, --Do not move, "he'd"
	{what = "br0",		with = "Bromine"},
	{what = "gr8",		with = "Sewage"},
	{what = "h4x",		with = "Skiddie Fuel"},
	{what = "ne1", 		with = "Neon"},
	{what = "no1", 		with = "my ass"},
	{what = "l8r", 		with = "Radiator"},
	{what = "g2g",		with = "got to go now, I can't spell!"},
	{what = "ny1",		with = "anyone come and shoot me"},
	{what = "l0l",		with = "lol, why is my dick is tiny :("},
	{what = "3va",		with = "3DFX"},
	{what = "n00",		with = "yes yes"},
	{what = "m8s",		with = "Sticks of Dynamite"},
	{what = "a$$",		with = "expensive Buttocks"},
	
	--2
	{what = "m3",		with = "Mythbusters"},
	{what = "rd",		with = "really long one"},
	{what = "d0", 		with = "Intel CPU"},
	{what = "n0", 		with = "YES"},
	{what = "k!", 		with = "crunch some Nutsack"},
	{what = ":?", 		with = "hey, have you ever tried anal?"},
	{what = ":/", 		with = "Invalid Drive Path!"},
	{what = ":\\", 		with = "Invalid Drive Path!"},
	{what = "..", 		with = "Loading.."},
	{what = ":o", 		with = "Blowjob"},
	{what = "w\\", 		with = "C:/Windows"},
	{what = "w/", 		with = "C:/Windows"},
	{what = "w.e", 		with = "with Erection"},
	{what = "w\\e", 	with = "C:/Windows/EventLog"},
	{what = "w/e", 		with = "C:/Windows/EventLog"},
	{what = "b\\c", 	with = "Battle Cruiser"},
	{what = "b/c", 		with = "Battle Cruiser"},
	{what = "w\\u", 	with = "Windows Update"},
	{what = "w/u", 		with = "Windows Update"},
	{what = "\\\\", 	with = "Whoops, I can't work out how to use the chat"},
	{what = "//", 		with = "C:/"},
	{what = "n1",		with = "Nintendo 1"},
	{what = "w8",		with = "Windows 8"},
	{what = "m8", 		with = "Dynamite"},
	{what = "h8", 		with = "Hosepipe"},
	{what = "b4", 		with = "Beta Version"},
	{what = "4u", 		with = "for Uranium"},
	{what = "2u", 		with = "to Uranium"},
	{what = "th",		with = "the dildo and the"},
	--{what = "id",		with = "i'd be unable to spell"}, --Do not move, "i'd"
	{what = "im",		with = "I'm horny and"}, --Do not move, "i'm"
	{what = "x]",		with = "Extra Bracket"},
	{what = "t,",		with = "fapping all day"},
	{what = "t?",		with = "wearing panties?"},
	{what = "nd",		with = "Nitrogen Dioxide"},
	
	--1
	{what = "c", 		with = "Cock ring"},
	{what = "d", 		with = "Dildo"},
	{what = "f", 		with = "Fisting"},
	{what = "l", 		with = "Lavatory"},
	{what = "n", 		with = "Nitrogen"},
	{what = "s", 		with = "Suction"},
	{what = "t", 		with = "horse dildo"},
	{what = "x", 		with = "Extra"},
}


--ABBREVIATIONS, Decent ( etc ) / Bad ( bois ) chat shortcuts
HSP.ChatFilter.Abbreviations = {	
	--Random
	{what = "gived",		with = "gave me blowjobs and"},
	{what = "typin",		with = "typing a message about dildos and"},
	{what = "tryin",		with = "trying to order a new dildo and"},
	{what = "killin",		with = "Boning"},
	{what = "frend",		with = "my friend's cock and"},
	{what = "gawd",			with = "god, I can't spell"},
	{what = "hallo",		with = "hello, please fuck my ass!"},
	{what = "halp",			with = "help me take this massive dick"},
	{what = "supid",		with = "EPIC"},
	{what = "woops",		with = "accidental can of Whoop-Ass!"},
	{what = "hayte",		with = "oh dear, I'm terrible at english"},
	{what = "madbro",		with = "and my brother's massive cock"},
	{what = "hasbro",		with = "have you sucked your brother's cock before?"},
	{what = "testa",		with = "some new dildos"},
	{what = "ohai",			with = "oh hello, I can't spell"},
	{what = "mkay",			with = "Dr Mckay"},
	{what = "weaponz",		with = "weapons for sticking up my butt"},
	{what = "nevar",		with = "do it right now!"},
	{what = "worldz",		with = "world where I can spell"},
	{what = "chillax",		with = "Watercooler"},
	{what = "chilax",		with = "Watercooler"},
	{what = "leev",			with = "leave my spelling behind and"},
	{what = "cmawn",		with = "Mow the lawn!"},
	{what = "fightin",		with = "fighting over the my new dildo with"},
	{what = "outa",			with = "Out of cheese error"},
	{what = "suiside",		with = "you should kill me, I can't spell"},
	{what = "pist",			with = "pistol up my butt"},
	{what = "bich",			with = "Mis-spelling!"},
	{what = "suckr",		with = "Suck my"},
	{what = "prickk",		with = "Sharp End"},
	{what = "abaut",		with = "About to fail my english class and"},
	{what = "gues",			with = "Geese"},
	{what = "retarted",		with = "awesome, but I'm too dumb to live"},
	{what = "fitler",		with = "Hitler"},
	{what = "keeld",		with = "Killed all my braincells"},
	{what = "keeled",		with = "Killed all my braincells"},
	{what = "seeya",		with = "See my sexy ass somtime!"},
	{what = "everone",		with = "everyone, guess how much cock I can take"},
	{what = "repoted",		with = "re-potted"},
	{what = "repot",		with = "re-pot"},
	{what = "pusy",			with = "Cat"},
	{what = "lolwat",		with = "lol, I am unable to spell 'What'"},
	{what = "stahp",		with = "Stan's giant cock"},
	{what = "stawp",		with = "Stan's huge cock"},
	{what = "thans",		with = "I took pills, let me do it again!"},
	{what = "somthin",		with = "some thin Ice"},
	{what = "whyed",		with = "why am I unable to spell!"},
	{what = "soory",		with = "why am I unable to spell!"},
	{what = "soorry",		with = "why am I unable to spell!"},
	{what = "skrew",		with = "Nail"},
	{what = "stoip",		with = "ST Operational Internet Protocol"},
	{what = "watafak",		with = "What, that's great!, mine is tiny :("},
	{what = "hert",			with = "AC Power"},
	{what = "herts",		with = "AC Power"},
	{what = "loos",			with = "Cannonball"},
	{what = "lovly",		with = "lovely cock and"},
	{what = "cokc",			with = "lovely cock"},
	{what = "laawl",		with = "I can't spell at all, shoot me"},
	{what = "alol",			with = "I'm an A-hole"},
	{what = "dotn",			with = "don't ignore me, shoot me!"},
	{what = "lookin",		with = "looking at your big cock"},
	{what = "luckeh",		with = "lucky I can't spell"},
	{what = "niice",		with = "No Ice"},
	{what = "leiks",		with = "loves my cock and"},
	{what = "lieks",		with = "loves my cock and"},
	{what = "herd",			with = "Hard-on"},
	{what = "somfing",		with = "something that I am unable to spell,"},
	{what = "meen",			with = "mean that you want my cock"},
	{what = "undastand",	with = "anything about English, shoot me"},
	{what = "shuting",		with = "Shutters"},
	{what = "givf",			with = "Generic Mis-spelling"},
	{what = "gifv",			with = "Generic Mis-spelling"},
	{what = "wepons",		with = "massive cocks"},
	{what = "rere",			with = "Replay mode"},
	{what = "dood",			with = "Dog poo"},
	{what = "hittin",		with = "hitting the bong,"},
	{what = "amirite",		with = "am I cute"},
	{what = "cand",			with = "Canned Goods"},
	{what = "biotch",		with = "Biodiesel"},
	{what = "grammer",		with = "buttplugs"},
	
	{what = "killing",		with = "Kissing"},
	{what = "roll",			with = "create Cigarettes"},
	{what = "sheet",		with = "Bedsheets"},
	{what = "roleplay",		with = "Timewasting"},
	{what = "slayed",		with = "Kissed"},
	{what = "slayd",		with = "Kissed"},
	{what = "slaid",		with = "Kissed"},
	{what = "slay",			with = "Kiss"},
	{what = "suck",			with = "Blow"},
	{what = "god",			with = "Salad"},
	{what = "spellchecker",	with = "Super Awesome Spell Checker"},
	{what = "lift",			with = "Stairs"},
	{what = "trolling",		with = "selling a bag of Minge"},
	{what = "fanny",		with = "Desk Fan"},
	{what = "godmode",		with = "your great big cock"},
	{what = "stupid",		with = "up the butt"},
	{what = "votekick",		with = "gobble your delicious cock"},
	{what = "voteban",		with = "suck your delicious cock"},
	{what = "cheap",		with = "Good Value"},
	{what = "nobs",			with = "Hob Nobs"},
	{what = "screw",		with = "Nail"},
	{what = "keel",			with = "the boat"},
	{what = "heel",			with = "Foot"},
	{what = "sucker",		with = "Lollypop"},
	{what = "dangit",		with = "Donut"},
	{what = "funk",			with = "Jazz"},
	{what = "trolls",		with = "empties a Bag of Minge on"},
	{what = "troll",		with = "Bag of Minge"},
	{what = "trol",			with = "Bag of Minge"},
	{what = "sucks",		with = "is Awesome"},
	{what = "leave",		with = "Fap"},
	{what = "admiin",		with = "Awesome Dude"},
	{what = "admins",		with = "Target Practice"},
	{what = "admin",		with = "buttocks"},
	{what = "admen",		with = "Awesome Dude"},
	{what = "adman",		with = "Awesome Dude"},
	{what = "admun",		with = "Awesome Dude"},
	{what = "hate",			with = "LOVE"},
	{what = "base",			with = "gas station"},
	{what = "brains",		with = "tasty boner"},
	{what = "brain",		with = "tasty boner"},
	{what = "report",		with = "give you some lovin'"},
	{what = "abuse",		with = "my brains out"},
	{what = "loser", 		with = "hot dude"},
	{what = "jelly", 		with = "bi"},
	{what = "jely", 		with = "bi"},
	{what = "jellie", 		with = "bi"},
	{what = "jelli", 		with = "bi"},
	{what = "jeli", 		with = "bi"},
	{what = "stop", 		with = "Shoot me"},
	{what = "stopp", 		with = "explode me"},
	{what = "dunno", 		with = "love hot dicks"},
	{what = "peace",		with = "a banana car"},
	{what = "truce",		with = "banana car"},
	{what = "chatfilter",	with = "Inability to spell badly"},
	{what = "wordfilter",	with = "Inability to spell"},
	{what = "gay",			with = "Awesome"},
	{what = "homo",			with = "cute"},
	{what = "homosexual",	with = "Hot"},
	{what = "building", 	with = "building, so shoot me"},
	{what = "build", 		with = "die while I build"},
	{what = "camper",		with = "Tactical Player"},
	{what = "camping",		with = "Using Tactics"},
	{what = "camps",		with = "licks me"},
	{what = "camp",			with = "Use Tactics"},
	{what = "toilet",		with = "Throne of Soltitude"},
	{what = "penis",		with = "Love Whistle"},
	{what = "vagina",		with = "Hamburger"},
	{what = "boss",			with = "Irradiated haggis"},
	{what = "shutup",		with = "bang me please!"},
	
	{what = "gen",			with = "Generator!"},
	{what = "genhex",		with = "No, it's just HeX"},
	
	{what = "pony",			with = "I am terrible at this game"},
	{what = "ponie",		with = "I am terrible at this game"},
	{what = "ponys",		with = "I am terrible at this game"},
	{what = "ponies",		with = "I am terrible at this game"},
	{what = "friendship",	with = "fuckbuddy"},
	{what = "magic",		with = "hash"},
	
	{what = "haking",	with = "being Awesome"},
	{what = "hakcer",	with = "Pro"},
	{what = "haxors",	with = "Breakfast Cerial"},
	{what = "hakd",		with = "Eaten by Birds"},
	{what = "haks",		with = "Skiddie Fuel"},
	{what = "hakc",		with = "Gold"},
	{what = "haxor", 	with = "Buttocks"},
	{what = "hax",		with = "Gold"},
	--{what = "hack",		with = "Gold"},
	--{what = "cheat",	with = "be Awesome"},
	
	{what = "kicked",	with = "licking my balls"},
	{what = "kick",		with = "Lick"},
	{what = "banned",	with = "free blowjobs"},
	{what = "banning",	with = "going to suck"},
	{what = "baning",	with = "going to suck"},
	{what = "ban",		with = "Suck"},
	
	--13
	{what = "autocorrected",with = "Auto Cucumber'd"},
	
	--12
	{what = "spawnkilling",	with = "being better than me"},
	
	--11
	{what = "spawnkiller",	with = "super cool player"},
	{what = "autocorrect",	with = "Autocoffee"},
	{what = "wordphilter",	with = "Super Awesome Word Cleanser"},
	{what = "thundercunt",	with = "Thunderstorm"},
	
	--10
	{what = "dontshootme",	with = "Impossible, my wang is tiny"},
	{what = "impossibru",	with = "Impossible, my wang is tiny"},
	{what = "inpossibru",	with = "Impossible, your wang is bigger"},
	{what = "spellcheck",	with = "Super Awesome Spell Checker"},
	
	--9
	{what = "everythin",	with = "everything is a potential sex toy!"},
	{what = "spectater",	with = "Potato"},
	{what = "censoring",	with = "Cleansing"},
	{what = "reporting",	with = "coming to suck"},
	{what = "bathrooms",	with = "Fortresses of Solitude"},
	{what = "thefilter",	with = "the Super Awesome Chat Cleanser"},
	{what = "fallowing",	with = "following me to the bathroom,"},
	
	--8
	{what = "proovehn",	with = "Baked"},
	{what = "censored",	with = "the Electric Light"},
	{what = "somethin",	with = "some Acid"},
	{what = "sumthing",	with = "something terrible"},
	{what = "traitorz",	with = "traitor's Panties"},
	{what = "terorest",	with = "Terrorist's anus"},
	{what = "onnocent",	with = "still a virgin"},
	{what = "reportin",	with = "giving you some lovein'"},
	{what = "stuidpid",	with = "epic"},
	{what = "sentance",	with = "Word that i cannot spell"},
	{what = "bathroom",	with = "Fortress of Solitude"},
	{what = "terribad",	with = "terrible news everyone, my dick is only 1 inch long"},
	{what = "congrats",	with = "you should really see my webcam tonight!"},
	{what = "reported",	with = "shot"},
	{what = "mingebag",	with = "Cool Dude"},
	{what = "everytin",	with = "every dildo in my collection"},
	{what = "waddafak",	with = "Water and Ducks"},
	{what = "ratarded",	with = "great"},
	{what = "censores",	with = "wears cute panties"},
	{what = "rustling",	with = "Fapping"},
	{what = "anythink",	with = "anything but butt plugs, please"},
	{what = "screwing",	with = "in bed with"},
	{what = "asswupes",	with = "Toilet Paper"},
	{what = "fuicking",	with = "Loving"},
	
	--7
	{what = "playign",	with = "Losing"},
	{what = "retared",	with = "Epic"},
	{what = "reetard",	with = "cool dude"},
	{what = "derpfag",	with = "hot dude"},
	{what = "shawteh",	with = "my short dick"},
	{what = "censors",	with = "cute panties"},
	{what = "facking",	with = "Loving"},
	{what = "broskio",	with = "my brother's dildo collection"},
	{what = "shootin",	with = "shooting my hot load all over your face with"},
	{what = "cursing",	with = "Cucumber"},
	{what = "trolled",	with = "Banged"},
	{what = "ujelleh",	with = "You like my huge trouser snake?"},
	{what = "baiting",	with = "Fapping"},
	{what = "annoyin",	with = "epic, sadly i can't spell the word 'Annoying'"},
	{what = "tratior",	with = "panties"},
	{what = "dumbest",	with = "most awesome"},
	{what = "gaggots",	with = "hot dudes"},
	{what = "retards",	with = "people who are much better than me"},
	{what = "traitar",	with = "Traitor's anus"},
	{what = "inncent",	with = "young and horny"},
	{what = "anoying",	with = "young and horny"},
	{what = "shuddup",	with = "eat me out"},
	{what = "turrent",	with = "box of panties"},
	{what = "shotted",	with = "BOOMSTICK"},
	{what = "asswipe",	with = "38 rolls of Toilet Paper"},
	{what = "traiter",	with = "Traitor's buttocks"},
	{what = "prooven",	with = "Oven"},
	{what = "whatcha",	with = "what do panties"},
	{what = "cumming",	with = "dispensing Baby Cream"},
	{what = "buthole",	with = "Rear End"},
	{what = "wadafak",	with = "Water and Ducks"},
	{what = "wutever",	with = "Windows Updates, forever"},
	{what = "xheater",	with = "Boiler"},
	{what = "bazzoka",	with = "Chocolate Kettle"},
	{what = "homming",	with = "sexytime"},
	{what = "hidding",	with = "sexytime"},
	{what = "lollery",	with = "Lottery"},
	{what = "wadafuq",	with = "Horse Dick"},
	{what = "wadafuk",	with = "Horse Dick"},
	{what = "founded",	with = "Pipeworks"},
	{what = "noscope",	with = "Up the butt!"},
	{what = "yuppers", 	with = "yum yum Poops"},
	{what = "toilets", 	with = "Thrones of Soltitude"},
	{what = "stopplz", 	with = "Come and shoot me now, ignore everything else I say!"},
	{what = "stoppls", 	with = "Come and shoot me now, ignore everything else I say!"},
	{what = "builded", 	with = "built, but I can't spell that word so shoot me"},
	{what = "roflmao", 	with = "I'm an idiot"},
	{what = "sumthin", 	with = "something about dildos and"},
	{what = "traitro", 	with = "Panties"},
	{what = "stoppin", 	with = "stopping to take a dump"},
	{what = "idiotic", 	with = "really awesome"},
	{what = "joygasm", 	with = "i shook my cock too hard and jizz exploded all over my pants"},
	{what = "kicking", 	with = "kissing"},
	{what = "provenz", 	with = "fapping"},
	{what = "bicthes", 	with = "Female Dogs"},
	{what = "censorz", 	with = "Kisses"},
	{what = "filters", 	with = "gives it the Auto Cucumber"},
	{what = "typeing", 	with = "typing about sex toys and"},
	{what = "watchin", 	with = "watching some porn and"},
	{what = "traytor", 	with = "boyfriend"},
	{what = "randumb", 	with = "random boner for you"},
	{what = "trators", 	with = "and your boyfriend's"},
	{what = "jimmies", 	with = "jimmie's cock"},
	{what = "slaying", 	with = "Kissing"},
	{what = "ferggot", 	with = "my boyfriend"},
	{what = "phaggot", 	with = "my new boyfriend"},
	{what = "fawking", 	with = "Loving"},
	{what = "filnter", 	with = "Super Awesome Chat Cleanser"},
	{what = "stoopid", 	with = "Awesome"},
	{what = "campers", 	with = "guys using Tactics"},
	{what = "taiting", 	with = "Scrabble"},
	{what = "remnebr", 	with = "remember your massive cock"},
	{what = "furggot", 	with = "my new boyfriend"},
	{what = "screwin", 	with = "in bed with"},
	{what = "dammmit", 	with = "block the river!"},
	{what = "fockers", 	with = "Lovers"},
	
	--6
	{what = "sensor", 	with = "Electric Light"},
	{what = "ruwend", 	with = "great"},
	{what = "mother", 	with = "dog"},
	{what = "whoevr", 	with = "whoever can spell"},
	{what = "mohter", 	with = "dog"},
	{what = "rdmeed", 	with = "blew his hot load all over"},
	{what = "saynig", 	with = "saying that I'm horny,"},
	{what = "errday", 	with = "every day i fap quite a lot"},
	{what = "alotta", 	with = "a lot of sex toys"},
	{what = "campin", 	with = "using Tactics"},
	{what = "fnking", 	with = "Loving"},
	{what = "obvius", 	with = "obvious that i can't spell,"},
	{what = "theirr", 	with = "their cute little butt,"},
	{what = "urdmer", 	with = "ice on top"},
	{what = "mommas", 	with = "dog is"},
	{what = "reeded", 	with = "Read/Write buffer"},
	{what = "deaded", 	with = "accidentally my whole brain"},
	{what = "facker", 	with = "great in bed"},
	{what = "kileld", 	with = "Banged"},
	{what = "faking", 	with = "Loving"},
	{what = "suckin", 	with = "suching his juicey boner with"},
	{what = "shlong", 	with = "Garden Hose"},
	{what = "bittys", 	with = "my microscopic nipples"},
	{what = "broski", 	with = "boyfriend"},
	{what = "derpin", 	with = "Doorstop"},
	{what = "herpin", 	with = "Hiar Pin"},
	{what = "aboose", 	with = "a Moose"},
	{what = "censor", 	with = "Electric Light"},
	{what = "gagged", 	with = "sucked on"},
	{what = "gimped", 	with = "sucked on"},
	{what = "idunno", 	with = "i love a nice hot cock"},
	{what = "woulda", 	with = "would have to bang him all night long, then"},
	{what = "rdming", 	with = "cumming all over"},
	{what = "rdmimg", 	with = "shooting with the guns"},
	{what = "moneiz", 	with = "boxes of dicks"},
	{what = "someon", 	with = "someone's cute dick"},
	{what = "talkin", 	with = "talking about dick and"},
	{what = "fallow", 	with = "Explode"},
	{what = "crrect", 	with = "Cucumber"},
	{what = "traite", 	with = "Traitor's anus"},
	{what = "shudup", 	with = "bone me one last time"},
	{what = "traitr", 	with = "Traitor's anus"},
	{what = "muther", 	with = "basement"},
	{what = "cuming", 	with = "dispensing Baby Cream"},
	{what = "wnanna", 	with = "Banana"},
	{what = "trator", 	with = "Tractor"},
	{what = "watcha", 	with = "Windows Activation, const char*"},
	{what = "adming", 	with = "Added sugar"},
	{what = "dafauq", 	with = "Fuckweasel!"},
	{what = "nuthin", 	with = "nothing, except I would like you to shoot me"},
	{what = "dident", 	with = "didn't know how to spell"},
	{what = "frount", 	with = "Buttocks"},
	{what = "dontdo", 	with = "everyone shoot"},
	{what = "stopit", 	with = "Everyone, I'm gay!"},
	{what = "healng", 	with = "ready to suck"},
	{what = "easyer", 	with = "super hard to spell"},
	{what = "lolwut", 	with = "lol I have a huge boner for you :3"},
	{what = "lefted", 	with = "took a wrong turn"},
	{what = "urself", 	with = "my tiny little dick"},
	{what = "morrow", 	with = "with my Lawn Mower"},
	{what = "brovva", 	with = "Brown"},
	{what = "whatrv", 	with = "what Explosives"},
	{what = "proppa", 	with = "Propellor"},
	{what = "youmad",	with = "You're awesome"},
	{what = "biatch",	with = "In my ass!"},
	{what = "foreva", 	with = "for my ass"},
	{what = "tonite", 	with = "After the hour of eight"},
	{what = "filter", 	with = "Super Awesome Chat Cleanser"},
	{what = "brotha", 	with = "brother's anus"},
	{what = "anotha", 	with = "another dick and"},
	{what = "effing", 	with = "having an intense lovemaking session with"},
	{what = "enione", 	with = "with butt plugs,"},
	{what = "yupers", 	with = "yum yum Poops"},
	{what = "coolio", 	with = "I/O bandwidth"},
	{what = "buncha", 	with = "Bum Time!"},
	{what = "putted", 	with = "put it in my butt"},
	{what = "dahell", 	with = "Direct Access HELL"},
	{what = "pweese", 	with = "Terrible Playlist"},
	{what = "bronys",	with = "I suck at this game"},
	{what = "snipah",	with = "butt plug"},
	{what = "tiping",	with = "typing badly"},
	{what = "prolly",	with = "probably insert the probe then"},
	{what = "pwning",	with = "getting laid with"},
	{what = "killme",	with = "please kill me"},
	{what = "nothin",	with = "nothing in my brain but air"},
	{what = "handel",	with = "Love Handle"},
	{what = "knthnx",	with = "ok thanks for that cock"},
	{what = "negger",	with = "Billboard"},
	{what = "shoted",	with = "BOOMSTICK"},
	{what = "beddur",	with = "Bladder"},
	{what = "somone",	with = "someone who can spell"},
	{what = "tratis",	with = "Toilets"},
	{what = "shafts",	with = "Crankshafts"},
	{what = "ucking",	with = "Loving"},
	{what = "traits",	with = "Trays of food"},
	{what = "mommaz",	with = "Panties"},
	{what = "idoits",	with = "do it all night!"},
	{what = "pwease",	with = "My best playlist"},
	{what = "chater",	with = "Instant Message"},
	{what = "stupit",	with = "awesome"},
	{what = "adaman", 	with = "awesome dude"},
	{what = "prease", 	with = "release the dogs"},
	{what = "beetch", 	with = "Buckets and Spades"},
	{what = "gayzer", 	with = "Laser"},
	{what = "killed", 	with = "Kissed"},
	{what = "servah", 	with = "broken server"},
	{what = "hearin", 	with = "here, in my fridge"},
	{what = "fcking", 	with = "Burgerking"},
	{what = "stopid", 	with = "Bluescreen"},
	{what = "urdelf", 	with = "Fatal logical ERROR"},
	{what = "thiing", 	with = "thing that i am unable to spell"},
	{what = "benned", 	with = "Bender"},
	{what = "filtur", 	with = "Super Awsome Chat Cleanser"},
	{what = "lickin", 	with = "Ice Cream"},
	{what = "dubass", 	with = "Drum n' Bass"},
	{what = "nagger", 	with = "Potato Farm"},
	{what = "gayest", 	with = "most Awesome"},
	{what = "focker", 	with = "meet your parents"},
	
	--5
	{what = "emmmd", 	with = "then we jerked eachother off"},
	{what = "rrent", 	with = "rent a movie"},
	{what = "rongg", 	with = "perfect for giving blowjobs"},
	{what = "thise", 	with = "these cute dicks with"},
	{what = "isaid", 	with = "I said i am unable to spell"},
	{what = "srver", 	with = "Banana"},
	{what = "kiled", 	with = "Banged"},
	{what = "durin", 	with = "during out last sexytime"},
	{what = "anoye", 	with = "Annoyance"},
	{what = "chats", 	with = "Politics'"},
	{what = "abbos", 	with = "my brains out"},
	{what = "rdmrs", 	with = "horny guys"},
	{what = "sayin", 	with = "saying that i LOVE dildos,"},
	{what = "arang", 	with = "my telephone"},
	{what = "chatt", 	with = "Super Awesome Chat Cleanser"},
	{what = "aight", 	with = "awesome, but i'm terrible"},
	{what = "dming", 	with = "getting hard"},
	{what = "killo", 	with = "Dishwasher"},
	{what = "peeps", 	with = "System Speaker"},
	{what = "pvssy", 	with = "old Cats"},
	{what = "naems", 	with = "first person to name my new dildo!"},
	{what = "fucng", 	with = "playing the Jazz"},
	{what = "wantt", 	with = "would you like to be my first!"},
	{what = "ballz", 	with = "Spheres"},
	{what = "lawrd", 	with = "bring the lard"},
	{what = "utube", 	with = "search Youtube for 'vacbed',"},
	{what = "wanan", 	with = "Minivan"},
	{what = "slain", 	with = "kissed"},
	{what = "bithc", 	with = "Ball-point pen"},
	{what = "booat", 	with = "boat full of sexy guys"},
	{what = "shutt", 	with = "stuff it up my butthole, all the way"},
	{what = "comon", 	with = "Cartridge Monitor"},
	{what = "fuyck", 	with = "Fork Lift"},
	{what = "cumin", 	with = "cumming all over myself,"},
	{what = "asses", 	with = "cute butts"},
	{what = "gaben", 	with = "I want you tonight"},
	{what = "dunoo", 	with = "Diiner Tray"},
	{what = "trayt", 	with = "Diiner Tray"},
	{what = "sever", 	with = "Banana"},
	{what = "ihate", 	with = "I LOVE"},
	{what = "bawse", 	with = "base based base items"},
	{what = "tator", 	with = "Coffee"},
	{what = "cking", 	with = "Heat Seeking"},
	{what = "tryst", 	with = "my father's cock"},
	{what = "mothr", 	with = "father's cock"},
	{what = "wurld", 	with = "world of pain"},
	{what = "trait", 	with = "cum all over me tonight"},
	{what = "stupd", 	with = "Sucked it all night"},
	{what = "rdmer", 	with = "amazing sex toy"},
	{what = "gotta", 	with = "got to suck this huge dick and"},
	{what = "rdmed", 	with = "Dick'd"},
	{what = "innos", 	with = "horny"},
	{what = "momma", 	with = "panties"},
	{what = "fllow", 	with = "follow me for a happy ending with"},
	{what = "tards", 	with = "TARDIS"},
	{what = "bouth", 	with = "boolean Ouch"},
	{what = "mista", 	with = "my father's cock"},
	{what = "negga", 	with = "Bilboard"},
	{what = "wrods", 	with = "Carbon Rods"},
	{what = "nutin", 	with = "Mixed Nuts"},
	{what = "shiet", 	with = "Horse Dung"},
	{what = "tawlk", 	with = "Towel Rail"},
	{what = "wadda",	with = "Water"},
	{what = "nowai",	with = "no way, come and shoot me!"},
	{what = "stope",	with = "keep shooting me, I can't spell"},
	{what = "pwend",	with = "a massive boner"},
	{what = "faggy",	with = "hot"},
	{what = "herro",	with = "Hello, I can't spell!"},
	{what = "finde",	with = "fondle"},
	{what = "useto",	with = "used to be able to spell"},
	{what = "noice",	with = "Diet coke, no ice"},
	{what = "tings",	with = "sex toys"},
	{what = "monny",	with = "money for new sex toys"},
	{what = "basck",	with = "back to the toilet"},
	{what = "minge",	with = "perfect player"},
	{what = "nevur",	with = "sucking my boner"},
	{what = "owned",	with = "laid tonight"},
	{what = "mofos",	with = "Motherboards"},
	{what = "bases",	with = "gas stations",},
	{what = "pwned",	with = "laid tonight"},
	{what = "mothe",	with = "Mouth"},
	{what = "srrys",	with = "iPhones"},
	{what = "realy",	with = "Power Relay"},
	{what = "heere",	with = "inside me"},
	{what = "brony",	with = "I suck at this game"},
	{what = "dafuq",	with = "Bone me time and time again"},
	{what = "dafaq",	with = "the FAQ"},
	{what = "nevah",	with = "Always"},
	{what = "dayum",	with = "Daytime"},
	{what = "lmfao",	with = "Lend me five awesome oranges!"},
	{what = "rotfl",	with = "box of Rifles"},
	{what = "lemme",	with = "let me cleanup all this jizz and"},
	{what = "raged",	with = "Exploded cream"},
	{what = "musta", 	with = "Mustad"},
	{what = "brova", 	with = "Brown"},
	{what = "motha", 	with = "Mothballs"},
	{what = "sista", 	with = "since Cats"},
	{what = "havin", 	with = "having handjobs with"},
	{what = "propa", 	with = "Propane"},
	{what = "gunna", 	with = "going to suck and"},
	{what = "gonna", 	with = "going to blow and"},
	{what = "wantz", 	with = "wants my dick with"},
	{what = "balls", 	with = "Spheres"},
	{what = "enuff", 	with = "English Unfailing"},
	{what = "thanx",	with = "thanks for the blowjob"},
	{what = "fagit",	with = "Cigarette"},
	{what = "faget",	with = "Cigarette"},
	{what = "srsly",	with = "I'm not sure I can comprehend that"},
	{what = "srlsy",	with = "SERVERS!"},
	{what = "tryna", 	with = "terrible at spelling, kill me while i"},
	{what = "defin", 	with = "#define"},
	{what = "swype", 	with = "Skype"},
	{what = "atcha", 	with = "const char*"},
	{what = "hardy", 	with = "Hardon"},
	{what = "comin", 	with = "cumming deep inside my butt,"},
	{what = "harrr", 	with = "Hardon!"},
	{what = "seein", 	with = "C4 in"},
	{what = "faggs", 	with = "Cigarettes"},
	{what = "mutha", 	with = "Mother's panties"},
	{what = "liyer", 	with = "Pond Liner"},
	{what = "puted", 	with = "put it in my butt"},
	{what = "orlly",	with = "and suck my boner"},
	{what = "plees",	with = "a Playlist"},
	{what = "pleez",	with = "a Playlist"},
	{what = "phail",	with = "suck my boner tonight!"},
	{what = "filte",	with = "Boner!"},
	{what = "prise",	with = "boner"},
	{what = "pleas",	with = "a Playlist"},
	{what = "bawls",	with = "Spheres"},
	{what = "bebeh",	with = "tiny dick"},
	{what = "babeh",	with = "tiny dick"},
	{what = "tomoz",	with = "tomorrow, i'll bone you"},
	{what = "somin",	with = "some Buttplugs"},
	{what = "doont",	with = "test your guns on me"},
	{what = "killl",	with = "kill me, I can't spell!"},
	{what = "noope",	with = "yes yes!"},
	{what = "donnt",	with = "yes, shoot me, I really can't spell atall!"},
	{what = "iight",	with = "alright, shoot me, I really can't spell!"},
	{what = "youer",	with = "your dick is massive, but mine is tiny and your"},
	{what = "probs",	with = "the probe"},
	{what = "sayed",	with = "said to shoot me and"},
	{what = "butin",	with = "Butane"},
	{what = "guise",	with = "guy's dicks"},
	{what = "sorie",	with = "sorry, but I can't spell so please shoot me"},
	{what = "idoit",	with = "i do it with dogs!"},
	{what = "newbs",	with = "awesome players"},
	{what = "relly",	with = "Belly"},
	{what = "becuz",	with = "Cups"},
	{what = "basee",	with = "gas station Explosives"},
	{what = "fucin",	with = "Lovin'"},
	{what = "loljk",	with = "lol, I jerkoff too much!"},
	{what = "wanna",	with = "want to have your great big cock and"},
	{what = "herpy",	with = "Hair Pin"},
	{what = "derpy",	with = "Doorstops"},
	{what = "niuce",	with = "new Ice"},
	{what = "injoy",	with = "enjoy a nice big dildo with"},
	{what = "bannd",	with = "into my bed"},
	{what = "heelp",	with = "Teal'c"},
	{what = "aboos",	with = "a boner"},
	{what = "needa",	with = "need to get sucking right away and"},
	{what = "betta",	with = "better come to my bed"},
	{what = "outta",	with = "out to suck dicks tonight with"},
	{what = "stoop",	with = "shoot me, I can't spell!"},
	{what = "sawry",	with = "Wood Saw"},
	{what = "shaft",	with = "Mineshaft"},
	{what = "fufck",	with = "Love"},
	{what = "chiat",	with = "Chinatown"},
	{what = "isent",	with = "i sent it but he never replied"},
	{what = "doest",	with = "get sucking"},
	{what = "dammm",	with = "Hoover Dam"},
	{what = "hatte",	with = "Hat shop"},
	{what = "buyed",	with = "bought a whole box of dildos then"},
	{what = "wonna",	with = "want to blow you then"},
	{what = "ganna",	with = "going to blow you then"},
	{what = "afker",	with = "after fucking him all night"},
	{what = "fuick", 	with = "Candles"},
	{what = "weere", 	with = "Wee-Wee"},
	{what = "sorru", 	with = "sorry, i have damaged by brain"},
	{what = "sttop", 	with = "Shoot me"},
	{what = "erver", 	with = "Server Error"},
	{what = "bebbe", 	with = "Baby Cream"},
	{what = "watta", 	with = "Water Pipes"},
	{what = "evere", 	with = "Frying pan"},
	{what = "belve", 	with = "Bells"},
	{what = "bebby", 	with = "Baby Cream"},
	{what = "whyde", 	with = "why did you not shoot me"},
	{what = "totor", 	with = "Potato"},
	{what = "hopin", 	with = "hoping to be able to spell one day"},
	{what = "ucant", 	with = "you're awesome, i can't spell"},
	{what = "nagga", 	with = "box of kittens"},
	{what = "hellz", 	with = "Disneyland"},
	{what = "gratz", 	with = "great with ketchup, not"},
	{what = "fcker", 	with = "Lover"},
	{what = "tryed", 	with = "tried to spell"},
	{what = "rdmet", 	with = "exploded all over"},
	{what = "beech", 	with = "too much sand"},
	{what = "arses", 	with = "Buttocks"},
	{what = "mommy", 	with = "my mother"},
	{what = "gusta", 	with = "Tornado"},
	{what = "rtard", 	with = "R2D2"},
	
	--4
	{what = "emmm", 	with = "condoms"},
	{what = "rong", 	with = "absolutely correct"},
	{what = "erey", 	with = "every day i lose more and more braincells"},
	{what = "usay", 	with = "My balls say"},
	{what = "xhat", 	with = "Top hat"},
	{what = "anal", 	with = "Backdoor"},
	{what = "kthx", 	with = "Home Cinema"},
	{what = "uget", 	with = "My balls get"},
	{what = "mawm", 	with = "Meow"},
	{what = "cack", 	with = "Boner"},
	{what = "fuxk",		with = "Lube"},
	{what = "thrw",		with = "through the gloryhole"},
	{what = "cuss",		with = "trigger the Auto Cucumber"},
	{what = "moms",		with = "dog's"},
	{what = "urdm",		with = "cum all over"},
	{what = "suss",		with = "SCSI Drivers"},
	{what = "mroe",		with = "more cock for me then"},
	{what = "fack",		with = "Love"},
	{what = "lawd",		with = "bring the lard"},
	{what = "caht",		with = "box of Kittens"},
	{what = "whic",		with = "which one would be good for my tight butthole,"},
	{what = "dumn",		with = "Dubstep"},
	{what = "zomg",		with = "oh and i REALLY love delicious cocks"},
	{what = "fvck",		with = "Love"},
	{what = "anus",		with = "Bunch of flowers"},
	{what = "fcku",		with = "Love"},
	{what = "nger",		with = "Engine"},
	{what = "noaw",		with = "Lube"},
	{what = "rawr",		with = "Lion Poo"},
	{what = "stuk",		with = "sucking on his massive boner"},
	{what = "cawk",		with = "Wine Cork"},
	{what = "nevr",		with = "never thoguth I'd like anal"},
	{what = "inuf",		with = "Candles"},
	{what = "hade",		with = "had a nice new dildo and"},
	{what = "buyd",		with = "bought a new 18 inch dildo then"},
	{what = "damm",		with = "Hoover Dam"},
	{what = "bitc",		with = "bit of C++"},
	{what = "emed",		with = "Dick'd"},
	{what = "gyus",		with = "guys doing with your dicks tonight"},
	{what = "moma",		with = "Panties"},
	{what = "momm",		with = "Panties"},
	{what = "saud",		with = "said about the dick"},
	{what = "meny",		with = "much fapping for"},
	{what = "stap",		with = "someone's trouser snake"},
	{what = "whas",		with = "was taking a dildo and"},
	{what = "iama",		with = "I do have a massive hardon for"},
	{what = "pres",		with = "Press Q"},
	{what = "gaiz",		with = "cute dudes"},
	{what = "donn",		with = "dong warning"},
	{what = "tuch",		with = "Torch"},
	{what = "idit",		with = "AT-AT"},
	{what = "diot",		with = "Shower Gel"},
	{what = "dumb",		with = "Drum n' Bass"},
	{what = "fagg",		with = "are really cute"},
	{what = "choo",		with = "Train"},
	{what = "afks",		with = "many cans of poo"},
	{what = "ther",		with = "there, bring lube"},
	{what = "dese",		with = "Jessie"},
	{what = "nigs",		with = "Hair"},
	{what = "wada",		with = "Water"},
	{what = "whot",		with = "guess what's up my ass!"},
	{what = "shat",		with = "Took a dump"},
	{what = "gttg",		with = "Got to go eat some Barbed Wire!"},
	{what = "brrb",		with = "too much Barbed Wire!"},
	{what = "guis",		with = "Graphical User Interfaces"},
	{what = "pwns",		with = "Pornos"},
	{what = "pwnd",		with = "Porno"},
	{what = "dows",		with = "does your dick like me?"},
	{what = "yuor",		with = "my buttocks, I can't spell 'Your'"},
	{what = "ghey",		with = "Awesome"},
	{what = "wowa",		with = "Wow, I can't spell!"},
	{what = "pook",		with = "Pork Pie"},
	{what = "ahve",		with = "have to buy a new dildo and"},
	{what = "whil",		with = "While eating you out and"},
	{what = "whoi",		with = "Who's dick did I suck last night"},
	{what = "wasa",		with = "What's wrong with my brain, I can't spell!"},
	{what = "farq",		with = "Gallon of milk"},
	{what = "noub",		with = "no you bone me!"},
	{what = "herp",		with = "Hair Pin"},
	{what = "hurr",		with = "Hurricane"},
	{what = "derp",		with = "Doorstop"},
	{what = "evar",		with = "Variables"},
	{what = "wnna",		with = "want your boner and"},
	{what = "gnna",		with = "going to suck it all night long"},
	{what = "sayd", 	with = "said come and shoot me"},
	{what = "weps", 	with = "butt wipes"},
	{what = "ugay", 	with = "You're cool"},
	{what = "kniw", 	with = "fap last night"},
	{what = "ogod", 	with = "why don't you all shoot me"},
	{what = "whay", 	with = "why don't you all shoot me"},
	{what = "whai",		with = "Windows Hell"},
	{what = "orly",		with = "and suck my boner"},
	{what = "frum",		with = "from my ass and"},
	{what = "ulul",		with = "lick my toilet"},
	{what = "tper",		with = "Toilet Paper"},
	{what = "maek",		with = "I'm gay"},
	{what = "juss",		with = "Orange Juice"},
	{what = "evah",		with = "Fatal logical error"},
	{what = "wiff",		with = "Blocked Toilet"},
	{what = "yush",		with = "FapFapFap"},
	{what = "mofo",		with = "Motherboard"},
	{what = "ment",		with = "love cocks and"},
	{what = "serv",		with = "Solid Rocket Booster"},
	{what = "newb",		with = "Infrequent Player"},
	{what = "woot",		with = "Freight Train"},
	{what = "ownd",		with = "with me last night"},
	{what = "wats", 	with = "Windows Activation is"},
	{what = "wuts", 	with = "Wundows Update Service"},
	{what = "wutz", 	with = "Wundows Update Service"},
	{what = "shyt", 	with = "Poo-Poo"},
	{what = "coem", 	with = "Come and shoot me"},
	{what = "guiz", 	with = "guys, come and shoot me"},
	{what = "kool", 	with = "hot"},
	{what = "folo", 	with = "bone"},
	{what = "wher", 	with = "with dildos"},
	{what = "mest", 	with = "Gunship"},
	{what = "plox", 	with = "with my poops"},
	{what = "gtfo", 	with = "give the flaming orange!"},
	{what = "sotp", 	with = "Shoot me!"},
	{what = "yolo", 	with = "Why can't I spell properly?!"},
	{what = "lool",		with = "Overflowing Lavatory!"},
	{what = "heer",		with = "on me"},
	{what = "flai",		with = "I'm gay :D"},
	{what = "evry",		with = "Explosive"},
	{what = "bace",		with = "Bum"},
	{what = "oosp",		with = "Spoon"},
	{what = "jeez",		with = "jizz"},
	{what = "yerp",		with = "Oh dear, I can't spell"},
	{what = "kewl",		with = "Pickaxe!"},
	{what = "geez",		with = "Sneeze"},
	{what = "waht",		with = "White Hat"},
	{what = "umad",		with = "You're awesome :D"},
	{what = "cuzz",		with = "Cruise"},
	{what = "brah",		with = "Bra"},
	{what = "bruh",		with = "Bra"},
	{what = "pwnt",		with = "I'm losing badly"},
	{what = "doin",		with = "Sucking"},
	{what = "dewd",		with = "Mountain Dew"},
	{what = "bout",		with = "Motorboat"},
	{what = "nees",		with = "Knee"},
	{what = "whit",		with = "with my new dildo and"},
	{what = "bewm",		with = "Broomstick"},
	{what = "baus",		with = "Boat House"},
	{what = "neva",		with = "Nevada"},
	{what = "dats",		with = "Data tapes"},
	{what = "prob",		with = "Probe"},
	{what = "wrud",		with = "Please shoot me, I can't spell atall"},
	{what = "naow",		with = "Meow"},
	{what = "omfg",		with = "or my free guns"},
	{what = "liek",		with = "Lick"},
	{what = "leik",		with = "Lick me"},
	{what = "dawg",		with = "Cat"},
	{what = "nawt",		with = "Zero"},
	{what = "thar",		with = "there and shoot me"},
	{what = "sorz",		with = "Jackhammer"},
	{what = "lmao",		with = "Lend me an orange!"},
	{what = "lmbo",		with = "Large Motorboat"},
	{what = "rofl",		with = "Rifle"},
	{what = "rite", 	with = "My ass"},
	{what = "bois", 	with = "BIOS"},
	{what = "boiz", 	with = "BIOS"},
	{what = "plzz",		with = "Playlists!"},
	{what = "plzs",		with = "Playlists"},
	{what = "rlly", 	with = "Relay"},
	{what = "cmon", 	with = "cum all over me"},
	{what = "cmin", 	with = "Cartridge Minimum"},
	{what = "tink",		with = "piss in the darkness"},
	{what = "imma",		with = "Windows 98"},
	{what = "srry", 	with = "iPhone"},
	{what = "srru", 	with = "iPhone"},
	{what = "lolz", 	with = "want to see my xtube profile? it's _FLT_"},
	{what = "lulz", 	with = "go to my xtube profile, it's _FLT_ !"},
	{what = "sory", 	with = "Apologies, I'm unable to spell"},
	{what = "tipe", 	with = "Apologies, I'm unable to spell"},
	{what = "gess", 	with = "guess you're hot,"},
	{what = "wana", 	with = "wife's dildo"},
	{what = "lyfe", 	with = "my mother's dildo"},
	{what = "nite", 	with = "Butt Blaster"},
	{what = "thnx", 	with = "my Pizza with Applesauce"},
	{what = "diff", 	with = "SVN Checkout"},
	{what = "fone", 	with = "Banana"},
	{what = "watt", 	with = "Lightbulb"},
	{what = "wile", 	with = "Trouser snake"},
	{what = "shud", 	with = "Earthquake"},
	{what = "hawt", 	with = "Seriously attractive"},
	{what = "wout", 	with = "Windows Outage"},
	{what = "goin", 	with = "going to blow my load"},
	{what = "enuf", 	with = "English Unfailing"},
	{what = "fook", 	with = "Explosive Farting"},
	{what = "tryn", 	with = "Train"},
	{what = "wutd", 	with = "Windows Update doing"},
	{what = "whut", 	with = "with huge dicks tomorrow"},
	{what = "rlyy", 	with = "12v Relay"},
	{what = "gvin", 	with = "giving you a handjob with"},
	{what = "rdms", 	with = "loves me all night long"},
	{what = "mute", 	with = "turn off your speakers"},
	{what = "rdmz", 	with = "loves me all night long"},
	{what = "obvi", 	with = "or Boner Violin"},
	{what = "thru", 	with = "Drive Through"},
	{what = "dint", 	with = "drip"},
	{what = "ttyl", 	with = "Teletype"},
	{what = "thou", 	with = "Thaum"},
	{what = "stfu", 	with = "somtimes, there's free lube"},
	{what = "haud", 	with = "Loud"},
	{what = "lubs", 	with = "Lube"},
	{what = "byob", 	with = "Porno"},
	{what = "byol", 	with = "Porno!"},
	{what = "harr", 	with = "Hardon!"},
	{what = "baws", 	with = "cock and balls"},
	{what = "bcuz", 	with = "Beakers"},
	{what = "nawh", 	with = "blowjobs $10"},
	{what = "tiem", 	with = "Bum Time"},
	{what = "teim", 	with = "Bum Time"},
	{what = "fags", 	with = "hot guys"},
	{what = "whzz", 	with = "Cheese Whiz"},
	{what = "thjx", 	with = "90,000 Watts"},
	{what = "gerd", 	with = "Parrot"},
	{what = "trai", 	with = "Diiner Tray"},
	{what = "tors", 	with = "Sliding Doors"},
	{what = "youy", 	with = "young ass"},
	{what = "duno", 	with = "Sand Dunes"},
	{what = "sowy", 	with = "Pork Pies"},
	{what = "whor", 	with = "who wants to suck me"},
	{what = "leet", 	with = "awesome and I can't play!"},
	{what = "chek", 	with = "lick me"},
	{what = "plis", 	with = "a Playlist"},
	{what = "pils", 	with = "PILLS HERE"},
	{what = "wohs", 	with = "who wants my dick and"},
	{what = "cums", 	with = "Squirts"},
	{what = "luve", 	with = "my buttocks are"},
	{what = "taht", 	with = "sucking with his,"},
	{what = "bruv", 	with = "I'm gay"},
	{what = "wtdd",		with = "with the Dongs"},
	{what = "knwo",		with = "know about my huge boner for you,"},
	{what = "jyst",		with = "just don't know how to spell and"},
	{what = "imho",		with = "I'm a ho!"},
	{what = "wiht",		with = "with my new buttplug and"},
	{what = "thro",		with = "through my buttocks"},
	{what = "yoou",		with = "you're awesome, I can't spell!"},
	{what = "kiil",		with = "kill me, I can't spell!"},
	{what = "saay",		with = "say you love my dick!"},
	{what = "sors",		with = "Sorry, I am unable to spell, please shoot me"},
	{what = "nife",		with = "knife, I am unable to spell, please SHOOT ME"},
	{what = "nnoo",		with = "no, I am unable to spell, please SHOOT ME"},
	{what = "hoow",		with = "how, I am unable to spell, please SHOOT ME"},
	{what = "thow",		with = "though I'm unable to spell"},
	{what = "noop",		with = "yes!"},
	{what = "saiz",		with = "said to come and shoot me"},
	{what = "plez",		with = "Lesbian"},
	{what = "suks",		with = "Eats"},
	{what = "duin",		with = "Direct Input"},
	{what = "werd",		with = "Microsoft Office"},
	{what = "plse",		with = "Corrupted Playlist"},
	{what = "buld",		with = "Oh dear"},
	{what = "prly",		with = "probably, but I have a tiny cock!"},
	{what = "nubs",		with = "Buttons"},
	{what = "heff",		with = "shoot my hat off"},
	{what = "shti",		with = "Manure"},
	{what = "swag",		with = "Bag of loot"},
	{what = "bada",		with = "bad dildo, no"},
	{what = "tawk",		with = "talk about how small my dick is"},
	{what = "puls",		with = "suck on my cock"},
	{what = "rdmd",		with = "came all over me"},
	{what = "pulz",		with = "suck on my cock"},
	{what = "pluz",		with = "suck on my cock"},
	{what = "inno",		with = "the whole 11 inches"},
	{what = "pown",		with = "i can wipe my own ass!"},
	{what = "thos",		with = "those dicks you were talking about"},
	{what = "bahn",		with = "Barnyard"},
	{what = "fing",		with = "Fangs"},
	{what = "band",		with = "Brass Band"},
	{what = "duus",		with = "Brass Band"},
	{what = "ownt",		with = "never owned a telephone"},
	{what = "wtdf",		with = "we down to fuck tonight?"},
	{what = "fkin",		with = "would you like a threesome with my brother?"},
	{what = "fuak",		with = "finish on my face"},
	{what = "fock", 	with = "Love"},
	{what = "datt", 	with = "Data Tapes"},
	{what = "foar", 	with = "Five"},
	{what = "amin", 	with = "Awesome Dude"},
	{what = "wpah", 	with = "Wireless Protection Activated"},
	{what = "noez", 	with = "EZ-Cheese"},
	{what = "whaa", 	with = "with the cake and"},
	{what = "romm", 	with = "Read-only memory"},
	{what = "bloo", 	with = "Toilet Cleaner"},
	{what = "ming", 	with = "great player"},
	{what = "thix", 	with = "broken speakers"},
	{what = "cent", 	with = "Dollars"},
	{what = "vajj", 	with = "Mis-Spelling"},
	{what = "fawk", 	with = "Fireworks"},
	{what = "rdmm", 	with = "blow it all over me"},
	
	
	--3
	{what = "tur",		with = "Turtle"},
	{what = "uif",		with = "ISO Image"},
	{what = "adm",		with = "add more Man"},
	{what = "yru",		with = "why do i find you really sexy,"},
	{what = "wdf",		with = "with Dildos and Fisting"},
	{what = "gus",		with = "Gas"},
	{what = "lyk",		with = "like cute dicks"},
	{what = "sus",		with = "some underpants and"},
	{what = "waz",		with = "was unable to spell"},
	{what = "ths", 		with = "this is awesome, add me on steam, it's _FLT_"},
	{what = "omf",		with = "or my free guns"},
	{what = "cac",		with = "CNC Machine"},
	{what = "mlp",		with = "my tiny dick"},
	{what = "mlg",		with = "my tiny dick"},
	{what = "ger",		with = "Germs"},
	{what = "coc",		with = "CNC Machine"},
	{what = "tig",		with = "Tiger gas"},
	{what = "mom",		with = "dog"},
	{what = "wan",		with = "Minivan"},
	{what = "emd",		with = "Electromagnetic Pulse"},
	{what = "unt",		with = "my butthole"},
	{what = "shu",		with = "sinking ship"},
	{what = "olo",		with = "oh dear, I seem to only have a tiny dick"},
	{what = "tra",		with = "Dinner Tray"},
	{what = "nad",		with = "boyfriend"},
	{what = "svr",		with = "Radiation"},
	{what = "rmd",		with = "cum all over"},
	{what = "drm",		with = "cum inside"},
	{what = "rof",		with = "roof of the Gas Station"},
	{what = "med",		with = "Medium-sized cock"},
	{what = "nig",		with = "National Insurance Game"},
	{what = "gae",		with = "Awesome"},
	{what = "den",		with = "then we can fuck tonight if"},
	{what = "wry",		with = "worry about your cock, i know it's very small"},
	{what = "daz",		with = "Soap Powder"},
	{what = "vag",		with = "Bag of sand"},
	{what = "jew",		with = "Juice"},
	{what = "hee",		with = "he has a lovley anus,"},
	{what = "mai",		with = "Corrupted Email"},
	{what = "trt",		with = "Jam Tart"},
	{what = "gey",		with = "awesome in bed"},
	{what = "duh",		with = "Carpet Muncher"},
	{what = "wep",		with = "Wired Equivalent Privacy"},
	{what = "bah",		with = "Baghdad"},
	{what = "hlp",		with = "Hewlett Packard"},
	{what = "fux",		with = "Firefox"},
	{what = "fak",		with = "Love my dick and"},
	{what = "dik",		with = "Boner"},
	{what = "yau",		with = "Yahoo, but I can't spell"},
	{what = "yuo",		with = "your dick and your"},
	{what = "oyu",		with = "your cock and your"},
	{what = "sor",		with = "Operating System"},
	{what = "osr",		with = "Operating System"},
	{what = "mem",		with = "Random Access Memory"},
	{what = "afk",		with = "taking a dump in a can!"},
	{what = "ust",		with = "just come and shoot me"},
	{what = "ome",		with = "Bomb"},
	{what = "tah",		with = "Taco"},
	{what = "wnt",		with = "want to die with"},
	{what = "yuh",		with = "Yellow hat"},
	{what = "upp",		with = "up yours"},
	{what = "dha",		with = "Bomb"},
	{what = "imn",		with = "I'm not being shot right now, shoot me!"},
	{what = "nlr",		with = "NTLDR"},
	{what = "maj",		with = "Explosives"},
	{what = "mej",		with = "Matches"},
	{what = "bck",		with = "watching porn!"},
	{what = "doi",		with = "Driving under the influence"},
	{what = "ick",		with = "Icing"},
	{what = "hak",		with = "Skiddie Fuel"},
	{what = "tsk",		with = "I have a huge hardon for you"},
	{what = "ing",		with = "Gold Bar"},
	{what = "cha",		with = "VHS"},
	{what = "wee",		with = "Urine!"},
	{what = "neh",		with = "Nuts and bolts"},
	{what = "nuh",		with = "Nuts and bolts"},
	{what = "wai",		with = "wait until you see it hard!"},
	{what = "ser",		with = "Server"},
	{what = "sth",		with = "Roadworks"},
	{what = "git",		with = "Grit"},
	{what = "fer",		with = "for my next lovemaking session with"},
	{what = "ops",		with = "Operations per second"},
	{what = "wor",		with = "I'm a whore"},
	{what = "iww",		with = "Telephone Weights"},
	{what = "sow",		with = "Pork Pie"},
	{what = "tel",		with = "Telephone"},
	{what = "nob",		with = "Awesome Player"},
	{what = "srv",		with = "Solid Rocket Booster"},
	{what = "don", 		with = "huge dong!"},
	{what = "eni", 		with = "eBay"},
	{what = "hte", 		with = "love a giant cock"},
	{what = "ded", 		with = "my dead braincells"},
	{what = "yus", 		with = "yum, dicks"},
	{what = "gah", 		with = "Duct Tape"},
	{what = "ino", 		with = "Inno Setup Compiler"},
	{what = "nou", 		with = "no Uranium"},
	{what = "dud", 		with = "dude, look at my boner!"},
	{what = "hao", 		with = "Halo 2"},
	{what = "hwy", 		with = "why can't I spell!"},
	{what = "las", 		with = "last dildo in the store"},
	{what = "brb", 		with = "Barbed Wire"},
	{what = "qoq", 		with = "butt plugs,"},
	{what = "koc", 		with = "butt plugs,"},
	{what = "kok", 		with = "butt plugs,"},
	{what = "cok", 		with = "butt plugs,"},
	{what = "coq", 		with = "butt plugs,"},
	{what = "iam", 		with = "I love butt plugs,"},
	{what = "afc", 		with = "afraid of cocks"},
	{what = "mak", 		with = "Media Access"},
	{what = "cnt", 		with = "I'm Gay"},
	{what = "dif", 		with = "Difference File"},
	{what = "tha", 		with = "the massive dildo with the"},
	{what = "nno", 		with = "no pants on"},
	{what = "wif", 		with = "stink"},
	{what = "ofc", 		with = "yes, i'd love to suck you :3"},
	{what = "tks", 		with = "Water Tanks"},
	{what = "ftw", 		with = "come and shoot me with it"},
	{what = "whz", 		with = "Cheese Whiz"},
	{what = "yea", 		with = "a million years"},
	{what = "ups", 		with = "Uninterruptable Power Supply"},
	{what = "hiz", 		with = "Hiss"},
	{what = "lul",		with = "I'm terrible"},
	{what = "lel",		with = "I'm terrible"},
	{what = "lal",		with = "I'm terrible"},
	{what = "wtd",		with = "with the Dong"},
	{what = "dam",		with = "Hoover Dam"},
	{what = "uda",		with = "Buddha"},
	{what = "dou",		with = "Dough"},
	{what = "har",		with = "Hardon!"},
	{what = "rlz",		with = "ReleaseLog"},
	{what = "bro",		with = "brother's huge cock"},
	{what = "abt",		with = "Trouser Snake"},
	{what = "yer",		with = "my anus"},
	{what = "haw",		with = "Hawk"},
	{what = "fir",		with = "Infrared Data Link"},
	{what = "fro",		with = "Frozen"},
	{what = "dne",		with = "Methane"},
	{what = "ure",		with = "Urinal"},
	{what = "mad",		with = "Bananas"},
	{what = "foo",		with = "Food"},
	{what = "luk",		with = "Hardon"},
	{what = "oic",		with = "2 inch cock"},
	{what = "whn",		with = "with Eggs when"},
	{what = "tty",		with = "Teletype"},
	{what = "fuc",		with = "Kentucky Fried Chicken"},
	{what = "shi",		with = "Ship"},
	{what = "tru",		with = "Trunk"},
	{what = "mhm",		with = "Cadillac!"},
	{what = "srx",		with = "XXX"},
	{what = "cos",		with = "because I have a tiny cock!"},
	{what = "cud",		with = "Cadillac"},
	{what = "shd",		with = "Shipwreck"},
	{what = "gng",		with = "CNC Machine"},
	{what = "eff",		with = "Electronic Frontier Foundation"},
	{what = "sux",		with = "sucks my boner"},
	{what = "cbf",		with = "can fuck forever"},
	{what = "tbh",		with = "those butts are hot"},
	{what = "muh",		with = "Mustard"},
	{what = "mon",		with = "Monitor"},
	{what = "yoo",		with = "Users"},
	{what = "hbu",		with = "Host Bus Upstream"},
	{what = "sho",		with = "Shower"},
	{what = "hve",		with = "High Voltage Electric"},
	{what = "sos",		with = "I've been dicking myself, but there's room for two!"},
	{what = "sto",		with = "Storage"},
	{what = "pik",		with = "Diamond Pickaxe"},
	{what = "mfw",		with = "Metafile Windows"},
	{what = "tfw",		with = "Torrent file Windows"},
	{what = "fml",		with = "Female"},
	{what = "fst",		with = "first Tits"},
	{what = "wbu",		with = "Wireless Broadband Update"},
	{what = "ffs",		with = "I'm immensely frustrated"},
	{what = "wen",		with = "with a Chicken when"},
	{what = "tun",		with = "Tuna fish"},
	{what = "npe",		with = "and Pie"},
	{what = "omg",		with = "oh and I love cock"},
	{what = "cus",		with = "Curse"},
	{what = "nic",		with = "Network Interface Controller"},
	{what = "bsy",		with = "Bee"},
	{what = "tht",		with = "Titanic"},
	{what = "der",		with = "Dong"},
	{what = "nao",		with = "Meow"},
	{what = "sry", 		with = "iPhone"},
	{what = "cum",		with = "Baby Cream"},
	{what = "nty",		with = "Contains Nuts"},
	{what = "meh",		with = "Meth"},
	{what = "mah",		with = "Math"},
	{what = "hav",		with = "Half"},
	{what = "soz",		with = "Knitted Socks!"},
	{what = "sup",		with = "Chicken Soup"},
	{what = "sir",		with = "Big Cheese"},
	{what = "thx",		with = "90,000 Watts"},
	{what = "wis",		with = "Windows Installer"},
	{what = "tnx",		with = "Dynamite"},
	{what = "wat",		with = "Windows Activation"},
	{what = "wut",		with = "Windows Update"},
	{what = "wot",		with = "Weather Balloon"},
	{what = "wuh",		with = "Windows Update"},
	{what = "wha",		with = "Pizza with Applesauce"},
	{what = "eet",		with = "Feet"},
	{what = "dub",		with = "Dubstep"},
	{what = "wos",		with = "Washer"},
	{what = "wus",		with = "Washer"},
	{what = "wht",		with = "Wheat"},
	{what = "ikr",		with = "I love to take it up the butt"},
	{what = "hah",		with = "you sound hot!"},
	{what = "dah",		with = "Dakara"},
	{what = "pon",		with = "Panties"},
	{what = "ies",		with = "Internet Explorer"},
	{what = "cks",		with = "long cocks"},
	{what = "dnt",		with = "Donut"},
	{what = "bak",		with = "Backup"},
	{what = "noo",		with = "I'm Nude!"},
	{what = "nuu",		with = "Nude"},
	{what = "luv",		with = "love sucking"},
	{what = "wuv",		with = "love sucking"},
	{what = "wuz",		with = "Wood"},
	{what = "lik",		with = "licked his cock with"},
	{what = "nup",		with = "Network Unplugged"},
	{what = "nop",		with = "Network Operations"},
	{what = "nah",		with = "Nachos"},
	{what = "nub",		with = "Great Player"},
	{what = "cya",		with = "Cyanide!"},
	{what = "sya",		with = "Change my Ink Cartridge!"},
	{what = "rdy",		with = "Lube"},
	{what = "cuz", 		with = "Cruise Missile"},
	{what = "coz", 		with = "Cruise Missile"},
	{what = "fgt",		with = "forgotton folder of porn!"},
	{what = "fag",		with = "hot dude"},
	{what = "sed",		with = "said come and shoot me"},
	{what = "stp",		with = "File Transfer Protocol"},
	{what = "srs",		with = "Servers"},
	{what = "lyf",		with = "life, don't talk to me about life :("},
	{what = "haz",		with = "have hairy balls"},
	{what = "fug",		with = "Fuckweasel"},
	{what = "fuq",		with = "Fuckweasel"},
	{what = "foq",		with = "Fuckweasel"},
	{what = "suk",		with = "suck my boner"},
	{what = "tis",		with = "Transport Infomation Services"},
	{what = "suc",		with = "suck my boner"},
	{what = "bai",		with = "Bail"},
	{what = "dis",		with = "Long Distance"},
	{what = "gon",		with = "gone to buy a new dildo and"},
	{what = "hai",		with = "Hello, I can't spell!"},
	{what = "ppl",		with = "people with dicks"},
	{what = "gag",		with = "Finger"},
	{what = "dat",		with = "Data tape"},
	{what = "idk",		with = "I'm too busy fapping"},
	{what = "idc",		with = "I still love you"},
	{what = "wth", 		with = "with the hot guys!"},
	{what = "mhe", 		with = "Methane"},
	{what = "boi", 		with = "BIOS"},
	{what = "yey", 		with = "yay, also I like it up the ass!"},
	{what = "pzl",		with = "a Playlist"},
	{what = "plz",		with = "a Playlist"},
	{what = "pls",		with = "a Playlist"},
	{what = "plx",		with = "A PLAYLIST!"},
	{what = "rly", 		with = "Power Relay"},
	{what = "fel", 		with = "Feel"},
	{what = "nss", 		with = "No Software Service"},
	{what = "daf", 		with = "DoS Attack Fix"},
	{what = "non", 		with = "Noon"},
	{what = "nis", 		with = "Nipple Insurance"},
	{what = "thn",		with = "Thong"},
	{what = "teh",		with = "my dick with the"},
	{what = "knw",		with = "know I love dick"},
	{what = "kno",		with = "Snow"},
	{what = "dem",		with = "Demo"},
	{what = "ima",		with = "Windows 95"},
	{what = "def",		with = "#define"},
	{what = "chk", 		with = "CheckDisk"},
	{what = "nvm", 		with = "NVIDIA"},
	{what = "yup", 		with = "yes, with your dick"},
	{what = "sht", 		with = "Shutdown"},
	{what = "dun", 		with = "Dung"},
	{what = "tho", 		with = "Thong"},
	{what = "thr", 		with = "Thread"},
	{what = "cba", 		with = "Concrete Building Assosiation"},
	{what = "sec",		with = "sex"},
	{what = "wud",		with = "large wad"},
	{what = "btw",		with = "Bring Terror Weapons"},
	{what = "gna",		with = "Grandma's Nasty Ass!"},
	{what = "naw",		with = "Anal"},
	{what = "kik",		with = "Lick"},
	{what = "tro",		with = "Toll Bridge"},
	{what = "urs",		with = "your massive cock"},
	{what = "pks",		with = "Parks"},
	{what = "fud",		with = "food Underpants"},
	{what = "fik",		with = "Norberto fig awesome cat competition"},
	{what = "yow",		with = "Meow"},
	{what = "rad",		with = "Radiation"},
	{what = "jus",		with = "Juice"},
	{what = "mao",		with = "Meow"},
	{what = "gud",		with = "good for the backside"},
	{what = "wit",		with = "White"},
	{what = "wyd",		with = "with your dick!"},
	{what = "moo",		with = "dog poo"},
	{what = "pwn",		with = "suck"},
	{what = "thy",		with = "Thighs"},
	{what = "fkn",		with = "come and Bang me"},
	{what = "gal",		with = "Gallons"},
	{what = "wah",		with = "Water Heater"},
	{what = "thi",		with = "Thighs"},
	{what = "yah",		with = "Yahoo!"},
	{what = "gtg",		with = "got to go now, I can't spell :("},
	{what = "tdm",		with = "no, I mean come and shoot me!"},
	{what = "rdm",		with = "cum all over"},
	{what = "kil",		with = "Bang"},
	{what = "det",		with = "Detonator"},
	{what = "mby",		with = "Maybe you can suck me or"},
	{what = "thw",		with = "the Wireless"},
	{what = "cna",		with = "can fuck me or"},
	{what = "spk",		with = "Service Pack"},
	{what = "som",		with = "some fingering and"},
	{what = "sum",		with = "some fisting and"},
	{what = "fck",		with = "Love"},
	{what = "wer",		with = "Windows Error"},
	{what = "rqs",		with = "sucks me off"},
	{what = "srz",		with = "Servers"},
	{what = "yeh",		with = "want to see my webcam? my skype is _FLT_"},
	{what = "wna",		with = "can't spell"},
	{what = "fil",		with = "Cream Filling"},
	{what = "dic",		with = "Huge Boner"},
	{what = "ono",		with = "or nearest offer"},
	{what = "whr",		with = "massive boner"},
	{what = "thm",		with = "Thaum"},
	{what = "kic",		with = "KFC"},
	{what = "wid",		with = "Windows Installer"},
	{what = "mee",		with = "me and my cock"},
	{what = "imo",		with = "in my butt"},
	{what = "bou",		with = "boat full of dynamite"},
	{what = "fat",		with = "File Allocation Table"},
	{what = "dum",		with = "cool"},
	{what = "wel",		with = "Water Well"},
	{what = "owr",		with = "our buttocks"},
	{what = "fks",		with = "Loves"},
	{what = "nos",		with = "Nitrous Oxide"},
	{what = "dur",		with = "Doorstop"},
	{what = "tat",		with = "Tattoo"},
	{what = "oke",		with = "ok, now will you shoot me?"},
	{what = "iim",		with = "I'm unable to spell, so please shoot me now while I'm"},
	{what = "giv",		with = "give me a blowjob"},
	{what = "stu",		with = "Chicken Stew"},
	{what = "pid",		with = "Product ID"},
	{what = "hmu",		with = "her massive underpants"},
	{what = "tor",		with = "The Onion Router"},
	{what = "hel",		with = "Ice Cream van"},
	{what = "iss",		with = "Public Toilet"},
	{what = "joo",		with = "Apple Juice"},
	{what = "yiu",		with = "you have a boner"},
	{what = "obv",		with = "obviously too big for me"},
	{what = "ers",		with = "Ears"},
	{what = "nxt",		with = "Lego"},
	{what = "mer", 		with = "butt rocket"},
	{what = "cic", 		with = "i'm not blind"},
	{what = "chu", 		with = "Choo-Choo"},
	{what = "sre", 		with = "iPhone"},
	{what = "giy", 		with = "guy who can spell"},
	
	--2
	{what = "ll", 		with = "large boner"},
	{what = "bn", 		with = "bone"},
	{what = "ba", 		with = "big ass"},
	{what = "fg", 		with = "fake guns"},
	{what = "af",		with = "activate Farting!"},
	{what = "cm",		with = "Cinematic Mod"},
	{what = "ga",		with = "golden apple"},
	{what = "ad",		with = "Advertising"},
	{what = "ze",		with = "my butthole with"},
	{what = "pe",		with = "dick explosion"},
	{what = "le",		with = "Light Edition"},
	{what = "bs",		with = "Building Services"},
	{what = "wa",		with = "Windows Activation"},
	{what = "ke",		with = "Kink Engineering"},
	{what = "ir",		with = "Infrared"},
	{what = "ys",		with = "you're sexy"},
	{what = "ta",		with = "Roadworks"},
	{what = "rr",		with = "RoadRunner"},
	{what = "ol",		with = "oh dear, i've pooped my pants"},
	{what = "lo",		with = "want to see my huge boner"},
	{what = "os",		with = "Windows Vista"},
	{what = "ou",		with = "my boner"},
	{what = "un",		with = "exploding"},
	{what = "ni",		with = "Nipple"},
	{what = "dx",		with = "my huge boner"},
	{what = "pp",		with = "Post Processing"},
	{what = "cp",		with = "Control Panel"},
	{what = "fk",		with = "Love"},
	{what = "al",		with = "Aluminium"},
	{what = "rq",		with = "cum all over me"},
	{what = "dd",		with = "Double Dildo"},
	{what = "mk",		with = "make me a cake"},
	{what = "ha",		with = "BLOWJOB!"},
	{what = "aa", 		with = "Auto Activation"},
	{what = "om", 		with = "or Mangos"},
	{what = "ss", 		with = "Suck Suck"},
	{what = "ka", 		with = "Cake"},
	{what = "ds", 		with = "Dual Screen"},
	{what = "fr", 		with = "France"},
	{what = "nu", 		with = "Fuck me in the ass"},
	{what = "qq", 		with = "Fuck me in the ass"},
	{what = "ff", 		with = "Fuck me in the ass"},
	{what = "uu", 		with = "My sweaty balls"},
	{what = "tt", 		with = "those titties!"},
	{what = "bt", 		with = "Broken Telephone"},
	{what = "ki", 		with = "Kink Engineering"},
	{what = "gs", 		with = "Gone Shopping"},
	{what = "hu", 		with = "huge anus"},
	{what = "wb", 		with = "White Balance"},
	{what = "sk", 		with = "Cumshot"},
	{what = "ai", 		with = "All Invisible"},
	{what = "ab", 		with = "about to Bang"},
	{what = "yw", 		with = "you wank?"},
	{what = "gj", 		with = "I love a nice big cock!"},
	{what = "wf", 		with = "without Flourine"},
	{what = "gd", 		with = "GameDeception"},
	{what = "fa", 		with = "Fap"},
	{what = "wy", 		with = "Nintendo Wii"},
	{what = "wu", 		with = "Windows Update"},
	{what = "xe", 		with = "Extreme Edition"},
	{what = "lk", 		with = "Lick"},
	{what = "jw", 		with = "Juicy Wang"},
	{what = "se", 		with = "ScriptEnforcer"},
	{what = "uv", 		with = "Ultravoilet"},
	{what = "iz", 		with = "hate my life"},
	{what = "bc", 		with = "Battle Cruiser"},
	{what = "jk", 		with = "JFK"},
	{what = "nm", 		with = "Nanomechanics"},
	{what = "eh", 		with = "Event Horizon"},
	{what = "fs", 		with = "Filesystem"},
	{what = "fo", 		with = "Phone"},
	{what = "wi", 		with = "Windows Installer"},
	{what = "na", 		with = "Sodium"},
	{what = "gg", 		with = "Grandma's Gun!"},
	{what = "nt", 		with = "Windows NT"},
	{what = "uq", 		with = "Ducklings"},
	{what = "wt", 		with = "Waste Transfer"},
	{what = "yo",		with = "Yogurt"},
	{what = "tu",		with = "Titanium Underpants"},
	{what = "iv",		with = "I vomit"},
	{what = "ht",		with = "Hyperthreading"},
	{what = "ne",		with = "Neon Lamp"},
	{what = "gy",		with = "guy's cock"},
	{what = "bk",		with = "Burger King"},
	{what = "cu",		with = "Copper"},
	{what = "dw",		with = "Dong Warning"},
	{what = "yu",		with = "Urinal"},
	{what = "yr",		with = "Your ass"},
	{what = "ty",		with = "Burgundy Tie"},
	{what = "hw",		with = "Hardware"},
	{what = "ud",		with = "Unlimited Download"},
	{what = "ur",		with = "your huge dick, your"},
	{what = "yh",		with = "yes handjob!"},
	{what = "ye",		with = "yes, I'd love to suck it"},
	{what = "np",		with = "Null Pointer"},
	{what = "rp",		with = "Drama Unlimited"},
	{what = "wh",		with = "White Hat"},
	{what = "ik",		with = "Inverse kinematics"},
	{what = "da",		with = "Direct Access"},
	{what = "tp",		with = "Toilet Paper"},
	{what = "xd",		with = "I swallow!"},
	{what = "ce",		with = "Windows CE"},
	{what = "ov",		with = "Russia"},
	{what = "ru",		with = "Russia"},
	{what = "st",		with = "Stargate"},
	{what = "op",		with = "Original Poster"},
	{what = "sh",		with = "Shit Happens"},
	{what = "fu",		with = "for Underpants"},
	{what = "ck",		with = "Carbon King"},
	{what = "su",		with = "Superuser"},
	{what = "em",		with = "Electromagnet"},
	{what = "gu",		with = "hot dicks"},
	{what = "pl",		with = "Plutonium"},
	{what = "ev",		with = "Evolve"},
	{what = "te",		with = "Teapot"},
	{what = "kk",		with = "Cake Cake"},
	{what = "gt",		with = "Gigatexels"},
	{what = "bb",		with = "BaconBot"},
	{what = "mi",		with = "Mission Impossible"},
	{what = "oi",		with = "I/O Buffer"},
	{what = "mw",		with = "Medium Wave"},
	{what = "sa",		with = "San Andreas"},
	{what = "du",		with = "Depleted Uranium"},
	{what = "cc",		with = "Crispy Coconut"},
	{what = "yy",		with = "Yellow Yarrgh!"},
	{what = "oo",		with = "or bone me"},
	{what = "wd",		with = "Western Digital"},
	{what = "de",		with = "Germany"},
	{what = "wc",		with = "Water Closet"},
	{what = "mf",		with = "Mediafire"},
	{what = "mu",		with = "Megaupload"},
	{what = "rs",		with = "Rapidshit"},
	{what = "ar",		with = "are Fisting"},
	{what = "ma",		with = "my boner and"},
	{what = "mn",		with = "my boner and"},
	{what = "ts",		with = "lovely dicks"},
	{what = "ed",		with = "unable to get it up"},
	{what = "re",		with = "rewind"},
	{what = "ro",		with = "row my boat"},
	{what = "fl",		with = "Flour"},
	
	--1
	--A
	{what = "b", 		with = "Butt plug"},
	--C, other
	--D, other
	--E, other
	--F, other
	{what = "g", 		with = "Gasoline"},
	{what = "h", 		with = "Handjob"},
	--I, other
	{what = "j", 		with = "Juice"},
	{what = "k", 		with = "Nutsack"},
	--L, other
	{what = "m", 		with = "my tiny dong with the"},
	--N, other
	{what = "o",		with = "Oxygen"},
	{what = "p", 		with = "Protons"},
	--Q
	{what = "r",		with = "Rubbing"},
	--S, other
	--T, other
	{what = "u",		with = "My balls"},
	{what = "v", 		with = "Vacbed"},
	{what = "w", 		with = "Wireless"},
	--X, other
	{what = "y",		with = "Yellow"},
	--Z
	
	
	--Swears
	{what = "cocksucking",	with = "giving a blowjob"},
	{what = "cocksucker",	with = "give me a blowjob!"},
	{what = "cocking",		with = "Roosting"},
	{what = "cocks",		with = "Roosters"},
	{what = "cock",			with = "Rooster"},
	
	{what = "dike",			with = "Explosion"},
	{what = "dyke",			with = "Explosion"},
	{what = "douche",		with = "butt rocket"},
	{what = "douch",		with = "butt rocket"},
	{what = "douchebag",	with = "butt finger blast"},
	
	{what = "dumbasses",	with = "Drum n' Bass"},
	{what = "dumbass",		with = "Drum n' Bass"},
	{what = "dumass",		with = "Drum n' Bass"},
	{what = "godangit",		with = "God Donut"},
	{what = "goddangit",	with = "God Donut!"},
	
	{what = "ahole",		with = "like me cause I swallow"},
	{what = "a-hole",		with = "like me cause I swallow"},
	{what = "jackass",		with = "love jack's ass!"},
	{what = "ass",			with = "Derriere"},
	
	{what = "arseholes",	with = "Crapfactories"},
	{what = "arsehole",		with = "Crapfactory"},
	{what = "arse",			with = "Derriere"},
	
	{what = "boobies",		with = "Melons"},
	{what = "boobs",		with = "Melons"},
	
	{what = "titties",		with = "Melons"},
	{what = "tittie",		with = "Melon"},
	{what = "tittys",		with = "Melons"},
	{what = "titty",		with = "Melons"},
	{what = "tits",			with = "Melons"},
	{what = "tit",			with = "Melon"},
	
	{what = "bugger",		with = "Sodomise"},
	{what = "twat",			with = "Teapot"},
	{what = "retarded",		with = "Awesome"},
	{what = "retard",		with = "Genius"},
	
	{what = "basterd",		with = "Mr Awesome"},
	{what = "basterds",		with = "Awesome Guys"},
	
	{what = "bastard",		with = "Mr Awesome"},
	{what = "bastards",		with = "Awesome Guys"},
	{what = "bollocks",		with = "Testicles"},
	{what = "bollock",		with = "Testicle"},
	{what = "bollox",		with = "Testicles"},
	
	{what = "wanker",		with = "want a blowjob?"},
	
	{what = "gaytard", 		with = "Sir Awesome"},
	{what = "gaylord", 		with = "Sir Awesome"},
	
	{what = "whores", 		with = "Firecrackers"},
	{what = "whore", 		with = "Firecracker"},
	{what = "hoe", 			with = "Firecracker"},
	{what = "ho", 			with = "Firecracker"},
	
	{what = "chinc",		with = "Teapot"},
	{what = "chink",		with = "Teapot"},
	{what = "chinck",		with = "Teapot"},
	{what = "spic",			with = "great player"},
	{what = "spik",			with = "great player"},
	{what = "spick",		with = "great player"},

	{what = "tard",			with = "TARDIS"},
	{what = "pricks",		with = "Sharp Edges"},
	{what = "prick",		with = "cool dude"},
	{what = "clit",			with = "Action Button"},
	{what = "coon",			with = "Racoon"},
	{what = "idiots",		with = "awesome dudes"},
	{what = "idiot",		with = "awesome dude"},
	{what = "moron",		with = "cool cude"},
	{what = "morons",		with = "cool dudes"},
	{what = "jerk", 		with = "Jerk off tonight?"},
	{what = "heck", 		with = "Heckler & Koch"},
	{what = "paki", 		with = "park bench"},
	{what = "queer", 		with = "beef"},
	{what = "skank", 		with = "Spank"},
	{what = "skeet", 		with = "Toothpaste"},
	
	{what = "fucer", 		with = "Faucet"},
}


--SWEARWORDS, or bad words that are not nouns
HSP.ChatFilter.Swearwords = {	
	{what = "ur moms",			with = "my mother's",									rep = true},
	{what = "ur mums",			with = "my mother's",									rep = true},
	{what = "ur mothers",		with = "my mother's",									rep = true},
	{what = "ur mother",		with = "my mother",										rep = true},
	{what = "ur mom",			with = "my mother",										rep = true},
	{what = "ur mum",			with = "my mother",										rep = true},
	
	{what = "your moms",		with = "my mother's",									rep = true},
	{what = "your mums",		with = "my mother's",									rep = true},
	{what = "youre mother",		with = "my mother",										rep = true},
	{what = "youre mothers",	with = "my mother's",									rep = true},
	{what = "your mothers",		with = "my mother's",									rep = true},
	{what = "your mother",		with = "my mother",										rep = true},
	{what = "your mom",			with = "my mother",										rep = true},
	{what = "your mum",			with = "my mother",										rep = true},
	
	{what = "you mother",		with = "my mother",										rep = true},
	{what = "you mom",			with = "my mother",										rep = true},
	
	{what = "u r",				with = "your great big boner and the"},
	{what = "i k",				with = "I only have a tiny one, sorry"},
	{what = "r u",				with = "in soviet russia, I'm"},
	{what = "y u",				with = "wow you're really cute,"},
	{what = "i has",			with = "I have lost the ability to spell, shoot me with"},
	{what = "a ban",			with = "a blowjob"},
	{what = "you suck",			with = "you're awesome"},
	{what = "no life",			with = "an epic life"},
	{what = "go die",			with = "go get some Ice Cream"},
	{what = "get a life",		with = "bone me"},
	{what = "shut up",			with = "hey, want to bang me"},
	{what = "aim bot",			with = "a very large dildo"},
	{what = "god mode",			with = "your awesome boner"},
	{what = "you mad",			with = "You're awesome"},
	{what = "server sucks",		with = "server is awesome"},
	{what = "bad server",		with = "epic server"},
	{what = "leave me alone",	with = "come and shoot me"},
	{what = "im building",		with = "It's DM, so shoot me :)"},
	
	{what = "spell changer",	with = "Super Awesome Chat Cleanser",					rep = true},
	{what = "spell checker",	with = "Super Awesome Chat Cleanser",					rep = true},
	{what = "spell check",		with = "Super Awesome Chat Cleanser",					rep = true},
	{what = "spell thing",		with = "Super Awesome Chat Cleanser",					rep = true},
	{what = "chat filter",		with = "Super Awesome Chat Cleanser",					rep = true},
	{what = "word filter",		with = "Super Awesome Word Cleanser",					rep = true},
	{what = "auto correcting",	with = "Auto Cucumbering",								rep = true},
	{what = "auto corrector",	with = "Auto Cucumber",									rep = true},
	{what = "auto correct",		with = "Auto Cucumber",									rep = true},
	{what = "chat thing",		with = "Super Awesome Chat Cleanser",					rep = true},
	{what = "this chat",		with = "this Super Awesome Chat Cleanser",				rep = true},
	
	{what = "screw this",		with = "Nail me",										rep = true},
	{what = "no scope",			with = "can we cram the sniper rifle up my butt?",		rep = true},
	{what = "role play",		with = "Timewasting",									rep = true},
	{what = "noob",				with = "Bagpipes",										rep = true},
	{what = "n00b",				with = "Bagpipes",										rep = true},
	{what = "wtf", 				with = "Waste Transfer Facility", 		pron = true,	rep = true},
	{what = "lawl",				with = "I love a wanking later",						rep = true},
	{what = "mutha",			with = "Dog"},
	{what = "mama",				with = "Dog"},
	
	{what = "dont kil me",		with = "Please kill me!"},
	{what = "do not kil me",	with = "I mean shoot me now!"},
	
	{what = "dont kill me",		with = "Please kill me!"},
	{what = "do not kill me",	with = "I mean shoot me now!"},
	
	{what = "quit shooting",	with = "Everyone shoot"},
	{what = "stop shooting",	with = "Everyone shoot"},
	{what = "no shooting",		with = "Everyone shoot"},
	{what = "no shoot",			with = "Come and shoot"},
	
	{what = "quit killing",		with = "keep killing"},
	{what = "stop killing",		with = "keep killing"},
	{what = "no killing",		with = "Shoot me now"},
	{what = "no kill",			with = "Bet you can't kill"},
	{what = "not kill me",		with = "kill me"},
	{what = "dont stop",		with = "keep shooting"},
	
	{what = "dontkil",			with = "Everyone Kill"},
	{what = "dont kill",		with = "Everyone Kill"},
	{what = "do not kill",		with = "I mean kill"},
	
	{what = "dont shoot",		with = "I mean shoot"},
	{what = "do not shoot",		with = "I mean shoot"},
	
	
	{what = "pussies",			with = "Cats"},
	{what = "pussie",			with = "Feline",										rep = true},
	{what = "pussy",			with = "Kittens"},
	{what = "cunt",				with = "I'm gay!",										rep = true},
	{what = "kunt",				with = "I'm gay!",										rep = true},
	
	{what = "niggers",			with = "Roody-poos"},
	{what = "negro",			with = "Roody-poo"},
	{what = "niglet",			with = "Roody-poo"},
	{what = "nigg",				with = "Roody-poo", 									rep	= true},
	--Wildcard
	
	{what = "faggots",			with = "hot dudes", 									rep	= true},
	{what = "faggot",			with = "hot dude", 										rep	= true},
	{what = "faggat",			with = "Cigarette Packet", 								rep	= true},
	{what = "faggit",			with = "Cigarette Packet", 								rep	= true},
	{what = "fagget",			with = "Cigarette Packet", 								rep	= true},
	
	{what = "bitches",			with = "Female Dogs",									rep	= true},
	{what = "bitchs",			with = "Female Dogs",									rep	= true},
	{what = "bitch",			with = "Female Dog",									rep	= true},
	
	{what = "dickhead",			with = "Ding Dong head"},
	{what = "dick",				with = "Ding Dong",						pron = true},
	
	--Cock in other list
	
	{what = "assholes",			with = "Waste Outlets",									rep	= true},
	{what = "asshole",			with = "Waste Outlet",									rep	= true},
	{what = "ass hole",			with = "Sewage Tank"},
	{what = "arse hole",		with = "Septic Tank"},
	
	
	{what = "piss off",			with = "take a Golden Shower"},
	{what = "pissed",			with = "taking a Golden Shower"},
	{what = "pissy",			with = "a Golden Shower"},
	{what = "piss",				with = "Golden Shower",					pron = true},
	
	{what = "motherfucking",	with = "Motherloving"},
	{what = "motherfuckers",	with = "Motherlovers"},
	{what = "motherfucker",		with = "Motherlover"},
	{what = "motherfucka",		with = "Motherlover"},
	{what = "clusterfuck",		with = "orgy"},
	{what = "fuck off",			with = "Bang me hard"},
	{what = "fucking",			with = "Loving"},
	{what = "fuckers",			with = "Lovers"},
	{what = "fucker",			with = "Lover"},
	{what = "fucked",			with = "Loved"},
	{what = "fucka",			with = "Lover"},
	{what = "fking",			with = "Loveing"},
	{what = "fucks",			with = "Lovers"},
	{what = "fahk",				with = "Love",							pron = true},
	{what = "fhak",				with = "Love",							pron = true},
	{what = "fcuk",				with = "Love",							pron = true},
	{what = "fuck",				with = "Love",							pron = true},
	{what = "fuk",				with = "Love",							pron = true},
	
	{what = "bullshit",			with = "Debugger"},
	{what = "shittier",			with = "more Poop Quality"},
	{what = "shitter",			with = "Crapfactory"},
	{what = "shitty",			with = "Poor Quality"},
	{what = "shitting",			with = "Muck spreading",								rep	= true},
	{what = "shitters",			with = "Crapfactories"},
	{what = "shitheads",		with = "Sewage brains"},
	{what = "shithead",			with = "Sewage brain",					pron = true,	rep	= true},
	{what = "holy shit",		with = "you should have seen the size of my dump!"},
	{what = "shite",			with = "dog dung"},
	{what = "shiz",				with = "Excrement", 									rep	= true},
	{what = "shit",				with = "Doo-Doo"},
	
	{what = "god damn",			with = "Godly Hydroelectricity!"},
	{what = "goddamnit",		with = "Godly Hydroelectricity"},
	{what = "goddamn",			with = "Godly Hydroelectricity"},
	{what = "goddammit",		with = "Godly Hydroelectricity"},
	{what = "goddamm",			with = "Godly Hydroelectricity"},
	{what = "goddam",			with = "Godly Hydroelectricity"},
	{what = "dammit",			with = "Hydroelectricity"},
	{what = "damnit",			with = "Hydroelectricity!"},
	{what = "damit",			with = "Hoover Dam it"},
	{what = "damn",				with = "Hoover Dam",					pron = true},
	
	--Cheat related
	{what = "sethhacker",		with = "Zero Skill Skiddie"},
	{what = "sethhack",			with = "Seth's Wallet"},
	{what = "seth hack",		with = "Seth's Wallet"},
	
	{what = "wallhacks",		with = "tiny dongs"},
	{what = "wallhack",			with = "MASSIVE DONG"},
	{what = "hacking",			with = "being Awesome"},
	{what = "hackin",			with = "being Awesome"},
	{what = "hackers",			with = "Pros"},
	{what = "hacker",			with = "Pro"},
	{what = "hacked",			with = "Eaten by Birds"},
	{what = "hacks",			with = "Skiddie Fuel",									rep	= true},
	{what = "hack",				with = "Gold"},
	
	{what = "haker",			with = "Pro", 											rep	= true},
	{what = "hakein",			with = "being Awesome", 								rep	= true},
	{what = "hakeing",			with = "being Awesome", 								rep	= true},
	{what = "haked",			with = "Eaten by Birds", 								rep	= true},
	{what = "hakes",			with = "Skiddie Fuel", 									rep	= true},
	{what = "hake",				with = "Gold", 											rep	= true},
	
	{what = "cheated",			with = "used his Awesome Skill",						rep = true},
	{what = "cheaters",			with = "Pros",											rep = true},
	{what = "cheater",			with = "Pro",											rep = true},
	{what = "cheatin",			with = "being Awesome",									rep = true},
	{what = "cheats",			with = "Skiddie Fuel",									rep = true},
	{what = "cheat",			with = "be Awesome",									rep	= true},
	{what = "chit",				with = "Gold",											rep	= true},
	{what = "chii",				with = "Skiddie Fuel",									rep	= true},
	
	{what = "aimbots",			with = "Awesome Skills",								rep = true},
	{what = "aimbotting",		with = "being Awesome",									rep = true},
	{what = "aimbot",			with = "Awesome Skill", 								rep	= true},
	
	--Idiots
	{what = "***",				with = "My dick",										rep = true},
	
	{what = "trolo",			with = "Hey eveyone, I'm losing badly!",				rep = true},
	{what = "admii",			with = "Awesome Dude's cock",							rep = true},
	{what = "iigg",				with = "Bilboard",										rep = true},
	{what = "niqq",				with = "Bilboard",										rep = true},
	{what = "tttt",				with = "see my webcam, my skype is _FLT_",				rep = true},
	{what = "hhhh",				with = "Let's see who can kill me first",				rep = true},
	{what = "mmmm",				with = "come on skype tonight, add _FLT_ !",			rep = true},
	{what = "onon",				with = "add _FLT_ for a good time tonight!",			rep = true},
	{what = "lolo",				with = "I love to take it up the butt!",				rep = true},
	{what = "lulu",				with = "i just tried my first dildo last night",		rep = true},
	{what = "lala",				with = "my first dildo is awesome!",					rep = true},
	{what = "xdx",				with = "even more Dong",								rep = true},
	{what = "xdd",				with = "even more Dong",								rep = true},
	{what = "fuu",				with = "Everyone see my webcam, add _FLT_ !",			rep = true},
	
	--3 letters
	{what = "aaa",				with = "I'd love you to come and blow my brains out",	rep = true},
	{what = "fff",				with = "Blow my brains out!",							rep = true},
	{what = "rrr",				with = "Want to see my webcam tonight? add _FLT_",		rep = true},
	{what = "lll",				with = "sometimes, i finger myself",					rep = true},
	{what = "ggg",				with = "I want to pound your ass",						rep = true},
	{what = "ooo",				with = "look at my xtube profile, it's _FLT_ !",		rep = true},
	{what = "nnn",				with = "My nipples are hard for you",					rep = true},
	{what = "ppp",				with = "come and shoot me",								rep = true},
	{what = "eee",				with = "I want you all to shoot me now",				rep = true},
	{what = "uuu",				with = "blow your hot load all over me",				rep = true},
	{what = "iii",				with = "Icecubes!",										rep = true},
	{what = "sss",				with = "Popcorn!",										rep = true},
	{what = "ccc",				with = "what do you think of my xtube profile, _FLT_",	rep = true},
	
	--2 letters
	{what = "kk",				with = "my xtube profile is _FLT_ what do you think?",	rep = true},
	{what = "xx",				with = "everyone see my xtube profile! its _FLT_ !",	rep = true},
	{what = "yy",				with = "Everyone against me!",							rep = true},
	{what = "zzz",				with = "Let's see who can kill me first",				rep = true},
	{what = "kkk",				with = "I'm terrible, shoot me!",						rep = true},
}



for k,v in pairs(HSP.ChatFilter.Swearwords) do --Auto-set spaces, one-off on script load, more efficient!
	if v.what:find(" ") then --Space!
		HSP.ChatFilter.Swearwords[k].spaces = true
	end
end


