
CLIENTENGINE_INTERFACE_VERSION

CLIENTENGINE_INTERFACE_VERSION001 > 002

VFileSystem017 > 019
VMaterialSystem070 > 080


CLIENT_DLL_INTERFACE_VERSION > "VClient016"

"VModelInfoClient005" > "VModelInfoClient006"


-- BETA --
GAMECONSOLE_INTERFACE_VERSION > "GameConsole004"

INTERFACEVERSION_VENGINESERVER > "VEngineServerGMod021"

VENGINE_CLIENT_INTERFACE_VERSION ("VEngineClient014") > "VGMODEngineClient014"

GAMEUI_INTERFACE_VERSION > "GameUI_GMOD_012"

FILESYSTEM_INTERFACE_VERSION > "VGModFileSystem019"


CLIENT_DLL_INTERFACE_VERSION ("VClient016") > "VGMODClient016"

"GMODGameUI011"



VGMODEngineClient013










