


--- False pos ---
HAC.White_FalsePositives = {
	"Key=TabQ",
	"WAddon=hax/HAX Swep",
	"WModule=lua/autorun/*bot*.lua/voxbot_playermodel.lua",
	"WModule=lua/autorun/*bot*.lua/Terrorist_Bot.lua",
	"WModule=lua/autorun/client/*crack*.lua/cracker_hud.lua",
	"WModule=lua/autorun/*isis*.lua/imcommandershepardandthisismyfavoritesnpcongarrysmod.lua",
	"WModule=lua/autorun/*force*.lua/FS_DeltaForce_Players.lua",
	"WAddon=hack/Halo-ish Hacks Playermodels V=1.00 (FS Jesse V-92,) [[Playermodels made from Sgt. Sh]]",
	"WModule=lua/autorun/*convar*.lua/convar_edit_group.lua",
	"WModule=lua/autorun/client/*convar*.lua/convar_edit.lua",
	"WModule=lua/includes/modules/*cvar*.dll/gm_cvar2.dll", --Hmm
	"WModule=lua/includes/modules/*cvar*.dll/cvar2.dll",
	
	"WModule=lua/autorun/*convar*.lua/pdmg_convars.lua",	
	"WModule=lua/*cvar*.lua/cvars.lua",
	"WModule=lua/autorun/*trooper_*.lua/Rebeltrooper_playermodels.lua",
	"WAddon=hax/Helmets_and_haxed_pcv_For_Dear_Azat_Brother V=1.00 (RaiR-2) [[For Dear Azatdr_house86]]",
	"WModule=lua/autorun/*hax*.lua/PM-CoD4PilotHax.lua",
	"WAddon=hax/[HeX]'s HaX V=4 (-=UH=- HeX) [[Incl_ Wallhack, ESP, Derma Ski]]",
	"WModule=lua/vgui/*block*.lua/inventory_block.lua",
	"WModule=lua/vgui/*block*.lua/inventory_block_description.lua",
	"WModule=lua/vgui/*block*.lua/inventory_block_equip.lua",
	"WModule=lua/vgui/*block*.lua/inventory_block_item.lua",
	"WModule=lua/vgui/*block*.lua/shop_player_block.lua",
	"WModule=lua/vgui/*block*.lua/shop_store_block.lua",
	"WModule=lua/vgui/*block*.lua/trade_inv_block.lua",
	"WModule=lua/vgui/*block*.lua/trade_offer_block.lua",
	"WModule=lua/vgui/*force*.lua/rename_force.lua",
	"WModule=lua/autorun/*bot*.lua/saboteur.lua",
	"WModule=lua/autorun/*block*.lua/FPP_DefaultBlockedModels.lua",
	"WAddon=exploit/exploitblock V=1 (Cherry) [[Exploit Blocker]]",
	"WModule=lua/autorun/client/*exploit*.lua/exploit.lua",
	"WModule=lua/*bot*.lua/Evilscaryrobotsfromouterspace.lua",
	"Datafile=data/faphack_friends.txt-5 (*faphack*.txt) [[check]]",
	"Datafile=data/faphack_entities.txt-5 (*faphack*.txt) [[check]]",
	"WModule=lua/autorun/*block*.lua/blockhead.lua",
	"WModule=lua/autorun/*block*.lua/blockheadnpc.lua",
	"WModule=lua/autorun/client/*troll*.lua/VehController_cl.lua",
	"WModule=lua/autorun/*hack*.lua/player_manager_hack.lua",
	"WAddon=hades/HadesWrath V=1.00 (Hoffa1337) [[Attack1_ Hells Bolt Attack2_ F]]",
	"WModule=lua/autorun/*force*.lua/deltaforce.lua",
	"WAddon=hack/Epsilon Helmetless Head Hacks V=1.00 (Wolly) [[gmod. gmod never changes.]]",
	"WAddon=hax/Haxor_Gun V=1.00 (Chicken) [[Haxor Weapon]]",
	"SLOG=npc_showanimwindow",
	"WAddon=hack/Purvis CTHack Playermodels V=1.00 (Purvis _ Jesse) [[Purvis_ CT Bodyhax made into p]]",
	"WModule=lua/autorun/*hax*.lua/FS-CSSHax-Purvis.lua",
	"WModule=lua/*block*.lua/FPP_DefaultBlockedModels.lua",
	"WAddon=spam/SPAMP",
	"WModule=lua/includes/enum/*cvar*.lua/cvar.lua",
	"WModule=lua/*bot*.lua/myrobot.lua",
	"WModule=lua/autorun/*cvar*.lua/plague_cvars.lua",
	"WModule=lua/autorun/*trooper_*.lua/stormtrooper_npcs.lua",
	"WAddon=hax/Dr Hax [[This is the Dr Hax NPC from Cl]]",
	"WAddon=spam/ambspamlogger V=0.0. (AmB Development) [[Catch thoes minges without adm]]",
	"WModule=lua/autorun/*trooper_*.lua/rebeltrooper_npcs.lua",
	"WAddon=hack/TF2 hacked parts pack V3 V=1.00 (Nobody) [[Contains the default Garry_s M]]",
	"WAddon=hack/TF2 mini hacks pack 1 V=1.00 (Nobody) [[Contains the default Garry_s M]]",
	"WAddon=hack/TF2 new items hacked apart and fixed physics V=1.00 (Nobody) [[Contains the default Garry_s M]]",
	"WAddon=hack/TF2 polycount items hacked and fixed V=1.00 (Valve) [[Contains the default Garry_s M]]",
	
	"WModule=lua/*force*.lua/cl_proxi_preforce.lua",
	"WAddon=aimbot/Aimbot Guns [[piss of some people xD]]",
	"WAddon=aimbot/Aimbot Gun V2 [[This is the Aimbot Gun V2 from]]",
	"WAddon=hax/[HeX]'s HaX 4 - SE2 Edition V=4 (-=UH=- HeX) [[Incl_ Aimbot, Wallhack, NoSpre]]",
	"WAddon=se2/[HeX]'s HaX 4 - SE2 Edition V=4 (-=UH=- HeX) [[Incl_ Aimbot, Wallhack, NoSpre]]",
	"WAddon=spam/spawnicon_spam_fix V=1 (Scorpius289) [[Fix for _Generated Spawn Icon_]]",
	"WModule=lua/*spam*.lua/CaroSpamProtect.lua",
	"WAddon=hack/AA3Hacks V=1.00 (Srgt. Shotup) [[America_s Army 3 models with c]]",
	"WAddon=hack/cod4pilothacks",
	"WAddon=hack/crysis_headhacks",
	"WAddon=hack/Hacked RailGun V=0.10 (Funley) [[Hacked Version of Ultras RailG]]",
	"WAddon=hack/HackedCSWeapons V=1.00 (Funley) [[Conatins the hacked version of]]",
	"WAddon=hack/Marine Headhacks V=1.1 (Srgt. Shotup) [[Now you too can have citizen-y]]",
	"WAddon=hack/NZHacks [[The German models from my shor]]",
	"WAddon=hack/ODST Headhacks V=1.1 (Srgt. Shotup) [[Now you too can have citizen-y]]",
	"WAddon=cheat/piratecats cheat stool",
	"WAddon=hack/Random Haloish Hacks V=1.00 (Srgt. Shotup) [[Made a couple of models that l]]",
	"WAddon=hack/replicasoldierhacks",
	"WAddon=hack/Roller-Hack-Gun V=1 (RedDotRampage_J) [[Fun _P]]",
	"WAddon=hack/weapon_manhack",
	"WModule=lua/autorun/client/*bot*.lua/jetboombot.lua",
	"WAddon=spam/ASpam V=1.90 (Jay209015) [[AntiSpam Module for ULib + Pro]]",
	"WAddon=block/BlockConsoleCommands V=1 (Slayer3032, Nep) [[Blockz Console Commands]]",
	"WAddon=block/BlockExplosives",
	"WAddon=hack/DarkRP Wallhack V=3 (Jammie Dodger) [[Hai, wallhacks]]",
	"WAddon=force/forcedynamite V=1.00 (Duncan Stead) [[Dynamite that pushes props in]]",
	"WAddon=force/ForceFieldsSTool V=1 (LuaPineapple) [[Meh, does anyone ever read thi]]",
	"WAddon=hack/hacknest V=1 (Studentloon) [[Manhack nests.]]",
	"WAddon=force/Ir_force_gun V=1.00 (Irtimid) [[Adds a Force Gun.]]",
	"WAddon=hack/manhacknade V=1 (jjm4) [[A manhack nade.]]",
	"WAddon=spam/NoSpawniconSpam V=1.00 (MDave) [[Replaces that annoying chat sp]]",
	"WAddon=hack/NO_HACK! V=3.00 (Robert1999) [[No Hack]]",
	"WAddon=spam/Spam Remover V=1.0. (philxyz) [[Spam Remover SWEP]]",
	"WAddon=block/WOTSLuaCinderblock V=1 (LuaPineapple) [[Go watch the movie or you are]]",
	"WModule=lua/autorun/*spam*.lua/cl_ASpaminit.lua",
	"WModule=lua/autorun/*spam*.lua/ASpam.lua",
	
	"WAddon=hax/Haxgun new V=1.00 (kratan) [[Hax gun new swep only for admi]]",
	"WAddon=hax/[HeX]'s HaX 4 - Awesome Edition V=4 (-=UH=- HeX) [[Incl_ Aimbot, Wallhack, NoSpre]]",
	"WAddon=hax/[HeX]'s HaX 4 - Awesome Edition V=4 (-=UH=- HeX) [[Incl_ Wallhack, ESP, Derma Ski]]",
	"WModule=lua/autorun/client/*crack*.lua/keypad_cracker.lua",
	"WModule=lua/autorun/*troll*.lua/StriderController.lua",
	
	[[SLOG=npc_control_npcprotect "1"]],
	[[SLOG=npc_allow_spawning "1"]],
	[[SLOG=npc_allow_moving "1"]],
	[[SLOG=npc_allow_specifics "1"]],
	[[SLOG=npc_allow_attacking "1"]],
	[[SLOG=npc_allow_attacking_players "1"]],
	[[SLOG=npc_adminonly "1"]],
	
	"KR30=host_timescale=1",
	"TS=host_timescale=1",
	
	"WModule=lua/autorun/*spam*.lua/anti_spawnicon_spam.lua",
	"WModule=lua/autorun/*spam*.lua/spawnicons_spam_fix.lua",
	"WModule=lua/autorun/*bot*.lua/Evilscaryrobotsfromouterspace.lua",
	"WModule=lua/autorun/*trooper_*.lua/clonetrooper_playermodels.lua",
	"WModule=lua/autorun/*trooper_*.lua/clonetrooper_playermodels.lua",
	"WModule=lua/*cvar*.lua/cl_inscript_cvar_custom.lua",
	"WModule=lua/*force*.lua/cl_sharpeye_preforce.lua",
	"WModule=lua/autorun/*troll*.lua/StalkerController.lua",
	"WModule=lua/autorun/*trooper_*.lua/stormtrooper_playermodels.lua",
	"WModule=autorun/*force*.lua/deltaforce.lua",
	"WModule=autorun/client/*crack*.lua/keypad_cracker.lua",
	"WModule=lua/*cvar*.lua/cl_proxi_cvar_custom.lua",
	"WModule=lua/*cvar*.lua/cl_proxi_cvar_static.lua",
	"WModule=lua/*cvar*.lua/cl_sharpeye_cvar_static.lua",
	"WModule=lua/*cvar*.lua/cl_sharpeye_cvar_custom.lua",
	"WModule=lua/autorun/*bot*.lua/iBots_playermodels.lua",
	"WModule=lua/autorun/*bot*.lua/npc_iBotBlack.lua",
	"WModule=lua/autorun/*bot*.lua/npc_iBotBlue.lua",
	"WModule=lua/autorun/*bot*.lua/npc_iBotGreen.lua",
	"WModule=lua/autorun/*bot*.lua/npc_iBotPink.lua",
	"WModule=lua/autorun/*bot*.lua/npc_iBotPurple.lua",
	"WModule=lua/autorun/*bot*.lua/npc_iBotRed.lua",
	"WModule=lua/autorun/*bot*.lua/npc_iBotWhite.lua",
	"WModule=lua/*cvar*.lua/cl_dhinline_cvar_static.lua",
	"WModule=lua/*cvar*.lua/cl_dhinline_cvar_custom.lua",
	"WModule=lua/autorun/client/*crack*.lua/keypadcracker_core.lua",
	"WModule=lua/autorun/client/*crack*.lua/keypadcracker_menu.lua",
	"WModule=lua/*crack*.lua/keypadcracker_core.lua",
	"WModule=lua/*crack*.lua/keypadcracker_menu.lua",
	"WModule=lua/*convar*.lua/pewpew_convars.lua",
	"WModule=lua/*hack*.lua/cl_hack_check_vgui_type.lua",
}






